# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_pl.py,v 1.15 2005/01/15 11:07:36 tarmo Exp $
#
# Copyright 2001, 2002 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the Polish translations for all Fle3 printable strings."""

common = {'language_name':
 ('Polski', 'Name of this language'),
 'charset_encoding':
 ('utf-8', 'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('Moja WebTop', 'Main tab for webtop'),
 'Knowledge_Building':
 ('Budowanie wiedzy', 'Main tab for knowledge building'),
 'Course_Management':
 ('Zarządzanie kursami', 'Main tab for course management'),
 'User_Management':
 ('Zarządzanie uczestnikami', 'Main tab for user management'),
 'Jamming':
 ('Dżem', 'Main tab for jamming'),
 'Type_Management':
 ('Zarządzanie typem wiedzy', 'Heading'),
 'cancel':
 ('Anuluj', 'Button label'),
 'submit':
 ('Zatwierdź', 'Button label'),
 'remove':
 ('Usuń', 'Button label'),
 'next':
 ('Następny ->', 'Label for button'),
 'previous':
 ('<- Poprzedni', 'Label for button'),
 'quick_submit':
 ('Szybkie zatwierdzanie', ''),
 'ok':
 ('OK', 'Button label'),
 'save':
 ('Zapisz', 'Button label'),
 'create':
 ('Utwórz', 'Button label'),
 'search':
 ('Szukaj', 'Button label'),
 'webtop':
 ('Moja Webtop', ''),
 'description':
 ('Opis', 'Label'),
 'short_date_format_display':
 ('YYYY-MM-DD', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%Y-%m-%d',
  'Format string for short dates. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'timestamp_format':
 ('%H:%M %Y-%m-%d',
  'Format string for long timestamps. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'invite':
 ('Zaproś', ''),
 'add':
 ('Dodaj', ''),
 'today':
 ('Dzisiaj', ''),
 'yesterday':
 ('Wczoraj', ''),
 'groupfolder':
 ('- folder kursu', 'Heading'),
 'dtml_reloaded':
 ('DTML odświeżono', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('pliki DTML dla tego obiektu odświeżono',
  'Message dialog text'),
 'dtmls_reloaded':
 ('DTMLs odświeżono', 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Wszystkie pliki DTML odświeżono', 'Message dialog text'),
 'css_reloaded':
 ('Arkusze stylów odświeżono',
  'Title for message dialog'),
 'css_files_reloaded':
 ('Arkusze stylów dla tego obiektu odświeżono',
  'Message text'),
 'error':
 ('Błąd', ''),
 'warning':
 ('Ostrzeżenie', ''),
 'invalid_url':
 ('Niewłaściwy url', 'Message title'),
 'invalid_url_message':
 ('Adres URL wpisano niewłaściwie.<br>Sprawdź, czy zaczyna się oznaczeniem protokołu adresu internetowego http://, ftp://, mailto: lub innego. Pamiętaj, że nie możesz używać adresów skróconych, jak "www.mojastrona.org", lecz musisz poprzedzić adres oznaczeniem protokołu, np. "http://www.mojastrona.org". W przypadku niepewności po prostu skopiuj cały adres URL z okienka adresowego Twojej przeglądarki.',
  'Message text'),
 'invalid_name':
 ('Niewłaściwa nazwa', 'Message title'),
 'give_valid_name':
 ('Wpisz właściwą nazwę', 'Message text'),
 'name_taken':
 ('Nazwa "%s" już jest w użyciu. Wpisz inną nazwę.',
  'Message text, name inserted inside'),
 'edit':
 ('Edytuj', 'Button label'),
 'you_are_in':
 ('Jesteś w:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ('Nie wypełniono wszystkich wymaganych pól.',
  'Erro message text'),
 'confirmation':
 ('Potwierdzenie', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Niewłaściwe dane', 'Message title'),
 'invalid_fields':
 ('W następujące pola wprowadzono niewłaściwe dane:',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ('Najpierw coś zaznacz', 'Message text'),
 'link_to_webtop':
 ('Utwórz odnośnik (link) do Mojej WebTop', 'Link'),
 'proxy_to_webtop':
 ('Podwiąż (zlinkuj) folder kursu do Mojej WebTop', 'Link'),
 'export':
 ('Eksport', 'Button label'),
 'import':
 ('Import', 'Button label'),
 'importing':
 ('Importowanie', 'Heading start'),
 'megabyte':
 ('MB', 'Abbreviation for megabyte'),
 'kilobyte':
 ('kB', 'Abbreviation for kilobyte'),
 'logout':
 ('Wyloguj', 'Link for logging out, also heading in logout dialogs'),
 'logout_pre3':
 ('Aby wylogować, po prostu zamknij przeglądarkę. Jeśli pojawi się okienko logowania, wybierz anulowanie.',
  'Instructions for logging out'),
 'any':
 ('Jakikolwiek', 'Label used in search forms'),
 'course':
 ('kurs', 'Part of location path'),
 'language':
 ('Język', ''),
 'announcements':
 ('Ogłoszenia', 'Link/heading'),
 'sun':
 ('Nie', 'Weekday abbreviation'),
 'mon':
 ('Poń', 'Weekday abbreviation'),
 'tue':
 ('Wto', 'Weekday abbreviation'),
 'wed':
 ('Śro', 'Weekday abbreviation'),
 'thu':
 ('Czw', 'Weekday abbreviation'),
 'fri':
 ('Pią', 'Weekday abbreviation'),
 'sat':
 ('Sob', 'Weekday abbreviation'),
 'sunday':
 ('Niedziela', 'Weekday'),
 'monday':
 ('Poniedziałek', 'Weekday'),
 'tuesday':
 ('Wtorek', 'Weekday'),
 'wednesday':
 ('Środa', 'Weekday'),
 'thursday':
 ('Czwartek', 'Weekday'),
 'friday':
 ('Piątek', 'Weekday'),
 'saturday':
 ('Sobota', 'Weekday'),
 'January':
 ('Styczeń', 'Month'),
 'February':
 ('Luty', 'Month'),
 'March':
 ('Marzec', 'Month'),
 'April':
 ('Kwiecień', 'Month'),
 'May':
 ('Maj', 'Month'),
 'June':
 ('Czerwiec', 'Month'),
 'July':
 ('Lipiec', 'Month'),
 'August':
 ('Sierpień', 'Month'),
 'September':
 ('Wrzesień', 'Month'),
 'October':
 ('Październik', 'Month'),
 'November':
 ('Listopad', 'Month'),
 'December':
 ('Grudzień', 'Month'),
 'remove_q':
 ('Usunąć?', 'Question')}

kb = {'month':
 ('miesiąc', ''),
 'week':
 ('tydzień', ''),
 'you_have_not_replied_to':
 ('Brak Twoich odpowiedzi do:', 'followed by a list of persons'),
 'total_replies':
 ('Ogólna liczba odpowiedzi na notki innych uczestników:',
  'followed by number'),
 'total_notes_written':
 ('Ogólna liczba napisanych notek:', 'followed by number'),
 'graph_type':
 ('Typ wykresu: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('typ wiedzy', 'graph type'),
 'adding_resource':
 ('dodawanie źródła', 'part of browser title'),
 'replies':
 ('odpowiedzi', 'graph type'),
 'display_by':
 ('Wyświetl wg:', 'Label for timescale (week/month) selection'),
 'modifying_resource':
 ('modyfikowanie źródła', 'part of browser title'),
 'title_resource':
 ('Tytuł źródła', 'The title of resource'),
 'author_resource':
 ('Autor', 'The author of the resource'),
 'url':
 ('URL', 'Resource URL'),
 'location':
 ('Miejsce', 'Resource location'),
 'course_info':
 ('Informacje o kursie', 'Label for link to course details'),
 'create_context':
 ('Utwórz kontekst kursu', 'Link to create new course context'),
 'hide_context':
 ('Ukryj kontekst', 'Link to hide a context from view'),
 'show_context':
 ('Pokaż kontekst', 'Link to show a hidden context'),
 'new_notes':
 ('nowych notatek',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('notatek', 'Label for showing the number of notes'),
 'full_description':
 ('pełen opis...', ''),
 'course':
 ('kursy', "String 'course' in context display"),
 'context':
 ('kontekst', "String 'context' in context display"),
 'thread':
 ('wątek', "String 'thread' in context display"),
 'note':
 ('notatka', "String 'note' in context display"),
 'start_thread':
 ('Zacznij wątek', 'Link'),
 'short_description':
 ('Krótki opis', 'Label'),
 'long_description':
 ('Długi opis', 'Label'),
 'full_description':
 ('Pełen opis', 'Label'),
 'select':
 ('Wybierz',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('typ wiedzy', 'Label'),
 'add_note':
 ('Dodaj notatkę', 'Button label'),
 'show_notes':
 ('Pokaż notatki', 'Heading start'),
 'show_thread':
 ('jako wątek', 'heading finish'),
 'show_type':
 ('wg typu wiedzy', 'heading finish'),
 'show_author':
 ('wg osoby', 'heading finish'),
 'show_date':
 ('wg daty', 'heading finish'),
 'select_course':
 ('Wybierz kurs', 'Label, followed by a drop-down list of available courses'),
 'change':
 ('Zmień', 'Button label'),
 'creating_context':
 ('Tworzenie kontekstu do kursu:', 'Title, followed by the course name'),
 'editing_context':
 ('Edytowanie kontekstu do kursu:', 'Title, followed by the course name'),
 'title_of_context':
 ('Tytuł kontekstu kursu', 'Label'),
 'type_set':
 ('Typ wiedzy', 'Label'),
 'creating_note_in':
 ('Utwórz notatkę dot. zadania:',
  'Title, followed by course context name'),
 'course_context':
 ('Kontekst kursu', 'Label for course context'),
 'you_are_replying_to':
 ('Odpowiadasz na', 'Label'),
 'title_of_note':
 ('Tytuł notatki', 'Label'),
 'message_body':
 ('Treść wiadomości', 'Label'),
 'current_image':
 ('Bieżący obraz', 'Label'),
 'replace_with':
 ('Zamień na', 'Label for image replacement in note edit'),
 'add_image':
 ('Dodaj (wgraj) obraz', 'Label'),
 'title_of_image':
 ('Tytuł obrazu', 'Label'),
 'add_link':
 ('Dodaj odnośnik (link, URL)', 'Label'),
 'title_of_link':
 ('Tytuł odnośnika', 'Label'),
 'preview':
 ('Podgląd', 'Button label'),
 'previewing_note':
 ('Podgląd notatki dot. zadania:',
  'Title/heading, followed by course context name'),
 'publish':
 ('Opublikuj', 'Button label'),
 'search_kb':
 ('Szukaj w sekcji Budowanie Wiedzy', 'Link label'),
 'searching_kb':
 ('Szukaj w notatkach sekcji Budowanie Wiedzy', 'Label'),
 'search_author':
 ('Autor', 'Label'),
 'search_notes_words':
 ('Notatki zawierające wyrazy', 'Label'),
 'search_context':
 ('Kontekst kursu', 'Label'),
 'search_tt':
 ('Typy wiedzy', 'Label'),
 'search_note':
 ('Notatka', 'Label'),
 'current_note':
 ('Bieżąca notatka', 'Label'),
 'you_didnt_select_type':
 ('Nie wybrano typu wiedzy.', 'Title'),
 'go_back':
 ('Wróć', 'Start of message, rendered into a link'),
 'and_select_type':
 ('i wybierz typ wiedzy dla swojej notatki.', 'Rest of message'),
 'inline_notes':
 ('Pokaż treść wszystkich notatek', 'Link'),
 'outline_notes':
 ('Ukryj treść wszystkich notatek', 'Link'),
 'view_info':
 ('wyświetlanie informacji', 'Part of location bar'),
 'edit_context':
 ('Edytuj kontekst', 'Link'),
 'to_note':
 ('do wypowiedzi', 'Part of a message'),
 'full_thread_no':
 ('Pokaż tylko początkowe notatki', 'Link'),
 'full_thread_yes':
 ('Pokaż cały wątek', 'Link'),
 'remove':
 ('Usuń notatkę', 'Button label for removing notes'),
 'restore':
 ('Przywróć notatkę', 'Button label for restoring notes'),
 'remove_form_title':
 ('Usuwanie notatki', 'Title for note removing form'),
 'remove_form_label':
 ('Usuwanie notatki', 'Explanation in remove form, followed by note subject'),
 'removed_msg':
 ('Wiadomość usunięto',
  'Message shown to the teacher when she has removed a note.'),
 'remove_verify2':
 ('Na pewno chcesz usunąć tę wiadomość? Twoje imię, bieżąca data i wyjaśnienie, które wpisujesz poniżej zostaną zapisane i będą wyświetlane wraz z adnotacją o usunięciu każdemu, kto zechce przeczytać tę notatkę.',
  'Verification message shown when removing is attempted'),
 'remove_explanation':
 ('Wyjaśnienie usunięcia',
  'Label for removee explanation text area'),
 'removed_subject':
 ('Usunięto', 'Title/subject for removed notes'),
 'removed_body':
 ('Ta wiadomość została usunięta przez %s w dniu %s.',
  "Body for removed messages. First placeholder is replaced by remover's name and the second by the date"),
 'notes_from_day':
 ('Notatki z dn.', 'Start of heading, followed by a date'),
 'previous':
 ('Poprzedni', 'Link label'),
 'next':
 ('Następny', 'Link label'),
 'who_has_read':
 ('Kto przeczytał tę notatkę?', 'Link label'),
 'last_read':
 ('Ostatnio przeczytana', 'Label'),
 'times_read':
 ('Przeczytana razy', 'Label'),
 'back':
 ('&lt; powrót', 'Link label'),
 'unread_to_read_msg':
 ('Wszystkie notatki w wątku oznaczono jako przeczytane.',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Oznacz wszystkie notatki jako przeczytane', 'text in a button'),
 'creating_groupfolder':
 ('Tworzenie foldera kursu w', 'Heading start'),
 'title_groupfolder':
 ('Tytuł foldera kursu', 'Label'),
 'flea_asks':
 ('Pomocnik (Flea) podpowiada',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Zmienić typ wiedzy?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ('To jedyny właściwy tutaj typ wiedzy.',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Zmień', 'Button label'),
 'down_to_note':
 ('W dół', 'Link label'),
 'use_roleplay':
 ('Użyj odpowiedzi w tym kontekście',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('Ustalanie ról do odgrywania',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 ('Kursy', "Heading for user's course list"),
 'totals_notes':
 ('Notatek',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ('Artefaktów',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s nowych / %s ogółem',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Dodaj folder', ''),
 'add_document':
 ('Dodaj (wgraj) dokument', ''),
 'add_link':
 ('Dodaj odnośnik (link)', ''),
 'create_memo':
 ('Utwórz memo', ''),
 'type':
 ('Typ', 'Link for sorting by type'),
 'title':
 ('Tytuł', 'Link for sorting by title'),
 'date':
 ('Data', 'Link for sorting by date'),
 'size':
 ('Rozmiar', 'Link for sorting by size'),
 'remove':
 ('Usuń', 'Button label'),
 'restore':
 ('Przywróć', 'Button label'),
 'rename':
 ('Zmień nazwę', 'Button label'),
 'copy':
 ('Kopiuj', 'Button label'),
 'cut':
 ('Wytnij', 'Button label'),
 'paste':
 ('Wklej', 'Button label'),
 'delete':
 ('Usuń', 'Button label'),
 'select_all':
 ('Wybierz wszystko', 'Button label'),
 'trash':
 ('Kosz', 'Label for trashcan'),
 'empty_trash':
 ('Opróżnij kosz', 'Button label'),
 'adding_folder':
 ('Dodawanie foldera', 'Heading'),
 'title_of_folder':
 ('Tytuł foldera', 'Label'),
 'viewing_memo':
 ('Wyświetlanie memo', 'Title'),
 'creating_memo':
 ('Tworzenie memo', 'Title'),
 'editing_memo':
 ('Edytowanie memo', 'Title'),
 'title_of_memo':
 ('Tytuł memo', 'Label'),
 'content':
 ('Treść', 'Label'),
 'show_memo_contents':
 ('Pokaż tylko treść memo', 'Link'),
 'adding_link':
 ('Dodawanie odnośnika (linku)', 'Title'),
 'title_of_link':
 ('Tytuł odnośnika (linku)', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Dokument dodano.', 'Status message'),
 'adding_document':
 ('Dodawanie (wgrywanie) dokumentu', 'Title'),
 'upload_document':
 ('Dodaj (wgraj) dokument', 'Label'),
 'title_of_document':
 ('Tytuł dokumentu', 'Label'),
 'search_wt':
 ('Szukaj w sekcjach WebTop', 'Link label'),
 'searching_wt':
 ('Szukanie w WebTopach', 'Label'),
 'search_results':
 ('Rezultaty wyszukiwania', 'Label'),
 'new_search':
 ('Nowe wyszukiwanie', 'Label'),
 'search_title':
 ('Tytuł', 'Label'),
 'search_owner':
 ('Właściciel', 'Label'),
 'search_words':
 ('Obiekty zawierające wyrazy', 'Label'),
 'search_object':
 ('Obiekt', 'Label'),
 'search_folder':
 ('Folder', 'Label'),
 'viewing_search_results':
 ('wyświetlanie rezultatów wyszukiwania',
  'Label in the location path'),
 'anyone':
 ('Ktokolwiek', 'Label'),
 'webtop_link_added':
 ('Odnośnik (link) do WebTopu dodany', 'Message title'),
 'added_webtop_link':
 ('Odnośnik (link) %s "%s" został utworzony w Twoim WebTopie. Kliknij OK aby wrócić do poprzedniej strony.',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 ('Folder kursu dodano', 'Message title'),
 'added_proxy':
 ('Folder kursu %s jest  niewidoczny w Twoim WebTopie. Kliknij OK aby wrócić do poprzedniej strony.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ('Nic nie wybrano!', 'Message dialog title'),
 'select_item_first':
 ('Wybierz chociaż jeden element, aby zrobić coś innego, niż wklejanie.',
  'Message dialog message'),
 'no_file_supplied':
 ('Nie wpisano żadnego pliku.', 'Message text'),
 'renaming':
 ('Zmiana nazwy', 'Title'),
 'invalid_names':
 ('Następujące nazwy są niewłaściwe:',
  'Message dialog messsage'),
 'same_names':
 ('Zaproponowano tę samą nazwę dla kilku obiektów.',
  'Message dialog message'),
 'names_in_use':
 ('Następujące nazwy są już w użyciu:',
  'Message dialog message'),
 'information':
 ('Informacje o uczestniku', 'Link'),
 'preferences':
 ('Preferencje', 'Link'),
 'editing_preferences':
 ('Edytowanie preferencji', 'Title'),
 'shared_course_folder':
 ('Wspólny folder kursu',
  'Printed after the name of the group folder in webtop contents list.'),
 'quota_reached_title':
 ('Limit (quota) wyczerpany', 'Title'),
 'quota_reached':
 ('Operacja nie może zostać przeprowadzona, ponieważ wyczerpano limit (quota) w Twojej WebtTop. Usuń jakieś obiekty i spróbuj ponownie.',
  'Message dialog message'),
 'obj_removed':
 ('(Odnośnik jest pusty)',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('&lt; powrót', 'Link label')}

usermgmnt = {'user':
 ('użytkownik', 'part of browser title'),
 'adding_users':
 ('Dodawanie użytkowników', 'Title'),
 'required_field':
 ('Pole wymagane', ''),
 'nickname':
 ('Nick (pseudonim)', 'Label'),
 'user_account':
 ('Konto użytkownika', 'Label'),
 'Confirm':
 ('Potwierdź', ''),
 'you_are_removing':
 ('Usuwasz', ''),
 'invite_user':
 ('Zaproś użytkownika', ''),
 'invite_users':
 ('Zaproś użytkowników', 'Heading for invitation form'),
 'email_addresses':
 ('Adresy E-mail', ''),
 'separate_with_comma':
 ('( oddziel przecinkiem: , )', ''),
 'Invitation_message':
 ('Treść zaproszenia', ''),
 'Invitation_language':
 ('Język zaproszenia', ''),
 'Courses_to_invite_to':
 ('Kursy, na które zapraszasz', ''),
 'Freeze':
 ('Zamroź', ''),
 'Remove':
 ('Usuń', ''),
 'role':
 ('Rola', 'label'),
 'role_staff':
 ('Personel', 'Global role stuff'),
 'role_user':
 ('Uczestnik', 'Global role user'),
 'role_fleadmin':
 ('FLE Admin', 'Global role fleadmin'),
 'invite_again':
 ('Zaproś ponownie', 'Button label'),
 'warning':
 ('Ostrzeżenie', 'Heading'),
 'want_remove_users':
 ('Czy chcesz usunąć następujących uczestników/użytkowników?',
  'Complete question'),
 'invited_user_manage':
 ('Zarządzanie zaproszonymi', 'Title'),
 'info_user':
 ('Informacje o użytkowniku',
  'Title for user info page, prefix before user name'),
 'edit_user':
 ('Edytuj info o użytkowniku', 'Link'),
 'editing':
 ('Edytowanie', 'Heading for user edit, inserted before user name'),
 'image_of_user':
 ('Portret uczestnika', 'Label'),
 'upload_image_of_user':
 ('Dodaj (wgraj) swój portrecik', 'Label'),
 'or_link_to_image':
 ('albo podaj do niego odnośnik (link)',
  'Label, continuing from the upload label'),
 'webtop_bg':
 ('Wybierz tło WebTopu', 'Label'),
 'upload_webtop_bg':
 ('albo wgraj własny obrazek tła',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Sprawdź zaproszenia', ''),
 'add_user':
 ('Dodaj użytkownika', ''),
 'Unfreeze':
 ('Odmroź', ''),
 'Users':
 ('Użytkownicy', ''),
 'gsm':
 ('Tel. komórkowy', ''),
 'last_name':
 ('Nazwisko', ''),
 'first_name':
 ('Imię', ''),
 'city':
 ('Miejscowość', ''),
 'organization':
 ('Organizacja', ''),
 'professional_interests':
 ('Zainteresowania zawodowe', ''),
 'email':
 ('E-mail', ''),
 'phone':
 ('Tel.', ''),
 'url_to_photo':
 ('URL do portreciku', ''),
 'country_menu_default':
 ('Wybierz kraj', ''),
 'group_menu_default':
 ('Wybierz grupę', 'Default value for drop-down menu'),
 'address':
 ('Adres', ''),
 'address1':
 ('Adres - wiersz 1', ''),
 'address2':
 ('Adres - wiersz 2', ''),
 'personal_interests':
 ('Zainteresowania osobiste', ''),
 'quote':
 ('Cytat, motto', ''),
 'homepage':
 ('Strona WWW', ''),
 'upload':
 ('Dodaj (wgraj)', ''),
 'group':
 ('Grupa', ''),
 'password':
 ('Hasło', ''),
 'background':
 ('Tło', ''),
 'country':
 ('Kraj', ''),
 'reserved_nickname':
 ('Upps! To hasło jest już w użyciu (zajęte).',
  'Message'),
 'password_mismatch':
 ('Podane hasła nie są jednakowe.', 'Message'),
 'could_not_send_invitation':
 ('Wysłanie zaproszenia było niemożliwe. Sprawdź czy twoje konto MailHost jest prawidłowo skonfigurowane.',
  'Error message'),
 'invitations_sent':
 ('Zaproszenia wysłano', 'Message title'),
 'invitations_sent_to':
 ('Zaproszenia wysłano do %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 ('Nie wysłano zaproszeń do: %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Użytkownicy usunięci', 'Message title'),
 'removed_users':
 ('Użytkownicy usunięci: %s', 'Message, list inserted inside'),
 'not_removed_users':
 ('Nie można usunąć tych użytkowników: %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 ('Powtórne zaproszenia wysłano', 'Message title'),
 're_invitations_sent_to':
 ('Powtórne zaproszenia wysłano do %s użytkowników. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Oczekujących użytkowników usunięto',
  'Message title'),
 'pending_removed_users':
 ('Usunięci oczekujący użytkownicy: %s',
  'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Nie można usunąć tych oczekujących użytkowników: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ('Zaproszenie do FLE', 'Subject for invitation messages'),
 'invitation_header':
 ('Zaproszenie', 'Header for invitation messages'),
 'invitation_footer':
 ('Odwiedź: ', 'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Witaj w systemie FLE. Wpisz poniżej informacje o użytkowniku.',
  'Welcome message used in invitation registration form'),
 'uname':
 ('Login', 'Label used for user login name in several places'),
 'registration_failed':
 ('Rejestracja nie powiodła się',
  "Title used when invited user can't register."),
 'invitation_key_used':
 ('Ten URL zaproszenia był już w użyciu albo już nie jest właściwy. Jeśli rejestracja nie powiodła się, skontaktuj się ze swoim nauczycielem, aby otrzymać zaproszenie jeszcze raz.',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ('Niewłaściwe dane do identyfikacji',
  "Message telling that the authentication key isn't valid."),
 'after_submit_give_name_and_passwd2':
 ('Po naciśnięciu "Submit" podaj swój login i hasło.',
  'Message'),
 'frozen':
 ('Zamrożony', 'User status code'),
 'show_frozen':
 ('Pokaż także zamrożonych użytkowników',
  'Link to show all users'),
 'show_active':
 ('Pokaż tylko aktywnych użytkowników',
  'Link to show only active users'),
 'no_email':
 ('Brak adresu E-mail', 'Message title'),
 'no_email_explanation':
 ('Nie możesz wysłać E-maila, ponieważ brakuje Twojego adresu E-mail.',
  'Message text'),
 'passwd_changed':
 ('Hasło zostało zmienione', 'Message title'),
 'passwd_changed_explanation2':
 ('Twoje hasło zostało zmienione. Przeglądarka zażąda podania loginu i hasła.',
  'Message text'),
 'external_user_database_explanation':
 ('Twój Fle3 korzysta z zewnętrznej bazy danych o użytkownikach. Aby dodać użytkowników do systemu, dodaj ich do tej bazy.',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 ('kurs', 'part of browser title'),
 'courses':
 ('Kursy', 'Title'),
 'create_course':
 ('Utwórz kurs', 'Link'),
 'edit_course':
 ('Edytuj kurs', 'Button label'),
 'edit_participants':
 ('Edytuj skład uczestników', 'Button label'),
 'creating_course':
 ('Tworzenie kursu', 'Title'),
 'editing_course':
 ('Edytowanie kursu', 'Title'),
 'course_title':
 ('Tytuł kursu', 'Label'),
 'organization':
 ('Organizacja', 'Label'),
 'methods':
 ('Metody', 'Label'),
 'starting_date':
 ('Data rozpoczęcia', 'Label'),
 'ending_date':
 ('Data zakończenia', 'Label'),
 'create_groupfolder':
 ('Utwórz folder grupy', 'Link'),
 'create_announcements':
 ('Utwórz ogłoszenia', 'Link'),
 'edit_announcements':
 ('Edytuj ogłoszenia', 'Link'),
 'add_announcement':
 ('Dodaj ogłoszenie', 'Link'),
 'adding_announcement':
 ('Dodawanie ogłoszenia dot. kursu:',
  'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('Naprawdę usunąć ogłoszenie?', 'Question'),
 'editing_announcements':
 ('Edytowanie ogłoszeń', 'Heading'),
 'viewing_announcements':
 ('Przeglądanie ogłoszeń kursu %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ('Dopisywanie uczestników kursu',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('Jeśli uczestnicy kursu nie są jeszcze użytkownikami Fle3,',
  'Message'),
 'new_participants_to_system':
 ('nowych uczestników systemu Fle3', 'Part of a phrase'),
 'by_email':
 ('e-mailem', 'Part of a phrase'),
 'manually':
 ('ręcznie', 'Part of a phrase'),
 'fle_users':
 ('Użytkownicy systemu FLE3', 'Heading'),
 'down':
 ('W dół', 'Button label'),
 'up':
 ('W górę', 'Button label'),
 'teachers':
 ('Nauczyciele', 'Heading'),
 'tutors':
 ('Tutorzy', 'Heading'),
 'students':
 ('Studenci', 'Heading'),
 'add_button':
 ('Dodaj ->', 'Button label'),
 'remove_button':
 ('<- Usuń', 'Button label'),
 'viewing_course':
 ('wyświetlanie kursu:', 'Part of a phrase in location path'),
 'viewing_course_resources':
 ('wyświetlanie źródeł do kursu %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 ('informacja', 'Part of a phrase in location path'),
 'no_course_selected':
 ('Nie wybrano żadnego kursu!', 'Message dialog title'),
 'select_course_first':
 ('Wybierz kurs z listy kursów.', 'Message dialog message'),
 'set_published':
 ('Opublikowano zestaw typów wiedzy', 'Message dialog title/text'),
 'users_updated':
 ('Zaktualizowano listę uczestników',
  'Message dialog title/message'),
 'select_some_users':
 ('Wybierz użytkowników', 'Message dialog title/message'),
 'edit_course_info':
 ('Edytuj informację o kursie', 'Link'),
 'edit_course_participants':
 ('Edytuj listę uczestników kursu', 'Link'),
 'edit_course_resources':
 ('Edytuj źródła kursu', 'Link'),
 'date':
 ('Data', 'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('Uczestnicy kursu', 'Label'),
 'type_sets':
 ('Zestawy typów wiedzy', 'Label, plural'),
 'delete':
 ('Usuń', 'Button label'),
 'my_participation':
 ('Moje uczestnictwo', 'Label'),
 'my_notes':
 ('Moje notki', 'Link'),
 'my_artefacts':
 ('moje artefakty (dzieła)', 'Link'),
 'course_resources':
 ('Źródła do kursu', 'Label'),
 'add_typeset':
 ('Dodaj zestaw typów wiedzy', 'Link'),
 'tt_yellow':
 ('Żółty', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Jasno żółty', 'Knowledge type colour name'),
 'tt_orange':
 ('Pomarańczowy', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Jasno pomarańczowy', 'Knowledge type colour name'),
 'tt_red':
 ('Czerwony', 'Knowledge type colour name'),
 'tt_pink':
 ('Różowy', 'Knowledge type colour name'),
 'tt_purple':
 ('Purpurowy', 'Knowledge type colour name'),
 'tt_blue':
 ('Niebieski', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Jasno niebieski', 'Knowledge type colour name'),
 'tt_aqua':
 ('Aqua', 'Knowledge type colour name'),
 'tt_green':
 ('Zielony', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Jasno zielony', 'Knowledge type colour name'),
 'tt_gray':
 ('Szary', 'Knowledge type colour name'),
 'tt_white':
 ('Biały', 'Knowledge type colour name'),
 'edit_typeset':
 ('Edytowanie zestawu typów wiedzy', 'Heading'),
 'create_typeset':
 ('Tworzenie zestawu typów wiedzy', 'Heading'),
 'form':
 ('Formularz', 'Start of heading'),
 'title':
 ('Tytuł', 'Start of label'),
 'of_typeset':
 ('zestawu typów wiedzy', 'Ending of label'),
 'abbreviations_and_icons':
 ('skróty i symbole (ikonki)', 'Ending for heading'),
 'type':
 ('Typ wiedzy', 'Label'),
 'types':
 ('Typy wiedzy', 'Title'),
 'types_management':
 ('Zarządzanie typami wiedzy', 'Title'),
 'abbreviation':
 ('Skrót', 'Label'),
 'color':
 ('Kolor', 'Label'),
 'icon':
 ('Symbol (ikonka)', 'Label'),
 'starting_phrase':
 ('Fraza początkowa', 'Label'),
 'checklist':
 ('Lista kontrolna', 'Label'),
 'no_types_entered':
 ('Nie wpisano typów wiedzy. W zestawie musi być co najmniej jeden typ.',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ('Ograniczenia użycia', 'Heading sentence.'),
 'that_can_start_thread':
 ('które mogą rozpoczynać dyskusję',
  'End of label'),
 'viewing':
 ('wyświetlanie', 'Part of location bar'),
 'new_typeset_from':
 ('Duplikuj i edytuj zestaw typów wiedzy',
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Nie zakończone', 'Label'),
 'manage_types':
 ('Zarządzaj typami wiedzy', 'Link'),
 'finalize_typeset':
 ('Zmień status na "Zakończone"', 'Button label'),
 'are_you_sure':
 ('Czy na pewno chcesz skasować następujące kursy:',
  'Message dialog message'),
 'are_you_sure_ctx':
 ('Czy na pewno chcesz skasować ten kontekst kursu:',
  'Message dialog message'),
 'are_you_sure_tts':
 ('Czy na pewno chcesz skasować następujące zestawy typów wiedzy:',
  'Message dialog message'),
 'typeset_importing':
 ('Wybierz do importu skompresowany (zip) plik zawierający potrzebne Ci zestawy typów wiedzy.',
  'Instructions for typeset importing'),
 'typesets_imported':
 ('Nowe zestawy typów wiedzy zaimportowano.', 'Message'),
 'import_typeset':
 ('Import zestawu typów wiedzy', 'link'),
 'course_importing':
 ('Wybierz do importu skompresowany (zip) plik zawierający potrzebne Ci kursy.',
  'Instructions for course importing'),
 'courses_imported':
 ('Nowe kursy zaimportowano.', 'Message'),
 'import_course':
 ('Importuj kursy', 'link'),
 'course_imported':
 ('(importowane)', 'Appended to imported course names.'),
 'can_start_thread':
 ('Można zacząć wątek?',
  'column title in a table'),
 'can_be_followed':
 ('można dołączyć', 'column title in a table'),
 'use_each_type':
 ('Każdy typ wiedzy musi zostać dołączony do co najmniej jednego innego typu albo musi rozpoczynać wątek.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Źródła', 'Title for list of course resources'),
 'add_resource':
 ('Dodaj źródło', 'Link'),
 'editing_course_resources':
 ('Edytowanie źródeł do kursu', 'Title'),
 'remove_resource_verify':
 ('Czy na pewno chcesz usunąć to źródło?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ('Dodaj sesję improwizacji', 'link'),
 'jam_sessions':
 ('Sesje improwizacji:',
  'a list of jam session will listed after/under this label'),
 'jam_session':
 ('Sesja improwizacji', ''),
 'annotations':
 ('adnotacje', ''),
 'continue_with_version':
 ('Kontynuuj ze swoją wersją', 'button label'),
 'artefact':
 ('artefakt (dzieło)', ''),
 'viewing_annotations':
 ('wyświetlanie adnotacji', ''),
 'Annotations':
 ('Adnotacje:', 'Label, followed by a list of annotations under it'),
 'add_annotation':
 ('Dodaj adnotację', 'link'),
 'adding_jam_session':
 ('Dodawanie sesji improwizacji', ''),
 'edit_jam_session':
 ('Edytuj sesję improwizacji', ''),
 'editing_jam_session':
 ('Edytowanie sesji improwizacji', ''),
 'title_of_jam_session':
 ('Tytuł sesji improwizacji', 'label'),
 'type_of_jam_session':
 ('Typ sesji improwizacji', 'label'),
 'mutate_on_previous':
 ('Utwórz odmianę poprzedniego typu sesji',
  'type of jam session'),
 'explore_possibilities':
 ('Zbadaj możliwości', 'type of jam session'),
 'diverge_and_converge':
 ('Zróżnicuj & Upodobnij', 'type of jam session'),
 'description_of_jam_session':
 ('Opis sesji improwizacji', 'label'),
 'upload_the_starting_artefact':
 ('Dodaj (wgraj) początkowy artefakt (dzieło)', 'label'),
 'title_of_the_starting_artefact':
 ('Tytuł początkowego artefaktu', 'label'),
 'annotation_of_the_starting_artefact':
 ('Adnotacja do artefaktu początkowego', 'label'),
 'adding_artefact':
 ('Dodawanie artefaktu (dzieła)', ''),
 'title_of_the_artefact':
 ('Tytuł artefaktu', 'label'),
 'upload_file':
 ('Dodaj (wgraj) plik', 'label'),
 'you_adding_annotation':
 ('Dodajesz adnotację do artefaktu',
  'message in adding annotations form'),
 'adding_annotation':
 ('Dodawanie adnotacji do', ''),
 'to_jam_session':
 ('do sesji improwizacji', 'Part of a message'),
 'to_jam_artefact':
 ('do artefaktu improwizacji', 'Part of a message'),
 'unread_artefacts':
 ('nowych artefaktów', 'There is a number before this message'),
 'total_artefacts':
 ('wszystkich', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ('Czy na pewno chcesz skasować te sesje improwizacji:',
  'Message dialog message'),
 'are_you_sure_jam_session':
 ('Czy na pewno chcesz skasować tę sesję improwizacji z %s artefaktami?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 ('Usuń artefakt', 'Button label for removing jam artefact'),
 'restore_artefact':
 ('Przywróć artefakt',
  'Button label for restoring jam artefact'),
 'remove_annotation':
 ('Usuń wybrane adnotacje',
  'Button label for removing jam annotations'),
 'restore_annotation':
 ('Przywróć wybraną adnotację',
  'Button label for restoring jam annotations'),
 'removed_name':
 ('Usunięto:', 'Title/name for removed jam artefact'),
 'removed_message':
 ('Ten artefakt został usunięty przez %s w dniu %s.',
  "First placeholder is replaced by remover's name and the second by the date"),
 'removed_msg':
 ('Artefakt został usunięty',
  'Message shown to the teacher when she has removed an artefact.'),
 'removed_annotation_msg':
 ('Adnotacja została usunięta',
  'Message shown to the teacher when she has removed an annotation.'),
 'remove_verify':
 ('Czy na pewno chcesz usunąć ten artefakt? Twoje imię i bieżąca data zostaną zachowane i będą wyświetlane wraz z adnotacją o usunięciu każdemu, kto będzie chciał zobaczyć ten artefakt.',
  'Verification message shown when removing is attempted'),
 'remove_annotations_verify':
 ('Czy na pewno chcesz usunąć wybrane adnotacje? Twoje imię i bieżąca data zostaną zachowane i będą wyświetlane wraz z adnotacją o usunięciu każdemu, kto będzie chciał zobaczyć te adnotacje.',
  'Verification message shown when removing is attempted'),
 'removed_annotation_body':
 ('Ta adnotacja została usunięta przez %s w dniu %s.',
  "Body for removed annotation. First placeholder is replaced by remover's name and the second by the date"),
 'search_jam':
 ('Szukaj w Improwizacjach', 'Link label'),
 'searching_jam':
 ('Szukanie artefaktów improwizacji', 'Label'),
 'search_artefact_name':
 ('Nazwa artefaktu (dzieła)', 'Label in search form'),
 'search_artefact_author':
 ('Autor', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Adnotacje zawierające wyrazy',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ('Typ artefaktu',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Obraz', 'Artefact type'),
 'type_audio':
 ('Dźwięk', 'Artefact type'),
 'type_text':
 ('Tekst', 'Artefact type'),
 'type_html':
 ('Strona HTML', 'Artefact type'),
 'type_video':
 ('Video', 'Artefact type'),
 'type_archive':
 ('Archiwum', 'Artefact type'),
 'search_annotated_by':
 ('Adnotacje wg', 'Label in search form'),
 'search_results_author':
 ('Autora', 'Heading in search results table'),
 'search_results_jam_artefact':
 ('Artefaktu', 'Heading in search results table'),
 'search_results_jam_session':
 ('Sesji dżem', 'Heading in search results table')}

announce = {'comments':
 ('Komentarze', 'Notice / form heading'),
 'no_comments':
 ('Nie ma komentarzy', 'Notice'),
 'recent_comments':
 ('Ostatnie komentarze', 'Heading'),
 'no_entries':
 ('Nie ma ogłoszeń', 'Notice'),
 'recent_entries':
 ('Ostatnie ogłoszenia', 'Heading'),
 'trackbacks':
 ('Trackback-i', 'Notice'),
 'no_trackbacks':
 ('Nie ma trackback-ów', 'Notice'),
 'recent_trackbacks':
 ('Ostatnie trackback-i', 'Heading'),
 'send_trackback':
 ('Wyślij trackback do:', 'Part of message, followed by url'),
 'syndicate':
 ('Syndykuj tę witrynę (XML).', 'Link'),
 'log_in':
 ('Zaloguj się do Fle3.', 'Link'),
 'entries':
 ('Ogłoszenia', 'Heading'),
 'category':
 ('Kategoria', 'Heading'),
 'categories':
 ('Kategorie', 'Heading'),
 'no_categories':
 ('Nie ma kategorii', 'Notice'),
 'items':
 ('ogłoszeń', 'Part of message: nn items.'),
 'posted_by':
 ('Nadesłane przez', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%d.%m %H:%M', 'Short date format'),
 'dateformat':
 ('%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 ('o godz.', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('Skomentuj', 'Heading'),
 'name':
 ('Nazwa', 'Form heading'),
 'email':
 ('Email', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('Tytuł', 'Form heading'),
 'body':
 ('Treść ogłoszenia', 'Form heading'),
 'forget_personal':
 ('Zapomnij dane personalne', 'Button'),
 'teachers_and_tutors_only':
 ('tylko nauczyciele i tutorzy',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('Zapamiętać Twoje dane w ciasteczku (cookie)?', 'Label'),
 'Announcement':
 ('Komunikat', 'Category'),
 'ToDo':
 ('Do zrobienia', 'Category'),
 'Event':
 ('Wydarzenie', 'Category'),
 'continue_reading':
 ('Kontynuuj czytanie', 'Part of message, followed by entry title'),
 'missing1':
 ('brakuje', 'Part of message'),
 'missingn':
 ('brakuje', 'Part of message'),
 'comment_preview':
 ('Podgląd komentarza', 'Heading'),
 'search_results':
 ('Szukaj', 'Heading'),
 'search_for':
 ('Szukaj ogłoszeń dot.', 'Part of message'),
 'no_match':
 ('Nie znaleziono żadnych pozycji', 'Notice'),
 'about':
 ('O kursie', 'Title'),
 'archives':
 ('Archiwum', 'Title'),
 'search':
 ('Szukaj', 'Heading'),
 'search_help':
 ('Możesz użyć operatorów logicznych AND oraz OR.',
  'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

