# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_et.py,v 1.19 2005/02/22 09:33:04 tarmo Exp $
#
# Copyright 2001, 2002, 2003 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the Estonian translations for all Fle3 printable strings."""

common = {'language_name':
 ('Estonian', 'Name of this language'),
 'charset_encoding':
 ('iso8859-1',
  'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('VeebiLaud', 'Main tab for webtop'),
 'Knowledge_Building':
 ('TeadmusPaja', 'Main tab for knowledge building'),
 'Course_Management':
 ('Kursuste haldus', 'Main tab for course management'),
 'User_Management':
 ('Kasutajate haldus', 'Main tab for user management'),
 'Jamming':
 ('MeediaPaja', 'Main tab for jamming'),
 'Type_Management':
 ('TeadmusTüüpide haldus', 'Heading'),
 'cancel':
 ('Katkesta', 'Button label'),
 'submit':
 ('Sisesta', 'Button label'),
 'remove':
 ('Eemalda', 'Button label'),
 'next':
 ('Järgmine ->', 'Label for button'),
 'previous':
 ('<- Eelmine', 'Label for button'),
 'quick_submit':
 ('Kiirsisestus', ''),
 'ok':
 ('Ok', 'Button label'),
 'save':
 ('Salvesta', 'Button label'),
 'create':
 ('Loo', 'Button label'),
 'search':
 ('Otsi', 'Button label'),
 'webtop':
 ('VeebiLaud', ''),
 'description':
 ('Kirjeldus', 'Label'),
 'short_date_format_display':
 ('DD-MM-YYYY', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%d-%m-%Y',
  'Format string for short dates. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'timestamp_format':
 ('%H:%M %d-%m-%Y',
  'Format string for long timestamps. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'invite':
 ('Kutsu', ''),
 'add':
 ('Lisa', ''),
 'today':
 ('Täna', ''),
 'yesterday':
 ('Eile', ''),
 'groupfolder':
 ('kursuse kaust', 'Heading'),
 'dtml_reloaded':
 ('DTML uuendatud', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('Objekti DTML failid uuendatud', 'Message dialog text'),
 'dtmls_reloaded':
 ('DTMLid uuendatud', 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Kõik DTML failid uuendatud', 'Message dialog text'),
 'css_reloaded':
 ('Laadilehed uuendatud', 'Title for message dialog'),
 'css_files_reloaded':
 ('Objekti laadilehed uuendatud', 'Message text'),
 'error':
 ('Viga', ''),
 'warning':
 ('Hoiatus', ''),
 'invalid_url':
 ('Vigane url', 'Message title'),
 'invalid_url_message':
 ('It appears that the URL address you typed is incorrect.<br>Please check that it begins with http://, ftp://, mailto: or other Internet address protocol you want to use. Please note that you cannot just enter web page addresses like "www.myaddress.org" but that you need to specify the protocol first: "http://www.myaddress.org". If you are not sure about the protocol for your web address, try copying and pasting the full URL from your web browser.',
  'Message text'),
 'invalid_name':
 ('Vigane nimi', 'Message title'),
 'give_valid_name':
 ('Sisesta õige nimi', 'Message text'),
 'name_taken':
 ('Objekt nimega "%s" on juba olemas. Palun pane teine nimi.',
  'Message text, name inserted inside'),
 'edit':
 ('Muuda', 'Button label'),
 'you_are_in':
 ('Oled siin:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ('Sa ei täitnud kõiki vajalikke välju.', 'Erro message text'),
 'confirmation':
 ('Kinnitus', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Vigane sisestus', 'Message title'),
 'invalid_fields':
 ('Järgmised väljad sisaldavad vigaseid andmeid',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ('Vali kõigepealt mõni objekt välja', 'Message text'),
 'link_to_webtop':
 ('Ühenda VeebiLauaga', 'Link'),
 'proxy_to_webtop':
 ('Näita kursuse kausta VeebiLaual', 'Link'),
 'export':
 ('Eksport', 'Button label'),
 'import':
 ('Import', 'Button label'),
 'importing':
 ('Impordin', 'Heading start'),
 'megabyte':
 ('MB', 'Abbreviation for megabyte'),
 'kilobyte':
 ('kB', 'Abbreviation for kilobyte'),
 'logout':
 ('Välju', 'Link for logging out, also heading in logout dialogs'),
 'logout_pre3':
 ('Väljumiseks sulge oma brauser.', 'Instructions for logging out'),
 'any':
 ('Suvaline', 'Label used in search forms'),
 'course':
 ('kursus', 'Part of location path'),
 'language':
 ('Keel', ''),
 'announcements':
 ('Teated', 'Link/heading'),
 'sun':
 ('P', 'Weekday abbreviation'),
 'mon':
 ('E', 'Weekday abbreviation'),
 'tue':
 ('T', 'Weekday abbreviation'),
 'wed':
 ('K', 'Weekday abbreviation'),
 'thu':
 ('N', 'Weekday abbreviation'),
 'fri':
 ('R', 'Weekday abbreviation'),
 'sat':
 ('L', 'Weekday abbreviation'),
 'sunday':
 ('pŸühapäŠev', 'Weekday'),
 'monday':
 ('esmaspŠäev', 'Weekday'),
 'tuesday':
 ('teisipŠäev', 'Weekday'),
 'wednesday':
 ('kolmapŠäev', 'Weekday'),
 'thursday':
 ('neljapŠäev', 'Weekday'),
 'friday':
 ('reede', 'Weekday'),
 'saturday':
 ('laupŠäev', 'Weekday'),
 'January':
 ('jaanuar', 'Month'),
 'February':
 ('veebruar', 'Month'),
 'March':
 ('mŠärts', 'Month'),
 'April':
 ('aprill', 'Month'),
 'May':
 ('mai', 'Month'),
 'June':
 ('juuni', 'Month'),
 'July':
 ('juuli', 'Month'),
 'August':
 ('august', 'Month'),
 'September':
 ('september', 'Month'),
 'October':
 ('oktoober', 'Month'),
 'November':
 ('november', 'Month'),
 'December':
 ('detsember', 'Month'),
 'remove_q':
 ('Kustuta?', 'Question')}

kb = {'month':
 ('kuu', ''),
 'week':
 ('nädal', ''),
 'you_have_not_replied_to':
 ('Sa ei ole vastanud neile', 'followed by a list of persons'),
 'total_replies':
 ('Kokku vastuseid:', 'followed by number'),
 'total_notes_written':
 ('Kokku märkusi kirjutatud:', 'followed by number'),
 'graph_type':
 ('Graafiku tüüp: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('teadmustüübi järgi', 'graph type'),
 'adding_resource':
 ('Materjali lisamine', 'part of browser title'),
 'replies':
 ('vastused', 'graph type'),
 'display_by':
 ('kuvamine:', 'Label for timescale (week/month) selection'),
 'modifying_resource':
 ('allika muutmine', 'part of browser title'),
 'title_resource':
 ('Pealkiri', 'The title of resource'),
 'author_resource':
 ('Autor', 'The author of the resource'),
 'url':
 ('URL', 'Resource URL'),
 'location':
 ('Asukoht', 'Resource location'),
 'course_info':
 ('Kursuse info', 'Label for link to course details'),
 'create_context':
 ('Loo uus kontekst', 'Link to create new course context'),
 'hide_context':
 ('Peida kontekst', 'Link to hide a context from view'),
 'show_context':
 ('Näita konteksti', 'Link to show a hidden context'),
 'new_notes':
 ('uut märkust',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('sõnumit', 'Label for showing the number of notes'),
 'full_description':
 ('täispikk kirjeldus...', ''),
 'course':
 ('arutelu', "String 'course' in context display"),
 'context':
 ('kontekst', "String 'context' in context display"),
 'thread':
 ('lõim', "String 'thread' in context display"),
 'note':
 ('sõnum', "String 'note' in context display"),
 'start_thread':
 ('Alusta uut jutulõime', 'Link'),
 'short_description':
 ('Lühikirjeldus', 'Label'),
 'long_description':
 ('Pikem kirjeldus', 'Label'),
 'full_description':
 ('Täispikk kirjeldus', 'Label'),
 'select':
 ('Vali',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('teadmustüüp', 'Label'),
 'add_note':
 ('Lisa sõnum', 'Button label'),
 'show_notes':
 ('Järjesta sõnumid', 'Heading start'),
 'show_thread':
 ('lõimede', 'heading finish'),
 'show_type':
 ('teadmustüüpide', 'heading finish'),
 'show_author':
 ('autorite', 'heading finish'),
 'show_date':
 ('aja järgi', 'heading finish'),
 'select_course':
 ('Vali kursus', 'Label, followed by a drop-down list of available courses'),
 'change':
 ('Vaheta', 'Button label'),
 'creating_context':
 ('Loo uus kontekst', 'Title, followed by the course name'),
 'editing_context':
 ('Muuda konteksti', 'Title, followed by the course name'),
 'title_of_context':
 ('Konteksti pealkiri', 'Label'),
 'type_set':
 ('Teadmustüüp', 'Label'),
 'creating_note_in':
 ('Lisa sõnum arutelusse', 'Title, followed by course context name'),
 'course_context':
 ('arutelu kontekst', 'Label for course context'),
 'you_are_replying_to':
 ('Vastad', 'Label'),
 'title_of_note':
 ('Pealkiri', 'Label'),
 'message_body':
 ('Sõnumi tekst', 'Label'),
 'current_image':
 ('Praegune pilt', 'Label'),
 'replace_with':
 ('Asenda järgmisega', 'Label for image replacement in note edit'),
 'add_image':
 ('Lisa pilt', 'Label'),
 'title_of_image':
 ('Pildi pealkiri', 'Label'),
 'add_link':
 ('Lisa veebiviide (URL)', 'Label'),
 'title_of_link':
 ('Veebiviite pealkiri', 'Label'),
 'preview':
 ('Eelvaade', 'Button label'),
 'previewing_note':
 ('Sõnumi eelvaade arutelus',
  'Title/heading, followed by course context name'),
 'publish':
 ('Avalda', 'Button label'),
 'search_kb':
 ('Otsi TeadmusPajast', 'Link label'),
 'searching_kb':
 ('Otsing TeadmusPaja sõnumitest', 'Label'),
 'search_author':
 ('Autor', 'Label'),
 'search_notes_words':
 ('Sõnumid, mis sisaldavad sõnu', 'Label'),
 'search_context':
 ('Kontekst', 'Label'),
 'search_tt':
 ('Teadmustüüp', 'Label'),
 'search_note':
 ('Sõnum', 'Label'),
 'current_note':
 ('Antud sõnum', 'Label'),
 'you_didnt_select_type':
 ('Sa ei valinud teadmustüüpi.', 'Title'),
 'go_back':
 ('Mine tagasi', 'Start of message, rendered into a link'),
 'and_select_type':
 ('ja vali oma sõnumile vastav teadmustüüp.', 'Rest of message'),
 'inline_notes':
 ('Näita kõigi märkuste tekste.', 'Link'),
 'outline_notes':
 ('Peida kõigi märkuste tekstid.', 'Link'),
 'view_info':
 ('info', 'Part of location bar'),
 'edit_context':
 ('Muuda konteksti', 'Link'),
 'to_note':
 ('sõnumile', 'Part of a message'),
 'full_thread_no':
 ('Näita üksnes esimesi märkusi', 'Link'),
 'full_thread_yes':
 ('Näita kogu jutulõime', 'Link'),
 'remove':
 ('Kustuta', 'Button label for removing notes'),
 'restore':
 ('Taasta', 'Button label for restoring notes'),
 'remove_form_title':
 ('Sõnumi kustutamine', 'Title for note removing form'),
 'remove_form_label':
 ('Kustutan sõnumi',
  'Explanation in remove form, followed by note subject'),
 'removed_msg':
 ('Sõnum kustutatud',
  'Message shown to the teacher when she has removed a note.'),
 'remove_verify2':
 ('Kas oled kindel, et soovid kustutada selle sõnumi? Sinu nimi, kuupäev ja kustutamise põhjus kuvatakse kustutatud sõnumi autorile.',
  'Verification message shown when removing is attempted'),
 'remove_explanation':
 ('Kustutamise põhjendus', 'Label for removee explanation text area'),
 'removed_subject':
 ('Kustutatud', 'Title/subject for removed notes'),
 'removed_body':
 ('%s kustutas selle sõnumi %s.',
  "Body for removed messages. First placeholder is replaced by remover's name and the second by the date"),
 'notes_from_day':
 ('Sõnumid alates', 'Start of heading, followed by a date'),
 'previous':
 ('Eelmine', 'Link label'),
 'next':
 ('Järgmine', 'Link label'),
 'who_has_read':
 ('Kes on seda lugenud?', 'Link label'),
 'last_read':
 ('Viimati loetud', 'Label'),
 'times_read':
 ('Loetud kordi', 'Label'),
 'back':
 ('< tagasi', 'Link label'),
 'unread_to_read_msg':
 ('Kõik sõnumid selles lõimes on märgitud loetuks.',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Märgi kõik loetuks.', 'text in a button'),
 'creating_groupfolder':
 ('Loon uue kursuse kausta', 'Heading start'),
 'title_groupfolder':
 ('Kausta nimi', 'Label'),
 'flea_asks':
 ('See teadmustüüp sobib kui:',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Kas muuta teadmustüüpi?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ('See on ainus lubatud teadmustüüp.',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Muuda', 'Button label'),
 'down_to_note':
 ('Alla', 'Link label'),
 'use_roleplay':
 ('Kasuta rollimängu selles kontekstis',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('Rollimängu rollide määramine',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 ('Kursused', "Heading for user's course list"),
 'totals_notes':
 ('Sõnumeid',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ('Meediafaile',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s uut / %s kokku',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Lisa kaust', ''),
 'add_document':
 ('Lisa dokument', ''),
 'add_link':
 ('Lisa veebiviide', ''),
 'create_memo':
 ('Lisa memo', ''),
 'type':
 ('Tüüp', 'Link for sorting by type'),
 'title':
 ('Nimi', 'Link for sorting by name'),
 'date':
 ('Aeg', 'Link for sorting by date'),
 'size':
 ('Suurus', 'Link for sorting by size'),
 'remove':
 ('Eemalda', 'Button label'),
 'restore':
 ('Taasta', 'Button label'),
 'rename':
 ('Nimeta ümber', 'Button label'),
 'copy':
 ('Kopeeri', 'Button label'),
 'cut':
 ('Lõika', 'Button label'),
 'paste':
 ('Kleebi', 'Button label'),
 'delete':
 ('Kustuta', 'Button label'),
 'select_all':
 ('Vali kõik', 'Button label'),
 'trash':
 ('Prügikast', 'Label for trashcan'),
 'empty_trash':
 ('Tühjenda', 'Button label'),
 'adding_folder':
 ('Lisan kausta', 'Heading'),
 'title_of_folder':
 ('Kausta nimi', 'Label'),
 'viewing_memo':
 ('Memo kuvamine', 'Title'),
 'creating_memo':
 ('Lisa memo', 'Title'),
 'editing_memo':
 ('Muuda memo', 'Title'),
 'title_of_memo':
 ('Memo pealkiri', 'Label'),
 'content':
 ('Sisu', 'Label'),
 'show_memo_contents':
 ('Näita üksnes memo sisu', 'Link'),
 'adding_link':
 ('Veebiviite lisamine', 'Title'),
 'title_of_link':
 ('Viite pealkiri', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Dokument lisatud.', 'Status message'),
 'adding_document':
 ('Dokumendi lisamine', 'Title'),
 'upload_document':
 ('Dokumendi üleslaadimine', 'Label'),
 'title_of_document':
 ('Dokumendi pealkiri', 'Label'),
 'search_wt':
 ('Otsi VeebiLaudadelt', 'Link label'),
 'searching_wt':
 ('Otsing VeebiLaudadelt', 'Label'),
 'search_results':
 ('Tulemused', 'Label'),
 'new_search':
 ('Uus otsing', 'Label'),
 'search_title':
 ('Nimi', 'Label'),
 'search_owner':
 ('Omanik', 'Label'),
 'search_words':
 ('Objektid, mis sisaldavad sõnu', 'Label'),
 'search_object':
 ('Objekt', 'Label'),
 'search_folder':
 ('Kaust', 'Label'),
 'viewing_search_results':
 ('Otsingu tulemused', 'Label in the location path'),
 'anyone':
 ('Kõik', 'Label'),
 'webtop_link_added':
 ('Viide lisatud veebilauale', 'Message title'),
 'added_webtop_link':
 ('Viide %s "%s" lisati sinu veebilauale. Klõpsa OK.',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 ('Kursuse kaust valmis', 'Message title'),
 'added_proxy':
 ('Kursuse %s kaust on nüüd sinu veebilaualt kättesaadav. Klõpsa OK.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ('Ühtegi objekti polnud valitud!', 'Message dialog title'),
 'select_item_first':
 ('Vali vähemalt üks objekt.', 'Message dialog message'),
 'no_file_supplied':
 ('Ühtegi faili ei pakutud.', 'Message text'),
 'renaming':
 ('Ümbernimetamine', 'Title'),
 'invalid_names':
 ('Järgmised nimed on vigased/sobimatud:', 'Message dialog messsage'),
 'same_names':
 ('Andsid sama nime mitmele objektile.', 'Message dialog message'),
 'names_in_use':
 ('Järgmised nimed on juba kasutusel:', 'Message dialog message'),
 'information':
 ('Kasutaja info', 'Link'),
 'preferences':
 ('Seaded', 'Link'),
 'editing_preferences':
 ('Seadete muutmine', 'Title'),
 'shared_course_folder':
 ('Kursuse jagatud kaust',
  'Printed after the name of the group folder in webtop contents list.'),
 'quota_reached_title':
 ('Kvoot ületatud', 'Title'),
 'quota_reached':
 ('Ei saanud lõpetada toimingut, kuna sinu VeebiLaua kvoot on ületatud. Palun kustuta mõned objektid oma veebilaualt ja ürita uuesti.',
  'Message dialog message'),
 'obj_removed':
 ('(objekt on kustutatud)',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('&lt; tagasi', 'Link label')}

usermgmnt = {'user':
 ('kasutaja', 'part of browser title'),
 'adding_users':
 ('Kasutajate lisamine', 'Title'),
 'required_field':
 ('Kohustuslik täita', ''),
 'nickname':
 ('Hüüdnimi', 'Label'),
 'user_account':
 ('Kasutajakonto', 'Label'),
 'Confirm':
 ('Kinnita', ''),
 'you_are_removing':
 ('Eemalda', ''),
 'invite_user':
 ('Saada kutse', ''),
 'invite_users':
 ('Kutsu uusi kasutajaid', 'Heading for invitation form'),
 'email_addresses':
 ('E-posti aadressid', ''),
 'separate_with_comma':
 ('( eralda komaga: , )', ''),
 'Invitation_message':
 ('Kutse tekst', ''),
 'Invitation_language':
 ('Mis keeles kutse on', ''),
 'Courses_to_invite_to':
 ('Mis kursusele kutsutakse', ''),
 'Freeze':
 ('Külmuta', ''),
 'Remove':
 ('Eemalda', ''),
 'role':
 ('Roll', 'label'),
 'role_staff':
 ('Personal', 'Global role stuff'),
 'role_user':
 ('Kasutaja', 'Global role user'),
 'role_fleadmin':
 ('FLE haldur', 'Global role fleadmin'),
 'invite_again':
 ('Kutsu uuesti', 'Button label'),
 'warning':
 ('Hoiatus', 'Heading'),
 'want_remove_users':
 ('Kas soovid eemaldada järgmised kasutajad?', 'Complete question'),
 'invited_user_manage':
 ('Kutsutud kasutajate haldamine', 'Title'),
 'info_user':
 ('Kasutajainfo ', 'Title for user info page, prefix before usre name'),
 'edit_user':
 ('Muuda kasutajainfot', 'Link'),
 'editing':
 ('Muuda', 'Heading for user edit, inserted before user name'),
 'image_of_user':
 ('Kasutaja pilt', 'Label'),
 'upload_image_of_user':
 ('Laadi pilt serverile', 'Label'),
 'or_link_to_image':
 ('või sisesta pildi veebiaadress (URL)',
  'Label, continuing from the upload label'),
 'add_user':
 ('Uue kasutaja lisamine', 'Title'),
 'webtop_bg':
 ('Vali veebilaua taustapilt', 'Label'),
 'upload_webtop_bg':
 ('või laadi serverile oma taustapilt',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Ootel kasutajakandidaadid', ''),
 'add_user':
 ('Lisa kasutaja', ''),
 'Unfreeze':
 ('Sulata üles', ''),
 'Users':
 ('Kasutajad', ''),
 'gsm':
 ('Mobiil', ''),
 'last_name':
 ('Perekonnanimi', ''),
 'first_name':
 ('Eesnimi', ''),
 'city':
 ('Linn', ''),
 'organization':
 ('Eriala', ''),
 'professional_interests':
 ('Hobid', ''),
 'email':
 ('E-post', ''),
 'phone':
 ('Tel.', ''),
 'url_to_photo':
 ('Foto URL', ''),
 'country_menu_default':
 ('Vali riik', ''),
 'group_menu_default':
 ('Vali rühm', 'Default value for drop-down menu'),
 'address':
 ('Aadress', ''),
 'address1':
 ('Aadressirida 1', ''),
 'address2':
 ('Aadressirida 2', ''),
 'personal_interests':
 ('Huvialad', ''),
 'quote':
 ('Moto', ''),
 'homepage':
 ('Kodulehekülg', ''),
 'upload':
 ('Laadi üles', ''),
 'group':
 ('Rühm', ''),
 'password':
 ('Salasõna', ''),
 'background':
 ('Taust', ''),
 'country':
 ('Riik', ''),
 'reserved_nickname':
 ('Vabandame, kuid see nimi/kasutajatunnus on juba kasutusel.', 'Message'),
 'password_mismatch':
 ('Salasõna kordus erines esialgsest.', 'Message'),
 'could_not_send_invitation':
 ('Ei suutnud kutset saata. Kontrolli, kas väljamineva e-posti server (MailHost) on korrektselt määratletud.',
  'Error message'),
 'invitations_sent':
 ('Kutsed saadetud', 'Message title'),
 'invitations_sent_to':
 ('Kutsed saadeti %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 ('Kutsed jäid saatmata: %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Kasutajad eemaldatud', 'Message title'),
 'removed_users':
 ('Eemaldati kasutajad: %s', 'Message, list inserted inside'),
 'not_removed_users':
 ('Ei suutnud eemaldada järgmisi kasutajaid: %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 ('Korduskutsed saadetud', 'Message title'),
 're_invitations_sent_to':
 ('Kordusutsed saadetud to %s kasutajale. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Ootel kasutajakandidaadid eemaldatud', 'Message title'),
 'pending_removed_users':
 ('Eemaldati ootel kasutajakandidaadid: %s', 'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Ei suudetud eemaldada järgmisi kasutajakandidaate: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ('Kutse virtuaalsesse õpikeskkonda FLE',
  'Subject for invitation messages'),
 'invitation_header':
 ('Kutse', 'Header for invitation messages'),
 'invitation_footer':
 ('Palun suuna oma Interneti-brauser aadressile: ',
  'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Tere tulemast FLE õpikeskkonda. Palun täida kasutaja-ankeet.',
  'Welcome message used in invitation registration form'),
 'uname':
 ('Kasutaja nimi', 'Label used in invitation registration form'),
 'registration_failed':
 ('Registreerumine ebaõnnestus',
  "Title used when invited user can't register."),
 'invitation_key_used':
 ('See kutse on aegunud või juba ära kasutatud. Kui registreerumine ebaõnnestus, võta uue kutse saamiseks ühendust oma koolitajaga.',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ('Autentimine ebaõnnestus - vale võti',
  "Message telling that the authentication key isn't valid."),
 'after_submit_give_name_and_passwd2':
 ('Pärast <b>Saada</b>-nupul klõpsamist sisesta oma kasutajatunnus ja salasõna.',
  'Message'),
 'show_frozen':
 ('Näita külmutatud kasutajaid', 'Link to show all users'),
 'show_active':
 ('Näita ainult aktiivseid kasutajaid', 'Link to show only active users'),
 'frozen':
 ('Külmutatud', 'User status code'),
 'no_email':
 ('E-posti aadress puudub', 'Message title'),
 'no_email_explanation':
 ('Sa ei saa saata e-posti, kuna sa pole sisestanud oma e-posti aadressi kasutajainfo lehele.',
  'Message text'),
 'passwd_changed':
 ('Salasõna muudetud', 'Message title'),
 'external_user_database_explanation':
 ('Sinu Fle3 kasutab välist kasutajate andmebaasi. Kasutajate lisamiseks süsteemi pead sa lisama nad enne sellesse andmebaasi.',
  'Explanation shown in place of "add users", "invite user" etc. links.'),
 'passwd_changed_explanation2':
 ('Muutsid oma salasõna: su brauser küsib uuesti kasutajatunnust ja salasõna.',
  'Message text')}

coursemgmnt = {'course':
 ('kursus', 'part of browser title'),
 'courses':
 ('Kursused', 'Title'),
 'create_course':
 ('Lisa kursus', 'Link'),
 'edit_course':
 ('Muuda kursus', 'Button label'),
 'edit_participants':
 ('Osalejad', 'Button label'),
 'creating_course':
 ('Uue kursuse lisamine', 'Title'),
 'editing_course':
 ('Kursuse muutmine', 'Title'),
 'course_title':
 ('Kursuse nimi', 'Label'),
 'organization':
 ('Osakond', 'Label'),
 'methods':
 ('Hindamine', 'Label'),
 'starting_date':
 ('Kursuse algus', 'Label'),
 'ending_date':
 ('Kursuse lõpp', 'Label'),
 'create_groupfolder':
 ('Loo kursuse kaust', 'Link'),
 'create_announcements':
 ('Teadete lisamine', 'Link'),
 'edit_announcements':
 ('Teadete muutmine', 'Link'),
 'add_announcement':
 ('Lisa teade', 'Link'),
 'adding_announcement':
 ('Teadete lisamine', 'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('Kas oled kindel, et soovid selle teate kustutada?', 'Question'),
 'editing_announcements':
 ('Teadete muutmine', 'Heading'),
 'viewing_announcements':
 ('Teated kursusel %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ('Osalejate lisamine kursusele',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('Kui kursusel osalejad pole registreerunud FLE kasutajaks', 'Message'),
 'new_participants_to_system':
 ('uued kasutajad FLE serveris', 'Part of a phrase'),
 'by_email':
 ('e-posti aadressi järgi', 'Part of a phrase'),
 'manually':
 ('käsitsi', 'Part of a phrase'),
 'fle_users':
 ('FLE kasutajad', 'Heading'),
 'down':
 ('Alla', 'Button label'),
 'up':
 ('Üles', 'Button label'),
 'teachers':
 ('Õpetajad', 'Heading'),
 'tutors':
 ('Tuutorid', 'Heading'),
 'students':
 ('Õppijad', 'Heading'),
 'add_button':
 ('Lisa ->', 'Button label'),
 'remove_button':
 ('<- Eemalda', 'Button label'),
 'viewing_course':
 ('kursuse', 'Part of a phrase in location path'),
 'viewing_course_resources':
 ('Kursuse %s materjalide vaatamine',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 ('info', 'Part of a phrase in location path'),
 'no_course_selected':
 ('Ühtegi kursust polnud valitud!', 'Message dialog title'),
 'select_course_first':
 ('Vali nimekirjast üks kursus.', 'Message dialog message'),
 'set_published':
 ('Teadmustüüp lisatud', 'Message dialog title/text'),
 'users_updated':
 ('Kasutajate nimekiri uuendatud', 'Message dialog title/message'),
 'select_some_users':
 ('Vali mõned kasutajad', 'Message dialog title/message'),
 'edit_course_info':
 ('Muuda kursuse infot', 'Link'),
 'edit_course_participants':
 ('Muuda osalejate nimekirja', 'Link'),
 'edit_course_resources':
 ('Kursuse materjalide muutmine', 'Link'),
 'date':
 ('Kuupäev',
  'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('Kursusel osalejad', 'Label'),
 'type_sets':
 ('Teadmustüübid', 'Label, plural'),
 'delete':
 ('Kustuta', 'Button label'),
 'my_participation':
 ('Minu osalemine', 'Label'),
 'my_notes':
 ('Minu sõnumid', 'Link'),
 'my_artefacts':
 ('Minu meediafailid', 'Link'),
 'course_resources':
 ('Kursuse materjalid', 'Label'),
 'add_typeset':
 ('Lisa teadmustüüp', 'Link'),
 'tt_yellow':
 ('Kollane', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Helekollane', 'Knowledge type colour name'),
 'tt_orange':
 ('Oranzh', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Heleoranzh', 'Knowledge type colour name'),
 'tt_red':
 ('Punane', 'Knowledge type colour name'),
 'tt_pink':
 ('Roosa', 'Knowledge type colour name'),
 'tt_purple':
 ('Lilla', 'Knowledge type colour name'),
 'tt_blue':
 ('Sinine', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Helesinine', 'Knowledge type colour name'),
 'tt_aqua':
 ('Aqua', 'Knowledge type colour name'),
 'tt_green':
 ('Roheline', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Heleroheline', 'Knowledge type colour name'),
 'tt_gray':
 ('Hall', 'Knowledge type colour name'),
 'tt_white':
 ('Valge', 'Knowledge type colour name'),
 'edit_typeset':
 ('Teadmustüübi muutmine', 'Heading'),
 'create_typeset':
 ('Uue teadmustüübi lisamine', 'Heading'),
 'form':
 ('Vorm', 'Start of heading'),
 'title':
 ('Nimi', 'Start of label'),
 'of_typeset':
 ('teadmustüübile.', 'Ending of label'),
 'abbreviations_and_icons':
 ('lühendid ja ikoonid', 'Ending for heading'),
 'type':
 ('Teadmustüüp', 'Label'),
 'types':
 ('Teadmustüübid', 'Title'),
 'types_management':
 ('Teadmustüüpide haldus', 'Title'),
 'abbreviation':
 ('Lühend', 'Label'),
 'color':
 ('Värv', 'Label'),
 'icon':
 ('Ikoon', 'Label'),
 'starting_phrase':
 ('Algusfraas', 'Label'),
 'checklist':
 ('Ankeet', 'Label'),
 'no_types_entered':
 ('Sa ei lisanud ühtegi teadmustüüpi, pead lisama vähemalt ühe.',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ('Kasutamise piirangud', 'Heading sentence.'),
 'viewing':
 ('vaade', 'Part of location bar'),
 'that_can_start_thread':
 ('kes võib algatada diskussiooni', 'End of label'),
 'new_typeset_from':
 ('Tee olemasolevast teadmustüübist koopia ja muuda seda',
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Lõpetamata', 'Label'),
 'manage_types':
 ('Teadmustüüpide haldamine', 'Link'),
 'finalize_typeset':
 ('Muuda staatus - Lõpetatuks', 'Button label'),
 'are_you_sure':
 ('Kas oled kindel, et soovid kustutada järgmised kursused:',
  'Message dialog message'),
 'are_you_sure_ctx':
 ('Kas oled kindel, et soovid kustutada järgmised kontekstid:',
  'Message dialog message'),
 'are_you_sure_tts':
 ('Kas oled kindel, et soovid kustutada järgmised teadmustüübid:',
  'Message dialog message'),
 'typeset_importing':
 ('Vali pakitud (zip) teadmustüüpe sisaldav fail, mida soovid importida.',
  'Instructions for typeset importing'),
 'typesets_imported':
 ('Uued teadmustüübid imporditi.', 'Message'),
 'import_typeset':
 ('Impordi teadmustüübistik', 'link'),
 'course_importing':
 ('Vali pakitud eksportfail kursuse sisuga, mida soovid importida.',
  'Instructions for course importing'),
 'courses_imported':
 ('Uued kursused imporditi.', 'Message'),
 'import_course':
 ('Impordi kursus', 'link'),
 'course_imported':
 ('(imporditud)', 'Appended to imported course names.'),
 'can_start_thread':
 ('Saab alustada jutulõime', 'column title in a table'),
 'can_be_followed':
 ('Sellele võib järgneda', 'column title in a table'),
 'use_each_type':
 ('Igale teadmustüübile peab järgnema teine tüüp või uue lõime algus.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Materjalid', 'Title for list of course resources'),
 'add_resource':
 ('Lisa materjal', 'Link'),
 'editing_course_resources':
 ('Kursuse materjalide toimetamine', 'Title'),
 'remove_resource_verify':
 ('Oled sa kindel, et tahad selle materjali kustutada?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ('Lisa meediaprojekt', 'link'),
 'jam_sessions':
 ('Projekt:', 'a list of jam session will listed after/under this label'),
 'jam_session':
 ('projekt', ''),
 'annotations':
 ('kommentaarid', ''),
 'continue_with_version':
 ('Lisa oma versioon', 'button label'),
 'artefact':
 ('meediafail', ''),
 'viewing_annotations':
 ('kommentaaride kuvamine', ''),
 'Annotations':
 ('Kommentaarid:', 'Label, followed by a list of annotations under it'),
 'add_annotation':
 ('Lisa kommentaar', 'link'),
 'adding_jam_session':
 ('Lisa uus projekt', ''),
 'edit_jam_session':
 ('Muuda meediaprojekti', ''),
 'editing_jam_session':
 ('Meediaprojekti muutmine', ''),
 'title_of_jam_session':
 ('Projekti nimi', 'label'),
 'type_of_jam_session':
 ('Projekti tüüp', 'label'),
 'mutate_on_previous':
 ('Eelnevast tuletatud', 'type of jam session'),
 'explore_possibilities':
 ('Vabas vormis', 'type of jam session'),
 'diverge_and_converge':
 ('Erista ja ühenda', 'type of jam session'),
 'description_of_jam_session':
 ('Projekti kirjeldus', 'label'),
 'upload_the_starting_artefact':
 ('Laadi üles esimene meediafail', 'label'),
 'title_of_the_starting_artefact':
 ('Esimese faili nimi', 'label'),
 'annotation_of_the_starting_artefact':
 ('Kommentaar esimese meediafaili juurde', 'label'),
 'adding_artefact':
 ('Lisa uus meediafail', ''),
 'title_of_the_artefact':
 ('Meediafaili nimi', 'label'),
 'upload_file':
 ('Laadi fail üles', 'label'),
 'you_adding_annotation':
 ('Kommentaari lisamine meediafailile', 'message in adding annotations form'),
 'adding_annotation':
 ('kommentaari lisamine', ''),
 'to_jam_session':
 ('projektis', 'Part of a message'),
 'to_jam_artefact':
 ('meediafailile', 'Part of a message'),
 'unread_artefacts':
 ('uut meediafaili', 'There is a number before this message'),
 'total_artefacts':
 ('meediafaili', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ('Kas oled kindel, et soovid kustutada järgmised projektid:',
  'Message dialog message'),
 'are_you_sure_jam_session':
 ('Kas oled kindel, et soovid kustutada selle meediaprojekti koos %s meediafailiga?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 ('Kustuta objekt', 'Button label for censoring jam artefact'),
 'restore_artefact':
 ('Taasta objekt', 'Button label for uncensoring jam artefact'),
 'remove_annotation':
 ('Kustuta valitud kommentaarid',
  'Button label for censoring jam annotations'),
 'restore_annotation':
 ('Taasta kustutatud kommentaarid',
  'Button label for uncensoring jam annotations'),
 'removed_name':
 ('Kustutatud', 'Title/name for censored jam artefact'),
 'removed_message':
 ('See meediafail kustutati %s poolt %s.',
  "First placeholder is replaced by censorer's name and the second by the date"),
 'removed_msg':
 ('Meediafail on kustutatud',
  'Message shown when teacher censores an artefact.'),
 'removed_annotation_msg':
 ('Kommentaar on kustutatud',
  'Message shown when teacher censores an annotation.'),
 'remove_verify':
 ('Kas oled kindel, et soovid kustutada seda objekti? Sinu nimi kuvatakse kõigile kursuslastele kustutatud objekti nime kõrval.',
  'Verification message shown when censoring is attempted'),
 'remove_annotations_verify':
 ('Kas oled kindel, et soovid kustutada seda kommentaari? Sinu nimi kuvatakse kõigile kursuslastele kustutatud kommnetaari pealkirja kõrval.',
  'Verification message shown when censoring is attempted'),
 'removed_annotation_body':
 ('See kommentaar kustutati %s poolt %s.',
  "Body for censored annotation. First placeholder is replaced by censorer's name and the second by the date"),
 'search_jam':
 ('Otsi MeediaPajast', 'Link label'),
 'searching_jam':
 ('Otsin meediafaile', 'Label'),
 'search_artefact_name':
 ('meediafaili nimi', 'Label in search form'),
 'search_artefact_author':
 ('Autor', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Kommentaar, mis sisaldab sõnu',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ('Meediafaili tüüp',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Pilt', 'Artefact type'),
 'type_audio':
 ('Audio', 'Artefact type'),
 'type_text':
 ('Tekst', 'Artefact type'),
 'type_html':
 ('Html', 'Artefact type'),
 'type_video':
 ('Video', 'Artefact type'),
 'type_archive':
 ('Pakitud', 'Artefact type'),
 'search_annotated_by':
 ('Kommenteeritud', 'Label in search form'),
 'search_results_author':
 ('Autor', 'Heading in search results table'),
 'search_results_jam_artefact':
 ('Meediafail', 'Heading in search results table'),
 'search_results_jam_session':
 ('Meediaprojekt', 'Heading in search results table')}

announce = {'comments':
 ('Kommentaarid', 'Notice / form heading'),
 'no_comments':
 ('Kommentaarid puuduvad.', 'Notice'),
 'recent_comments':
 ('Viimased kommentaarid', 'Heading'),
 'no_entries':
 ('Teated puuduvad.', 'Notice'),
 'recent_entries':
 ('Viimased teated', 'Heading'),
 'trackbacks':
 ('Viitamised', 'Notice'),
 'no_trackbacks':
 ('Viitamised puuduvad.', 'Notice'),
 'recent_trackbacks':
 ('Viimased viitamised', 'Heading'),
 'send_trackback':
 ('Palun saatke viitamised:', 'Part of message, followed by url'),
 'syndicate':
 ('Loe XML voona.', 'Link'),
 'log_in':
 ('Logi Fle3 keskkonda', 'Link'),
 'entries':
 ('Teated', 'Heading'),
 'category':
 ('Teema', 'Heading'),
 'categories':
 ('Teemad', 'Heading'),
 'no_categories':
 ('Teemad puuduvad', 'Notice'),
 'items':
 ('teadet', 'Part of message: nn items.'),
 'posted_by':
 ('Postitas', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%m/%d %H:%M', 'Short date format'),
 'dateformat':
 ('%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 ('', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('Lisa kommentaar', 'Heading'),
 'name':
 ('Nimi', 'Form heading'),
 'email':
 ('E-post', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('Pealkiri', 'Form heading'),
 'body':
 ('Teate sisu', 'Form heading'),
 'forget_personal':
 ('Unusta isiklik informatsioon', 'Button'),
 'teachers_and_tutors_only':
 ('Ainult õpetajatele ja tuutoritele',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('Kas säilitada sinu isiklikku infot?', 'Label'),
 'Announcement':
 ('Teade', 'Category'),
 'ToDo':
 ('Töö', 'Category'),
 'Event':
 ('Sündmus', 'Category'),
 'continue_reading':
 ('Jätka lugemist', 'Part of message, followed by entry title'),
 'missing1':
 ('puudub', 'Part of message'),
 'missingn':
 ('puuduvad', 'Part of message'),
 'comment_preview':
 ('Kommentaari eelvaade', 'Heading'),
 'search_results':
 ('Otsingu tulemused', 'Heading'),
 'search_for':
 ('Otsi teateid', 'Part of message'),
 'no_match':
 ('Midagi ei leitud', 'Notice'),
 'about':
 ('Teadmiseks', 'Title'),
 'archives':
 ('Arhiivid', 'Title'),
 'search':
 ('Otsing', 'Heading'),
 'search_help':
 ('Sa võid kasutada otsingus AND/OR.', 'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

