# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_fr.py,v 1.86 2005/01/15 11:07:36 tarmo Exp $
#
# Copyright 2001, 2002, 2003 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the french translations for all FLE printable strings."""

common = {'language_name':
 ('Francais', 'Name of this language'),
 'charset_encoding':
 ('iso-8859-1',
  'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('Pupitre', 'Main tab for webtop'),
 'Knowledge_Building':
 ('Petite fabrique du savoir', 'Main tab for knowledge building'),
 'Course_Management':
 ('Gestion de cours', 'Main tab for course management'),
 'User_Management':
 ('Gestion utilisateur', 'Main tab for user management'),
 'Jamming':
 ('Improvisation', 'Main tab for jamming'),
 'Type_Management':
 ("Gestion des types d'élément pédagogique", 'Heading'),
 'cancel':
 ('annuler', 'Button label'),
 'submit':
 ('Valider', 'Button label'),
 'remove':
 ('Effacer', 'Button label'),
 'next':
 ('Suivant ->', 'Label for button'),
 'previous':
 ('<- Précédent', 'Label for button'),
 'quick_submit':
 ('Valider', ''),
 'ok':
 ('Ok', 'Button label'),
 'save':
 ('Sauvegarder', 'Button label'),
 'create':
 ('Créer', 'Button label'),
 'search':
 ('Chercher', 'Button label'),
 'webtop':
 ('Pupitre', ''),
 'description':
 ('description', 'Label'),
 'short_date_format_display':
 ('aaaa.mm.jj', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%d/%m/%Y', 'Format string for short dates'),
 'timestamp_format':
 ('%d/%m/%Y %H:%M', 'Format string for long timestamps'),
 'invite':
 ('Inviter', ''),
 'add':
 ('Ajouter', ''),
 'today':
 ("Aujourd'hui", ''),
 'yesterday':
 ('Hier', ''),
 'groupfolder':
 ('Dossier du cours', 'Heading'),
 'dtml_reloaded':
 ('DTML rechargement', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('rechargement des fichiers DTML', 'Message dialog text'),
 'dtmls_reloaded':
 ('DTML rechargement', 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Rechargement de tous les fichiers DTML', 'Message dialog text'),
 'css_reloaded':
 ('Rechargement des CSS', 'Title for message dialog'),
 'css_files_reloaded':
 ('Rechargement des fichiers CSS', 'Message text'),
 'error':
 ('Erreur', ''),
 'warning':
 ('Attention', ''),
 'invalid_url':
 ('URL invalide', 'Message title'),
 'invalid_url_message':
 ('Il Semble que l\'adresse URL que vous avez entrée est incorrecte.<br>Verifiez, s\'il vous plait qu\'elle commence avec http://, ftp://, mailto: ou tout autre protocole internet que vous désirez utiliser. Notez que vous ne pouvez pas entrer simplement une adresse internet telle que "www.mon_adresse.org" mais que vous devez spécifier le protocole avant: "http://www.mon_adresse.org". Si vous n\'êtes pas sure du protocole pour votre adressse internet, essayez de copier and coller l\'URL complet inscrit dans la barre d\'adresse de votre web browser.',
  'Message text'),
 'invalid_name':
 ('Nom invalide', 'Message title'),
 'give_valid_name':
 ('Donnez un nom valide', 'Message text'),
 'name_taken':
 ('Le nom "%s" a été inséré.',
  'Message text, name inserted inside'),
 'edit':
 ('Editer', 'Button label'),
 'you_are_in':
 ('Vous êtes dans:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ("Vous n'avez pas rempli tous les champs obligatoires.", 'Erro message text'),
 'confirmation':
 ('Confirmation', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Entrée invalide', 'Message title'),
 'invalid_fields':
 ('Les champs suivant ne sont pas valides',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ("Choisissez des objets d'abord", 'Message text'),
 'link_to_webtop':
 ('Poser un raccourci sur le pupitre', 'Link'),
 'proxy_to_webtop':
 ('Ajouter ce dossier de cours sur votre pupitre', 'Link'),
 'export':
 ('Exporter', 'Button label'),
 'import':
 ('Importer', 'Button label'),
 'importing':
 ("En train d'importer,", 'Heading start'),
 'megabyte':
 ('MO', 'Abbreviation for megabyte'),
 'kilobyte':
 ('KO', 'Abbreviation for kilobyte'),
 'logout_pre3':
 ('Pour quitter, closez simplement votre browser.',
  'Instructions for logging out'),
 'logout':
 ('Quitter', 'Link for logging out'),
 'any':
 ('Tout', 'Label'),
 'course':
 ('cours', 'Part of location path'),
 'language':
 ('Langage', ''),
 'announcements':
 ('Annonces', 'Link/heading'),
 'sun':
 ('Dim', 'Weekday abbreviation'),
 'mon':
 ('Lun', 'Weekday abbreviation'),
 'tue':
 ('Mar', 'Weekday abbreviation'),
 'wed':
 ('Mer', 'Weekday abbreviation'),
 'thu':
 ('Jeu', 'Weekday abbreviation'),
 'fri':
 ('Ven', 'Weekday abbreviation'),
 'sat':
 ('Sam', 'Weekday abbreviation'),
 'sunday':
 ('Dimanche', 'Weekday'),
 'monday':
 ('Lundi', 'Weekday'),
 'tuesday':
 ('Mardi', 'Weekday'),
 'wednesday':
 ('Mercredi', 'Weekday'),
 'thursday':
 ('Jeudi', 'Weekday'),
 'friday':
 ('Vendredi', 'Weekday'),
 'saturday':
 ('Samedi', 'Weekday'),
 'January':
 ('Janvier', 'Month'),
 'February':
 ('Février', 'Month'),
 'March':
 ('Mars', 'Month'),
 'April':
 ('Avril', 'Month'),
 'May':
 ('Mai', 'Month'),
 'June':
 ('Juin', 'Month'),
 'July':
 ('Juillet', 'Month'),
 'August':
 ('Aout', 'Month'),
 'September':
 ('Septembre', 'Month'),
 'October':
 ('Octobre', 'Month'),
 'November':
 ('Novembre', 'Month'),
 'December':
 ('Decembre', 'Month'),
 'remove_q':
 ('Effacer?', 'Question')}

kb = {'month':
 ('mois', ''),
 'week':
 ('semaine', ''),
 'you_have_not_replied_to':
 ("Vous n'avez pas répondu à", 'followed by a list of persons'),
 'total_replies':
 ("Nombre total de réponses aux notes posées par d'autres:",
  'followed by number'),
 'total_notes_written':
 ('Nombre total de notes écrites:', 'followed by number'),
 'graph_type':
 ('Type de Graphe: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('Type de connaissance', 'graph type'),
 'adding_resource':
 ('Ajout de la ressource', 'part of browser title'),
 'replies':
 ('Réponses', 'graph type'),
 'display_by':
 ('Affichage par:', 'Label for timescale (week/month) selection'),
 'modifying_resource':
 ('Modification de la ressource', 'part of browser title'),
 'title_resource':
 ('Titre', 'The title of resource'),
 'author_resource':
 ('Auteur', 'The author of the resource'),
 'url':
 ('URL', 'Resource URL'),
 'location':
 ('Endroit', 'Resource location'),
 'course_info':
 ('Détails du cours', 'Label for link to course details'),
 'create_context':
 ('Créer une séance de cours', 'Link to create new course context'),
 'hide_context':
 ('Rendre une séance invisible', 'Link to hide a context from view'),
 'show_context':
 ('Rendre une séance visible', 'Link to show a hidden context'),
 'new_notes':
 ('nouvelles notes',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('notes au total', 'Label for showing the number of notes'),
 'full_description':
 ('Description complète ...', ''),
 'course':
 ('cours', "String 'course' in context display"),
 'context':
 ('séance', "String 'context' in context display"),
 'thread':
 ('discussion', "String 'thread' in context display"),
 'note':
 ('note', "String 'note' in context display"),
 'start_thread':
 ('Début de la discussion', 'Link'),
 'short_description':
 ('Description courte', 'Label'),
 'long_description':
 ('Description longue', 'Label'),
 'full_description':
 ('Description complète', 'Label'),
 'select':
 ('Choisir',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('Type pédagogique', 'Label'),
 'add_note':
 ("Ajout d'une note", 'Button label'),
 'show_notes':
 ('Montrer les notes', 'Heading start'),
 'show_thread':
 ('Montrer les discussions', 'hading finish'),
 'show_type':
 ('Montrer les types', 'heading finish'),
 'show_author':
 ("Montrer l'auteur", 'heading finish'),
 'select_course':
 ('Choisissez un cours',
  'Label, followed by a drop-down list of available courses'),
 'show_date':
 ('Montrer la date', 'heading finish'),
 'creating_context':
 ('Créer une séance', 'Title, followed by the course name'),
 'editing_context':
 ('Editer une séance', 'Title, followed by the course name'),
 'title_of_context':
 ('Titre de la séance', 'Label'),
 'type_set':
 ("Typologie d'élément pédagogique", 'Label'),
 'creating_note_in':
 ('Ajouter une note dans', 'Title, followed by course context name'),
 'course_context':
 ('séance du cours', 'Label for course context'),
 'you_are_replying_to':
 ('Vous répondez à', 'Label'),
 'title_of_note':
 ('Titre de la note', 'Label'),
 'message_body':
 ('Corps du message', 'Label'),
 'current_image':
 ('Image courante', 'Label'),
 'replace_with':
 ('Remplacer par', 'Label for image replacement in note edit'),
 'add_image':
 ('Ajouter une image', 'Label'),
 'title_of_image':
 ("Titre de l'image", 'Label'),
 'add_link':
 ('Ajouter un lien (URL)', 'Label'),
 'title_of_link':
 ('Titre du lien', 'Label'),
 'preview':
 ('Prévisualisation', 'Button label'),
 'previewing_note':
 ('Prévisualisation de la note',
  'Title/heading, followed by course context name'),
 'search_kb':
 ('Chercher Petite fabrique du savoir', 'Link label'),
 'searching_kb':
 ('Cherchant les ntes de la Petite fabrique du savoir', 'Label'),
 'search_author':
 ('Auteur', 'Label'),
 'search_notes_words':
 ('Notes qui contiennent les mots', 'Label'),
 'search_context':
 ('Contexte du cours', 'Label'),
 'search_tt':
 ('Type pédagogique', 'Label'),
 'search_note':
 ('Note', 'Label'),
 'current_note':
 ('Note courante', 'Label'),
 'publish':
 ('Publier', 'Button label'),
 'you_didnt_select_type':
 ('Vous devez choisir un type.', 'Title'),
 'go_back':
 ('Retournez', 'Start of message, rendered into a link'),
 'and_select_type':
 ('et choisissez un type ', 'Rest of message'),
 'inline_notes':
 ('Notes en ligne', 'Link'),
 'outline_notes':
 ('Notes hors ligne', 'Link'),
 'view_info':
 ('Voir les infos', 'Part of location bar'),
 'edit_context':
 ('Editer la séance', 'Link'),
 'to_note':
 ('A la note', 'Part of a message'),
 'notes_from_day':
 ('Notes from', 'Start of heading, followed by a date'),
 'full_thread_no':
 ('Montrer uniquement les premières notes', 'Link'),
 'full_thread_yes':
 ('Montrer toute la discussion', 'Link'),
 'remove':
 ('Effacer la note', 'Button label for censoring notes'),
 'restore':
 ('Restorer note', 'Button label for uncensoring notes'),
 'remove_form_title':
 ('Effaçage de la note', 'Title for note censoring form'),
 'remove_form_label':
 ('Effaçage de la note',
  'Explanation in censor form, followed by note subject'),
 'removed_msg':
 ('le message est effacé', 'Message shown when teacher censores a note.'),
 'remove_verify2':
 ("Etes vous sures de vouloir effacer ce message? Votre nom, la date et l'explication que vous donnez ci-dessous vont être sauvegardés et affichés avec la note d'effaçage à quiconque visitant ce message.",
  'Verification message shown when removing is attempted'),
 'remove_explanation':
 ("Explication de l'effaçage", 'Label for censor explanation text area'),
 'removed_subject':
 ('Effacé', 'Title/subject for censored notes'),
 'removed_body':
 ('Ce message à été effacé par %s à %s.',
  "Body for censored messages. First placeholder is replaced by censorer's name and the second by the date"),
 'previous':
 ('Précédent', 'Link label'),
 'next':
 ('Suivant', 'Link label'),
 'who_has_read':
 ('Qui a lu cette note?', 'Link label'),
 'last_read':
 ('Dernière lecture', 'Label'),
 'times_read':
 ('nombre de lecture', 'Label'),
 'back':
 ('&lt; retour', 'Link label'),
 'unread_to_read_msg':
 ('Toutes les notes dans une discussion marqués comme lu.',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Marquer les notes comme lues', 'text in a button'),
 'creating_groupfolder':
 ('Créer un nouveau dossier de cours', 'Heading start'),
 'title_groupfolder':
 ('Titre du dossier de cours', 'Label'),
 'flea_asks':
 ('Demander à flea',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Changer le Type pédagogique?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ("C'est le seul type autorisé ici.",
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Changer', 'Button label'),
 'use_roleplay':
 ('Utiliser le jeu de rôles',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('Configuration des rôles du jeu de rôles',
  'Title for form, where roleplaying roles are set'),
 'down_to_note':
 ('Descendre à la note dans la session', 'Link label')}

webtop = {'users_courses':
 ('Des cours', "Postfix for user's course list heading"),
 'totals_notes':
 ('Notes',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ("sources d'inspiration",
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s nouveaux / %s total',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Ajouter un dossier', ''),
 'add_document':
 ('Ajouter un document', ''),
 'add_link':
 ('Ajouter un lien', ''),
 'create_memo':
 ('Créer un memo', ''),
 'type':
 ('Type', 'Link for sorting by type'),
 'title':
 ('Titre', 'Link for sorting by title'),
 'date':
 ('Date', 'Link for sorting by date'),
 'size':
 ('Taille', 'Link for sorting by size'),
 'remove':
 ('Effacer', 'Button label'),
 'restore':
 ('Restorer', 'Button label'),
 'select_all':
 ('Selectionner tout', 'Button label'),
 'rename':
 ('Renommer', 'Button label'),
 'empty_trash':
 ('Vider la poubelle', 'Button label'),
 'copy':
 ('Copier', 'Button label'),
 'cut':
 ('Couper', 'Button label'),
 'paste':
 ('Coller', 'Button label'),
 'creating_memo':
 ('Créer un memo', 'Title'),
 'delete':
 ('Effacer', 'Button label'),
 'title_of_memo':
 ('Titre du memo', 'Label'),
 'trash':
 ('Poubelle', 'Label for trashcan'),
 'adding_folder':
 ('Ajout de dossier', 'Heading'),
 'title_of_folder':
 ('Titre du dossier', 'Label'),
 'viewing_memo':
 ("Visualisation d'un mémo", 'Title'),
 'editing_memo':
 ("Edition d'un mémo", 'Title'),
 'content':
 ('Contenu', 'Label'),
 'show_memo_contents':
 ('Montrer le contenu du mémo', 'Link'),
 'search_wt':
 ('Chercher Dans les Pupitres', 'Link label'),
 'searching_wt':
 ('Recherche des pupitres', 'Label'),
 'search_results':
 ('Resultat de la recherche', 'Label'),
 'new_search':
 ('Nouvelle recherche', 'Label'),
 'search_title':
 ('Titre', 'Label'),
 'search_owner':
 ('Propriétaire', 'Label'),
 'search_words':
 ('Objets qui contiennent les mots', 'Label'),
 'search_object':
 ('Objet', 'Label'),
 'search_folder':
 ('Dossier', 'Label'),
 'viewing_search_results':
 ('Voir les reultats de la recherche', 'Label in the location path'),
 'anyone':
 ("n'importe qui", 'Label'),
 'adding_link':
 ("Ajout d'un lien", 'Title'),
 'title_of_link':
 ('Titre du lien', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Document téléchargé.', 'Status message'),
 'adding_document':
 ("Ajout d'un document", 'Title'),
 'upload_document':
 ('Téléchargement du document', 'Label'),
 'title_of_document':
 ('Titre du document', 'Label'),
 'webtop_link_added':
 ("Ajout d'un lien sur le pupitre", 'Message title'),
 'added_webtop_link':
 ('Le lien %s pointant vers "%s" a été ajouté. ???',
  'Message text; link name and url inserted into placeholders (2)'),
 'proxy_added':
 ('Dossier de cours ajouté', 'Message title'),
 'added_proxy':
 ('Le dossier de cours %s est maintenant visible sur votre pupitre. Cliquez sur Ok  pour retourner à la page précédente.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ("Pas d'objet sélectionné", 'Message dialog title'),
 'select_item_first':
 ("Sélectionnez un objet d'abord", 'Message dialog message'),
 'no_file_supplied':
 ('Pas de fichier fourni.', 'Message text'),
 'renaming':
 ('Renommage', 'Title'),
 'quota_reached_title':
 ('la limite de quote-part a été atteinte', 'Title'),
 'quota_reached':
 ("L'opération ne peut pas être effectuée parce que vous avez atteint la limite de quote-part dans votre pupitre. Veuillez enlever quelques objets et essayez encore.",
  'Message dialog message'),
 'invalid_names':
 ('Nom invalide', 'Message dialog messsage'),
 'same_names':
 ('Ce nom est déja utilisé.', 'Message dialog message'),
 'names_in_use':
 ('Noms déja utilisés :', 'Message dialog message'),
 'information':
 ('Information', 'Link'),
 'shared_course_folder':
 ('Dossier de cours partagés ',
  'Printed after the name of the group folder in webtop contents list.'),
 'preferences':
 ('Préferences', 'Link'),
 'editing_preferences':
 ('Editon des préférences', 'Title'),
 'obj_removed':
 ('(Cet objet a été enlevé)',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('&lt; retour', 'Link label')}

usermgmnt = {'user':
 ('utilisateur', 'part of browser title'),
 'adding_users':
 ("Ajout d'utilisateurs", 'Title'),
 'required_field':
 ('Champs obligatoire', ''),
 'nickname':
 ('Identifiant', ''),
 'user_account':
 ('Compte utilisateur', 'Label'),
 'Confirm':
 ('Confirmer', ''),
 'you_are_removing':
 ('Vous effacez', ''),
 'invite_user':
 ('Inviter un utilisateur', ''),
 'invite_users':
 ("Invitation d'un utilisateur", 'Heading for invitation form'),
 'email_addresses':
 ('Courrièl', ''),
 'separate_with_comma':
 ('( séparé par des virgules )', ''),
 'Invitation_message':
 ("Message d'invitation", ''),
 'Invitation_language':
 ("Langage de l'invitation", ''),
 'Courses_to_invite_to':
 ('Inviter aux cours ', ''),
 'Freeze':
 ('Geler', ''),
 'Remove':
 ('Effacer', ''),
 'role':
 ('Rôle', 'label'),
 'role_staff':
 ('Staff', 'Global role stuff'),
 'role_user':
 ('Utilisateur', 'Global role user'),
 'role_fleadmin':
 ('FLE-Administrateur', 'Global role fleadmin'),
 'invite_again':
 ('Ré-inviter', 'Button label'),
 'warning':
 ('Attention', 'Heading'),
 'want_remove_users':
 ('Voulez-vous effacer ces utilisateurs?', 'Complete question'),
 'invited_user_manage':
 ('Gestion des invitations', 'Title'),
 'info_user':
 ('Infos utilisateurs ', 'Title for user info page, prefix before usre name'),
 'edit_user':
 ('Editer info utilisateur ', 'Link'),
 'editing':
 ("Edition d'info utilisateur ",
  'Hading for user edit, inserted before user name'),
 'image_of_user':
 ('Image utilisateur', 'Label'),
 'upload_image_of_user':
 ("Télécharger l'image utilisateur", 'Label'),
 'or_link_to_image':
 ("ou indiquer un lien vers l'image",
  'Label, continuing from the upload label'),
 'webtop_bg':
 ('Image de fond du pupitre', 'Label'),
 'upload_webtop_bg':
 ("ou télécharger l'image de fond du pupitre",
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Montrer les utilisateurs non enregistrés', ''),
 'add_user':
 ('Ajouter utilisateurs', ''),
 'Unfreeze':
 ('Dégeler (;))', ''),
 'Users':
 ('Utilisateurs', ''),
 'gsm':
 ('Téléphone GSM', ''),
 'last_name':
 ('Nom', ''),
 'first_name':
 ('Prénom', ''),
 'city':
 ('Ville', ''),
 'organization':
 ('Organisation', ''),
 'professional_interests':
 ('Intérêts professionels', ''),
 'email':
 ('Courrièl', ''),
 'phone':
 ('Téléphone', ''),
 'url_to_photo':
 ('URL vers la photo', ''),
 'country_menu_default':
 ('Choisir le pays', ''),
 'group_menu_default':
 ('Choisir le groupe', ''),
 'address':
 ('Adresse', ''),
 'address1':
 ('Adresse 1)', ''),
 'address2':
 ('Adresse 2)', ''),
 'personal_interests':
 ('Intérêts personnels', ''),
 'quote':
 ('Citation', ''),
 'homepage':
 ('Site web', ''),
 'upload':
 ('Télécharger', ''),
 'group':
 ('Groupe', ''),
 'password':
 ('Mot de passe', ''),
 'background':
 ('séance (formation)', ''),
 'country':
 ('Pays', ''),
 'reserved_nickname':
 ('Identifiant utilisateur réservé', 'Message'),
 'password_mismatch':
 ('Les mots de passe ne sont pas identiques.', 'Message'),
 'could_not_send_invitation':
 ("L'invitation n'a pas pu être envoyée", 'Error message'),
 'invitations_not_sent_to':
 ("Les invitations n'ont pas été envoyées à: %s.",
  'Message, email list is inserted into the placeholder.'),
 'invitations_sent':
 ('Invitation envoyée', 'Message title'),
 'invitations_sent_to':
 ('Invitation envoyée à : %s. ',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Utilisateurs effacés', 'Message title'),
 'removed_users':
 ('Utilisateurs effacés: %s', 'Message, list inserted inside'),
 'not_removed_users':
 ('Utilisateurs non-effacés: %s', 'Message, list inserted inside'),
 're_invitations_sent':
 ('Ré-invitations envoyées', 'Message title'),
 're_invitations_sent_to':
 ('ré-invitations %s envoyées. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Utilisateurs non enregistrés effacés', 'Message title'),
 'pending_removed_users':
 ('Utilisateurs non enregistrés effacés: %s',
  'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Utilisateurs non enregistrés non effacés: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ("Sujet de l'invitation", 'Subject for invitation messages'),
 'invitation_header':
 ('Invitation', 'Header for invitation messages'),
 'invitation_footer':
 ('Adresse: ', 'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Bienvenue sur FLE, le service de e-formation du portail.',
  'Welcome message used in invitation registration form'),
 'uname':
 ("Nom d'utilisateur", 'Label used for user login name in several places'),
 'registration_failed':
 ("L'enregistrement a échoué",
  "Title used when invited user can't register."),
 'after_submit_give_name_and_passwd2':
 ('Après avoir pressé "Valider" entrez votre nom d\'utilisateur et votre mot de passe.',
  'Message'),
 'invitation_key_used':
 ("L'invitation a été utilisée.",
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ("Votre clé d'authentification n'est pas valide",
  "Message telling that the authentication key isn't valid."),
 'frozen':
 ('Gelé', 'User status code'),
 'show_frozen':
 ('Montrer les utilisateurs gelés', 'Link to show all users'),
 'show_active':
 ('Montrer seulement les utilisateurs actifs',
  'Link to show only active users'),
 'passwd_changed_explanation2':
 ("Vous avez changé votre mot de passe: votre browser va vous re-demander votre nom d'utilisateur et votre mot de passe.",
  'Message text'),
 'no_email':
 ('Pas de courrièl', 'Message title'),
 'no_email_explanation':
 ("Vous ne pouvez pas envoyer de message car vous n'avez pas indiqué votre courrièl.",
  'Message text'),
 'passwd_changed':
 ('Mot de passe modifié', 'Message title'),
 'external_user_database_explanation':
 ('Votre Fle3 utilise une base de données externe. Pour ajouter des utilisateur au système vous devez les ajouter à cette base de données.',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 ('Cours', 'part of browser title'),
 'courses':
 ('Cours', 'Title'),
 'create_course':
 ('Créer un cours', 'Link'),
 'edit_course':
 ('Editer un cours', 'Button label'),
 'edit_participants':
 ('Editer les participants', 'Button label'),
 'creating_course':
 ('Création de cours', 'Title'),
 'course_title':
 ('Nom du cours', 'Label'),
 'editing_course':
 ('Edition de cours', 'Title'),
 'organization':
 ('Organisation', 'Label'),
 'methods':
 ('Methodes', 'Label'),
 'starting_date':
 ('Date de début', 'Label'),
 'ending_date':
 ('Date de fin', 'Label'),
 'create_groupfolder':
 ('Créer un nouveau dossier de cours', 'Link'),
 'create_announcements':
 ('Creer des annonces', 'Link'),
 'edit_announcements':
 ('Éditer des annonces', 'Link'),
 'add_announcement':
 ("Ajouter l'annonce", 'Link'),
 'adding_announcement':
 ("Ajoute l'annonce dans", 'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('Voulez vous vraiment effacer cette annonce?', 'Question'),
 'editing_announcements':
 ('Éditing les annonces', 'Heading'),
 'viewing_announcements':
 ('Voir les annonces du cours %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ("Ajout d'utilisateur à un cours",
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('Si les participants ne sont pas des utilisateurs', 'Message'),
 'new_participants_to_system':
 ('Nouveaux participants sur le système', 'Part of a phrase'),
 'by_email':
 ('via courrièl', 'Part of a phrase'),
 'manually':
 ('manuel', 'Part of a phrase'),
 'fle_users':
 ('Utilisateur de FLE', 'Heading'),
 'down':
 ('Bas', 'Button label'),
 'up':
 ('Haut', 'Button label'),
 'teachers':
 ('Enseignants', 'Heading'),
 'tutors':
 ('Tuteurs', 'Heading'),
 'students':
 ('Etudiants', 'Heading'),
 'viewing_course':
 ('Vue du cours', 'Part of a phrase in location path'),
 'information':
 ('Information', 'Part of a phrase in location path'),
 'add_button':
 ('Ajouter ->', 'Button label'),
 'viewing_course_resources':
 ('Vue des ressources du cours %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'remove_button':
 ('<- Effacer', 'Button label'),
 'no_course_selected':
 ('Pas de cours sélectionnés!', 'Message dialog title'),
 'select_course_first':
 ("Sélectionnez un cours d'abord.", 'Message dialog message'),
 'set_published':
 ('Type de contenu publié.', 'Message dialog title/text'),
 'users_updated':
 ('Les utilisateurs ont été mis à jour',
  'Message dialog title/message'),
 'select_some_users':
 ('Choisissez un ou plusieurs utilisateurs', 'Message dialog title/message'),
 'edit_course_info':
 ('Editer les infos du cours', 'Link'),
 'edit_course_participants':
 ('Editer les participants au cours', 'Link'),
 'edit_course_resources':
 ('Editer les ressources au cours', 'Link'),
 'date':
 ('Date', 'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('Participants au cours', 'Label'),
 'add_typeset':
 ('Ajouter un groupe pédagogique', 'Link'),
 'type_sets':
 ("Gérer les typologies d'élément pédagogique", 'Label, plural'),
 'my_participation':
 ('Ma participation', 'Label'),
 'my_notes':
 ('Mes notes', 'Link'),
 'my_artefacts':
 ("Mes source d'inspiration", 'Link'),
 'course_resources':
 ('Ressources du cours', 'Label'),
 'delete':
 ('Effacer', 'Button label'),
 'tt_yellow':
 ('Jaune', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Jaune clair', 'Knowledge type colour name'),
 'tt_orange':
 ('Orange', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Orange clair', 'Knowledge type colour name'),
 'tt_red':
 ('Rouge', 'Knowledge type colour name'),
 'tt_pink':
 ('Rose', 'Knowledge type colour name'),
 'tt_purple':
 ('Violet', 'Knowledge type colour name'),
 'tt_blue':
 ('Bleu', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Bleu clair', 'Knowledge type colour name'),
 'tt_aqua':
 ('Eau', 'Knowledge type colour name'),
 'tt_green':
 ('Vert', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Vert clair', 'Knowledge type colour name'),
 'tt_gray':
 ('Gris', 'Knowledge type colour name'),
 'tt_white':
 ('Blanc', 'Knowledge type colour name'),
 'title':
 ('Titre', 'Start of label'),
 'edit_typeset':
 ("Edition des typologies d'élément pédagogique", 'Heading'),
 'create_typeset':
 ("Création d'une nouvelle typologie d'élément pédagogique",
  'Heading'),
 'form':
 ('Formulaire', 'Start of heading'),
 'types_management':
 ('Gestion des types pédagogiques', 'Title'),
 'of_typeset':
 ("de l'ensemble de type d'élément pédagogique", 'Ending of label'),
 'abbreviations_and_icons':
 ('abréviations et icônes', 'Ending for heading'),
 'type':
 ("Type d'élément pédagogique", 'Label'),
 'types':
 ("Types d'élément pédagogique", 'Title'),
 'abbreviation':
 ('Abreviation', 'Label'),
 'color':
 ('Couleur', 'Label'),
 'icon':
 ('Icône', 'Label'),
 'starting_phrase':
 ('Phrase de début', 'Label'),
 'viewing':
 ('Vue', 'Part of location bar'),
 'checklist':
 ('Vérification de la liste', 'Label'),
 'no_types_entered':
 ("Vous n'avez entré aucun type pédagogique. Un ensemble doit contenir au moins un type.",
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ("Restriction d'usage", 'Heading sentence.'),
 'that_can_start_thread':
 ('qui peut commencer une discussion', 'End of label'),
 'new_typeset_from':
 ("Dupliquer et éditer les typologies d'élément pédagogique",
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Non fini', 'Label'),
 'manage_types':
 ("Gerer les types d'élément pédagogique", 'Link'),
 'finalize_typeset':
 ('Changer le statut pour finir', 'Button label'),
 'are_you_sure':
 ('Etes vous sûr de vouloir effacer les cours suivant :',
  'Message dialog message'),
 'are_you_sure_ctx':
 ('Etes vous sûr de vouloir effacer cette séance de cours:',
  'Message dialog message'),
 'are_you_sure_tts':
 ("Etes vous sûr de vouloir effacer ce type d'élément pédagogique:",
  'Message dialog message'),
 'typeset_importing':
 ("Sélectonnez the ficher d'export zip contenant l'ensemble d'Žlement pŽdagogique que vous dŽsirez importer.",
  'Instructions for typeset importing'),
 'typesets_imported':
 ("Un nouvel ensemble d'élément pédagique a été importé.",
  'Message'),
 'import_typeset':
 ("Importer un nouvel ensemble d'élément pédagogique", 'link'),
 'course_importing':
 ("Sélectonnez the ficher d'export zip contenant le cours que vous désirez importer.",
  'Instructions for course importing'),
 'courses_imported':
 ('Un nouveau cours a été importé.', 'Message'),
 'import_course':
 ('Importation de cours', 'link'),
 'course_imported':
 ('(importé)', 'Appended to imported course names.'),
 'can_start_thread':
 ('Peut commencer une discussion?', 'column title in a table'),
 'can_be_followed':
 ('peut être suivi par', 'column title in a table'),
 'use_each_type':
 ('Chaque type pédagogique doit suivre au moins un autre type ou commencer un discussion.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Ressources', 'Title for list of course resources'),
 'add_resource':
 ('Ajouter une ressource', 'Link'),
 'editing_course_resources':
 ('Editer les ressources du cours', 'Title'),
 'remove_resource_verify':
 ('Etes vous sûr de vouloir effacer cette ressource?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ("Ajouter une session d'improvisation", 'link'),
 'jam_sessions':
 ("Sessions d'improvisation:",
  'a list of jam session will listed after/under this label'),
 'jam_session':
 ("Session d'improvisation", ''),
 'annotations':
 ('annotations', ''),
 'continue_with_version':
 ('continuer avec votre version', 'button label'),
 'artefact':
 ("source d'inspiration", ''),
 'viewing_annotations':
 ('visualiser les annotations', ''),
 'Annotations':
 ('Annotations:', 'Label, followed by a list of annotations under it'),
 'adding_jam_session':
 ("Ajout d'une session d'improvisation", ''),
 'edit_jam_session':
 ("Editer une session d'improvisation", ''),
 'editing_jam_session':
 ("Edition d'une session d'improvisation", ''),
 'add_annotation':
 ('Annotater', 'link'),
 'title_of_jam_session':
 ('Titre de la session', 'label'),
 'type_of_jam_session':
 ('Type de la session', 'label'),
 'mutate_on_previous':
 ('Reprise du précédent en le modifiant légèrement',
  'type of jam session'),
 'explore_possibilities':
 ('Exploration des possibilités', 'type of jam session'),
 'diverge_and_converge':
 ('Divergence & Convergence', 'type of jam session'),
 'title_of_the_starting_artefact':
 ("Titre de la source d'inspiration d'origine", 'label'),
 'description_of_jam_session':
 ('Description de la session', 'label'),
 'adding_artefact':
 ("Ajouter une source d'inspiration", ''),
 'title_of_the_artefact':
 ("Titre de la source d'inspiration", 'label'),
 'upload_the_starting_artefact':
 ("Télécharger la source d'inspiration", 'label'),
 'annotation_of_the_starting_artefact':
 ("Annotation pour la source d'inspiration du début", 'label'),
 'upload_file':
 ('Télécharger le fichier', 'label'),
 'you_adding_annotation':
 ('Vous ajoutez une annotation', 'message in adding annotations form'),
 'adding_annotation':
 ("Ajout d'une annotation sur", ''),
 'are_you_sure_jam_session':
 ("Etes vous sûr de vouloir effacer cette session d'improvisation avec %s sources d'inspiration?",
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'to_jam_session':
 ("à la session d'improvisation", 'Part of a message'),
 'to_jam_artefact':
 ("à la source d'inspiration", 'Part of a message'),
 'unread_artefacts':
 ("Nouvelles sources d'inpiration", 'There is a number before this message'),
 'total_artefacts':
 ("sources d'inspiration au total", 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ("Etes vous sûr de vouloir effacer la session d'improvition suivante:",
  'Message dialog message'),
 'remove_artefact':
 ("Effacer la source d'inspiration",
  'Button label for censoring jam artefact'),
 'restore_artefact':
 ("Restorer la source d'inspiration",
  'Button label for restoring jam artefact'),
 'remove_annotation':
 ('Effacer les annotations sélectionnées',
  'Button label for censoring jam annotations'),
 'restore_annotation':
 ('Restorer les annotations sélectionnées',
  'Button label for uncensoring jam annotations'),
 'removed_name':
 ('Effacée', 'Title/name for censored jam artefact'),
 'removed_message':
 ("Cette source d'improvisation a été effacée par %s à %s.",
  "First placeholder is replaced by censorer's name and the second by the date"),
 'removed_msg':
 ("La Source d'inspiration est effacée",
  'Message shown when teacher censores an artefact.'),
 'removed_annotation_msg':
 ("L'annotation est effacée",
  'Message shown when teacher censores an annotation.'),
 'remove_verify':
 ("Etes vous sûr de vouloir effacer cette source d'inspiration? Votre nom et la date vont être sauvegardé et affiché avec la note d'effaçage note à quiconque visitant cette source d'inspiration.",
  'Verification message shown when censoring is attempted'),
 'remove_annotations_verify':
 ("Etes vous sûr de vouloir effacer les annotations sélectionnées? Votre nom et la date vont être sauvegardé et affiché avec la note d'effaçage note à quiconque visitant ces annotations.",
  'Verification message shown when censoring is attempted'),
 'removed_annotation_body':
 ('Cette Annotation a été effacée par %s à %s.',
  "Body for censored annotation. First placeholder is replaced by censorer's name and the second by the date"),
 'search_jam':
 ("Chercher des sessions d'improvisation", 'Link label'),
 'searching_jam':
 ("Recherche de session d'improvisation", 'Label'),
 'search_artefact_name':
 ("Nom de la source d'inspiration", 'Label in search form'),
 'search_artefact_author':
 ('Auteur', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Ces annotations contiennent les mots',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ("Type de source d'inspiration",
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Image', 'Artefact type'),
 'type_audio':
 ('Audio', 'Artefact type'),
 'type_text':
 ('Texte', 'Artefact type'),
 'type_html':
 ('Html', 'Artefact type'),
 'type_video':
 ('Video', 'Artefact type'),
 'type_archive':
 ('Archive', 'Artefact type'),
 'search_annotated_by':
 ('Annoté par', 'Label in search form'),
 'search_results_author':
 ('Auteur', 'Heading in search results table'),
 'search_results_jam_artefact':
 ("Source d'inspiration", 'Heading in search results table'),
 'search_results_jam_session':
 ("Session d'improvisation", 'Heading in search results table')}

announce = {'comments':
 ('Commentaires', 'Notice / form heading'),
 'no_comments':
 ("Il n'y a aucun commentaire.", 'Notice'),
 'recent_comments':
 ('Commentaires récents', 'Heading'),
 'no_entries':
 ("Il n'y a aucune entrée.", 'Notice'),
 'recent_entries':
 ('Entrées récentes', 'Heading'),
 'trackbacks':
 ('Les Trackbacks', 'Notice'),
 'no_trackbacks':
 ("Il n'y a aucun trackbacks.", 'Notice'),
 'recent_trackbacks':
 ('Trackbacks récents', 'Heading'),
 'send_trackback':
 ('Envoyez svp le trackback à:', 'Part of message, followed by url'),
 'syndicate':
 ('Syndiquer ce site (XML).', 'Link'),
 'log_in':
 ('Login sur Fle3.', 'Link'),
 'entries':
 ('Entrée', 'Heading'),
 'category':
 ('Catégorie', 'Heading'),
 'categories':
 ('Catégories', 'Heading'),
 'no_categories':
 ('Pas de catégories', 'Notice'),
 'items':
 ('entrées', 'Part of message: nn items.'),
 'posted_by':
 ('Posté par', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%d/%m %H:%M', 'Short date format'),
 'dateformat':
 ('%d %B %Y %H:%M', 'Date format'),
 'at_time':
 ('à', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('Poster un commentaire', 'Heading'),
 'name':
 ('Nom', 'Form heading'),
 'email':
 ('Adresse email:', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('Titre', 'Form heading'),
 'body':
 ("Corps de l'annonce", 'Form heading'),
 'forget_personal':
 ("Oublier l'information personelle", 'Button'),
 'teachers_and_tutors_only':
 ('Enseignants et tuteurs seulement',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('Se Rapeller des informations personnelles dans un cookie?', 'Label'),
 'Announcement':
 ('Annonce', 'Category'),
 'ToDo':
 ('À faire', 'Category'),
 'Event':
 ('Événement', 'Category'),
 'continue_reading':
 ('Continuer à lire', 'Part of message, followed by entry title'),
 'missing1':
 ('manque', 'Part of message'),
 'missingn':
 ('manquent', 'Part of message'),
 'comment_preview':
 ('Prevision du commentaire', 'Heading'),
 'search_results':
 ('Résultats de recherche', 'Heading'),
 'search_for':
 ('Chercher les annonces pour', 'Part of message'),
 'no_match':
 ('Aucun résultat trouvé', 'Notice'),
 'about':
 ('Au sujet de', 'Title'),
 'archives':
 ('Archives', 'Title'),
 'search':
 ('Chercher', 'Heading'),
 'search_help':
 ('Vous pouvez employer AND/OR pour la recherche booléenne.',
  'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

