# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_hu.py,v 1.4 2005/01/18 15:47:32 tarmo Exp $
#
# Copyright 2001, 2002, 2003 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the Hungarian translations for all Fle3 printable strings."""

# How to do a new translation:
#
# 1. Copy this file into a new file, appending the language code after it, so
# you get something like "vocabulary_es.py" for Spanish and so on.
#
# 2. Edit the new file, translating the second portion of each line. The
# first portion is the keyword, which you shouldn't touch. The second is the
# translation that should be translated to the target language. The third
# is the supplementary instruction, that should help you do the translations.
#
# 3. Please note that the file is in Python code and needs to follow certain
# syntax rules:
#  - Strings can either be quoted by singles quotes (') or double quotes (").
#    If you need to use either of these quotation marks in your translation,
#    make sure that you use the other quotation mark to surround the string.
#    If you need to use both quotation marks in the same translation string,
#    you can surround the string with triple quotes (''' or """), which
#    allows you to use either of the quotation marks inside the string.
#  - Line breaks are not allowed inside strings, so make sure you don't
#    use an editor that wraps lines. You can have line breaks between
#    strings, though.
#
# 4. If you need to use special characters (outside of the 127 character
# ASCII range), you have several choices:
#
# A. Write in your native encoding (whatever suits you best). This requires
#    that you change the "charset_encoding" keyword in the "common" module to
#    the encoding type you will use. This document is written in iso8859-1,
#    although as english does not contain special characters, it could be
#    in utf-8 as well without any differences.
#    Most European languages are easiest to write in iso8859-1.
#
# B. Write in utf-8 encoded unicode. If your editor can save files in utf-8,
#    use that feature. If not, you can add the special characters manually
#    with the \x escape sequences. Make sure you remove the keyword
#    "charset_encoding" from the "common" module, or change its value to
#    "utf-8" so that the strings are interpreted correctly.
#    'key', ('\xe3\x82\xaa','This is the katakana letter O,encoded in utf-8.'),
#
# C. Write in unicode. Each unicode string starts with u followed by the
#    quotes. Each unicode character starts with \u followed by the code in
#    hexadecimal notation. The value of the "charset_encoding" keyword
#    is irrelevant if you use unicode all the way.
#    'key', (u'\u30aa','This is the katakana letter O, encoded in unicode.'),
#
# 5. Check your translation. If you have Python installed and you've
#    downloaded Fle3 sources, you can execute "python TranslationLint.py"
#    which will check through all the translation files and will produce
#    an error if there is a syntax error.
#    If you have installed Fle3, you can test the translation yourself
#    by going to Zope Management and selecting the Tools tab in your FLE
#    instance, and clicking on "reload_translations". After this you
#    should be able to select your translation from user preferences
#    and see the translated strings.
#

common = {'language_name':
 ('Magyar', 'Name of this language'),
 'charset_encoding':
 ('iso8859-2',
  'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('Kuckó', 'Main tab for webtop'),
 'Knowledge_Building':
 ('Tudásfa', 'Main tab for knowledge building'),
 'Course_Management':
 ('Kurzusvezetés', 'Main tab for course management'),
 'User_Management':
 ('Felhasználói ügyek', 'Main tab for user management'),
 'Jamming':
 ('Ötletház', 'Main tab for jamming'),
 'Type_Management':
 ('Információ típusok', 'Heading'),
 'cancel':
 ('Mégsem', 'Button label'),
 'submit':
 ('Elküldés', 'Button label'),
 'remove':
 ('Törlés', 'Button label'),
 'next':
 ('Következõ -&gt;', 'Label for button'),
 'previous':
 ('&lt;- Elõzõ', 'Label for button'),
 'quick_submit':
 ('Gyors küldés', ''),
 'ok':
 ('Ok', 'Button label'),
 'save':
 ('Mentés', 'Button label'),
 'create':
 ('Létrehozás', 'Button label'),
 'search':
 ('Keresés', 'Button label'),
 'webtop':
 ('Kuckó', ''),
 'description':
 ('Leírás', 'Label'),
 'short_date_format_display':
 ('ÉÉÉÉ-HH-NN', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%Y-%m-%d',
  'Format string for short dates. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'timestamp_format':
 ('%H:%M %Y-%m-%d',
  'Format string for long timestamps. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'invite':
 ('Meghívás', ''),
 'add':
 ('Hozzáadás', ''),
 'today':
 ('Ma', ''),
 'yesterday':
 ('Tegnap', ''),
 'groupfolder':
 ('kurzusmappa', 'Heading'),
 'dtml_reloaded':
 ('DTML újratöltve', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('DTML állományok újratöltése ehhez az objektumhoz',
  'Message dialog text'),
 'dtmls_reloaded':
 ('DTML állományok újratöltve', 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Minden DTML állomány újratöltve', 'Message dialog text'),
 'css_reloaded':
 ('Stíluslapok újratöltése', 'Title for message dialog'),
 'css_files_reloaded':
 ('Stíluslapok újratöltése ehhez az objektumhoz', 'Message text'),
 'error':
 ('Hiba', ''),
 'warning':
 ('Figyelmeztetés', ''),
 'invalid_url':
 ('Érvénytelen webcím', 'Message title'),
 'invalid_url_message':
 ('Úgy tûnik, hogy a megadott webcím hibás.&lt;br&gt;Ellenõrizd, hogy az elején ott van-e a http://, ftp://, mailto: vagy más Internet protokollra utaló címke. Ne feledd, hogy nem elég egy webcímet úgy megadni, hogy "www.valami.org", hanem így valahogy:  "http://www.valami.org". Ha nem vagy biztos a címben, akkor másold ki a böngészõbõl a címet és illeszd be ide.',
  'Message text'),
 'invalid_name':
 ('Érvénytelen név', 'Message title'),
 'give_valid_name':
 ('Kérlek, írj be egy érvényes nevet', 'Message text'),
 'name_taken':
 ('Van már ilyen név: "%s". Kérlek, válassz egy másik nevet!',
  'Message text, name inserted inside'),
 'edit':
 ('Szerkeszt', 'Button label'),
 'you_are_in':
 ('Itt vagy most:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ('Nem töltöttél ki minden szükséges mezõt.',
  'Erro message text'),
 'confirmation':
 ('Jóváhagyás', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Érvénytelen bevitel', 'Message title'),
 'invalid_fields':
 ('A következõ mezõk tartalma érvénytelen',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ('Elõbb válassz ki valamit!', 'Message text'),
 'link_to_webtop':
 ('Link létrehozása a Kuckóban', 'Link'),
 'proxy_to_webtop':
 ('Link a kurzusmappára a Kuckóban', 'Link'),
 'export':
 ('Kivitel', 'Button label'),
 'import':
 ('Behozatal', 'Button label'),
 'importing':
 ('Behozatal', 'Heading start'),
 'megabyte':
 ('MB', 'Abbreviation for megabyte'),
 'kilobyte':
 ('kB', 'Abbreviation for kilobyte'),
 'logout':
 ('Kilépés', 'Link for logging out, also heading in logout dialogs'),
 'logout_pre3':
 ('A kilépéshez a böngészõdet is be kell zárni.',
  'Instructions for logging out'),
 'any':
 ('Akármi', 'Label used in search forms'),
 'course':
 ('kurzus', 'Part of location path'),
 'language':
 ('Nyelv', ''),
 'announcements':
 ('Hirdetmények', 'Link/heading'),
 'sun':
 ('Vas', 'Weekday abbreviation'),
 'mon':
 ('Hét', 'Weekday abbreviation'),
 'tue':
 ('Ked', 'Weekday abbreviation'),
 'wed':
 ('Sze', 'Weekday abbreviation'),
 'thu':
 ('Csü', 'Weekday abbreviation'),
 'fri':
 ('Pén', 'Weekday abbreviation'),
 'sat':
 ('Szo', 'Weekday abbreviation'),
 'sunday':
 ('Vasárnap', 'Weekday'),
 'monday':
 ('Hétfõ', 'Weekday'),
 'tuesday':
 ('Kedd', 'Weekday'),
 'wednesday':
 ('Szerda', 'Weekday'),
 'thursday':
 ('Csütörtök', 'Weekday'),
 'friday':
 ('Péntek', 'Weekday'),
 'saturday':
 ('Szombat', 'Weekday'),
 'January':
 ('január', 'Month'),
 'February':
 ('február', 'Month'),
 'March':
 ('március', 'Month'),
 'April':
 ('április', 'Month'),
 'May':
 ('május', 'Month'),
 'June':
 ('június', 'Month'),
 'July':
 ('július', 'Month'),
 'August':
 ('augusztus', 'Month'),
 'September':
 ('szeptember', 'Month'),
 'October':
 ('október', 'Month'),
 'November':
 ('november', 'Month'),
 'December':
 ('december', 'Month'),
 'remove_q':
 ('Töröljük?', 'Question')}

kb = {'month':
 ('hónap', ''),
 'week':
 ('hét', ''),
 'you_have_not_replied_to':
 ('Nem reagáltál az õ megjegyzéseikre',
  'followed by a list of persons'),
 'total_replies':
 ('A megjegyzésekre adott reakciók száma:', 'followed by number'),
 'total_notes_written':
 ('A megjegyzések száma:', 'followed by number'),
 'graph_type':
 ('ábra típusa: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('információ típus', 'graph type'),
 'replies':
 ('reakciók', 'graph type'),
 'display_by':
 ('Megjelenítés a következõk szerint:',
  'Label for timescale (week/month) selection'),
 'adding_resource':
 ('Háttéranyag hozzáadása', 'part of browser title'),
 'modifying_resource':
 ('Háttéranyag módosítása', 'part of browser title'),
 'title_resource':
 ('Cím', 'The title of resource'),
 'author_resource':
 ('Szerzõ', 'The author of the resource'),
 'url':
 ('URL', 'Resource URL'),
 'location':
 ('Hely', 'Resource location'),
 'course_info':
 ('Kurzusinformáció', 'Label for link to course details'),
 'create_context':
 ('Kurzustéma indítása', 'Link to create new course context'),
 'hide_context':
 ('Kurzustéma elrejtése', 'Link to hide a context from view'),
 'show_context':
 ('Kurzustéma megjelenítése', 'Link to show a hidden context'),
 'new_notes':
 ('új megjegyzés',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('megjegyzés', 'Label for showing the number of notes'),
 'full_description':
 ('teljes leírás...', ''),
 'course':
 ('kurzus', "String 'course' in context display"),
 'context':
 ('leírás', "String 'context' in context display"),
 'thread':
 ('gondolatsor', "String 'thread' in context display"),
 'note':
 ('megjegyzés', "String 'note' in context display"),
 'start_thread':
 ('Gondolatsor indítása', 'Link'),
 'short_description':
 ('Rövid leírás', 'Label'),
 'long_description':
 ('Hosszabb leírás', 'Label'),
 'full_description':
 ('Teljes leírás', 'Label'),
 'select':
 ('Válassz',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('információ típus', 'Label'),
 'add_note':
 ('Megjegyzés hozzáfûzése', 'Button label'),
 'show_notes':
 ('Mutasd a megjegyzéseket', 'Heading start'),
 'show_thread':
 ('gondolatsorként', 'heading finish'),
 'show_type':
 ('információ típus szerint', 'heading finish'),
 'show_author':
 ('személyek alapján', 'heading finish'),
 'show_date':
 ('dátum szerint', 'heading finish'),
 'select_course':
 ('Válassz kurzust',
  'Label, followed by a drop-down list of available courses'),
 'change':
 ('Változtatás', 'Button label'),
 'creating_context':
 ('Kurzustéma létrehozása', 'Title, followed by the course name'),
 'editing_context':
 ('Kurzustéma szerkesztése', 'Title, followed by the course name'),
 'title_of_context':
 ('A kurzustéma címe', 'Label'),
 'type_set':
 ('információ típusok', 'Label'),
 'creating_note_in':
 ('Megjegyzés hozzáfûzése a következõhöz',
  'Title, followed by course context name'),
 'course_context':
 ('kurzusleírás', 'Label for course context'),
 'you_are_replying_to':
 ('Válasz a következõre', 'Label'),
 'title_of_note':
 ('A megjegyzés címe', 'Label'),
 'message_body':
 ('Szövegtörzs', 'Label'),
 'current_image':
 ('Jelenlegi kép', 'Label'),
 'replace_with':
 ('Cserélje másra', 'Label for image replacement in note edit'),
 'add_image':
 ('Kép hozzáadása', 'Label'),
 'title_of_image':
 ('Kép címe', 'Label'),
 'add_link':
 ('Link hozzáadása (URL)', 'Label'),
 'title_of_link':
 ('Link címe', 'Label'),
 'preview':
 ('Elõnézet', 'Button label'),
 'previewing_note':
 ('A megjegyzés elõnézete:',
  'Title/heading, followed by course context name'),
 'publish':
 ('Megjelentetés', 'Button label'),
 'search_kb':
 ('Keresés a Tudásfában', 'Link label'),
 'searching_kb':
 ('Keresés a Tudásfa megjegyzései között', 'Label'),
 'search_author':
 ('Szerzõ', 'Label'),
 'search_notes_words':
 ('Szöveges megjegyzések', 'Label'),
 'search_context':
 ('Kurzus leírása', 'Label'),
 'search_tt':
 ('Információ típusok', 'Label'),
 'search_note':
 ('Megjegyzés', 'Label'),
 'current_note':
 ('Aktuális megjegyzés', 'Label'),
 'you_didnt_select_type':
 ('Nem választottál információ típust.', 'Title'),
 'go_back':
 ('Menj vissza', 'Start of message, rendered into a link'),
 'and_select_type':
 ('és válaszd ki a a megjegyzésedhez illeszkedõ tudástípust.',
  'Rest of message'),
 'inline_notes':
 ('Mutasd a megjegyzések szövegeit', 'Link'),
 'outline_notes':
 ('Rejtsd el a megjegyzések szövegeit', 'Link'),
 'view_info':
 ('az információk megtekintése', 'Part of location bar'),
 'edit_context':
 ('A kurzusleírás szerkesztése', 'Link'),
 'to_note':
 ('a megjegyzéshez', 'Part of a message'),
 'full_thread_no':
 ('Csak a kezdõ megjegyzéseket mutasd', 'Link'),
 'full_thread_yes':
 ('Mutasd az egész gondolatsort', 'Link'),
 'remove':
 ('Megjegyzés törlése', 'Button label for removing notes'),
 'restore':
 ('Megjegyzés visszaállítása', 'Button label for restoring notes'),
 'remove_form_title':
 ('Megjegyzés törlése', 'Title for note removing form'),
 'remove_form_label':
 ('Megjegyzés törlése',
  'Explanation in remove form, followed by note subject'),
 'removed_msg':
 ('Üzenet törölve',
  'Message shown to the teacher when she has removed a note.'),
 'remove_verify2':
 ('Biztos vagy benne, hogy ki akarod törölni ezt az üzenetet? A nevedet, a dátumot és az általad megadott okot a rendszer tárolja és a törlés jelölésével együtt megjeleníti.',
  'Verification message shown when removing is attempted'),
 'remove_explanation':
 ('A törlés oka', 'Label for removee explanation text area'),
 'removed_subject':
 ('Törölve', 'Title/subject for removed notes'),
 'removed_body':
 ('Ezt az üzenetet %s törölte. Idõpont: %s.',
  "Body for removed messages. First placeholder is replaced by remover's name and the second by the date"),
 'notes_from_day':
 ('A megjegyzést hozzáfûzte', 'Start of heading, followed by a date'),
 'previous':
 ('Elõzõ', 'Link label'),
 'next':
 ('Következõ', 'Link label'),
 'who_has_read':
 ('Ki olvasta ezt a megjegyzést?', 'Link label'),
 'last_read':
 ('Utoljára olvasva', 'Label'),
 'times_read':
 ('Olvasások száma', 'Label'),
 'back':
 ('&amp;lt; vissza', 'Link label'),
 'unread_to_read_msg':
 ('Jelöld olvasottnak a gondolatsor összes megjegyzését!',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Jelöljünk mindent olvasottnak', 'text in a button'),
 'creating_groupfolder':
 ('Kurzusmappa létrehozása itt', 'Heading start'),
 'title_groupfolder':
 ('Kurzusmappa címe', 'Label'),
 'flea_asks':
 ('A bolha (a segítõ) kérdezi',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Változtassunk a tudástípuson?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ('Ez itt az egyetlen elfogadható típus.',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Változtatás', 'Button label'),
 'down_to_note':
 ('Le', 'Link label'),
 'use_roleplay':
 ('Szereposztás használata',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('A szerepek kiosztása',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 ('Kurzusok', "Heading for user's course list"),
 'totals_notes':
 ('Megjegyzések',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ('Ötletmorzsák',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s új / %s összes',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Mappa hozzáadása', ''),
 'add_document':
 ('Dokumentum hozzáadása', ''),
 'add_link':
 ('Link hozzáadása', ''),
 'create_memo':
 ('Jegyzet készítése', ''),
 'type':
 ('Típus', 'Link for sorting by type'),
 'title':
 ('Cím', 'Link for sorting by title'),
 'date':
 ('Dátum', 'Link for sorting by date'),
 'size':
 ('Méret', 'Link for sorting by size'),
 'remove':
 ('Törlés', 'Button label'),
 'restore':
 ('Visszaállítás', 'Button label'),
 'rename':
 ('Átnevezés', 'Button label'),
 'copy':
 ('Másolás', 'Button label'),
 'cut':
 ('Kivágás', 'Button label'),
 'paste':
 ('Beillesztés', 'Button label'),
 'delete':
 ('Törlés', 'Button label'),
 'select_all':
 ('Az összes kiválasztása', 'Button label'),
 'trash':
 ('Kuka', 'Label for trashcan'),
 'empty_trash':
 ('Kuka ürítése', 'Button label'),
 'adding_folder':
 ('Mappa hozzáadása', 'Heading'),
 'title_of_folder':
 ('A mappa címe', 'Label'),
 'viewing_memo':
 ('Jegyzet megtekintése', 'Title'),
 'creating_memo':
 ('Jegyzet készítése', 'Title'),
 'editing_memo':
 ('Jegyzet szerkesztése', 'Title'),
 'title_of_memo':
 ('Jegyzet címe', 'Label'),
 'content':
 ('Tartalom', 'Label'),
 'show_memo_contents':
 ('Mutasd a jegyzet tartalmát', 'Link'),
 'adding_link':
 ('Link hozzáadása', 'Title'),
 'title_of_link':
 ('Link címe', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Dokumentum feltöltve.', 'Status message'),
 'adding_document':
 ('Dokumentum hozzáadása', 'Title'),
 'upload_document':
 ('Dokumentum feltöltése', 'Label'),
 'title_of_document':
 ('Dokumentum címe', 'Label'),
 'search_wt':
 ('Keresés a Kuckókban', 'Link label'),
 'searching_wt':
 ('Keresés a Kuckókban', 'Label'),
 'search_results':
 ('A keresés eredménye', 'Label'),
 'new_search':
 ('Új keresés', 'Label'),
 'search_title':
 ('Cím', 'Label'),
 'search_owner':
 ('Tulajdonos', 'Label'),
 'search_words':
 ('Keresés szavak alapján', 'Label'),
 'search_object':
 ('Tárgy', 'Label'),
 'search_folder':
 ('Mappa', 'Label'),
 'viewing_search_results':
 ('a találatok megtekintése', 'Label in the location path'),
 'anyone':
 ('Mindenki', 'Label'),
 'webtop_link_added':
 ('Kuckó link hozzáadva', 'Message title'),
 'added_webtop_link':
 ('%s "%s" link jött létre a te Kuckódban. Kattints az OK gombra és visszatérsz az elõzõ oldalra.',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 ('Kurzusmappa létrehozva', 'Message title'),
 'added_proxy':
 ('A(z) %s kurzus mappája már látható a Kuckódban. Kattints az OK gombra és visszatérsz az elõzõ oldalra.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ('Semmi sincs kiválasztva!', 'Message dialog title'),
 'select_item_first':
 ('Válassz ki legalább egy elemet!', 'Message dialog message'),
 'no_file_supplied':
 ('Nincs megfelelõ fájl.', 'Message text'),
 'renaming':
 ('Átnevezés', 'Title'),
 'invalid_names':
 ('Érvénytelen nevek:', 'Message dialog messsage'),
 'same_names':
 ('Néhány tárgy azonos.', 'Message dialog message'),
 'names_in_use':
 ('Ezek a nevek már foglaltak:', 'Message dialog message'),
 'information':
 ('Felhasználói adatok', 'Link'),
 'preferences':
 ('Beállítások', 'Link'),
 'editing_preferences':
 ('Beállítások szerkesztése', 'Title'),
 'shared_course_folder':
 ('Megosztott kurzusmappa',
  'Printed after the name of the group folder in webtop contents list.'),
 'quota_reached_title':
 ('A tárhely megtelt', 'Title'),
 'quota_reached':
 ('A mûveletet nem lehetett végrehajtani, mert a rendelkezésre álló hely a Kuckóban megtelt. Törlés után próbáld meg újra.',
  'Message dialog message'),
 'obj_removed':
 ('(link törölve)',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('&amp;lt; Vissza', 'Link label')}

usermgmnt = {'user':
 ('felhasználó', 'part of browser title'),
 'adding_users':
 ('Felhasználók hozzáadása', 'Title'),
 'required_field':
 ('Kitöltendõ mezõ', ''),
 'nickname':
 ('Becenév', 'Label'),
 'user_account':
 ('Felhasználói név', 'Label'),
 'Confirm':
 ('Megerõsítés', ''),
 'you_are_removing':
 ('Most törölsz', ''),
 'invite_user':
 ('Meghívás', ''),
 'invite_users':
 ('Meghívás', 'Heading for invitation form'),
 'email_addresses':
 ('E-mail címek', ''),
 'separate_with_comma':
 ('( elválasztva a következõvel: , )', ''),
 'Invitation_message':
 ('A meghívó szövege', ''),
 'Invitation_language':
 ('A meghívó nyelve', ''),
 'Courses_to_invite_to':
 ('Melyik kurzushoz hívod meg', ''),
 'Freeze':
 ('Letiltás', ''),
 'Remove':
 ('Törlés', ''),
 'role':
 ('Szerepkör', 'label'),
 'role_staff':
 ('Személyzet', 'Global role stuff'),
 'role_user':
 ('Felhasználó', 'Global role user'),
 'role_fleadmin':
 ('FLE adminisztrátor', 'Global role fleadmin'),
 'invite_again':
 ('Meghívás újra', 'Button label'),
 'warning':
 ('Figyelmeztetés', 'Heading'),
 'want_remove_users':
 ('Ki akarod törölni a következõ felhasználókat?',
  'Complete question'),
 'invited_user_manage':
 ('A meghívottak rendezése', 'Title'),
 'info_user':
 ('Felhasználói információk - ',
  'Title for user info page, prefix before user name'),
 'edit_user':
 ('Felhasználók szerkesztése', 'Link'),
 'editing':
 ('Szerkesztés', 'Heading for user edit, inserted before user name'),
 'image_of_user':
 ('A felhasználó képe', 'Label'),
 'upload_image_of_user':
 ('Saját kép feltöltése', 'Label'),
 'or_link_to_image':
 ('esetleg addj meg egy elérési utat a képedhez',
  'Label, continuing from the upload label'),
 'webtop_bg':
 ('Válassz egy háttérmintát a Kuckód számára', 'Label'),
 'upload_webtop_bg':
 ('esetleg töltsd fel a saját háttérmintádat',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Meghívottak ellenõrzése', ''),
 'add_user':
 ('Felhasználó hozzáadása', ''),
 'Unfreeze':
 ('Letiltás feloldása', ''),
 'Users':
 ('Felhasználók', ''),
 'gsm':
 ('Mobil', ''),
 'last_name':
 ('Vezetéknév', ''),
 'first_name':
 ('Keresztnév', ''),
 'city':
 ('Város', ''),
 'organization':
 ('Szervezet', ''),
 'professional_interests':
 ('Szakmai érdeklõdés', ''),
 'email':
 ('E-mail', ''),
 'phone':
 ('Telefon', ''),
 'url_to_photo':
 ('Kép elérési címe', ''),
 'country_menu_default':
 ('Válassz országot', ''),
 'group_menu_default':
 ('Válassz csoportot', 'Default value for drop-down menu'),
 'address':
 ('Cím', ''),
 'address1':
 ('Cím 1. sor', ''),
 'address2':
 ('Cím 2. sor', ''),
 'personal_interests':
 ('Érdeklõdési kör', ''),
 'quote':
 ('Mottó', ''),
 'homepage':
 ('Honlap', ''),
 'upload':
 ('Feltöltés', ''),
 'group':
 ('Csoport', ''),
 'password':
 ('Jelszó', ''),
 'background':
 ('Háttér', ''),
 'country':
 ('Ország', ''),
 'reserved_nickname':
 ('Sajnos ez a becenév már foglalt.', 'Message'),
 'password_mismatch':
 ('Nem egyeznek a megadott jelszavak.', 'Message'),
 'could_not_send_invitation':
 ('A meghívót nem lehetett elküldeni. Ellenõrizd a levelezési beállításokat!',
  'Error message'),
 'invitations_sent':
 ('Meghívók elküldve', 'Message title'),
 'invitations_sent_to':
 ('Meghívók elküldve a következõknek: %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 ('A meghívók nem mentek el a következõknek: %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Felhasználók törölve', 'Message title'),
 'removed_users':
 ('Felhasználók törölve: %s', 'Message, list inserted inside'),
 'not_removed_users':
 ('Nem törölhetõk a következõ felhasználók: %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 ('Ismételt meghívások elküldve', 'Message title'),
 're_invitations_sent_to':
 ('Ismételt meghívások elküldve a következõknek: %s. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Felfüggesztett felhasználók törölve', 'Message title'),
 'pending_removed_users':
 ('Felfüggesztett felhasználók törölve: %s',
  'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Nem lehet törölni a következõ felfüggesztett felhasználókat: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ('Meghívó a FLE rendszerbe', 'Subject for invitation messages'),
 'invitation_header':
 ('Meghívó', 'Header for invitation messages'),
 'invitation_footer':
 ('Látogasd meg ezt: ',
  'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Üdvözlünk a FLE rendszerben! Add meg a felhasználói adataidat!',
  'Welcome message used in invitation registration form'),
 'uname':
 ('Belépési azonosító',
  'Label used for user login name in several places'),
 'registration_failed':
 ('A regisztráció sikertelen volt',
  "Title used when invited user can't register."),
 'invitation_key_used':
 ('Ez a meghívó már használatban levõ címet tartalmaz vagy már lejárt. Ha nem sikerült regisztrálnod, kérd meg a tanárodat, hogy küldjön újra meghívót.',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ('A hitelesítõ kulcsok érvénytelenek',
  "Message telling that the authentication key isn't valid."),
 'after_submit_give_name_and_passwd2':
 ('Kattints az "Elküld" gombra, majd add meg a belépési azonosítódat és a jelszavadat.',
  'Message'),
 'frozen':
 ('Letiltva', 'User status code'),
 'show_frozen':
 ('Mutasd a letiltott felhasználókat', 'Link to show all users'),
 'show_active':
 ('Mutasd csak az aktív felhasználókat',
  'Link to show only active users'),
 'no_email':
 ('Nincs e-mail cím', 'Message title'),
 'no_email_explanation':
 ('Nem tudsz e-mailt küldeni, mert nem adtad meg a címedet.',
  'Message text'),
 'passwd_changed':
 ('A jelszó megváltozott', 'Message title'),
 'passwd_changed_explanation2':
 ('Megváltoztattad a jelszavadat: a böngészõd újra meg fogja kérdezni a belépési azonosítódat és a jelszavadat.',
  'Message text'),
 'external_user_database_explanation':
 ('A te Fle3 rendszered külsõ felhasználói adatbázist használ. Új felhasználó felvételéhez ezt a külsõ adatbázist kell módosítani.',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 ('kurzus', 'part of browser title'),
 'courses':
 ('Kurzus', 'Title'),
 'create_course':
 ('Kurzus indítása', 'Link'),
 'edit_course':
 ('Kurzus szerkesztése', 'Button label'),
 'edit_participants':
 ('Résztvevõk szerkesztése', 'Button label'),
 'creating_course':
 ('Kurzus indítása', 'Title'),
 'editing_course':
 ('Kurzus szerkesztése', 'Title'),
 'course_title':
 ('Kurzus címe', 'Label'),
 'organization':
 ('Szervezet', 'Label'),
 'methods':
 ('Módszerek', 'Label'),
 'starting_date':
 ('Elsõ nap', 'Label'),
 'ending_date':
 ('Utolsó nap', 'Label'),
 'create_groupfolder':
 ('Csoportmappa létrehozása', 'Link'),
 'create_announcements':
 ('Hirdetmény létrehozása', 'Link'),
 'edit_announcements':
 ('Hirdetmény szerkesztése', 'Link'),
 'add_announcement':
 ('Hirdetmény hozzáadása', 'Link'),
 'adding_announcement':
 ('Hirdetmény a következõhöz:',
  'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('Valóban töröljük a hirdetményt?', 'Question'),
 'editing_announcements':
 ('Hirdetmény szerkesztése', 'Heading'),
 'viewing_announcements':
 ('Hirdetmények megtekintése: %',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ('Felhasználók hozzáadása a kurzushoz',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('Amennyiben a kurzus résztvevõi még nem Fle3 felhasználók',
  'Message'),
 'new_participants_to_system':
 ('a Fle3 rendszerbe', 'Part of a phrase'),
 'by_email':
 ('e-mailben', 'Part of a phrase'),
 'manually':
 ('manuálisan', 'Part of a phrase'),
 'fle_users':
 ('FLE3 felhasználók', 'Heading'),
 'down':
 ('Le', 'Button label'),
 'up':
 ('Fel', 'Button label'),
 'teachers':
 ('Tanárok', 'Heading'),
 'tutors':
 ('Segítõk', 'Heading'),
 'students':
 ('Diákok', 'Heading'),
 'add_button':
 ('Hozzáadás -&gt;', 'Button label'),
 'remove_button':
 ('&lt;- Törlés', 'Button label'),
 'viewing_course':
 ('kurzus megtekintése', 'Part of a phrase in location path'),
 'viewing_course_resources':
 ('A %s kurzus háttéranyagainak megtekintése',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 ('információk', 'Part of a phrase in location path'),
 'no_course_selected':
 ('Nincs kiválasztott kurzus!', 'Message dialog title'),
 'select_course_first':
 ('Válassz egy kurzust a listából!', 'Message dialog message'),
 'set_published':
 ('Megjelenített információ típusok', 'Message dialog title/text'),
 'users_updated':
 ('Felhasználói információk frissítve',
  'Message dialog title/message'),
 'select_some_users':
 ('Válassz néhány felhasználót',
  'Message dialog title/message'),
 'edit_course_info':
 ('Kurzusinformáció szerkesztése', 'Link'),
 'edit_course_participants':
 ('Kurzus résztvevõinek szerkesztése', 'Link'),
 'edit_course_resources':
 ('Kurzus háttéranyag szerkesztése', 'Link'),
 'date':
 ('Dátum',
  'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('A kurzus résztvevõi', 'Label'),
 'type_sets':
 ('Információ típusok', 'Label, plural'),
 'delete':
 ('Törlés', 'Button label'),
 'my_participation':
 ('Saját részvételem', 'Label'),
 'my_notes':
 ('Saját megjegyzések', 'Link'),
 'my_artefacts':
 ('Saját ötletmorzsák', 'Link'),
 'course_resources':
 ('Kurzus háttéranyagai', 'Label'),
 'add_typeset':
 ('Információ típusok hozzáadása', 'Link'),
 'tt_yellow':
 ('Sárga', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Citromsárga', 'Knowledge type colour name'),
 'tt_orange':
 ('Narancssárga', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Világos narancs', 'Knowledge type colour name'),
 'tt_red':
 ('Piros', 'Knowledge type colour name'),
 'tt_pink':
 ('Rózsaszín', 'Knowledge type colour name'),
 'tt_purple':
 ('Bíbor', 'Knowledge type colour name'),
 'tt_blue':
 ('Kék', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Világoskék', 'Knowledge type colour name'),
 'tt_aqua':
 ('Vízkék', 'Knowledge type colour name'),
 'tt_green':
 ('Zöld', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Világoszöld', 'Knowledge type colour name'),
 'tt_gray':
 ('Szürke', 'Knowledge type colour name'),
 'tt_white':
 ('Fehér', 'Knowledge type colour name'),
 'edit_typeset':
 ('Információ típusok szerkesztése', 'Heading'),
 'create_typeset':
 ('Információ típusok létrehozása', 'Heading'),
 'form':
 ('Ûrlap', 'Start of heading'),
 'title':
 ('Információ típusok', 'Start of label'),
 'of_typeset':
 ('címe', 'Ending of label'),
 'abbreviations_and_icons':
 ('rövidítések és ikonok', 'Ending for heading'),
 'type':
 ('Információ típus', 'Label'),
 'types':
 ('Információ típusok', 'Title'),
 'types_management':
 ('Típusok', 'Title'),
 'abbreviation':
 ('Rövidítés', 'Label'),
 'color':
 ('Szín', 'Label'),
 'icon':
 ('Ikon', 'Label'),
 'starting_phrase':
 ('Kezdõ gondolat', 'Label'),
 'checklist':
 ('Lista', 'Label'),
 'no_types_entered':
 ('Nem vittél be információ típusokat. Egy készletnek legalább egy típust kell tartalmaznia.',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ('A használat korlátozása', 'Heading sentence.'),
 'that_can_start_thread':
 ('ez egy gondolatsort indíthat el', 'End of label'),
 'viewing':
 ('megtekintés', 'Part of location bar'),
 'new_typeset_from':
 ('Információ típus duplikálása és szerkesztése',
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Befejezetlen', 'Label'),
 'manage_types':
 ('Információ típusok rendezése', 'Link'),
 'finalize_typeset':
 ('Változtass az állapoton a Befejezéshez', 'Button label'),
 'are_you_sure':
 ('Biztos, hogy törölni szeretnéd a következõ kurzusokat?',
  'Message dialog message'),
 'are_you_sure_ctx':
 ('Biztos, hogy törölni szeretnéd a kurzustémát?',
  'Message dialog message'),
 'are_you_sure_tts':
 ('Biztos, hogy törölni szeretnéd a következõ információ típusokat?',
  'Message dialog message'),
 'typeset_importing':
 ('Válaszd ki a tömörített fájlt, amely a behozni kívánt készletet tartalmazza.',
  'Instructions for typeset importing'),
 'typesets_imported':
 ('Új információ típusok érkeztek.', 'Message'),
 'import_typeset':
 ('Információ típusok behozatala', 'link'),
 'course_importing':
 ('Válaszd ki a tömörített fájlt, ami a behozni kívánt kurzust tartalmazza.',
  'Instructions for course importing'),
 'courses_imported':
 ('Új kurzusok jöttek.', 'Message'),
 'import_course':
 ('Kurzus behozatal', 'link'),
 'course_imported':
 ('(behozva)', 'Appended to imported course names.'),
 'can_start_thread':
 ('gondolatsort indíthat', 'column title in a table'),
 'can_be_followed':
 ('ezzel folytatható', 'column title in a table'),
 'use_each_type':
 ('Mindegyik információ típust legalább egy másik kell kövesse vagy induljon egy gondolatsor.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Háttéranyagok', 'Title for list of course resources'),
 'add_resource':
 ('Háttéranyag hozzáadása', 'Link'),
 'editing_course_resources':
 ('Kurzus háttéranyagának szerkesztése', 'Title'),
 'remove_resource_verify':
 ('Biztos ki akarod törölni ezt a háttéranyagot?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ('Ötletbörze indítása', 'link'),
 'jam_sessions':
 ('Ötletbörzék:',
  'a list of jam session will listed after/under this label'),
 'jam_session':
 ('ötletbörze', ''),
 'annotations':
 ('megjegyzések', ''),
 'continue_with_version':
 ('Folytasd a saját változatoddal', 'button label'),
 'artefact':
 ('ötletmorzsa', ''),
 'viewing_annotations':
 ('Megjegyzések megtekintése', ''),
 'Annotations':
 ('Megjegyzések:', 'Label, followed by a list of annotations under it'),
 'add_annotation':
 ('Megjegyzés hozzáadása', 'link'),
 'adding_jam_session':
 ('Ötletbörze indítása', ''),
 'edit_jam_session':
 ('Ötletbörze szerkesztése', ''),
 'editing_jam_session':
 ('Ötletbörze szerkesztése', ''),
 'title_of_jam_session':
 ('Ötletbörze címe', 'label'),
 'type_of_jam_session':
 ('Ötletbörze típusa', 'label'),
 'mutate_on_previous':
 ('Változatok egy témára', 'type of jam session'),
 'explore_possibilities':
 ('Felfedezés', 'type of jam session'),
 'diverge_and_converge':
 ('Pro és kontra', 'type of jam session'),
 'description_of_jam_session':
 ('Ötletbörze leírása', 'label'),
 'upload_the_starting_artefact':
 ('Elsõ ötletmorzsa feltöltése', 'label'),
 'title_of_the_starting_artefact':
 ('Elsõ ötletmorzsa címe', 'label'),
 'annotation_of_the_starting_artefact':
 ('Megjegyzés az elsõ ötletmorzsához', 'label'),
 'adding_artefact':
 ('Ötletmorzsa hozzáadása', ''),
 'title_of_the_artefact':
 ('Ötletmorzsa címe', 'label'),
 'upload_file':
 ('Fájl feltöltése', 'label'),
 'you_adding_annotation':
 ('Most egy ötletmorzsához fûzöl megjegyzést',
  'message in adding annotations form'),
 'adding_annotation':
 ('Megjegyzés hozzáfûzése a következõhöz', ''),
 'to_jam_session':
 ('az ötletbörzéhez', 'Part of a message'),
 'to_jam_artefact':
 ('az ötletmorzsákhoz', 'Part of a message'),
 'unread_artefacts':
 ('új ötletmorzsák', 'There is a number before this message'),
 'total_artefacts':
 ('összesen', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ('Biztosan tötölni szeretnéd a következõ ötletbörzé(ke)t:',
  'Message dialog message'),
 'are_you_sure_jam_session':
 ('Biztos, hogy törölni szeretnéd ezt az ötletbörzét %s ötletmorzsával együtt?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 ('Ötletmorzsa törlése', 'Button label for removing jam artefact'),
 'restore_artefact':
 ('Ötletmorzsa visszaállítása',
  'Button label for restoring jam artefact'),
 'remove_annotation':
 ('Kijelölt megjegyzések törölve',
  'Button label for removing jam annotations'),
 'restore_annotation':
 ('A kiválasztott megjegyzés visszaállítása',
  'Button label for restoring jam annotations'),
 'removed_name':
 ('Törölve', 'Title/name for removed jam artefact'),
 'removed_message':
 ('Ezt az ötletmorzsát %s törölte. Idõpont: %s.',
  "First placeholder is replaced by remover's name and the second by the date"),
 'removed_msg':
 ('Ötletmorzsa törölve',
  'Message shown to the teacher when she has removed an artefact.'),
 'removed_annotation_msg':
 ('Megjegyzés törölve',
  'Message shown to the teacher when she has removed an annotation.'),
 'remove_verify':
 ('Biztos, hogy törölni szeretnéd ezt az ötletmorzsát? A nevedet, a dátumot és az általad megadott okot a rendszer tárolja és a törlés jelölésével együtt megjeleníti.',
  'Verification message shown when removing is attempted'),
 'remove_annotations_verify':
 ('Biztos, hogy törölni szeretnéd a kiválasztott megjegyzést? A nevedet, a dátumot és az általad megadott okot a rendszer tárolja és a törlés jelölésével együtt megjeleníti.',
  'Verification message shown when removing is attempted'),
 'removed_annotation_body':
 ('Ezt a megjegyzést %s törölte. Idõpont: %s.',
  "Body for removed annotation. First placeholder is replaced by remover's name and the second by the date"),
 'search_jam':
 ('Keresés az Ötletházban', 'Link label'),
 'searching_jam':
 ('Keresés az ötletmorzsák között', 'Label'),
 'search_artefact_name':
 ('Ötletmorzsa neve', 'Label in search form'),
 'search_artefact_author':
 ('Szerzõ', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Szöveges megjegyzések',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ('Ötletmorzsa típusa',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Kép', 'Artefact type'),
 'type_audio':
 ('Hang', 'Artefact type'),
 'type_text':
 ('Szöveg', 'Artefact type'),
 'type_html':
 ('Html', 'Artefact type'),
 'type_video':
 ('Videó', 'Artefact type'),
 'type_archive':
 ('Archívum', 'Artefact type'),
 'search_annotated_by':
 ('Jegyzetekkel ellátta:', 'Label in search form'),
 'search_results_author':
 ('Szerzõ', 'Heading in search results table'),
 'search_results_jam_artefact':
 ('Ötletmorzsa', 'Heading in search results table'),
 'search_results_jam_session':
 ('Ötletbörze', 'Heading in search results table')}

announce = {'comments':
 ('Megjegyzések', 'Notice / form heading'),
 'no_comments':
 ('Nincsenek megjegyzések.', 'Notice'),
 'recent_comments':
 ('Friss megjegyzések', 'Heading'),
 'no_entries':
 ('Nincsenek bejegyzések.', 'Notice'),
 'recent_entries':
 ('Friss bejegyzések', 'Heading'),
 'trackbacks':
 ('Utalások', 'Notice'),
 'no_trackbacks':
 ('Nincsenek utalások.', 'Notice'),
 'recent_trackbacks':
 ('Friss utalások', 'Heading'),
 'send_trackback':
 ('Kérlek, küldj utalást a következõ helyhez:',
  'Part of message, followed by url'),
 'syndicate':
 ('A honlap átvétele (XML)', 'Link'),
 'log_in':
 ('Fle3 - belépés.', 'Link'),
 'entries':
 ('Bejegyzések', 'Heading'),
 'category':
 ('Kategória', 'Heading'),
 'categories':
 ('Kategóriák', 'Heading'),
 'no_categories':
 ('Nincsenek kategóriák', 'Notice'),
 'items':
 ('bejegyzés', 'Part of message: nn items.'),
 'posted_by':
 ('küldõ:', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%m/%d %H:%M', 'Short date format'),
 'dateformat':
 ('%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 ('idõpont: ', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('Megjegyzés küldése', 'Heading'),
 'name':
 ('Név', 'Form heading'),
 'email':
 ('E-mail', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('Cím', 'Form heading'),
 'body':
 ('A hirdetmény szövege', 'Form heading'),
 'forget_personal':
 ('Személyes információk nélkül', 'Button'),
 'teachers_and_tutors_only':
 ('csak tanároknak és segítõknek',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('Megjegyezzük a szeméyes információkat "süti" formájában?',
  'Label'),
 'Announcement':
 ('Hirdetmény', 'Category'),
 'ToDo':
 ('Tennivaló', 'Category'),
 'Event':
 ('Esemény', 'Category'),
 'continue_reading':
 ('Olvasás folytatása', 'Part of message, followed by entry title'),
 'missing1':
 ('hiányzik', 'Part of message'),
 'missingn':
 ('hiányoznak', 'Part of message'),
 'comment_preview':
 ('Megjegyzés elõnézete', 'Heading'),
 'search_results':
 ('Keresés eredménye', 'Heading'),
 'search_for':
 ('Keresés a hirdetmények között', 'Part of message'),
 'no_match':
 ('Nincs találat', 'Notice'),
 'about':
 ('Leírás', 'Title'),
 'archives':
 ('Archívum', 'Title'),
 'search':
 ('Keresés', 'Heading'),
 'search_help':
 ('Használhatod az AND/OR szavakat a logikai kereséshez.',
  'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

