# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_no.py,v 1.43 2005/01/15 11:07:36 tarmo Exp $
#
# Copyright 2001, 2002, 2003 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the norwegian translations for all Fle3 printable strings."""

# How to do a new translation:
#
# 1. Copy this file into a new file, appending the language code after it, so
# you get something like "vocabulary_es.py" for Spanish and so on.
#
# 2. Edit the new file, translating the second portion of each line. The
# first portion is the keyword, which you shouldn't touch. The second is the
# translation that should be translated to the target language. The third
# is the supplementary instruction, that should help you do the translations.
#
# 3. Please note that the file is in Python code and needs to follow certain
# syntax rules:
#  - Strings can either be quoted by singles quotes (') or double quotes (").
#    If you need to use either of these quotation marks in your translation,
#    make sure that you use the other quotation mark to surround the string.
#    If you need to use both quotation marks in the same translation string,
#    you can surround the string with triple quotes (''' or """), which
#    allows you to use either of the quotation marks inside the string.
#  - Line breaks are not allowed inside strings, so make sure you don't
#    use an editor that wraps lines. You can have line breaks between
#    strings, though.
#
# 4. If you need to use special characters (outside of the 127 character
# ASCII range), you have several choices:
#
# A. Write in your native encoding (whatever suits you best). This requires
#    that you change the "charset_encoding" keyword in the "common" module to
#    the encoding type you will use. This document is written in iso8859-1,
#    although as english does not contain special characters, it could be
#    in utf-8 as well without any differences.
#    Most European languages are easiest to write in iso8859-1.
#
# B. Write in utf-8 encoded unicode. If your editor can save files in utf-8,
#    use that feature. If not, you can add the special characters manually
#    with the \x escape sequences. Make sure you remove the keyword
#    "charset_encoding" from the "common" module, or change its value to
#    "utf-8" so that the strings are interpreted correctly.
#    'key', ('\xe3\x82\xaa','This is the katakana letter O,encoded in utf-8.'),
#
# C. Write in unicode. Each unicode string starts with u followed by the
#    quotes. Each unicode character starts with \u followed by the code in
#    hexadecimal notation. The value of the "charset_encoding" keyword
#    is irrelevant if you use unicode all the way.
#    'key', (u'\u30aa','This is the katakana letter O, encoded in unicode.'),
#
# 5. Check your translation. If you have Python installed and you've
#    downloaded Fle3 sources, you can execute "python TranslationLint.py"
#    which will check through all the translation files and will produce
#    an error if there is a syntax error.
#    If you have installed Fle3, you can test the translation yourself
#    by going to Zope Management and selecting the Tools tab in your FLE
#    instance, and clicking on "reload_translations". After this you
#    should be able to select your translation from user preferences
#    and see the translated strings.
#

common = {'language_name':
 ('Norwegian(Bokmål)', 'Name of this language'),
 'charset_encoding':
 ('iso8859-1',
  'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('WebTop', 'Main tab for webtop'),
 'Knowledge_Building':
 ('Kunnskapsbygging', 'Main tab for knowledge building'),
 'Course_Management':
 ('Kursadministrering', 'Main tab for course management'),
 'User_Management':
 ('Brukeradministrering', 'Main tab for user management'),
 'Jamming':
 ('Jamming', 'Main tab for jamming'),
 'Type_Management':
 ('Kunnskapstyper-redigering', 'Heading'),
 'cancel':
 ('Avbryte', 'Button label'),
 'submit':
 ('Registrere', 'Button label'),
 'remove':
 ('Fjerne', 'Button label'),
 'next':
 ('Neste ->', 'Label for button'),
 'previous':
 ('<- Forrige', 'Label for button'),
 'quick_submit':
 ('Hurtigregistrering', ''),
 'ok':
 ('Ok', 'Button label'),
 'save':
 ('Lagre', 'Button label'),
 'create':
 ('Opprette', 'Button label'),
 'search':
 ('Søke', 'Button label'),
 'webtop':
 ('Webtop', ''),
 'description':
 ('Beskrivelse', 'Label'),
 'short_date_format_display':
 ('YYYY-MM-DD', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%Y-%m-%d', 'Format string for short dates'),
 'timestamp_format':
 ('%H:%M %Y-%m-%d', 'Format string for long timestamps'),
 'invite':
 ('Invitere', ''),
 'add':
 ('Legg til', ''),
 'today':
 ('I dag', ''),
 'groupfolder':
 ('Gruppemappe', 'Heading'),
 'yesterday':
 ('I går', ''),
 'dtml_reloaded':
 ('DTML lastet på nytt', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('DTML filer lastet på nytt for dette objektet', 'Message dialog text'),
 'dtmls_reloaded':
 ("DTML'er lastet på nytt", 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Alle DTML filer lastet på nytt', 'Message dialog text'),
 'css_reloaded':
 ('Stil ark (CSS) lastet på nytt', 'Title for message dialog'),
 'css_files_reloaded':
 ('Stil ark filer lastet på nytt for dette objektet', 'Message text'),
 'error':
 ('Feil', ''),
 'warning':
 ('Advarsel', ''),
 'invalid_url':
 ('Ugyldig adresse (URL)', 'Message title'),
 'invalid_url_message':
 ('Det virker som om URL adressa du skrev inn er feil.<br>Vennligst sjekk at den begynner med http://, ftp://, mailto: eller andre Internett adresse protokoller du vil bruke. Legg merke til at du ikke kan skrive inn en adresse av typen "www.myaddress.org" men at du må spesifiser protokollen først: "htpp://www.myaddress.org". Hvis du ikke vet protokollen for din web-adresse, prøv å kopiere og deretter lime inn den komplette adressen fra adressefeltet i din nettleser.',
  'Message text'),
 'invalid_name':
 ('Ugyldig navn', 'Message title'),
 'give_valid_name':
 ('Vennligst skriv inn et gyldig navn', 'Message text'),
 'name_taken':
 ('Et annet element har dette navnet "%s". Velg et annet navn.',
  'Message text, name inserted inside'),
 'edit':
 ('Rediger', 'Button label'),
 'you_are_in':
 ('Du er i:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ('Du har ikke fylt inn alle felt.', 'Erro message text'),
 'confirmation':
 ('Bekreftelse', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Ugyldig inntastingsdata', 'Message title'),
 'invalid_fields':
 ('Følgende felt har ugyldig inntastingsdata',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ('Velg et element først', 'Message text'),
 'link_to_webtop':
 ('Lage lenke på WebTop', 'Link'),
 'proxy_to_webtop':
 ('Legg gruppemappe til WebTop', 'Link'),
 'export':
 ('Eksportere', 'Button label'),
 'import':
 ('Importere', 'Button label'),
 'importing':
 ('Importerer', 'Heading start'),
 'megabyte':
 ('MB', 'Abbreviation for megabyte'),
 'kilobyte':
 ('KB', 'Abbreviation for kilobyte'),
 'logout_pre3':
 ('For å logge av, avslutt nettleseren.', 'Instructions for logging out'),
 'logout':
 ('Logge av', 'Link for logging out, also heading in logout dialogs'),
 'any':
 ('Ethvert', 'Label'),
 'course':
 ('kurs', 'Part of location path'),
 'language':
 ('Språk', ''),
 'announcements':
 ('Kunngjøringer', 'Link/heading'),
 'sun':
 ('Sun', 'Weekday abbreviation'),
 'mon':
 ('Man', 'Weekday abbreviation'),
 'tue':
 ('Tir', 'Weekday abbreviation'),
 'wed':
 ('Ons', 'Weekday abbreviation'),
 'thu':
 ('Tor', 'Weekday abbreviation'),
 'fri':
 ('Fre', 'Weekday abbreviation'),
 'sat':
 ('Lør', 'Weekday abbreviation'),
 'sunday':
 ('Søndag', 'Weekday'),
 'monday':
 ('mandag', 'Weekday'),
 'tuesday':
 ('tirsdag', 'Weekday'),
 'wednesday':
 ('onsdag', 'Weekday'),
 'thursday':
 ('Torsdag', 'Weekday'),
 'friday':
 ('fredag', 'Weekday'),
 'saturday':
 ('lørdag', 'Weekday'),
 'January':
 ('Januar', 'Month'),
 'February':
 ('Februa', 'Month'),
 'March':
 ('Mars', 'Month'),
 'April':
 ('April', 'Month'),
 'May':
 ('Mai', 'Month'),
 'June':
 ('Juni', 'Month'),
 'July':
 ('July', 'Month'),
 'August':
 ('August', 'Month'),
 'September':
 ('September', 'Month'),
 'October':
 ('Oktober', 'Month'),
 'November':
 ('November', 'Month'),
 'December':
 ('Desember', 'Month'),
 'remove_q':
 ('Fjerne?', 'Question')}

kb = {'month':
 ('måned', ''),
 'week':
 ('uke', ''),
 'you_have_not_replied_to':
 ('Du har ikke svart', 'followed by a list of persons'),
 'total_replies':
 ('Antall svar på andres innlegg:', 'followed by number'),
 'total_notes_written':
 ('Antall innlegg skrevet:', 'followed by number'),
 'graph_type':
 ('Graf type: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('kunnskapstype', 'graph type'),
 'adding_resource':
 ('legger til ressurs', 'part of browser title'),
 'replies':
 ('svar', 'graph type'),
 'display_by':
 ('Vis etter:', 'Label for timescale (week/month) selection'),
 'modifying_resource':
 ('endrer ressurs', 'part of browser title'),
 'title_resource':
 ('Tittel', 'The title of resource'),
 'author_resource':
 ('Forfatter', 'The author of the resource'),
 'url':
 ('URL', 'Resource URL'),
 'location':
 ('Lokasjon', 'Resource location'),
 'course_info':
 ('Kursopplysninger', 'Label for link to course details'),
 'create_context':
 ('Lage ny kurskontekst', 'Link to create new course context'),
 'hide_context':
 ('Skjule kontekst', 'Link to hide a context from view'),
 'show_context':
 ('Vise kontekst', 'Link to show a hidden context'),
 'new_notes':
 ('nye innlegg',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('innlegg', 'Label for showing the number of notes'),
 'full_description':
 ('hel beskrivelse...', ''),
 'course':
 ('kurs', "String 'course' in context display"),
 'context':
 ('kontekst', "String 'context' in context display"),
 'thread':
 ('tråd', "String 'thread' in context display"),
 'note':
 ('innlegg', "String 'note' in context display"),
 'start_thread':
 ('Start tråd', 'Link'),
 'short_description':
 ('Kort beskrivelse', 'Label'),
 'long_description':
 ('Lang beskrivelse', 'Label'),
 'full_description':
 ('Hel beskrivelse', 'Label'),
 'select':
 ('Velge',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('kunnskapstype', 'Label'),
 'add_note':
 ('Lage nytt innlegg', 'Button label'),
 'show_notes':
 ('Vise innlegg', 'Heading start'),
 'show_thread':
 ('som tråd', 'heading finish'),
 'show_type':
 ('etter kunnskapstyper', 'heading finish'),
 'show_author':
 ('etter person', 'heading finish'),
 'show_date':
 ('etter dato', 'heading finish'),
 'select_course':
 ('velg kurs', 'Label, followed by a drop-down list of available courses'),
 'creating_context':
 ('Lager ny kurskontekst i', 'Title, followed by the course name'),
 'editing_context':
 ('Redigerer kurskontekst i', 'Title, followed by the course name'),
 'title_of_context':
 ('Tittelen til kurskonteksten', 'Label'),
 'type_set':
 ('Kunnskapstype sett', 'Label'),
 'creating_note_in':
 ('Lager nytt notat i', 'Title, followed by course context name'),
 'course_context':
 ('kurskontekst', 'Label for course context'),
 'you_are_replying_to':
 ('Du svarer på', 'Label'),
 'title_of_note':
 ('Tittelen til innlegget', 'Label'),
 'message_body':
 ('Innlegg tekst', 'Label'),
 'current_image':
 ('Nåværende bilde', 'Label'),
 'replace_with':
 ('Bytte ut med', 'Label for image replacement in note edit'),
 'add_image':
 ('Legge til bilde', 'Label'),
 'title_of_image':
 ('Tittel for bilde', 'Label'),
 'add_link':
 ('Legge til (URL)', 'Label'),
 'title_of_link':
 ('Tittel for lenka', 'Label'),
 'preview':
 ('Forhåndsvisning', 'Button label'),
 'previewing_note':
 ('Forhåndsviser innlegget i',
  'Title/heading, followed by course context name'),
 'publish':
 ('Publisere', 'Button label'),
 'search_kb':
 ('Søk i kunnskapsbyggingen', 'Link label'),
 'searching_kb':
 ('Søker i innlegg', 'Label'),
 'search_author':
 ('Forfatter', 'Label'),
 'search_notes_words':
 ('Innlegg som inneholder ordene', 'Label'),
 'search_context':
 ('Kurskontekst', 'Label'),
 'search_tt':
 ('Kunnskapstyper', 'Label'),
 'search_note':
 ('Innlegg', 'Label'),
 'you_didnt_select_type':
 ('Du glemte å velge en kunnskapstype.', 'Title'),
 'current_note':
 ('Aktuelt innlegg', 'Label'),
 'go_back':
 ('Gå tilbake', 'Start of message, rendered into a link'),
 'and_select_type':
 ('og velg en kunnskapstype for innlegget ditt.', 'Rest of message'),
 'inline_notes':
 ('Vise teksten til alle innlegg', 'Link'),
 'outline_notes':
 ('Skjule teksten til alle innlegg', 'Link'),
 'view_info':
 ('se på informasjon', 'Part of location bar'),
 'edit_context':
 ('Redigere kurskontekst', 'Link'),
 'to_note':
 ('til innlegg', 'Part of a message'),
 'full_thread_no':
 ('Vis bare start innlegg', 'Link'),
 'full_thread_yes':
 ('Vis hele tråden', 'Link'),
 'remove':
 ('Ta vekk', 'Button label for censoring notes'),
 'restore':
 ('Gjenopprette innlegg', 'Button label for uncensoring notes'),
 'remove_form_title':
 ('Ta vekk innlegg', 'Title for note censoring form'),
 'remove_form_label':
 ('Fjerner innlegg', 'Explanation in censor form, followed by note subject'),
 'removed_msg':
 ('Beskjed fjernet', 'Message shown when teacher censores a note.'),
 'remove_explanation':
 ('Forklaring for fjerning', 'Label for censor explanation text area'),
 'remove_verify2':
 ('Er du sikker på at du vil fjerne denne beskjeden ? Ditt navn, dagens dato og forklaringen du gir under vil bli lagret og vist sammen med en "fjernet beskjed" til alle som ser dette innlegget.',
  'Verification message shown when removing is attempted'),
 'removed_subject':
 ('Fjernet', 'Title/subject for censored notes'),
 'removed_body':
 ('Denne beskjeden er fjernet av %s : %s.',
  "Body for censored messages. First placeholder is replaced by censorer's name and the second by the date"),
 'notes_from_day':
 ('Innlegg fra', 'Start of heading, followed by a date'),
 'previous':
 ('Forrige', 'Link label'),
 'next':
 ('Neste', 'Link label'),
 'who_has_read':
 ('Hvem har lest dette innlegget ?', 'Link label'),
 'last_read':
 ('Sist gang lest', 'Label'),
 'times_read':
 ('Antall ganger lest', 'Label'),
 'back':
 ('< tilbake', 'Link label'),
 'unread_to_read_msg':
 ('Alle innlegg i tråden merket som lest.',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Merk alle innlegg som lest', 'text in a button'),
 'creating_groupfolder':
 ('Lager en ny gruppemappe i', 'Heading start'),
 'title_groupfolder':
 ('Tittelen til gruppemappa', 'Label'),
 'flea_asks':
 ('Flea sier',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Endre kunnskapstypen?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ('Dette er den eneste typen tillatt her.',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Endre', 'Button label'),
 'down_to_note':
 ('Gå til innlegget i tråden', 'Link label'),
 'use_roleplay':
 ('Bruk rollespill i denne konteksten',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('Setter opp roller til bruk i rollespillet',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 ('Kurs', "Heading for user's course list"),
 'totals_notes':
 ('Innlegg',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ('Artefakter',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s nye / %s totalt',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Lage ny mappe', ''),
 'add_document':
 ('Legge til dokument', ''),
 'add_link':
 ('Legge til lenke', ''),
 'create_memo':
 ('Lage notat', ''),
 'type':
 ('Type', 'Common heading for sort links by_name and by_date'),
 'title':
 ('Tittel', 'Link for sorting by name'),
 'date':
 ('Dato', 'Link for sorting by date'),
 'size':
 ('Størrelse', 'Link for sorting by size'),
 'remove':
 ('Fjerne', 'Button label'),
 'restore':
 ('Gjenopprette', 'Button label'),
 'rename':
 ('Gi nytt navn', 'Button label'),
 'copy':
 ('Kopiere', 'Button label'),
 'cut':
 ('Klippe ut', 'Button label'),
 'paste':
 ('Lime inn', 'Button label'),
 'delete':
 ('Slette', 'Button label'),
 'select_all':
 ('Velge alle', 'Button label'),
 'trash':
 ('Papirkurv', 'Label for trashcan'),
 'empty_trash':
 ('Tøme papirkurv', 'Button label'),
 'adding_folder':
 ('Legger til en mappe', 'Heading'),
 'title_of_folder':
 ('Tittelen til mappa', 'Label'),
 'creating_memo':
 ('Lager notat', 'Title'),
 'viewing_memo':
 ('Ser på notat', 'Title'),
 'editing_memo':
 ('Redigerer notat', 'Title'),
 'title_of_memo':
 ('Tittelen til notatet', 'Label'),
 'content':
 ('Innhold', 'Label'),
 'show_memo_contents':
 ('Vis bare innholdet', 'Link'),
 'adding_link':
 ('Legger til en lenke', 'Title'),
 'title_of_link':
 ('Tittelen til lenka', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Dokument lastet opp.', 'Status message'),
 'adding_document':
 ('Legger til dokument', 'Title'),
 'upload_document':
 ('Laste opp dokument', 'Label'),
 'title_of_document':
 ('Tittelen til dokumentet', 'Label'),
 'search_wt':
 ('Søke WebTop', 'Link label'),
 'searching_wt':
 ('Søker på WebTop', 'Label'),
 'search_results':
 ('Søke resultat', 'Label'),
 'new_search':
 ('Nytt søk', 'Label'),
 'search_title':
 ('Tittel', 'Label'),
 'search_owner':
 ('Eier', 'Label'),
 'search_words':
 ('Element som inneholder ordene', 'Label'),
 'search_object':
 ('Element', 'Label'),
 'search_folder':
 ('Mappe', 'Label'),
 'viewing_search_results':
 ('Ser på søkeresultat', 'Label in the location path'),
 'anyone':
 ('Noen', 'Label'),
 'webtop_link_added':
 ('WebTop lenke lagt til', 'Message title'),
 'added_webtop_link':
 ('En lenke %s "%s" ble lagt til din Webtop. Klikk ok for å returnere til den forrige sida.',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 ('Gruppe lagt til', 'Message title'),
 'added_proxy':
 ('Gruppemappa til kurs %s er nå synlig på din WebTop. Klikk ok for å returnere til den forrige sida.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ('Ingen element valgt!', 'Message dialog title'),
 'select_item_first':
 ('Vennligst velg minst et element for å utføre en handling annet enn å lime inn.',
  'Message dialog message'),
 'no_file_supplied':
 ('Ingen fil spesifisert.', 'Message text'),
 'renaming':
 ('Gir nytt navn', 'Title'),
 'invalid_names':
 ('De følgende navnene er ugyldige:', 'Message dialog messsage'),
 'same_names':
 ('Du gav det samme navnet til flere element.', 'Message dialog message'),
 'names_in_use':
 ('De følgende navnene er allerede i bruk:', 'Message dialog message'),
 'information':
 ('Opplysninger', 'Link'),
 'preferences':
 ('Instillinger', 'Link'),
 'editing_preferences':
 ('Rediger instillinger', 'Title'),
 'shared_course_folder':
 ('Delt kursmappe',
  'Printed after the name of the group folder in webtop contents list.'),
 'quota_reached_title':
 ('Plasskvote øvre grense nådd', 'Title'),
 'quota_reached':
 ('Operasjonen kan ikke bli utført for du har brukt opp all tilgjengelig disk-plass på din WebtTop. Fjern noen objekt og prøv igjen.',
  'Message dialog message'),
 'obj_removed':
 ('(mållenka er fjernet)',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('< tilbake', 'Link label')}

usermgmnt = {'user':
 ('bruker', 'part of browser title'),
 'adding_users':
 ('Legger til ny bruker', 'Title'),
 'required_field':
 ('Krevd felt', ''),
 'nickname':
 ('nick', 'Label'),
 'user_account':
 ('Brukerkonto', 'Label'),
 'Confirm':
 ('Bekreft', ''),
 'you_are_removing':
 ('Du fjerner', ''),
 'invite_user':
 ('Invitere ny', ''),
 'invite_users':
 ('Invitere brukere', 'Heading for invitation form'),
 'email_addresses':
 ('E-post adresse', ''),
 'separate_with_comma':
 ('( separer med: , )', ''),
 'Invitation_message':
 ('Invitasjons tekst', ''),
 'Invitation_language':
 ('Invitasjons språk', ''),
 'Courses_to_invite_to':
 ('Kurs invitert til', ''),
 'Freeze':
 ('Lås fast', ''),
 'Remove':
 ('Fjerne', ''),
 'role':
 ('Rolle', 'label'),
 'role_staff':
 ('Lærer', 'Global role stuff'),
 'role_user':
 ('Bruker', 'Global role user'),
 'role_fleadmin':
 ('FLE Admin', 'Global role fleadmin'),
 'invite_again':
 ('Invitere igjen', 'Button label'),
 'warning':
 ('Advarsel', 'Heading'),
 'want_remove_users':
 ('Vil du fjerne de følgende brukerene ?', 'Complete question'),
 'invited_user_manage':
 ('Administrering av inviterte brukere', 'Title'),
 'info_user':
 ('Informasjon om ', 'Title for user info page, prefix before usre name'),
 'edit_user':
 ('Rediger bruker', 'Link'),
 'editing':
 ('Redigerer', 'Heading for user edit, inserted before user name'),
 'image_of_user':
 ('Bilde av brukeren', 'Label'),
 'upload_image_of_user':
 ('Last opp et bilde av brukeren', 'Label'),
 'or_link_to_image':
 ('eller skriv inn en adresse(URL) til bildet',
  'Label, continuing from the upload label'),
 'webtop_bg':
 ('WebTop bakgrunnsbilde', 'Label'),
 'upload_webtop_bg':
 ('eller last opp eget bakgrunnsbilde',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Vise ikke registrerte', ''),
 'add_user':
 ('Legge til ny', ''),
 'Unfreeze':
 ('Lås opp', ''),
 'Users':
 ('Brukere', ''),
 'gsm':
 ('Mobil', ''),
 'last_name':
 ('Etternavn', ''),
 'first_name':
 ('Fornavn', ''),
 'city':
 ('By', ''),
 'organization':
 ('Organisasjon', ''),
 'professional_interests':
 ('Faglige interesser', ''),
 'email':
 ('E-post', ''),
 'phone':
 ('Telefon', ''),
 'url_to_photo':
 ('URL til bilde', ''),
 'country_menu_default':
 ('Velg land', ''),
 'group_menu_default':
 ('Velg gruppe', 'Default value for drop-down menu'),
 'address':
 ('Adresse', ''),
 'address1':
 ('Adress linje 1', ''),
 'address2':
 ('Adress linje 2', ''),
 'personal_interests':
 ('Personlige interesser', ''),
 'quote':
 ('Sitat', ''),
 'homepage':
 ('Hjemmeside', ''),
 'upload':
 ('Laste opp', ''),
 'group':
 ('Gruppe', ''),
 'password':
 ('Passord', ''),
 'background':
 ('Bakgrunn', ''),
 'country':
 ('Land', ''),
 'reserved_nickname':
 ('Beklager. Nick er allerede i bruk.', 'Message'),
 'password_mismatch':
 ('Passordene passer ikke sammen.', 'Message'),
 'could_not_send_invitation':
 ('Kunne ikke sende invitasjon. Vennligst sjekk at ditt MailHost objekt er konfigurert riktig.',
  'Error message'),
 'invitations_sent':
 ('Invitasjon sendt', 'Message title'),
 'invitations_sent_to':
 ('Invitasjon sendt til %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 ('Invitasjon vart ikke sendt til: %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Brukere fjernet', 'Message title'),
 'removed_users':
 ('Bruker fjernet: %s', 'Message, list inserted inside'),
 'not_removed_users':
 ('Ute av stand til å fjerne dissse brukerne: %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 ('Invitasjon sendt om igjen', 'Message title'),
 're_invitations_sent_to':
 ('Invitasjon sendt om igjen til %s brukere. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Påventende brukere fjernet', 'Message title'),
 'pending_removed_users':
 ('Inviterte men ikke innmeldte brukere fjernet: %s',
  'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Ute av stand til å fjerne disse påventende brukerne: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ('Invitasjon til FLE', 'Subject for invitation messages'),
 'invitation_header':
 ('Invitasjon', 'Header for invitation messages'),
 'invitation_footer':
 ('Vennligst besøk: ',
  'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Velkommen til FLE. Fyll inn dine personlige opplysninger under.',
  'Welcome message used in invitation registration form'),
 'uname':
 ('Login navn', 'Label used for user login name in several places'),
 'registration_failed':
 ('Registrering misslykket', "Title used when invited user can't register."),
 'after_submit_give_name_and_passwd2':
 ('Klikk "Submit" gi deretter ditt login navn og passord.', 'Message'),
 'invitation_key_used':
 ('Denne invitasjons adressa(URL) er allerede blitt brukt eller er ikke gyldig lenger. Hvis du ikke har registreret deg enda, ta kontakt med din læreren.',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ('Autentiseringsnøkkler er ugyldige',
  "Message telling that the authentication key isn't valid."),
 'frozen':
 ('Fryst fast', 'User status code'),
 'show_frozen':
 ('Vis låste brukere', 'Link to show all users'),
 'show_active':
 ('Vis bare aktive brukere', 'Link to show only active users'),
 'passwd_changed_explanation2':
 ('Du har endret ditt passord: Nettleseren vil nå spørre deg om brukernavn og passord på nytt.',
  'Message text'),
 'no_email':
 ('Ingen e-post adresse', 'Message title'),
 'no_email_explanation':
 ('Du kan ikke sende e-post fordi du har ikke satt opp en e-post adresse.',
  'Message text'),
 'passwd_changed':
 ('Passord endret', 'Message title'),
 'external_user_database_explanation':
 ('Din FLE3 installasjon bruker en ekstern brukerdatabase. For å kunne legge til nye brukere må du bruke den eksterne databasen.',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 ('kurs', 'part of browser title'),
 'courses':
 ('Kurs', 'Title'),
 'create_course':
 ('Opprette kurs', 'Link'),
 'edit_course':
 ('Redigere kurs', 'Button label'),
 'edit_participants':
 ('Redigere brukere', 'Button label'),
 'creating_course':
 ('Lager et nytt kurs', 'Title'),
 'editing_course':
 ('Redigerer kurs', 'Title'),
 'course_title':
 ('Kurs tittel', 'Label'),
 'organization':
 ('Organisasjon', 'Label'),
 'methods':
 ('Metoder', 'Label'),
 'starting_date':
 ('Start dato', 'Label'),
 'ending_date':
 ('Slutt dato', 'Label'),
 'create_groupfolder':
 ('Lag gruppe mappe', 'Link'),
 'create_announcements':
 ('Lag kunngjøring', 'Link'),
 'edit_announcements':
 ('Rediger kunngjøring', 'Link'),
 'add_announcement':
 ('Ny kunngjøring', 'Link'),
 'adding_announcement':
 ('Legger til kunngjøring i', 'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('Vil du virkelig fjerne denne kunngjøringa?', 'Question'),
 'editing_announcements':
 ('Redigerer kunngjøringer', 'Heading'),
 'viewing_announcements':
 ('Viser kunngjøringer i kurset %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ('Legger til ny bruker til kurs',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('Hvis ikke kursdeltakerene allerede er FLE3-brukere', 'Message'),
 'new_participants_to_system':
 ('nye deltakere til Fle3 systemet', 'Part of a phrase'),
 'by_email':
 ('via e-post', 'Part of a phrase'),
 'manually':
 ('manuelt', 'Part of a phrase'),
 'fle_users':
 ('FLE3 brukere', 'Heading'),
 'down':
 ('Ned', 'Button label'),
 'up':
 ('Opp', 'Button label'),
 'teachers':
 ('Lærere', 'Heading'),
 'tutors':
 ('Veiledere', 'Heading'),
 'students':
 ('Studenter', 'Heading'),
 'add_button':
 ('Legg til ->', 'Button label'),
 'remove_button':
 ('<- Fjern', 'Button label'),
 'viewing_course':
 ('Ser på kurs', 'Part of a phrase in location path'),
 'viewing_course_resources':
 ('viser ressurser for kurs %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 ('Informasjon', 'Part of a phrase in location path'),
 'no_course_selected':
 ('Ingen kurs valgt!', 'Message dialog title'),
 'select_course_first':
 ('Vennligst velg et kurs fra kurslisten.', 'Message dialog message'),
 'set_published':
 ('Kunnskapstype type sett publisert', 'Message dialog title/text'),
 'users_updated':
 ('Brukere oppdatert', 'Message dialog title/message'),
 'select_some_users':
 ('Vennligst velg noen brukere', 'Message dialog title/message'),
 'edit_course_info':
 ('Rediger kurs opplysninger', 'Link'),
 'edit_course_participants':
 ('Endre kursdeltakere', 'Link'),
 'edit_course_resources':
 ('Rediger kursressurser', 'Link'),
 'date':
 ('Dato', 'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('Kursdeltakere', 'Label'),
 'type_sets':
 ('Kunnskapstypesett', 'Label, plural'),
 'delete':
 ('Slette', 'Button label'),
 'my_participation':
 ('Min deltakelse', 'Label'),
 'my_notes':
 ('Mine innlegg', 'Link'),
 'my_artefacts':
 ('mine artefakter', 'Link'),
 'course_resources':
 ('Kursressurser', 'Label'),
 'add_typeset':
 ('Legg til kunnskapstypesett', 'Link'),
 'tt_yellow':
 ('Gul', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Lys gul', 'Knowledge type colour name'),
 'tt_orange':
 ('Oransje', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Lys oransje', 'Knowledge type colour name'),
 'tt_red':
 ('Rød', 'Knowledge type colour name'),
 'tt_pink':
 ('Rosa', 'Knowledge type colour name'),
 'tt_purple':
 ('Lilla', 'Knowledge type colour name'),
 'tt_blue':
 ('Blå', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Lys blå', 'Knowledge type colour name'),
 'tt_aqua':
 ('Aqua', 'Knowledge type colour name'),
 'tt_green':
 ('Grønn', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Lys grønn', 'Knowledge type colour name'),
 'tt_gray':
 ('Grå', 'Knowledge type colour name'),
 'tt_white':
 ('Hvit', 'Knowledge type colour name'),
 'edit_typeset':
 ('Rediger kunnskapstypesett ', 'Heading'),
 'create_typeset':
 ('Lager nytt kunnskapstype sett', 'Heading'),
 'title':
 ('Tittel', 'Start of label'),
 'form':
 ('Form', 'Start of heading'),
 'of_typeset':
 ('til kunnskapstypesettet', 'Ending of label'),
 'abbreviations_and_icons':
 ('forkortelser og ikoner', 'Ending for heading'),
 'type':
 ('Kunnskapstype', 'Label'),
 'types':
 ('Kunnskapstype typer', 'Title'),
 'types_management':
 ('Kunnskapstyper redigering', 'Title'),
 'abbreviation':
 ('Forkortelse', 'Label'),
 'color':
 ('Farge', 'Label'),
 'icon':
 ('Ikon', 'Label'),
 'starting_phrase':
 ('Start frase', 'Label'),
 'checklist':
 ('Sjekk liste', 'Label'),
 'no_types_entered':
 ('Du har ikke lagt inn noen kunnskapstype. Et sett må inkludere minst en type.',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ('Bruksrestriksjoner', 'Heading sentence.'),
 'that_can_start_thread':
 ('som kan starte en diskusjon', 'End of label'),
 'viewing':
 ('ser', 'Part of location bar'),
 'new_typeset_from':
 ('Dupliser og rediger kunnskapstypeset',
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Uferdig', 'Label'),
 'manage_types':
 ('Administrere kunnskapstyper', 'Link'),
 'finalize_typeset':
 ('Endre status til ferdig', 'Button label'),
 'are_you_sure':
 ('Er du sikker på at du vil slette følgende kurs:',
  'Message dialog message'),
 'are_you_sure_ctx':
 ('Er du sikker på at du vil slette denne kurskonteksten ?',
  'Message dialog message'),
 'are_you_sure_tts':
 ('Er du sikker på at du vil slette følgende kunnskapstype sett ?',
  'Message dialog message'),
 'typeset_importing':
 ('Vennligst velg den kommprimerte (zip) eksport filen som inneholder kunnskapstypesettet du vil importere.',
  'Instructions for typeset importing'),
 'typesets_imported':
 ('Nytt kunnskapstypesett er blitt importert', 'Message'),
 'import_typeset':
 ('Importere kunnskapstypesett', 'link'),
 'course_importing':
 ('Vennligst velg den kommprimerte (zip) eksport filen som inneholder kurset du vil importere.',
  'Instructions for course importing'),
 'courses_imported':
 ('Nytt kurs er importert.', 'Message'),
 'import_course':
 ('Importere kurs', 'link'),
 'course_imported':
 ('(importert)', 'Appended to imported course names.'),
 'can_start_thread':
 ('Kan starte tråd?', 'column title in a table'),
 'can_be_followed':
 ('kan etterfølges av', 'column title in a table'),
 'use_each_type':
 ('Hver kunnskapstype må følge etter minst en annen type eller starte en tråd.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Ressurser', 'Title for list of course resources'),
 'add_resource':
 ('Legge til ressurs', 'Link'),
 'editing_course_resources':
 ('Redigerer ressursene til kurset', 'Title'),
 'remove_resource_verify':
 ('Er du sikker på at du vil fjerne denne ressursen ?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ("Legge til 'jam sesjon'", 'link'),
 'jam_sessions':
 ('Jam sesjoner:', 'a list of jam session will listed after/under this label'),
 'jam_session':
 ('jam sesjon', ''),
 'annotations':
 ('annoteringer', ''),
 'continue_with_version':
 ('Fortsette med din versjon', 'button label'),
 'artefact':
 ('artefakt', ''),
 'viewing_annotations':
 ('ser på annoteringer', ''),
 'Annotations':
 ('Annoteringer:', 'Label, followed by a list of annotations under it'),
 'adding_jam_session':
 ('Legger til jam session', ''),
 'add_annotation':
 ('Legge til annotering', 'link'),
 'edit_jam_session':
 ('Redigere jam session', ''),
 'editing_jam_session':
 ('Redigerer jam session', ''),
 'title_of_jam_session':
 ('Tittelen til jam sesjonen', 'label'),
 'type_of_jam_session':
 ('Jam-sesjons type', 'label'),
 'mutate_on_previous':
 ('Muter forrige', 'type of jam session'),
 'explore_possibilities':
 ('Utforske muligheter', 'type of jam session'),
 'diverge_and_converge':
 ('Splitt & Flett', 'type of jam session'),
 'description_of_jam_session':
 ('Beskrivelse av jam sesjonen', 'label'),
 'upload_the_starting_artefact':
 ('Last opp et artefact som starter denne jam sesjonen', 'label'),
 'adding_artefact':
 ('Legger til artefakt', ''),
 'title_of_the_starting_artefact':
 ('Tittel til startartefakt', 'label'),
 'annotation_of_the_starting_artefact':
 ('Annotering for startartefaktet', 'label'),
 'title_of_the_artefact':
 ('Artefakt tittel', 'label'),
 'upload_file':
 ('Laste opp fil', 'label'),
 'you_adding_annotation':
 ('Du legger til en annotering til artefaktet',
  'message in adding annotations form'),
 'adding_annotation':
 ('Legger annotering til', ''),
 'to_jam_session':
 ('til jam-sesjon', 'Part of a message'),
 'to_jam_artefact':
 ('til jamartefakt', 'Part of a message'),
 'unread_artefacts':
 ('nye artefact', 'There is a number before this message'),
 'total_artefacts':
 ('totalt antall artefakt', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ('Er du sikker på at du vil slette de følgende jam-sesjonene ?',
  'Message dialog message'),
 'are_you_sure_jam_session':
 ('Er du sikker på at du vil slette dennne jam-sesjonen med %s artefaktene?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 ('Fjerne artefakt', 'Button label for censoring jam artefact'),
 'restore_artefact':
 ('Gjenopprette artefakt', 'Button label for restoring jam artefact'),
 'remove_annotation':
 ('Fjerne valgte annoteringer', 'Button label for censoring jam annotations'),
 'restore_annotation':
 ('Gjenopprette valgte annoteringer',
  'Button label for uncensoring jam annotations'),
 'removed_name':
 ('Fjernet', 'Title/name for censored jam artefact'),
 'removed_message':
 ('Dette artefaktet er fjernet av %s : %s.',
  "First placeholder is replaced by censorer's name and the second by the date"),
 'removed_msg':
 ('Artefakt er fjernet', 'Message shown when teacher censores an artefact.'),
 'removed_annotation_msg':
 ('Annotering er fjernet',
  'Message shown when teacher censores an annotation.'),
 'remove_verify':
 ('Er du sikker på at du vil fjerne artefaktet? Navnet ditt sammen med en beskjed om at det er fjernet vil bli tilgjengelig til alle.',
  'Verification message shown when censoring is attempted'),
 'remove_annotations_verify':
 ('Er du sikker på at du vil fjerne valgte annotering? Navnet ditt sammen med en beskjed om at det er fjernet vil bli tilgjengelig til alle.',
  'Verification message shown when censoring is attempted'),
 'removed_annotation_body':
 ('Denne annoteringen er fjernet av %s : %s.',
  "Body for censored annotation. First placeholder is replaced by censorer's name and the second by the date"),
 'search_jam':
 ('Søke Jamming', 'Link label'),
 'searching_jam':
 ('Søker jam artefakter', 'Label'),
 'search_artefact_name':
 ('Artefakt navn', 'Label in search form'),
 'search_artefact_author':
 ('Forfatter', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Annoteringer inneholder ordene',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ('Artefakt type',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Bilde', 'Artefact type'),
 'type_audio':
 ('Audio', 'Artefact type'),
 'type_text':
 ('Text', 'Artefact type'),
 'type_html':
 ('Html', 'Artefact type'),
 'type_video':
 ('Video', 'Artefact type'),
 'type_archive':
 ('Arkiv', 'Artefact type'),
 'search_annotated_by':
 ('Annotert av', 'Label in search form'),
 'search_results_author':
 ('Forfatter', 'Heading in search results table'),
 'search_results_jam_artefact':
 ('Jam artefakt', 'Heading in search results table'),
 'search_results_jam_session':
 ('Jam-sesjon', 'Heading in search results table')}

announce = {'comments':
 ('Kommentarer', 'Notice / form heading'),
 'no_comments':
 ('Det finnes ingen kommentarer.', 'Notice'),
 'recent_comments':
 ('Nylige kommentarer', 'Heading'),
 'no_entries':
 ('Det finnes ingen postinger.', 'Notice'),
 'recent_entries':
 ('Nylige postinger', 'Heading'),
 'trackbacks':
 ('Trackbacks', 'Notice'),
 'no_trackbacks':
 ('Det finnes ingen trackbacks.', 'Notice'),
 'recent_trackbacks':
 ('Nylige trackbacks', 'Heading'),
 'send_trackback':
 ('Send trackback til:', 'Part of message, followed by url'),
 'syndicate':
 ('Abonner via RSS (XML).', 'Link'),
 'log_in':
 ('Logg på Fle3.', 'Link'),
 'entries':
 ('Postinger', 'Heading'),
 'category':
 ('Kategori', 'Heading'),
 'categories':
 ('Kategorier', 'Heading'),
 'no_categories':
 ('Ingen kategorier', 'Notice'),
 'items':
 ('postinger', 'Part of message: nn items.'),
 'posted_by':
 ('Posta av', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%m/%d %H:%M', 'Short date format'),
 'dateformat':
 ('%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 (' ', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('Legg til en kommentar', 'Heading'),
 'name':
 ('Navn', 'Form heading'),
 'email':
 ('E-post', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('Tittel', 'Form heading'),
 'body':
 ('Beskjed', 'Form heading'),
 'forget_personal':
 ('Glemt personlig informasjon', 'Button'),
 'teachers_and_tutors_only':
 ('Kun lærere og veiledere',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('Vil du lagre din personlige informasjon i en cookie?', 'Label'),
 'Announcement':
 ('Kunngjøring', 'Category'),
 'ToDo':
 ('ToDo', 'Category'),
 'Event':
 ('Hendelse', 'Category'),
 'continue_reading':
 ('Fortsett lesning', 'Part of message, followed by entry title'),
 'missing1':
 ('mangler', 'Part of message'),
 'missingn':
 ('mangler', 'Part of message'),
 'comment_preview':
 ('Forhåndsvisning', 'Heading'),
 'search_results':
 ('Søke resultat', 'Heading'),
 'search_for':
 ('Søk kunngjøringer for', 'Part of message'),
 'no_match':
 ('Ingen maken funnet', 'Notice'),
 'about':
 ('Info', 'Title'),
 'archives':
 ('Arkiv', 'Title'),
 'search':
 ('Søk', 'Heading'),
 'search_help':
 ('Du kan bruke AND/OR for boolske søk.', 'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

