# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_zh_hk.py,v 1.7 2005/01/15 11:23:09 tarmo Exp $
#
# Copyright 2001, 2002 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the english translations for all Fle3 printable strings."""

# How to do a new translation:
#
# 1. Copy this file into a new file, appending the language code after it, so
# you get something like "vocabulary_es.py" for Spanish and so on.
#
# 2. Edit the new file, translating the second portion of each line. The
# first portion is the keyword, which you shouldn't touch. The second is the
# translation that should be translated to the target language. The third
# is the supplementary instruction, that should help you do the translations.
#
# 3. Please note that the file is in Python code and needs to follow certain
# syntax rules:
#  - Strings can either be quoted by singles quotes (') or double quotes (").
#    If you need to use either of these quotation marks in your translation,
#    make sure that you use the other quotation mark to surround the string.
#    If you need to use both quotation marks in the same translation string,
#    you can surround the string with triple quotes (''' or """), which
#    allows you to use either of the quotation marks inside the string.
#  - Line breaks are not allowed inside strings, so make sure you don't
#    use an editor that wraps lines. You can have line breaks between
#    strings, though.
#
# 4. If you need to use special characters (outside of the 127 character
# ASCII range), you have several choices:
#
# A. Write in your native encoding (whatever suits you best). This requires
#    that you change the "charset_encoding" keyword in the "common" module to
#    the encoding type you will use. This document is written in iso8859-1,
#    although as english does not contain special characters, it could be
#    in utf-8 as well without any differences.
#    Most European languages are easiest to write in iso8859-1.
#
# B. Write in utf-8 encoded unicode. If your editor can save files in utf-8,
#    use that feature. If not, you can add the special characters manually
#    with the \x escape sequences. Make sure you remove the keyword
#    "charset_encoding" from the "common" module, or change its value to
#    "utf-8" so that the strings are interpreted correctly.
#    'key'	: (u'\xe3\x82\xaa','This is the katakana letter O,encoded in utf-8.'),
#
# C. Write in unicode. Each unicode string starts with u followed by the
#    quotes. Each unicode character starts with \u followed by the code in
#    hexadecimal notation. The value of the "charset_encoding" keyword
#    is irrelevant if you use unicode all the way.
#    'key', (u'\u30aa ','This is the katakana letter O, encoded in unicode.'),
#
# 5. Check your translation. If you have Python installed and you've
#    downloaded Fle3 sources, you can execute "python TranslationLint.py"
#    which will check through all the translation files and will produce
#    an error if there is a syntax error.
#    If you have installed Fle3, you can test the translation yourself
#    by going to Zope Management and selecting the Tools tab in your FLE
#    instance, and clicking on "reload_translations". After this you
#    should be able to select your translation from user preferences
#    and see the translated strings.
#
# Edited By: Arthur Chan @ Smart Open Quote Company (SoQ) @ Hong Kong  @ www.soqhome.com @ 30 Oct , 2003
# Email: arthur@soqhome.com
# Last Modified: 2005/01/15
# Version 1.4.5

common = {'language_name':
 (u'\u7e41\u9ad4\u4e2d\u6587  ', 'Name of this language'),
 'charset_encoding':
 (u'utf-8', 'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 (u'\u5de5\u4f5c\u574a  ', 'Main tab for webtop'),
 'Knowledge_Building':
 (u'\u77e5\u8b58\u5275\u5efa  ', 'Main tab for knowledge building'),
 'Course_Management':
 (u'\u8ab2\u7a0b\u7ba1\u7406  ', 'Main tab for course management'),
 'User_Management':
 (u'\u6210\u54e1  ', 'Main tab for user management'),
 'Jamming':
 (u'\u593e\u8a08  ', 'Main tab for jamming'),
 'Type_Management':
 (u'\u77e5\u8b58\u985e\u578b\u7ba1\u7406  ', 'Heading'),
 'cancel':
 (u'\u53d6\u6d88  ', 'Button label'),
 'submit':
 (u'\u905e\u4ea4  ', 'Button label'),
 'remove':
 (u'\u6e05\u9664  ', 'Button label'),
 'next':
 (u'\u4e0b\u4e00\u6b65   ->', 'Label for button'),
 'previous':
 (u'<- \u4e0a\u4e00\u6b65  ', 'Label for button'),
 'quick_submit':
 (u'\u5feb\u905e  ', ''),
 'ok':
 (u'\u6210\u529f  ', 'Button label'),
 'save':
 (u'\u5b58\u6a94  ', 'Button label'),
 'create':
 (u'\u88fd\u9020  ', 'Button label'),
 'search':
 (u'\u641c\u5c0b  ', 'Button label'),
 'webtop':
 (u'\u5de5\u4f5c\u574a  ', ''),
 'description':
 (u'\u63cf\u8ff0  ', 'Label'),
 'short_date_format_display':
 (u'YYYY-MM-DD', 'String displayed as clue when entering a date'),
 'short_date_format':
 (u'%Y-%m-%d',
  'Format string for short dates. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'timestamp_format':
 (u'%H:%M %Y-%m-%d',
  'Format string for long timestamps. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'invite':
 (u'\u9080\u8acb  ', ''),
 'add':
 (u'\u52a0\u5165  ', ''),
 'today':
 (u'\u4eca\u5929  ', ''),
 'yesterday':
 (u'\u6628\u5929  ', ''),
 'groupfolder':
 (u'\u8ab2\u7a0b\u7d44\u5408  ', 'Heading'),
 'dtml_reloaded':
 (u'DTML \u5df2\u7d93\u66f4\u751f  ', 'Title for message dialog'),
 'dtml_files_reloaded':
 (u'\u6b64\u7269\u4ef6\u7684  DTML \u6a94\u6848\u5df2\u7d93\u66f4\u751f  ',
  'Message dialog text'),
 'dtmls_reloaded':
 (u'\u591a\u500b  DTML \u5df2\u7d93\u66f4\u751f  ',
  'Title for message dialog'),
 'dtmls_files_reloaded':
 (u'\u5168\u90e8   DTML \u6a94\u6848\u5df2\u7d93\u66f4\u751f  ',
  'Message dialog text'),
 'css_reloaded':
 (u'\u4e32\u63a5\u6a23\u5f0f\u8868\u5df2\u7d93\u66f4\u751f  ',
  'Title for message dialog'),
 'css_files_reloaded':
 (u'\u9019\u7269\u4ef6\u7684\u4e32\u63a5\u6a23\u5f0f\u8868\u6a94\u5df2\u7d93\u66f4\u751f  ',
  'Message text'),
 'error':
 (u'\u932f\u8aa4  ', ''),
 'warning':
 (u'\u8b66\u544a  ', ''),
 'invalid_url':
 (u'\u7db2\u5740\u4e0d\u6b63\u78ba  ', 'Message title'),
 'invalid_url_message':
 (u'\u7db2\u5740\u4e0d\u6b63\u78ba  .<br>\u8acb\u6aa2\u67e5\u958b\u7aef\u5b57\u53e5\u662f\u5426   <i>http://, ftp://, mailto:</i>\u6216\u4f60\u5fc3\u76ee\u4e2d\u5176\u4ed6\u7db2\u5740\u898f\u7d04  . \u8acb\u7559\u610f\u985e\u4f3c\u4ee5\u4e0b\u7684\u7db2\u5740\u662f\u4e0d\u5bb9\u8a31\u7684   "www.myaddress.org". \u4f46\u52a0\u4e0a\u7db2\u5740\u898f\u7d04\u4fbf\u53ef  : "http://www.myaddress.org". \u82e5\u4f60\u4e0d\u6e05\u695a\u6240\u7528\u7db2\u5740\u898f\u7d04  , \u53ef\u5617\u8a66\u8cbc\u4e0a\u7db2\u9801\u5728\u700f\u89bd\u5668\u4e0a\u7684\u7db2\u5740  .',
  'Message text'),
 'invalid_name':
 (u'\u540d\u5b57\u4e0d\u6b63\u78ba  ', 'Message title'),
 'give_valid_name':
 (u'\u8acb\u8f38\u5165\u6b63\u78ba\u540d\u5b57  ', 'Message text'),
 'name_taken':
 (u'\u5176\u4ed6\u7269\u4ef6\u5df2\u7d93\u4f7f\u7528\u4e86\u540d\u5b57  "%s". \u8acb\u8f38\u5165\u5176\u4ed6\u540d\u5b57  .',
  'Message text, name inserted inside'),
 'edit':
 (u'\u4fee\u6539  ', 'Button label'),
 'you_are_in':
 (u'\u4f60\u5728\u6b64  :',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 (u'\u8acb\u586b\u59a5\u6240\u6709\u9805\u76ee  .', 'Erro message text'),
 'confirmation':
 (u'\u78ba\u8a8d  ', 'Title for confirmation dialogs'),
 'invalid_input':
 (u'\u4e0d\u6b63\u78ba\u8f38\u5165  ', 'Message title'),
 'invalid_fields':
 (u'\u4ee5\u4e0b\u9805\u76ee\u5305\u542b\u4e0d\u6b63\u78ba\u8f38\u5165  ',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 (u'\u8acb\u5148\u9078\u64c7\u7269\u4ef6  ', 'Message text'),
 'link_to_webtop':
 (u'\u5728\u5de5\u4f5c\u574a\u52a0\u5165\u9023\u7d50  ', 'Link'),
 'proxy_to_webtop':
 (u'\u9023\u7d50\u8ab2\u7a0b\u7d44\u5408\u81f3\u5de5\u4f5c\u574a  ', 'Link'),
 'export':
 (u'\u8f38\u51fa  ', 'Button label'),
 'import':
 (u'\u8f38\u5165  ', 'Button label'),
 'importing':
 (u'\u8f38\u5165\u4e2d  ', 'Heading start'),
 'megabyte':
 (u'MB', 'Abbreviation for megabyte'),
 'kilobyte':
 (u'kB', 'Abbreviation for kilobyte'),
 'logout':
 (u'\u767b\u51fa  ', 'Link for logging out, also heading in logout dialogs'),
 'logout_pre3':
 (u'\u5982\u6b32\u767b\u51fa\ufe50\u8acb\u95dc\u9589\u4f60\u7684\u700f\u89bd\u5668 ',
  'Instructions for logging out'),
 'any':
 (u'\u4efb\u4f55\u5c08\u6848  ', 'Label used in search forms'),
 'course':
 (u'\u8ab2\u7a0b  ', 'Part of location path'),
 'language':
 (u'\u8a9e\u8a00  ', ''),
 'announcements':
 ('\\u4f48\\u544a', 'Link/heading'),
 'sun':
 ('\\u661f\\u671f\\u65e5', 'Weekday abbreviation'),
 'mon':
 ('\\u661f\\u671f\\u4e00', 'Weekday abbreviation'),
 'tue':
 ('\\u661f\\u671f\\u4e8c', 'Weekday abbreviation'),
 'wed':
 ('\\u661f\\u671f\\u4e09', 'Weekday abbreviation'),
 'thu':
 ('\\u661f\\u671f\\u56db', 'Weekday abbreviation'),
 'fri':
 ('\\u661f\\u671f\\u4e94', 'Weekday abbreviation'),
 'sat':
 ('\\u661f\\u671f\\u516d', 'Weekday abbreviation'),
 'sunday':
 ('\\u661f\\u671f\\u516d', 'Weekday'),
 'monday':
 ('\\u661f\\u671f\\u4e00', 'Weekday'),
 'tuesday':
 ('\\u661f\\u671f\\u4e8c', 'Weekday'),
 'wednesday':
 ('\\u661f\\u671f\\u4e09', 'Weekday'),
 'thursday':
 ('\\u661f\\u671f\\u56db', 'Weekday'),
 'friday':
 ('\\u661f\\u671f\\u4e94', 'Weekday'),
 'saturday':
 ('\\u661f\\u671f\\u516d', 'Weekday'),
 'January':
 ('\\u4e00\\u6708', 'Month'),
 'February':
 ('\\u4e8c\\u6708', 'Month'),
 'March':
 ('\\u4e09\\u6708', 'Month'),
 'April':
 ('\\u56db\\u6708', 'Month'),
 'May':
 ('\\u4e94\\u6708', 'Month'),
 'June':
 ('\\u516d\\u6708', 'Month'),
 'July':
 ('\\u4e03\\u6708', 'Month'),
 'August':
 ('\\u516b\\u6708', 'Month'),
 'September':
 ('\\u4e5d\\u6708', 'Month'),
 'October':
 ('\\u5341\\u6708', 'Month'),
 'November':
 ('\\u5341\\u4e00\\u6708 ', 'Month'),
 'December':
 ('\\u5341\\u4e8c\\u6708', 'Month'),
 'remove_q':
 ('\\u79fb\\u9664\\ufe56', 'Question')}

kb = {'month':
 (u'\u6708 ', ''),
 'week':
 (u'\u5468 ', ''),
 'you_have_not_replied_to':
 (u'\u4f60\u6c92\u6709\u56de\u8986\u9019\u4e9b\u6210\u54e1 ',
  'followed by a list of persons'),
 'total_replies':
 (u'\u56de\u8986\u5176\u4ed6\u6210\u54e1\u7684\u7b46\u8a18\u7e3d\u6578 :',
  'followed by number'),
 'total_notes_written':
 (u'\u5beb\u4e0b\u7b46\u8a18\u7e3d\u6578 : ', 'followed by number'),
 'graph_type':
 (u'\u5716\u50cf\u985e\u578b : ', 'Label for graph type selection'),
 'by_knowledge_type':
 (u'\u77e5\u8b58\u985e\u578b ', 'graph type'),
 'replies':
 (u'\u56de\u8986 ', 'graph type'),
 'display_by':
 (u'\u986f\u793a\u65b9\u6cd5 :', 'Label for timescale (week/month) selection'),
 'adding_resource':
 (u'\u52a0\u5165\u4f86\u6e90\u9032\u884c\u4e2d ', 'part of browser title'),
 'modifying_resource':
 (u'\u4fee\u6539\u4f86\u6e90\u9032\u884c\u4e2d ', 'part of browser title'),
 'title_resource':
 (u'\u6a19\u984c ', 'The title of resource'),
 'author_resource':
 (u'\u4f5c\u8005 ', 'The author of the resource'),
 'url':
 (u'\u7db2\u5740 (URL)', 'Resource URL'),
 'location':
 (u'\u4f4d\u7f6e ', 'Resource location'),
 'course_info':
 (u'\u8ab2\u7a0b\u8cc7\u6599  ', 'Label for link to course details'),
 'create_context':
 (u'\u52a0\u5165\u8ab2\u7a0b\u7bc7\u5e45  ',
  'Link to create new course context'),
 'hide_context':
 (u'\u96b1\u85cf\u8ab2\u7a0b\u7bc7\u5e45  ',
  'Link to hide a context from view'),
 'show_context':
 (u'\u986f\u793a\u7bc7\u5e45  ', 'Link to show a hidden context'),
 'new_notes':
 (u'\u65b0\u7b46\u8a18  ',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 (u'\u7b46\u8a18  ', 'Label for showing the number of notes'),
 'full_description':
 (u'\u8a73\u7d30\u63cf\u8ff0  ...', ''),
 'course':
 (u'\u8ab2\u7a0b  ', "String 'course' in context display"),
 'context':
 (u'\u7bc7\u5e45  ', "String 'context' in context display"),
 'thread':
 (u'\u5206\u652f  ', "String 'thread' in context display"),
 'note':
 (u'\u7b46\u8a18  ', "String 'note' in context display"),
 'start_thread':
 (u'\u958b\u59cb\u5206\u652f  ', 'Link'),
 'short_description':
 (u'\u7c21\u77ed\u63cf\u8ff0  ', 'Label'),
 'long_description':
 (u'\u9577\u7bc7\u63cf\u8ff0  ', 'Label'),
 'full_description':
 (u'\u8a73\u7d30\u63cf\u8ff0  ', 'Label'),
 'select':
 (u'\u9078\u9805  ',
  'Start of sentence, followed by a drop-down list of available knowledge type'),
 'knowledge_type':
 (u'\u77e5\u8b58\u985e\u578b  ', 'Label'),
 'add_note':
 (u'\u52a0\u5165\u7b46\u8a18  ', 'Button label'),
 'show_notes':
 (u'\u986f\u793a\u7b46\u8a18  ', 'Heading start'),
 'show_thread':
 (u'\u7528\u5206\u652f  ', 'heading finish'),
 'show_type':
 (u'\u4ee5\u77e5\u8b58\u985e\u578b\u6392\u5e8f  ', 'heading finish'),
 'show_author':
 (u'\u4ee5\u500b\u4eba\u6392\u5e8f  ', 'heading finish'),
 'show_date':
 (u'\u4ee5\u65e5\u671f\u6392\u5e8f  ', 'heading finish'),
 'select_course':
 (u'\u9078\u64c7\u8ab2\u7a0b  ',
  'Label, followed by a drop-down list of available courses'),
 'change':
 (u'\u6539\u8b8a  ', 'Button label'),
 'creating_context':
 (u'\u52a0\u5165\u8ab2\u7a0b\u7bc7\u5e45\u9032\u884c\u4e2d  ,\u4f4d\u7f6e\u5728  ',
  'Title, followed by the course name'),
 'editing_context':
 (u'\u4fee\u6539\u8ab2\u7a0b\u7bc7\u5e45\u9032\u884c\u4e2d  ,\u4f4d\u7f6e\u5728  ',
  'Title, followed by the course name'),
 'title_of_context':
 (u'\u8ab2\u7a0b\u7bc7\u5e45\u6a19\u984c  ', 'Label'),
 'type_set':
 (u'\u77e5\u8b58\u985e\u578b\u7d44  ', 'Label'),
 'creating_note_in':
 (u'\u52a0\u5165\u7b46\u8a18\u9032\u884c\u4e2d  ,\u4f4d\u7f6e\u5728  ',
  'Title, followed by course context name'),
 'course_context':
 (u'\u8ab2\u7a0b\u7bc7\u5e45  ', 'Label for course context'),
 'you_are_replying_to':
 (u'\u4f60\u6b63\u5728\u56de\u5fa9  ', 'Label'),
 'title_of_note':
 (u'\u7b46\u8a18\u6a19\u984c  ', 'Label'),
 'message_body':
 (u'\u8a0a\u606f  ', 'Label'),
 'current_image':
 (u'\u76ee\u524d\u5716\u6848  ', 'Label'),
 'replace_with':
 (u'\u53d6\u4ee3\u70ba  ', 'Label for image replacement in note edit'),
 'add_image':
 (u'\u52a0\u5165\u5716\u6848  ', 'Label'),
 'title_of_image':
 (u'\u5716\u6848\u6a19\u984c  ', 'Label'),
 'add_link':
 (u'\u52a0\u5165\u9023\u7d50  (URL)', 'Label'),
 'title_of_link':
 (u'\u9023\u7d50\u6a19\u984c  ', 'Label'),
 'preview':
 (u'\u9810\u89bd  ', 'Button label'),
 'previewing_note':
 (u'\u9810\u89bd\u7b46\u8a18  , \u4f4d\u7f6e\u5728  ',
  'Title/heading, followed by course context name'),
 'publish':
 (u'\u520a\u767b  ', 'Button label'),
 'search_kb':
 (u'\u641c\u5c0b\u77e5\u8b58\u5eab  ', 'Link label'),
 'searching_kb':
 (u'\u641c\u5c0b\u77e5\u8b58\u5eab\u7b46\u8a18  ', 'Label'),
 'search_author':
 (u'\u4f5c\u8005  ', 'Label'),
 'search_notes_words':
 (u'\u7b46\u8a18\u5305\u542b\u5b57\u53e5  ', 'Label'),
 'search_context':
 (u'\u8ab2\u7a0b\u7bc7\u5e45  ', 'Label'),
 'search_tt':
 (u'\u77e5\u8b58\u985e\u578b  ', 'Label'),
 'search_note':
 (u'\u7b46\u8a18  ', 'Label'),
 'current_note':
 (u'\u76ee\u524d\u7b46\u8a18  ', 'Label'),
 'you_didnt_select_type':
 (u'\u4f60\u6c92\u6709\u9078\u53d6\u77e5\u8b58\u985e\u578b  .', 'Title'),
 'go_back':
 (u'\u9000\u56de  ', 'Start of message, rendered into a link'),
 'and_select_type':
 (u'\u53ca\u70ba\u4f60\u7684\u7b46\u8a18\u9078\u53d6\u77e5\u8b58\u985e\u578b  .',
  'Rest of message'),
 'inline_notes':
 (u'\u986f\u793a\u6240\u6709\u7b46\u8a18\u5167\u5bb9  ', 'Link'),
 'outline_notes':
 (u'\u96b1\u85cf\u6240\u6709\u7b46\u8a18\u5167\u5bb9  ', 'Link'),
 'view_info':
 (u'\u986f\u793a\u8cc7\u6599  ', 'Part of location bar'),
 'edit_context':
 (u'\u4fee\u6539\u8ab2\u7a0b\u7bc7\u5e45  ', 'Link'),
 'to_note':
 (u'\u81f3\u7b46\u8a18  ', 'Part of a message'),
 'full_thread_no':
 (u'\u53ea\u986f\u793a\u8d77\u521d\u7684\u7b46\u8a18  ', 'Link'),
 'full_thread_yes':
 (u'\u986f\u793a\u6240\u6709\u5206\u652f  ', 'Link'),
 'remove':
 (u'\u6e05\u9664\u7b46\u8a18  ', 'Button label for removing notes'),
 'restore':
 (u'\u9084\u539f\u7b46\u8a18  ', 'Button label for restoring notes'),
 'remove_form_title':
 (u'\u6e05\u9664\u7b46\u8a18  ', 'Title for note removing form'),
 'remove_form_label':
 (u'\u6e05\u9664\u7b46\u8a18  ',
  'Explanation in remove form, followed by note subject'),
 'removed_msg':
 (u'\u8a0a\u606f\u5df2\u7d93\u6e05\u9664  ',
  'Message shown to the teacher when she has removed a note.'),
 'remove_verify2':
 (u'\u8acb\u78ba\u8a8d\u6e05\u9664\u8a0a\u606f  . \u4f60\u4ee5\u4e0b\u7684\u540d\u5b57  , \u9019\u65e5\u671f\u548c\u4f60\u63d0\u4f9b\u7684\u89e3\u91cb\u5c07\u6703\u88ab\u5132\u5b58  . \u7576\u9019\u7b46\u8a18\u518d\u88ab\u700f\u89bd\u6642  ,\u9019\u4e9b\u8cc7\u6599\u5c07\u6703\u9023\u540c\u6e05\u9664\u544a\u793a\u986f\u793a\u51fa\u4f86  .',
  'Verification message shown when removing is attempted'),
 'remove_explanation':
 (u'\u6e05\u9664\u7406\u7531  ', 'Label for removee explanation text area'),
 'removed_subject':
 (u'\u6e05\u9664  ', 'Title/subject for removed notes'),
 'removed_body':
 (u'\u9019\u6bb5\u8a0a\u606f\u7531  %s\u5728  %s\u6e05\u9664  .',
  "Body for removed messages. First placeholder is replaced by remover's name and the second by the date"),
 'notes_from_day':
 (u'\u7b46\u8a18  , \u7531  ', 'Start of heading, followed by a date'),
 'previous':
 (u'\u4e0a\u4e00\u6b65  ', 'Link label'),
 'next':
 (u'\u4e0b\u4e00\u6b65  ', 'Link label'),
 'who_has_read':
 (u'\u8ab0\u95b1\u8b80\u904e\u9019\u7b46\u8a18  ?', 'Link label'),
 'last_read':
 (u'\u6700\u5f8c\u95b1\u8b80  ', 'Label'),
 'times_read':
 (u'\u95b1\u8b80\u6b21\u6578  ', 'Label'),
 'back':
 (u'&lt; \u9000\u56de  ', 'Link label'),
 'unread_to_read_msg':
 (u'\u5168\u90e8\u5728\u5206\u652f\u7684\u7b46\u8a18\u6a19\u8a18\u70ba\u5df2\u95b1\u8b80  .',
  'title and message in a message dialog'),
 'mark_notes_read':
 (u'\u6a19\u8a18\u6240\u6709\u7b46\u8a18\u70ba\u5df2\u95b1\u8b80  ',
  'text in a button'),
 'creating_groupfolder':
 (u'\u52a0\u5165\u8ab2\u7a0b\u7d44\u5408  , \u4f4d\u7f6e\u5728  ',
  'Heading start'),
 'title_groupfolder':
 (u'\u8ab2\u7a0b\u7d44\u5408\u6a19\u984c  ', 'Label'),
 'flea_asks':
 (u'\u963f\u82b1\u63d0\u554f  ',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 (u'\u6539\u8b8a\u77e5\u8b58\u985e\u578b ',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 (u'\u9019\u662f\u552f\u4e00\u51c6\u8a31\u985e\u578b ',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 (u'\u6539\u8b8a  ', 'Button label'),
 'down_to_note':
 (u'\u5411\u4e0b  ', 'Link label'),
 'use_roleplay':
 (u'\u5728\u9019\u7bc7\u5e45\u4f7f\u7528\u89d2\u8272\u626e\u6f14  ',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 (u'\u8a2d\u5b9a\u89d2\u8272\u626e\u6f14\u8eab\u4efd  ',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 (u'\u8ab2\u7a0b  ', "Heading for user's course list"),
 'totals_notes':
 (u'\u7b46\u8a18 ',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 (u'\u4f5c\u54c1 ',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 (u'\u65b0  %s/\u5171  %s',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 (u'\u52a0\u5165\u6587\u4ef6\u593e  ', ''),
 'add_document':
 (u'\u52a0\u5165\u6587\u4ef6  ', ''),
 'add_link':
 (u'\u52a0\u5165\u9023\u7d50  ', ''),
 'create_memo':
 (u'\u52a0\u5165\u5b57\u689d  ', ''),
 'type':
 (u'\u985e\u578b  ', 'Link for sorting by type'),
 'title':
 (u'\u6a19\u984c  ', 'Link for sorting by title'),
 'date':
 (u'\u65e5\u671f  ', 'Link for sorting by date'),
 'size':
 (u'\u5927\u5c0f  ', 'Link for sorting by size'),
 'remove':
 (u'\u6e05\u9664  ', 'Button label'),
 'restore':
 (u'\u9084\u539f  ', 'Button label'),
 'rename':
 (u'\u6539\u540d  ', 'Button label'),
 'copy':
 (u'\u8907\u88fd  ', 'Button label'),
 'cut':
 (u'\u526a\u4e0b  ', 'Button label'),
 'paste':
 (u'\u8cbc\u4e0a  ', 'Button label'),
 'delete':
 (u'\u6e05\u9664  ', 'Button label'),
 'select_all':
 (u'\u5168\u9078  ', 'Button label'),
 'trash':
 (u'\u5ee2\u7d19\u7bb1  ', 'Label for trashcan'),
 'empty_trash':
 (u'\u6e05\u7406\u5ee2\u7d19\u7bb1  ', 'Button label'),
 'adding_folder':
 (u'\u52a0\u5165\u6587\u4ef6\u593e  ', 'Heading'),
 'title_of_folder':
 (u'\u6587\u4ef6\u593e\u6a19\u984c  ', 'Label'),
 'viewing_memo':
 (u'\u700f\u89bd\u5b57\u689d  ', 'Title'),
 'creating_memo':
 (u'\u52a0\u5165\u5b57\u689d  ', 'Title'),
 'editing_memo':
 (u'\u4fee\u6539\u5b57\u689d  ', 'Title'),
 'title_of_memo':
 (u'\u5b57\u689d\u6a19\u984c  ', 'Label'),
 'content':
 (u'\u5167\u5bb9  ', 'Label'),
 'show_memo_contents':
 (u'\u53ea\u986f\u793a\u5b57\u689d\u5167\u5bb9  ', 'Link'),
 'adding_link':
 (u'\u52a0\u5165\u9023\u7d50  ', 'Title'),
 'title_of_link':
 (u'\u9023\u7d50\u984c\u76ee  ', 'Label'),
 'url':
 (u'\u7db2\u5740  ', ''),
 'document_uploaded':
 (u'\u4e0a\u8f09\u6587\u4ef6  .', 'Status message'),
 'adding_document':
 (u'\u52a0\u5165\u6587\u4ef6  ', 'Title'),
 'upload_document':
 (u'\u4e0a\u8f09\u6587\u4ef6  ', 'Label'),
 'title_of_document':
 (u'\u6587\u4ef6\u984c\u76ee  ', 'Label'),
 'search_wt':
 (u'\u641c\u5c0b\u5de5\u4f5c\u574a  ', 'Link label'),
 'searching_wt':
 (u'\u6b63\u5728\u641c\u5c0b\u5de5\u4f5c\u574a  ', 'Label'),
 'search_results':
 (u'\u641c\u5c0b\u7d50\u679c  ', 'Label'),
 'new_search':
 (u'\u65b0\u7684\u641c\u5c0b  ', 'Label'),
 'search_title':
 (u'\u984c\u76ee  ', 'Label'),
 'search_owner':
 (u'\u6301\u6709\u4eba  ', 'Label'),
 'search_words':
 (u'\u7269\u4ef6\u5305\u542b\u5b57  ', 'Label'),
 'search_object':
 (u'\u7269\u4ef6  ', 'Label'),
 'search_folder':
 (u'\u6587\u4ef6\u593e  ', 'Label'),
 'viewing_search_results':
 (u'\u700f\u89bd\u641c\u5c0b\u7d50\u679c  ', 'Label in the location path'),
 'anyone':
 (u'\u4efb\u4f55\u4eba\u4ed5  ', 'Label'),
 'webtop_link_added':
 (u'\u5df2\u52a0\u5165\u5de5\u4f5c\u574a\u9023\u7d50  ', 'Message title'),
 'added_webtop_link':
 (u'\u4f60\u7684\u5de5\u4f5c\u574a\u5df2\u7d93\u52a0\u5165\u9023\u7d50   %s "%s" . \u6309  "\u78ba\u8a8d  "\u56de\u5230\u524d\u4e00\u9801  .',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 (u'\u5df2\u52a0\u5165\u8ab2\u7a0b\u6587\u4ef6\u593e  ', 'Message title'),
 'added_proxy':
 (u'\u8ab2\u7a0b  %s\u7684\u8ab2\u7a0b\u7d44\u5408\u73fe\u5df2\u986f\u793a\u5728\u60a8\u7684\u5de5\u4f5c\u574a  . \u6309  "\u78ba\u8a8d  "\u56de\u5230\u524d\u4e00\u9801  .',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 (u'\u6c92\u6709\u9078\u53d6\u9805\u76ee  !', 'Message dialog title'),
 'select_item_first':
 (u'\u9664\u4e86\u8cbc\u4e0a\u5916  , \u5176\u4ed6\u52d5\u4f5c\u4e5f\u9808\u8981\u9078\u53d6\u7269\u4ef6  .',
  'Message dialog message'),
 'no_file_supplied':
 (u'\u6c92\u6709\u63d0\u4f9b\u6a94\u6848  .', 'Message text'),
 'renaming':
 (u'\u6539\u540d\u9032\u884c\u4e2d  ', 'Title'),
 'invalid_names':
 (u'\u4ee5\u4e0b\u540d\u5b57\u7121\u6548  :', 'Message dialog messsage'),
 'same_names':
 (u'\u591a\u500b\u9805\u76ee\u4f7f\u7528\u540c\u4e00\u540d\u5b57  .',
  'Message dialog message'),
 'names_in_use':
 (u'\u4ee5\u4e0b\u540d\u5b57\u5df2\u88ab\u4f7f\u7528  :',
  'Message dialog message'),
 'information':
 (u'\u6210\u54e1\u8cc7\u6599  ', 'Link'),
 'shared_course_folder':
 (u'\u5206\u4eab\u8ab2\u7a0b\u7d44\u5408 ',
  'Printed after the name of the group folder in webtop contents list.'),
 'preferences':
 (u'\u559c\u597d  ', 'Link'),
 'editing_preferences':
 (u'\u4fee\u6539\u559c\u597d  ', 'Title'),
 'quota_reached_title':
 (u'\u9650\u984d\u5df2\u6eff  ', 'Title'),
 'quota_reached':
 (u'\u56e0\u70ba\u4f60\u7684\u5de5\u4f5c\u574a\u9650\u984d\u5df2\u6eff  , \u4e0d\u80fd\u9032\u884c\u64cd\u4f5c  . \u8acb\u6e05\u9664\u4e00\u4e9b\u7269\u4ef6\u518d\u7e7c\u7e8c  .',
  'Message dialog message'),
 'obj_removed':
 (u'(\u9023\u7d50\u76ee\u6a19\u5df2\u88ab\u6e05\u9664  )',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 (u'&lt; \u9000\u56de  ', 'Link label')}

usermgmnt = {'user':
 (u'\u6210\u54e1  ', 'part of browser title'),
 'adding_users':
 (u'\u52a0\u5165\u6210\u54e1  ', 'Title'),
 'required_field':
 (u'\u5fc5\u8981\u9805\u76ee  ', ''),
 'nickname':
 (u'\u5225\u540d  ', 'Label'),
 'user_account':
 (u'\u6210\u54e1\u6236\u53e3  ', 'Label'),
 'Confirm':
 (u'\u78ba\u8a8d  ', ''),
 'you_are_removing':
 (u'\u4f60\u6b63\u88ab\u6e05\u9664  ', ''),
 'invite_user':
 (u'\u9080\u8acb\u6210\u54e1  ', ''),
 'invite_users':
 (u'\u9080\u8acb\u6210\u54e1  ', 'Heading for invitation form'),
 'email_addresses':
 (u'\u96fb\u90f5  ', ''),
 'separate_with_comma':
 (u'( \u76f8\u9694\u7b26\u865f  : , )', ''),
 'Invitation_message':
 (u'\u9080\u8acb\u8a0a\u606f  ', ''),
 'Invitation_language':
 (u'\u9080\u8acb\u8a9e\u8a00  ', ''),
 'Courses_to_invite_to':
 (u'\u9080\u8acb\u53c3\u8207\u8ab2\u7a0b  ', ''),
 'Freeze':
 (u'\u51cd\u7d50  ', ''),
 'Remove':
 (u'\u6e05\u9664  ', ''),
 'role':
 (u'\u8eab\u4efd  ', 'label'),
 'role_staff':
 (u'\u54e1\u5de5  ', 'Global role stuff'),
 'role_user':
 (u'\u6210\u54e1  ', 'Global role user'),
 'role_fleadmin':
 (u'FLE \u7cfb\u7d71\u7ba1\u7406  ', 'Global role fleadmin'),
 'invite_again':
 (u'\u518d\u6b21\u9080\u8acb  ', 'Button label'),
 'warning':
 (u'\u8b66\u544a  ', 'Heading'),
 'want_remove_users':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u4ee5\u4e0b\u6210\u54e1  ?',
  'Complete question'),
 'invited_user_manage':
 (u'\u7ba1\u7406\u9080\u8acb\u6210\u54e1  ', 'Title'),
 'info_user':
 (u'\u76f8\u95dc\u8cc7\u6599   ',
  'Title for user info page, prefix before user name'),
 'edit_user':
 (u'\u4fee\u6539\u6210\u54e1  ', 'Link'),
 'editing':
 (u'\u4fee\u6539\u9032\u884c\u4e2d  ',
  'Heading for user edit, inserted before user name'),
 'image_of_user':
 (u'\u6210\u54e1\u5716\u7247  ', 'Label'),
 'upload_image_of_user':
 (u'\u4e0a\u8f09\u4f60\u7684\u5716\u7247  ', 'Label'),
 'or_link_to_image':
 (u'\u6216\u9023\u7d50\u81f3\u4f60\u7684\u5716\u7247  ',
  'Label, continuing from the upload label'),
 'webtop_bg':
 (u'\u9078\u64c7\u5de5\u4f5c\u574a\u80cc\u666f\u5716\u6848  ', 'Label'),
 'upload_webtop_bg':
 (u'\u6216\u4e0a\u8f09\u4f60\u7684\u80cc\u666f\u5716\u6848  ',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 (u'\u6aa2\u67e5\u9080\u8acb\u540d\u55ae  ', ''),
 'add_user':
 (u'\u52a0\u5165\u6210\u54e1  ', ''),
 'Unfreeze':
 (u'\u53d6\u6d88\u51cd\u7d50  ', ''),
 'Users':
 (u'\u6210\u54e1  ', ''),
 'gsm':
 (u'\u624b\u63d0\u96fb\u8a71  ', ''),
 'last_name':
 (u'\u59d3  ', ''),
 'first_name':
 (u'\u540d  ', ''),
 'city':
 (u'\u57ce\u5e02  ', ''),
 'organization':
 (u'\u5718\u9ad4  ', ''),
 'professional_interests':
 (u'\u5c08\u696d\u8208\u8da3  ', ''),
 'email':
 (u'\u96fb\u90f5  ', ''),
 'phone':
 (u'\u96fb\u8a71  ', ''),
 'url_to_photo':
 (u'\u5716\u7247\u7db2\u5740  ', ''),
 'country_menu_default':
 (u'\u9078\u64c7\u570b\u5bb6  ', ''),
 'group_menu_default':
 (u'\u9078\u64c7\u7d44\u5225  ', 'Default value for drop-down menu'),
 'address':
 (u'\u5730\u5740  ', ''),
 'address1':
 (u'\u5730\u5740\u7b2c\u4e00\u884c  ', ''),
 'address2':
 (u'\u5730\u5740\u7b2c\u4e8c\u884c  ', ''),
 'personal_interests':
 (u'\u500b\u4eba\u559c\u597d  ', ''),
 'quote':
 (u'\u5f15\u8a00  ', ''),
 'homepage':
 (u'\u500b\u4eba\u7db2\u9801  ', ''),
 'upload':
 (u'\u4e0a\u8f09  ', ''),
 'group':
 (u'\u7d44\u5225  ', ''),
 'password':
 (u'\u5bc6\u78bc  ', ''),
 'background':
 (u'\u80cc\u666f  ', ''),
 'country':
 (u'\u570b\u5bb6  ', ''),
 'reserved_nickname':
 (u'\u5c0d\u4e0d\u8d77  . \u9019\u5225\u540d\u5df2\u88ab\u4f7f\u7528  .',
  'Message'),
 'password_mismatch':
 (u'\u63d0\u4f9b\u5bc6\u78bc\u4e0d\u7b26  .', 'Message'),
 'could_not_send_invitation':
 (u'\u4e0d\u80fd\u9001\u51fa\u9080\u8acb\u8a0a\u606f  . \u8acb\u6aa2\u67e5\u4f60\u7684  MailHost\u7269\u4ef6\u662f\u5426\u8a2d\u5b9a\u59a5\u7576  .',
  'Error message'),
 'invitations_sent':
 (u'\u5df2\u7d93\u9001\u51fa\u9080\u8acb  ', 'Message title'),
 'invitations_sent_to':
 (u'\u9080\u8acb\u50b3\u9001\u81f3  %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 (u'\u9080\u8acb\u5df2\u7d93\u50b3\u9001\u81f3  : %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 (u'\u6210\u54e1\u5df2\u7d93\u6e05\u9664  ', 'Message title'),
 'removed_users':
 (u'\u6210\u54e1\u5df2\u7d93\u6e05\u9664  : %s',
  'Message, list inserted inside'),
 'not_removed_users':
 (u'\u4e0d\u80fd\u6e05\u9664\u9019\u4e9b\u6210\u54e1  : %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 (u'\u5df2\u7d93\u518d\u6b21\u9001\u51fa\u9080\u8acb  ', 'Message title'),
 're_invitations_sent_to':
 (u'\u5df2\u7d93\u518d\u6b21\u9080\u8acb\u6210\u54e1  %s. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 (u'\u5df2\u7d93\u6e05\u9664\u7b49\u5019\u7528\u8005  ', 'Message title'),
 'pending_removed_users':
 (u'\u5df2\u7d93\u6e05\u9664\u7b49\u5019\u7528\u8005  : %s',
  'Message, list inserted inside'),
 'pending_not_removed_users':
 (u'\u4e0d\u80fd\u6e05\u9664\u9019\u4e9b\u7b49\u5019\u7528\u8005  : %s',
  'Message, list inserted inside'),
 'invitation_subject':
 (u'\u9080\u8acb\u4f86\u81e8  FLE', 'Subject for invitation messages'),
 'invitation_header':
 (u'\u9080\u8acb  ', 'Header for invitation messages'),
 'invitation_footer':
 (u'\u8acb\u700f\u89bd  : ',
  'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 (u'\u6b61\u8fce\u4f86\u81e8  fle. \u8acb\u586b\u5beb\u4ee5\u4e0b\u6210\u54e1\u8cc7\u6599  .',
  'Welcome message used in invitation registration form'),
 'uname':
 (u'\u767b\u5165  ', 'Label used for user login name in several places'),
 'registration_failed':
 (u'\u767b\u8a18\u5931\u6557  ',
  "Title used when invited user can't register."),
 'invitation_key_used':
 (u'\u9019\u9080\u8acb\u7db2\u5740\u5df2\u7d93\u88ab\u4f7f\u7528\u6216\u7121\u6548  . \u5982\u82e5\u4f60\u4e0d\u80fd\u767b\u8a18  , \u8acb\u9023\u7d61\u4f60\u7684\u8001\u5e2b\u9001\u51fa\u53e6\u4e00\u500b\u9080\u8acb  .',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 (u'\u8a8d\u8b49\u9470\u5319\u7121\u6548  ',
  "Message telling that the authentication key isn't valid."),
 'after_submit_give_name_and_passwd2':
 (u'\u7576\u6309\u4e0b  "\u905e\u4ea4  "\u9375\u5f8c  , \u8acb\u586b\u5beb\u4f60\u7684\u767b\u5165\u540d\u5b57\u53ca\u5bc6\u78bc  .',
  'Message'),
 'frozen':
 (u'\u5df2\u51cd\u7d50  ', 'User status code'),
 'show_frozen':
 (u'\u986f\u793a\u88ab\u51cd\u7d50\u6210\u54e1 ', 'Link to show all users'),
 'show_active':
 (u'\u53ea\u986f\u793a\u6709\u6548\u6210\u54e1 ',
  'Link to show only active users'),
 'no_email':
 (u'\u6c92\u6709\u96fb\u90f5  ', 'Message title'),
 'no_email_explanation':
 (u'\u56e0\u70ba\u4f60\u672a\u8a2d\u5b9a\u96fb\u90f5\u4f4d\u5740  , \u6240\u4ee5\u4e0d\u80fd\u9001\u51fa\u96fb\u90f5  .',
  'Message text'),
 'passwd_changed':
 (u'\u5b8c\u6210\u4fee\u6539\u5bc6\u78bc  ', 'Message title'),
 'passwd_changed_explanation2':
 (u'\u4f60\u5df2\u6539\u8b8a\u4e86\u5bc6\u78bc  : \u4f60\u7684\u700f\u89bd\u5668\u5c07\u6703\u8981\u6c42\u4f60\u7684\u767b\u5165\u540d\u5b57\u53ca\u5bc6\u78bc  .',
  'Message text'),
 'external_user_database_explanation':
 (u'\u4f60\u7684  Fle3\u6b63\u5728\u4f7f\u7528\u5916\u4f86\u6210\u54e1\u8cc7\u6599\u5eab  . \u5982\u6b32\u52a0\u5165\u6210\u54e1  , \u4f60\u5fc5\u9808\u5148\u5728\u4f60\u7684\u8cc7\u6599\u5eab\u52a0\u5165\u9019\u4e9b\u6210\u54e1 .',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 (u'\u8ab2\u7a0b  ', 'part of browser title'),
 'courses':
 (u'\u8ab2\u7a0b  ', 'Title'),
 'create_course':
 (u'\u52a0\u5165\u8ab2\u7a0b  ', 'Link'),
 'edit_course':
 (u'\u4fee\u6539\u8ab2\u7a0b  ', 'Button label'),
 'edit_participants':
 (u'\u4fee\u6539\u53c3\u52a0\u8005  ', 'Button label'),
 'creating_course':
 (u'\u52a0\u5165\u8ab2\u7a0b\u9032\u884c\u4e2d  ', 'Title'),
 'editing_course':
 (u'\u4fee\u6539\u8ab2\u7a0b\u9032\u884c\u4e2d  ', 'Title'),
 'course_title':
 (u'\u8ab2\u7a0b\u984c\u76ee  ', 'Label'),
 'organization':
 (u'\u7d44\u7e54  ', 'Label'),
 'methods':
 (u'\u65b9\u6cd5  ', 'Label'),
 'starting_date':
 (u'\u958b\u59cb\u65e5\u671f  ', 'Label'),
 'ending_date':
 (u'\u5b8c\u6210\u65e5\u671f  ', 'Label'),
 'create_groupfolder':
 (u'\u52a0\u5165\u7d44\u5225  ', 'Link'),
 'create_announcements':
 ('\\u52a0\\u5165\\u4f48\\u544a', 'Link'),
 'edit_announcements':
 ('\\u4fee\\u6539\\u4f48\\u544a', 'Link'),
 'add_announcement':
 ('\\u65b0\\u589e\\u4f48\\u544a', 'Link'),
 'adding_announcement':
 ('\\u65b0\\u589e\\u4f48\\u544a\\u81f3',
  'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('\\u78ba\\u5b9a\\u522a\\u9664\\u4f48\\u544a\\ufe56', 'Question'),
 'editing_announcements':
 ('\\u6b63\\u5728\\u4fee\\u6539\\u4f48\\u544a', 'Heading'),
 'viewing_announcements':
 ('\\u700f\\u89bd\\u8ab2\\u7a0b %s \\u7684\\u4f48\\u544a',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 (u'\u6b63\u5728\u628a\u6210\u54e1\u52a0\u5165\u8ab2\u7a0b\u4e2d  ',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 (u'\u5982\u82e5\u53c3\u52a0\u8005\u4e0d\u662f  Fle3\u6210\u54e1  ',
  'Message'),
 'new_participants_to_system':
 (u'\u5728  Fle3\u7cfb\u7d71\u52a0\u5165\u65b0\u6210\u54e1  ',
  'Part of a phrase'),
 'by_email':
 (u'\u4f7f\u7528\u96fb\u90f5  ', 'Part of a phrase'),
 'manually':
 (u'\u7528\u624b\u64cd\u7e31  ', 'Part of a phrase'),
 'fle_users':
 (u'FLE3\u6210\u54e1  ', 'Heading'),
 'down':
 (u'\u4e0b  ', 'Button label'),
 'up':
 (u'\u4e0a  ', 'Button label'),
 'teachers':
 (u'\u6559\u5e2b  ', 'Heading'),
 'tutors':
 (u'\u52a9\u6559  ', 'Heading'),
 'students':
 (u'\u5b78\u751f  ', 'Heading'),
 'add_button':
 (u'\u52a0\u5165   ->', 'Button label'),
 'remove_button':
 (u'<- \u6e05\u9664  ', 'Button label'),
 'viewing_course':
 (u'\u986f\u793a\u8ab2\u7a0b  ', 'Part of a phrase in location path'),
 'viewing_course_resources':
 (u'\u700f\u89bd\u8ab2\u7a0b %s\u4f86\u6e90 ',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 (u'\u8cc7\u6599  ', 'Part of a phrase in location path'),
 'no_course_selected':
 (u'\u6c92\u6709\u9078\u53d6\u8ab2\u7a0b  !', 'Message dialog title'),
 'select_course_first':
 (u'\u8acb\u5728\u8ab2\u7a0b\u5217\u9078\u53d6\u8ab2\u7a0b  .',
  'Message dialog message'),
 'set_published':
 (u'\u767c\u4f48\u77e5\u8b58\u985e\u578b  ', 'Message dialog title/text'),
 'users_updated':
 (u'\u5df2\u66f4\u65b0\u6210\u54e1  ', 'Message dialog title/message'),
 'select_some_users':
 (u'\u8acb\u9078\u53d6\u4f7f\u7528\u6210\u54e1  ',
  'Message dialog title/message'),
 'edit_course_info':
 (u'\u4fee\u6539\u8ab2\u7a0b\u8cc7\u6599  ', 'Link'),
 'edit_course_participants':
 (u'\u4fee\u6539\u8ab2\u7a0b\u53c3\u52a0\u8005  ', 'Link'),
 'edit_course_resources':
 (u'\u4fee\u6539\u8ab2\u7a0b\u4f86\u6e90 ', 'Link'),
 'date':
 (u'\u65e5\u671f  ',
  'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 (u'\u8ab2\u7a0b\u53c3\u52a0\u8005  ', 'Label'),
 'type_sets':
 (u'\u77e5\u8b58\u985e\u578b\u7d44  ', 'Label, plural'),
 'delete':
 (u'\u6e05\u9664  ', 'Button label'),
 'my_participation':
 (u'\u6211\u7684\u53c3\u8207 ', 'Label'),
 'my_notes':
 (u'\u6211\u7684\u7b46\u8a18 ', 'Link'),
 'my_artefacts':
 (u'\u6211\u7684\u4f5c\u54c1 ', 'Link'),
 'course_resources':
 (u'\u8ab2\u7a0b\u4f86\u6e90 ', 'Label'),
 'add_typeset':
 (u'\u52a0\u5165\u77e5\u8b58\u985e\u578b\u7d44  ', 'Link'),
 'tt_yellow':
 (u'\u9ec3  ', 'knowledge type colour name'),
 'tt_yellowlt':
 (u'\u6dfa\u9ec3  ', 'knowledge type colour name'),
 'tt_orange':
 (u'\u6a59  ', 'knowledge type colour name'),
 'tt_orangelt':
 (u'\u6dfa\u6a59  ', 'knowledge type colour name'),
 'tt_red':
 (u'\u7d05  ', 'knowledge type colour name'),
 'tt_pink':
 (u'\u7c89\u7d05  ', 'knowledge type colour name'),
 'tt_purple':
 (u'\u7d2b  ', 'knowledge type colour name'),
 'tt_blue':
 (u'\u7c43  ', 'knowledge type colour name'),
 'tt_bluelt':
 (u'\u6dfa\u7c43  ', 'knowledge type colour name'),
 'tt_aqua':
 (u'\u6c34\u7c43  ', 'knowledge type colour name'),
 'tt_green':
 (u'\u7da0  ', 'knowledge type colour name'),
 'tt_greenlt':
 (u'\u6dfa\u7da0  ', 'knowledge type colour name'),
 'tt_gray':
 (u'\u7070  ', 'knowledge type colour name'),
 'tt_white':
 (u'\u767d  ', 'knowledge type colour name'),
 'edit_typeset':
 (u'\u4fee\u6539\u77e5\u8b58\u985e\u578b\u7d44  ', 'Heading'),
 'create_typeset':
 (u'\u52a0\u5165\u77e5\u8b58\u985e\u578b\u7d44  ', 'Heading'),
 'form':
 (u'\u8868\u683c  ', 'Start of heading'),
 'title':
 (u'\u984c\u76ee  ', 'Start of label'),
 'of_typeset':
 (u'\u7684\u77e5\u8b58\u985e\u578b\u7d44  ', 'Ending of label'),
 'abbreviations_and_icons':
 (u'\u7e2e\u5beb\u53ca\u6a19\u8a8c  ', 'Ending for heading'),
 'type':
 (u'\u77e5\u8b58\u985e\u578b  ', 'Label'),
 'types':
 (u'\u77e5\u8b58\u985e\u578b  ', 'Title'),
 'types_management':
 (u'\u77e5\u8b58\u985e\u578b\u7ba1\u7406  ', 'Title'),
 'abbreviation':
 (u'\u7e2e\u5beb  ', 'Label'),
 'color':
 (u'\u984f\u8272  ', 'Label'),
 'icon':
 (u'\u6a19\u8a8c  ', 'Label'),
 'starting_phrase':
 (u'\u8d77\u59cb\u968e\u6bb5  ', 'Label'),
 'checklist':
 (u'\u6e05\u55ae  ', 'Label'),
 'no_types_entered':
 (u'\u4f60\u6c92\u6709\u8f38\u5165\u77e5\u8b58\u985e\u578b  . \u6bcf\u500b\u77e5\u8b58\u985e\u578b\u7d44\u4e5f\u8981\u52a0\u5165\u8d77\u78bc\u4e00\u500b\u77e5\u8b58\u985e\u578b  .',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 (u'\u4f7f\u7528\u9650\u5236  ', 'Heading sentence.'),
 'that_can_start_thread':
 (u'\u53ef\u4ee5\u958b\u59cb\u8a0e\u8ad6  ', 'End of label'),
 'viewing':
 (u'\u700f\u89bd\u4e2d  ', 'Part of location bar'),
 'new_typeset_from':
 (u'\u8907\u88fd\u53ca\u4fee\u6539\u77e5\u8b58\u985e\u578b\u7d44  ',
  'Link, followed by knowledge type set name'),
 'unfinished':
 (u'\u672a\u5b8c\u6210  ', 'Label'),
 'manage_types':
 (u'\u7ba1\u7406\u77e5\u8b58\u985e\u578b  ', 'Link'),
 'finalize_typeset':
 (u'\u6539\u8b8a\u72c0\u614b\u53ca\u5b8c\u6210  ', 'Button label'),
 'are_you_sure':
 (u'\u4f60\u662f\u5426\u78ba\u8981\u6e05\u9664\u4ee5\u4e0b\u8ab2\u7a0b  :',
  'Message dialog message'),
 'are_you_sure_ctx':
 (u'\u4f60\u662f\u5426\u78ba\u5b9a\u8981\u6e05\u9664\u9019\u8ab2\u7a0b\u7bc7\u5e45  :',
  'Message dialog message'),
 'are_you_sure_tts':
 (u'\u4f60\u662f\u5426\u78ba\u5b9a\u6e05\u9664\u4ee5\u4e0b\u77e5\u8b58\u985e\u578b\u7d44  :',
  'Message dialog message'),
 'typeset_importing':
 (u'\u8acb\u9078\u64c7\u5c07\u6703\u8f38\u5165\u7684\u77e5\u8b58\u985e\u578b\u58d3\u7e2e\u6a94\u6848  .',
  'Instructions for typeset importing'),
 'typesets_imported':
 (u'\u5df2\u7d93\u8f38\u5165\u65b0\u7684\u77e5\u8b58\u985e\u578b  .',
  'Message'),
 'import_typeset':
 (u'\u8f38\u5165\u77e5\u8b58\u985e\u578b\u7d44  ', 'link'),
 'course_importing':
 (u'\u8acb\u9078\u64c7\u5c07\u6703\u8f38\u5165\u7684\u77e5\u8b58\u985e\u578b\u58d3\u7e2e\u6a94\u6848  .',
  'Instructions for course importing'),
 'courses_imported':
 (u'\u5df2\u7d93\u8f38\u5165\u65b0\u7684\u8ab2\u7a0b  .', 'Message'),
 'import_course':
 (u'\u8f38\u5165\u8ab2\u7a0b  ', 'link'),
 'course_imported':
 (u'(\u5df2\u8f38\u5165  )', 'Appended to imported course names.'),
 'can_start_thread':
 (u'\u53ef\u4ee5\u958b\u59cb\u5206\u652f ', 'column title in a table'),
 'can_be_followed':
 (u'\u53ef\u4ee5\u8ddf\u9032 ', 'column title in a table'),
 'use_each_type':
 (u'\u6bcf\u500b\u77e5\u8b58\u985e\u578b\u5fc5\u9808\u9023\u63a5\u8d77\u78bc\u4e00\u500b\u5176\u4ed6\u985e\u578b\u6216\u5206\u652f .',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 (u'\u4f86\u6e90 ', 'Title for list of course resources'),
 'add_resource':
 (u'\u52a0\u5165\u4f86\u6e90 ', 'Link'),
 'editing_course_resources':
 (u'\u4fee\u6539\u8ab2\u7a0b\u4f86\u6e90 ', 'Title'),
 'remove_resource_verify':
 (u'\u4f60\u662f\u5426\u78ba\u5b9a\u6e05\u9664\u9019\u4f86\u6e90 ?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 (u'\u52a0\u5165\u593e\u8a08\u5c0f\u7bc0  ', 'link'),
 'jam_sessions':
 (u'\u593e\u8a08\u5c0f\u7bc0  :',
  'a list of jam session will listed after/under this label'),
 'jam_session':
 (u'\u593e\u8a08\u5c0f\u7bc0  ', ''),
 'annotations':
 (u'\u8a3b\u91cb  ', ''),
 'continue_with_version':
 (u'\u7e7c\u7e8c\u4f60\u7684\u7248\u672c  ', 'button label'),
 'artefact':
 (u'\u4f5c\u54c1  ', ''),
 'viewing_annotations':
 (u'\u700f\u89bd\u8a3b\u91cb  ', ''),
 'Annotations':
 (u'\u8a3b\u91cb  :', 'Label, followed by a list of annotations under it'),
 'add_annotation':
 (u'\u52a0\u5165\u8a3b\u91cb  ', 'link'),
 'adding_jam_session':
 (u'\u52a0\u5165\u593e\u8a08\u5c0f\u7bc0  ', ''),
 'edit_jam_session':
 (u'\u4fee\u6539\u593e\u8a08\u5c0f\u7bc0  ', ''),
 'editing_jam_session':
 (u'\u4fee\u6539\u593e\u8a08\u5c0f\u7bc0  ', ''),
 'title_of_jam_session':
 (u'\u593e\u8a08\u5c0f\u7bc0\u6a19\u984c  ', 'label'),
 'type_of_jam_session':
 (u'\u593e\u8a08\u5c0f\u7bc0\u985e\u578b  ', 'label'),
 'mutate_on_previous':
 (u'\u7a81\u8b8a\u5148\u524d\u7684  ', 'type of jam session'),
 'explore_possibilities':
 (u'\u63a2\u7d22\u53ef\u80fd\u6027  ', 'type of jam session'),
 'diverge_and_converge':
 (u'\u5206\u6b67\u53ca\u6e4a\u5408  ', 'type of jam session'),
 'description_of_jam_session':
 (u'\u593e\u8a08\u5c0f\u7bc0\u63cf\u8ff0  ', 'label'),
 'upload_the_starting_artefact':
 (u'\u4e0a\u8f09\u53ca\u958b\u59cb\u4f5c\u54c1  ', 'label'),
 'title_of_the_starting_artefact':
 (u'\u8d77\u521d\u4f5c\u54c1\u7684\u6a19\u984c  ', 'label'),
 'annotation_of_the_starting_artefact':
 (u'\u8d77\u521d\u4f5c\u54c1\u7684\u8a3b\u91cb  ', 'label'),
 'adding_artefact':
 (u'\u52a0\u5165\u8a3b\u91cb  ', ''),
 'title_of_the_artefact':
 (u'\u8a3b\u91cb\u6a19\u984c  ', 'label'),
 'upload_file':
 (u'\u4e0a\u8f09\u6a94\u6848  ', 'label'),
 'you_adding_annotation':
 (u'\u4f60\u5728\u52a0\u5165  arefact\u7684\u8a3b\u91cb  ',
  'message in adding annotations form'),
 'adding_annotation':
 (u'\u52a0\u5165\u8a3b\u91cb\u81f3  ', ''),
 'to_jam_session':
 (u'\u53bb\u593e\u8a08\u5c0f\u7bc0  ', 'Part of a message'),
 'to_jam_artefact':
 (u'\u53bb\u593e\u8a08\u4f5c\u54c1  ', 'Part of a message'),
 'unread_artefacts':
 (u'\u65b0\u4f5c\u54c1  ', 'There is a number before this message'),
 'total_artefacts':
 (u'\u7e3d\u6578  ', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u4ee5\u4e0b\u593e\u8a08\u5c0f\u7bc0  :',
  'Message dialog message'),
 'are_you_sure_jam_session':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u4ee5\u4e0b\u593e\u8a08\u5c0f\u7bc0\u9023\u540c   %s \u4f5c\u54c1  ?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 (u'\u6e05\u9664\u4f5c\u54c1  ', 'Button label for removing jam artefact'),
 'restore_artefact':
 (u'\u66f4\u751f\u4f5c\u54c1  ', 'Button label for restoring jam artefact'),
 'remove_annotation':
 (u'\u6e05\u9664\u9078\u53d6\u7684\u8a3b\u91cb  ',
  'Button label for removing jam annotations'),
 'restore_annotation':
 (u'\u66f4\u751f\u9078\u53d6\u7684\u8a3b\u91cb  ',
  'Button label for restoring jam annotations'),
 'removed_name':
 (u'\u5df2\u6e05\u9664  ', 'Title/name for removed jam artefact'),
 'removed_message':
 (u'\u9019\u4f5c\u54c1\u5df2\u88ab  %s\u5728  %s\u6e05\u9664  .',
  "First placeholder is replaced by remover's name and the second by the date"),
 'removed_msg':
 (u'\u4f5c\u54c1\u5df2\u88ab\u6e05\u9664  ',
  'Message shown to the teacher when she has removed an artefact.'),
 'removed_annotation_msg':
 (u'\u8a3b\u91cb\u5df2\u88ab\u6e05\u9664  ',
  'Message shown to the teacher when she has removed an annotation.'),
 'remove_verify':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u9019\u4f5c\u54c1  ? \u4f60\u4ee5\u4e0b\u7684\u540d\u5b57\u548c\u9019\u65e5\u671f\u5c07\u6703\u88ab\u5132\u5b58  . \u7576\u9019\u4f5c\u54c1\u518d\u88ab\u700f\u89bd\u6642  ,\u9019\u4e9b\u8cc7\u6599\u5c07\u6703\u9023\u540c\u6e05\u9664\u544a\u793a\u986f\u793a\u51fa\u4f86  .',
  'Verification message shown when removing is attempted'),
 'remove_annotations_verify':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u9019\u8a3b\u91cb  ? \u4f60\u4ee5\u4e0b\u7684\u540d\u5b57\u548c\u9019\u65e5\u671f\u5c07\u6703\u88ab\u5132\u5b58  . \u7576\u9019\u8a3b\u91cb\u518d\u88ab\u700f\u89bd\u6642  ,\u9019\u4e9b\u8cc7\u6599\u5c07\u6703\u9023\u540c\u6e05\u9664\u544a\u793a\u986f\u793a\u51fa\u4f86  .',
  'Verification message shown when removing is attempted'),
 'removed_annotation_body':
 (u'\u9019\u8a3b\u91cb\u5df2\u88ab  %s\u5728  %s\u6e05\u9664  .',
  "Body for removed annotation. First placeholder is replaced by remover's name and the second by the date"),
 'search_jam':
 (u'\u641c\u5c0b\u593e\u8a08  ', 'Link label'),
 'searching_jam':
 (u'\u641c\u5c0b\u593e\u8a08\u4f5c\u54c1  ', 'Label'),
 'search_artefact_name':
 (u'\u4f5c\u54c1\u540d\u5b57  ', 'Label in search form'),
 'search_artefact_author':
 (u'\u4f5c\u8005  ', 'Label for author of artefact in search form'),
 'search_annotation_words':
 (u'\u8a3b\u91cb\u5305\u542b\u5b57  ',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 (u'\u4f5c\u54c1\u985e\u578b  ',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 (u'\u5716\u6848  ', 'Artefact type'),
 'type_audio':
 (u'\u97f3\u6a02  ', 'Artefact type'),
 'type_text':
 (u'\u6587\u5b57  ', 'Artefact type'),
 'type_html':
 (u'\u7db2\u9801  ', 'Artefact type'),
 'type_video':
 (u'\u5f71\u7247  ', 'Artefact type'),
 'type_archive':
 (u'\u6a94\u6848\u5eab  ', 'Artefact type'),
 'search_annotated_by':
 (u'\u8a3b\u91cb\u8005  ', 'Label in search form'),
 'search_results_author':
 (u'\u4f5c\u8005  ', 'Heading in search results table'),
 'search_results_jam_artefact':
 (u'\u593e\u8a08\u4f5c\u54c1  ', 'Heading in search results table'),
 'search_results_jam_session':
 (u'\u593e\u8a08\u5c0f\u7bc0  ', 'Heading in search results table')}

announce = {'comments':
 ('\\u610f\\u898b', 'Notice / form heading'),
 'no_comments':
 ('\\u6c92\\u6709\\u610f\\u898b\\u3002', 'Notice'),
 'recent_comments':
 ('\\u6700\\u8fd1\\u610f\\u898b', 'Heading'),
 'no_entries':
 ('\\u6c92\\u6709\\u9805\\u76ee', 'Notice'),
 'recent_entries':
 ('\\u6700\\u8fd1\\u9805\\u76ee', 'Heading'),
 'trackbacks':
 ('\\u5f15\\u7528\\u901a\\u544a', 'Notice'),
 'no_trackbacks':
 ('\\u6c92\\u6709\\u5f15\\u7528\\u901a\\u544a', 'Notice'),
 'recent_trackbacks':
 ('\\u6700\\u8fd1\\u5f15\\u7528\\u901a\\u544a', 'Heading'),
 'send_trackback':
 ('\\u8acb\\u5bc4\\u51fa\\u5f15\\u7528\\u901a\\u544a\\u81f3\\ufe55',
  'Part of message, followed by url'),
 'syndicate':
 ('\\u806f\\u5408\\u4f9b\\u7a3f\\u9019\\u7db2\\u5740(XML)\\u3002', 'Link'),
 'log_in':
 ('\\u767b\\u5165 Fle3\\u3002', 'Link'),
 'entries':
 ('\\u9805\\u76ee', 'Heading'),
 'category':
 ('\\u985e\\u5225', 'Heading'),
 'categories':
 ('\\u985e\\u5225', 'Heading'),
 'no_categories':
 ('\\u6c92\\u6709\\u985e\\u5225', 'Notice'),
 'items':
 ('\\u9805\\u76ee', 'Part of message: nn items.'),
 'posted_by':
 ('\\u767c\\u4f48\\u8005', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%m/%d %H:%M', 'Short date format'),
 'dateformat':
 ('%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 ('\\u5728', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('\\u8cbc\\u4e0a\\u610f\\u898b', 'Heading'),
 'name':
 ('\\u59d3\\u540d', 'Form heading'),
 'email':
 ('\\u96fb\\u90f5', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('\\u984c\\u76ee', 'Form heading'),
 'body':
 ('\\u4f48\\u544a\\u4e3b\\u9ad4', 'Form heading'),
 'forget_personal':
 ('\\u5fd8\\u8a18\\u500b\\u4eba\\u8cc7\\u6599', 'Button'),
 'remember_personal':
 ('\\u5728 cookie \\u8a18\\u9304\\u500b\\u4eba\\u8cc7\\u6599?', 'Label'),
 'teachers_and_tutors_only':
 ('\\u53ea\\u9650\\u6559\\u5e2b\\u53ca\\u52a9\\u6559',
  'Message, displayed in parenthesis after a link'),
 'Announcement':
 ('\\u4f48\\u544a', 'Category'),
 'ToDo':
 ('ToDo', 'Category'),
 'Event':
 ('\\u4e8b\\u4ef6', 'Category'),
 'continue_reading':
 ('\\u7e7c\\u7e8c\\u95b1\\u8b80', 'Part of message, followed by entry title'),
 'missing1':
 ('\\u5df2\\u5931', 'Part of message'),
 'missingn':
 ('\\u5df2\\u5931', 'Part of message'),
 'comment_preview':
 ('\\u610f\\u898b\\u9810\\u89bd', 'Heading'),
 'search_results':
 ('\\u641c\\u5c0b\\u7d50\\u679c', 'Heading'),
 'search_for':
 ('\\u641c\\u5c0b\\u4f48\\u544a', 'Part of message'),
 'no_match':
 ('\\u6c92\\u6709\\u76f8\\u95dc\\u7d50\\u679c', 'Notice'),
 'about':
 ('\\u95dc\\u65bc', 'Title'),
 'archives':
 ('Archives', 'Title'),
 'search':
 ('\\u641c\\u5c0b', 'Heading'),
 'search_help':
 ('\\u60a8\\u53ef\\u4f7f\\u7528 AND/OR \\u4ee5\\u4f7f\\u7528\\u4e8c\\u5143\\u641c\\u5c0b.',
  'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

