# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_zh.py,v 1.6 2005/01/25 20:24:48 tarmo Exp $
#
# Copyright 2001, 2002 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the english translations for all Fle3 printable strings."""

# How to do a new translation:
#
# 1. Copy this file into a new file, appending the language code after it, so
# you get something like "vocabulary_es.py" for Spanish and so on.
#
# 2. Edit the new file, translating the second portion of each line. The
# first portion is the keyword, which you shouldn't touch. The second is the
# translation that should be translated to the target language. The third
# is the supplementary instruction, that should help you do the translations.
#
# 3. Please note that the file is in Python code and needs to follow certain
# syntax rules:
#  - Strings can either be quoted by singles quotes (') or double quotes (").
#    If you need to use either of these quotation marks in your translation,
#    make sure that you use the other quotation mark to surround the string.
#    If you need to use both quotation marks in the same translation string,
#    you can surround the string with triple quotes (''' or """), which
#    allows you to use either of the quotation marks inside the string.
#  - Line breaks are not allowed inside strings, so make sure you don't
#    use an editor that wraps lines. You can have line breaks between
#    strings, though.
#
# 4. If you need to use special characters (outside of the 127 character
# ASCII range), you have several choices:
#
# A. Write in your native encoding (whatever suits you best). This requires
#    that you change the "charset_encoding" keyword in the "common" module to
#    the encoding type you will use. This document is written in iso8859-1,
#    although as english does not contain special characters, it could be
#    in utf-8 as well without any differences.
#    Most European languages are easiest to write in iso8859-1.
#
# B. Write in utf-8 encoded unicode. If your editor can save files in utf-8,
#    use that feature. If not, you can add the special characters manually
#    with the \x escape sequences. Make sure you remove the keyword
#    "charset_encoding" from the "common" module, or change its value to
#    "utf-8" so that the strings are interpreted correctly.
#    'key', (u'\xe3\x82\xaa','This is the katakana letter O,encoded in utf-8.'),
#
# C. Write in unicode. Each unicode string starts with u followed by the
#    quotes. Each unicode character starts with \u followed by the code in
#    hexadecimal notation. The value of the "charset_encoding" keyword
#    is irrelevant if you use unicode all the way.
#    'key', (u'\u5de6 ','This is the katakana letter O, encoded in unicode.'),
#
# 5. Check your translation. If you have Python installed and you've
#    downloaded Fle3 sources, you can execute "python TranslationLint.py"
#    which will check through all the translation files and will produce
#    an error if there is a syntax error.
#    If you have installed Fle3, you can test the translation yourself
#    by going to Zope Management and selecting the Tools tab in your FLE
#    instance, and clicking on "reload_translations". After this you
#    should be able to select your translation from user preferences
#    and see the translated strings.
#

# Edited By: Arthur Chan @ Smart Open Quote Company (SoQ) @ Hong Kong  @ www.soqhome.com @ 25 Jan, 2005

common = {'language_name':
 (u'\u7b80\u4f53\u4e2d\u6587  ', 'Name of this language'),
 'charset_encoding':
 (u'utf-8', 'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 (u'\u5de5\u4f5c\u574a  ', 'Main tab for webtop'),
 'Knowledge_Building':
 (u'\u77e5\u8bc6\u521b\u5efa  ', 'Main tab for knowledge building'),
 'Course_Management':
 (u'\u8bfe\u7a0b\u7ba1\u7406  ', 'Main tab for course management'),
 'User_Management':
 (u'\u6210\u5458  ', 'Main tab for user management'),
 'Jamming':
 (u'\u5939\u8ba1  ', 'Main tab for jamming'),
 'Type_Management':
 (u'\u77e5\u8bc6\u7c7b\u578b\u7ba1\u7406  ', 'Heading'),
 'cancel':
 (u'\u53d6\u6d88  ', 'Button label'),
 'submit':
 (u'\u9012\u4ea4  ', 'Button label'),
 'remove':
 (u'\u6e05\u9664  ', 'Button label'),
 'next':
 (u'\u4e0b\u4e00\u6b65   ->', 'Label for button'),
 'previous':
 (u'<- \u4e0a\u4e00\u6b65  ', 'Label for button'),
 'quick_submit':
 (u'\u5feb\u9012  ', ''),
 'ok':
 (u'\u6210\u529f  ', 'Button label'),
 'save':
 (u'\u5b58\u6863  ', 'Button label'),
 'create':
 (u'\u5236\u9020  ', 'Button label'),
 'search':
 (u'\u641c\u5bfb  ', 'Button label'),
 'webtop':
 (u'\u5de5\u4f5c\u574a  ', ''),
 'description':
 (u'\u63cf\u8ff0  ', 'Label'),
 'short_date_format_display':
 (u'YYYY-MM-DD', 'String displayed as clue when entering a date'),
 'short_date_format':
 (u'%Y-%m-%d',
  'Format string for short dates. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'timestamp_format':
 (u'%H:%M %Y-%m-%d',
  'Format string for long timestamps. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'invite':
 (u'\u9080\u8bf7  ', ''),
 'add':
 (u'\u52a0\u5165  ', ''),
 'today':
 (u'\u4eca\u5929  ', ''),
 'yesterday':
 (u'\u6628\u5929  ', ''),
 'groupfolder':
 (u'\u8bfe\u7a0b\u7ec4\u5408  ', 'Heading'),
 'dtml_reloaded':
 (u'DTML \u5df2\u7ecf\u66f4\u751f  ', 'Title for message dialog'),
 'dtml_files_reloaded':
 (u'\u6b64\u7269\u4ef6\u7684  DTML \u6863\u6848\u5df2\u7ecf\u66f4\u751f  ',
  'Message dialog text'),
 'dtmls_reloaded':
 (u'\u591a\u4e2a  DTML \u5df2\u7ecf\u66f4\u751f  ',
  'Title for message dialog'),
 'dtmls_files_reloaded':
 (u'\u5168\u90e8   DTML \u6863\u6848\u5df2\u7ecf\u66f4\u751f  ',
  'Message dialog text'),
 'css_reloaded':
 (u'\u4e32\u63a5\u6837\u5f0f\u8868\u5df2\u7ecf\u66f4\u751f  ',
  'Title for message dialog'),
 'css_files_reloaded':
 (u'\u8fd9\u7269\u4ef6\u7684\u4e32\u63a5\u6837\u5f0f\u8868\u6863\u5df2\u7ecf\u66f4\u751f  ',
  'Message text'),
 'error':
 (u'\u9519\u8bef  ', ''),
 'warning':
 (u'\u8b66\u544a  ', ''),
 'invalid_url':
 (u'\u7f51\u5740\u4e0d\u6b63\u786e  ', 'Message title'),
 'invalid_url_message':
 (u'\u7f51\u5740\u4e0d\u6b63\u786e  .<br>\u8bf7\u68c0\u67e5\u5f00\u7aef\u5b57\u53e5\u662f\u5426   <i>http://, ftp://, mailto:</i>\u6216\u4f60\u5fc3\u76ee\u4e2d\u5176\u4ed6\u7f51\u5740\u89c4\u7ea6  . \u8bf7\u7559\u610f\u7c7b\u4f3c\u4ee5\u4e0b\u7684\u7f51\u5740\u662f\u4e0d\u5bb9\u8bb8\u7684   "www.myaddress.org". \u4f46\u52a0\u4e0a\u7f51\u5740\u89c4\u7ea6\u4fbf\u53ef  : "http://www.myaddress.org". \u82e5\u4f60\u4e0d\u6e05\u695a\u6240\u7528\u7f51\u5740\u89c4\u7ea6  , \u53ef\u5c1d\u8bd5\u8d34\u4e0a\u7f51\u9875\u5728\u6d4f\u89c8\u5668\u4e0a\u7684\u7f51\u5740  .',
  'Message text'),
 'invalid_name':
 (u'\u540d\u5b57\u4e0d\u6b63\u786e  ', 'Message title'),
 'give_valid_name':
 (u'\u8bf7\u8f93\u5165\u6b63\u786e\u540d\u5b57  ', 'Message text'),
 'name_taken':
 (u'\u5176\u4ed6\u7269\u4ef6\u5df2\u7ecf\u4f7f\u7528\u4e86\u540d\u5b57  "%s". \u8bf7\u8f93\u5165\u5176\u4ed6\u540d\u5b57  .',
  'Message text, name inserted inside'),
 'edit':
 (u'\u4fee\u6539  ', 'Button label'),
 'you_are_in':
 (u'\u4f60\u5728\u6b64  :',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 (u'\u8bf7\u586b\u59a5\u6240\u6709\u9879\u76ee  .', 'Erro message text'),
 'confirmation':
 (u'\u786e\u8ba4  ', 'Title for confirmation dialogs'),
 'invalid_input':
 (u'\u4e0d\u6b63\u786e\u8f93\u5165  ', 'Message title'),
 'invalid_fields':
 (u'\u4ee5\u4e0b\u9879\u76ee\u5305\u542b\u4e0d\u6b63\u786e\u8f93\u5165  ',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 (u'\u8bf7\u5148\u9009\u62e9\u7269\u4ef6  ', 'Message text'),
 'link_to_webtop':
 (u'\u5728\u5de5\u4f5c\u574a\u52a0\u5165\u8fde\u7ed3  ', 'Link'),
 'proxy_to_webtop':
 (u'\u8fde\u7ed3\u8bfe\u7a0b\u7ec4\u5408\u81f3\u5de5\u4f5c\u574a  ', 'Link'),
 'export':
 (u'\u8f93\u51fa  ', 'Button label'),
 'import':
 (u'\u8f93\u5165  ', 'Button label'),
 'importing':
 (u'\u8f93\u5165\u4e2d  ', 'Heading start'),
 'megabyte':
 (u'MB', 'Abbreviation for megabyte'),
 'kilobyte':
 (u'kB', 'Abbreviation for kilobyte'),
 'logout':
 (u'\u767b\u51fa  ', 'Link for logging out, also heading in logout dialogs'),
 'logout_pre3':
 (u'\u5982\u6b32\u767b\u51fa\uff0c\u8bf7\u5173\u95ed\u4f60\u7684\u6d4f\u89c8\u5668 ',
  'Instructions for logging out'),
 'any':
 (u'\u4efb\u4f55\u4e13\u6848  ', 'Label used in search forms'),
 'course':
 (u'\u8bfe\u7a0b  ', 'Part of location path'),
 'language':
 (u'\u8bed\u8a00  ', ''),
 'announcements':
 ('\\u5e03\\u544a', 'Link/heading'),
 'sun':
 ('\\u661f\\u671f\\u65e5', 'Weekday abbreviation'),
 'mon':
 ('\\u661f\\u671f\\u4e00', 'Weekday abbreviation'),
 'tue':
 ('\\u661f\\u671f\\u4e8c', 'Weekday abbreviation'),
 'wed':
 ('\\u661f\\u671f\\u4e09', 'Weekday abbreviation'),
 'thu':
 ('\\u661f\\u671f\\u56db', 'Weekday abbreviation'),
 'fri':
 ('\\u661f\\u671f\\u4e94', 'Weekday abbreviation'),
 'sat':
 ('\\u661f\\u671f\\u516d', 'Weekday abbreviation'),
 'sunday':
 ('\\u661f\\u671f\\u516d', 'Weekday'),
 'monday':
 ('\\u661f\\u671f\\u4e00', 'Weekday'),
 'tuesday':
 ('\\u661f\\u671f\\u4e8c', 'Weekday'),
 'wednesday':
 ('\\u661f\\u671f\\u4e09', 'Weekday'),
 'thursday':
 ('\\u661f\\u671f\\u56db', 'Weekday'),
 'friday':
 ('\\u661f\\u671f\\u4e94', 'Weekday'),
 'saturday':
 ('\\u661f\\u671f\\u516d', 'Weekday'),
 'January':
 ('\\u4e00\\u6708', 'Month'),
 'February':
 ('\\u4e8c\\u6708', 'Month'),
 'March':
 ('\\u4e09\\u6708', 'Month'),
 'April':
 ('\\u56db\\u6708', 'Month'),
 'May':
 ('\\u4e94\\u6708', 'Month'),
 'June':
 ('\\u516d\\u6708', 'Month'),
 'July':
 ('\\u4e03\\u6708', 'Month'),
 'August':
 ('\\u516b\\u6708', 'Month'),
 'September':
 ('\\u4e5d\\u6708', 'Month'),
 'October':
 ('\\u5341\\u6708', 'Month'),
 'November':
 ('\\u5341\\u4e00\\u6708 ', 'Month'),
 'December':
 ('\\u5341\\u4e8c\\u6708', 'Month'),
 'remove_q':
 ('\\u79fb\\u9664\\uff1f', 'Question')}

kb = {'month':
 (u'\u6708 ', ''),
 'week':
 (u'\u5468 ', ''),
 'you_have_not_replied_to':
 (u'\u4f60\u6ca1\u6709\u56de\u8986\u8fd9\u4e9b\u6210\u5458 ',
  'followed by a list of persons'),
 'total_replies':
 (u'\u56de\u8986\u5176\u4ed6\u6210\u5458\u7684\u7b14\u8bb0\u603b\u6570 :',
  'followed by number'),
 'total_notes_written':
 (u'\u5199\u4e0b\u7b14\u8bb0\u603b\u6570 : ', 'followed by number'),
 'graph_type':
 (u'\u56fe\u50cf\u7c7b\u578b : ', 'Label for graph type selection'),
 'by_knowledge_type':
 (u'\u77e5\u8bc6\u7c7b\u578b ', 'graph type'),
 'replies':
 (u'\u56de\u8986 ', 'graph type'),
 'display_by':
 (u'\u663e\u793a\u65b9\u6cd5 :', 'Label for timescale (week/month) selection'),
 'adding_resource':
 (u'\u52a0\u5165\u6765\u6e90\u8fdb\u884c\u4e2d ', 'part of browser title'),
 'modifying_resource':
 (u'\u4fee\u6539\u6765\u6e90\u8fdb\u884c\u4e2d ', 'part of browser title'),
 'title_resource':
 (u'\u6807\u9898 ', 'The title of resource'),
 'author_resource':
 (u'\u4f5c\u8005 ', 'The author of the resource'),
 'url':
 (u'\u7f51\u5740 (URL)', 'Resource URL'),
 'location':
 (u'\u4f4d\u7f6e ', 'Resource location'),
 'course_info':
 (u'\u8bfe\u7a0b\u8d44\u6599  ', 'Label for link to course details'),
 'create_context':
 (u'\u52a0\u5165\u8bfe\u7a0b\u7bc7\u5e45  ',
  'Link to create new course context'),
 'hide_context':
 (u'\u9690\u85cf\u8bfe\u7a0b\u7bc7\u5e45  ',
  'Link to hide a context from view'),
 'show_context':
 (u'\u663e\u793a\u7bc7\u5e45  ', 'Link to show a hidden context'),
 'new_notes':
 (u'\u65b0\u7b14\u8bb0  ',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 (u'\u7b14\u8bb0  ', 'Label for showing the number of notes'),
 'full_description':
 (u'\u8be6\u7ec6\u63cf\u8ff0  ...', ''),
 'course':
 (u'\u8bfe\u7a0b  ', "String 'course' in context display"),
 'context':
 (u'\u7bc7\u5e45  ', "String 'context' in context display"),
 'thread':
 (u'\u5206\u652f  ', "String 'thread' in context display"),
 'note':
 (u'\u7b14\u8bb0  ', "String 'note' in context display"),
 'start_thread':
 (u'\u5f00\u59cb\u5206\u652f  ', 'Link'),
 'short_description':
 (u'\u7b80\u77ed\u63cf\u8ff0  ', 'Label'),
 'long_description':
 (u'\u957f\u7bc7\u63cf\u8ff0  ', 'Label'),
 'full_description':
 (u'\u8be6\u7ec6\u63cf\u8ff0  ', 'Label'),
 'select':
 (u'\u9009\u9879  ',
  'Start of sentence, followed by a drop-down list of available knowledge type'),
 'knowledge_type':
 (u'\u77e5\u8bc6\u7c7b\u578b  ', 'Label'),
 'add_note':
 (u'\u52a0\u5165\u7b14\u8bb0  ', 'Button label'),
 'show_notes':
 (u'\u663e\u793a\u7b14\u8bb0  ', 'Heading start'),
 'show_thread':
 (u'\u7528\u5206\u652f  ', 'heading finish'),
 'show_type':
 (u'\u4ee5\u77e5\u8bc6\u7c7b\u578b\u6392\u5e8f  ', 'heading finish'),
 'show_author':
 (u'\u4ee5\u4e2a\u4eba\u6392\u5e8f  ', 'heading finish'),
 'show_date':
 (u'\u4ee5\u65e5\u671f\u6392\u5e8f  ', 'heading finish'),
 'select_course':
 (u'\u9009\u62e9\u8bfe\u7a0b  ',
  'Label, followed by a drop-down list of available courses'),
 'change':
 (u'\u6539\u53d8  ', 'Button label'),
 'creating_context':
 (u'\u52a0\u5165\u8bfe\u7a0b\u7bc7\u5e45\u8fdb\u884c\u4e2d  ,\u4f4d\u7f6e\u5728  ',
  'Title, followed by the course name'),
 'editing_context':
 (u'\u4fee\u6539\u8bfe\u7a0b\u7bc7\u5e45\u8fdb\u884c\u4e2d  ,\u4f4d\u7f6e\u5728  ',
  'Title, followed by the course name'),
 'title_of_context':
 (u'\u8bfe\u7a0b\u7bc7\u5e45\u6807\u9898  ', 'Label'),
 'type_set':
 (u'\u77e5\u8bc6\u7c7b\u578b\u7ec4  ', 'Label'),
 'creating_note_in':
 (u'\u52a0\u5165\u7b14\u8bb0\u8fdb\u884c\u4e2d  ,\u4f4d\u7f6e\u5728  ',
  'Title, followed by course context name'),
 'course_context':
 (u'\u8bfe\u7a0b\u7bc7\u5e45  ', 'Label for course context'),
 'you_are_replying_to':
 (u'\u4f60\u6b63\u5728\u56de\u590d  ', 'Label'),
 'title_of_note':
 (u'\u7b14\u8bb0\u6807\u9898  ', 'Label'),
 'message_body':
 (u'\u8baf\u606f  ', 'Label'),
 'current_image':
 (u'\u76ee\u524d\u56fe\u6848  ', 'Label'),
 'replace_with':
 (u'\u53d6\u4ee3\u4e3a  ', 'Label for image replacement in note edit'),
 'add_image':
 (u'\u52a0\u5165\u56fe\u6848  ', 'Label'),
 'title_of_image':
 (u'\u56fe\u6848\u6807\u9898  ', 'Label'),
 'add_link':
 (u'\u52a0\u5165\u8fde\u7ed3  (URL)', 'Label'),
 'title_of_link':
 (u'\u8fde\u7ed3\u6807\u9898  ', 'Label'),
 'preview':
 (u'\u9884\u89c8  ', 'Button label'),
 'previewing_note':
 (u'\u9884\u89c8\u7b14\u8bb0  , \u4f4d\u7f6e\u5728  ',
  'Title/heading, followed by course context name'),
 'publish':
 (u'\u520a\u767b  ', 'Button label'),
 'search_kb':
 (u'\u641c\u5bfb\u77e5\u8bc6\u5e93  ', 'Link label'),
 'searching_kb':
 (u'\u641c\u5bfb\u77e5\u8bc6\u5e93\u7b14\u8bb0  ', 'Label'),
 'search_author':
 (u'\u4f5c\u8005  ', 'Label'),
 'search_notes_words':
 (u'\u7b14\u8bb0\u5305\u542b\u5b57\u53e5  ', 'Label'),
 'search_context':
 (u'\u8bfe\u7a0b\u7bc7\u5e45  ', 'Label'),
 'search_tt':
 (u'\u77e5\u8bc6\u7c7b\u578b  ', 'Label'),
 'search_note':
 (u'\u7b14\u8bb0  ', 'Label'),
 'current_note':
 (u'\u76ee\u524d\u7b14\u8bb0  ', 'Label'),
 'you_didnt_select_type':
 (u'\u4f60\u6ca1\u6709\u9009\u53d6\u77e5\u8bc6\u7c7b\u578b  .', 'Title'),
 'go_back':
 (u'\u9000\u56de  ', 'Start of message, rendered into a link'),
 'and_select_type':
 (u'\u53ca\u4e3a\u4f60\u7684\u7b14\u8bb0\u9009\u53d6\u77e5\u8bc6\u7c7b\u578b  .',
  'Rest of message'),
 'inline_notes':
 (u'\u663e\u793a\u6240\u6709\u7b14\u8bb0\u5185\u5bb9  ', 'Link'),
 'outline_notes':
 (u'\u9690\u85cf\u6240\u6709\u7b14\u8bb0\u5185\u5bb9  ', 'Link'),
 'view_info':
 (u'\u663e\u793a\u8d44\u6599  ', 'Part of location bar'),
 'edit_context':
 (u'\u4fee\u6539\u8bfe\u7a0b\u7bc7\u5e45  ', 'Link'),
 'to_note':
 (u'\u81f3\u7b14\u8bb0  ', 'Part of a message'),
 'full_thread_no':
 (u'\u53ea\u663e\u793a\u8d77\u521d\u7684\u7b14\u8bb0  ', 'Link'),
 'full_thread_yes':
 (u'\u663e\u793a\u6240\u6709\u5206\u652f  ', 'Link'),
 'remove':
 (u'\u6e05\u9664\u7b14\u8bb0  ', 'Button label for removing notes'),
 'restore':
 (u'\u8fd8\u539f\u7b14\u8bb0  ', 'Button label for restoring notes'),
 'remove_form_title':
 (u'\u6e05\u9664\u7b14\u8bb0  ', 'Title for note removing form'),
 'remove_form_label':
 (u'\u6e05\u9664\u7b14\u8bb0  ',
  'Explanation in remove form, followed by note subject'),
 'removed_msg':
 (u'\u8baf\u606f\u5df2\u7ecf\u6e05\u9664  ',
  'Message shown to the teacher when she has removed a note.'),
 'remove_verify2':
 (u'\u8bf7\u786e\u8ba4\u6e05\u9664\u8baf\u606f  . \u4f60\u4ee5\u4e0b\u7684\u540d\u5b57  , \u8fd9\u65e5\u671f\u548c\u4f60\u63d0\u4f9b\u7684\u89e3\u91ca\u5c06\u4f1a\u88ab\u50a8\u5b58  . \u5f53\u8fd9\u7b14\u8bb0\u518d\u88ab\u6d4f\u89c8\u65f6  ,\u8fd9\u4e9b\u8d44\u6599\u5c06\u4f1a\u8fde\u540c\u6e05\u9664\u544a\u793a\u663e\u793a\u51fa\u6765  .',
  'Verification message shown when removing is attempted'),
 'remove_explanation':
 (u'\u6e05\u9664\u7406\u7531  ', 'Label for removee explanation text area'),
 'removed_subject':
 (u'\u6e05\u9664  ', 'Title/subject for removed notes'),
 'removed_body':
 (u'\u8fd9\u6bb5\u8baf\u606f\u7531  %s\u5728  %s\u6e05\u9664  .',
  "Body for removed messages. First placeholder is replaced by remover's name and the second by the date"),
 'notes_from_day':
 (u'\u7b14\u8bb0  , \u7531  ', 'Start of heading, followed by a date'),
 'previous':
 (u'\u4e0a\u4e00\u6b65  ', 'Link label'),
 'next':
 (u'\u4e0b\u4e00\u6b65  ', 'Link label'),
 'who_has_read':
 (u'\u8c01\u9605\u8bfb\u8fc7\u8fd9\u7b14\u8bb0  ?', 'Link label'),
 'last_read':
 (u'\u6700\u5f8c\u9605\u8bfb  ', 'Label'),
 'times_read':
 (u'\u9605\u8bfb\u6b21\u6570  ', 'Label'),
 'back':
 (u'&lt; \u9000\u56de  ', 'Link label'),
 'unread_to_read_msg':
 (u'\u5168\u90e8\u5728\u5206\u652f\u7684\u7b14\u8bb0\u6807\u8bb0\u4e3a\u5df2\u9605\u8bfb  .',
  'title and message in a message dialog'),
 'mark_notes_read':
 (u'\u6807\u8bb0\u6240\u6709\u7b14\u8bb0\u4e3a\u5df2\u9605\u8bfb  ',
  'text in a button'),
 'creating_groupfolder':
 (u'\u52a0\u5165\u8bfe\u7a0b\u7ec4\u5408  , \u4f4d\u7f6e\u5728  ',
  'Heading start'),
 'title_groupfolder':
 (u'\u8bfe\u7a0b\u7ec4\u5408\u6807\u9898  ', 'Label'),
 'flea_asks':
 (u'\u963f\u82b1\u63d0\u95ee  ',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 (u'\u6539\u53d8\u77e5\u8bc6\u7c7b\u578b ',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 (u'\u8fd9\u662f\u552f\u4e00\u51c6\u8bb8\u7c7b\u578b ',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 (u'\u6539\u53d8  ', 'Button label'),
 'down_to_note':
 (u'\u5411\u4e0b  ', 'Link label'),
 'use_roleplay':
 (u'\u5728\u8fd9\u7bc7\u5e45\u4f7f\u7528\u89d2\u8272\u626e\u6f14  ',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 (u'\u8bbe\u5b9a\u89d2\u8272\u626e\u6f14\u8eab\u4efd  ',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 (u'\u8bfe\u7a0b  ', "Heading for user's course list"),
 'totals_notes':
 (u'\u7b14\u8bb0 ',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 (u'\u4f5c\u54c1 ',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 (u'\u65b0  %s/\u5171  %s',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 (u'\u52a0\u5165\u6587\u4ef6\u5939  ', ''),
 'add_document':
 (u'\u52a0\u5165\u6587\u4ef6  ', ''),
 'add_link':
 (u'\u52a0\u5165\u8fde\u7ed3  ', ''),
 'create_memo':
 (u'\u52a0\u5165\u5b57\u6761  ', ''),
 'type':
 (u'\u7c7b\u578b  ', 'Link for sorting by type'),
 'title':
 (u'\u6807\u9898  ', 'Link for sorting by title'),
 'date':
 (u'\u65e5\u671f  ', 'Link for sorting by date'),
 'size':
 (u'\u5927\u5c0f  ', 'Link for sorting by size'),
 'remove':
 (u'\u6e05\u9664  ', 'Button label'),
 'restore':
 (u'\u8fd8\u539f  ', 'Button label'),
 'rename':
 (u'\u6539\u540d  ', 'Button label'),
 'copy':
 (u'\u590d\u5236  ', 'Button label'),
 'cut':
 (u'\u526a\u4e0b  ', 'Button label'),
 'paste':
 (u'\u8d34\u4e0a  ', 'Button label'),
 'delete':
 (u'\u6e05\u9664  ', 'Button label'),
 'select_all':
 (u'\u5168\u9009  ', 'Button label'),
 'trash':
 (u'\u5e9f\u7eb8\u7bb1  ', 'Label for trashcan'),
 'empty_trash':
 (u'\u6e05\u7406\u5e9f\u7eb8\u7bb1  ', 'Button label'),
 'adding_folder':
 (u'\u52a0\u5165\u6587\u4ef6\u5939  ', 'Heading'),
 'title_of_folder':
 (u'\u6587\u4ef6\u5939\u6807\u9898  ', 'Label'),
 'viewing_memo':
 (u'\u6d4f\u89c8\u5b57\u6761  ', 'Title'),
 'creating_memo':
 (u'\u52a0\u5165\u5b57\u6761  ', 'Title'),
 'editing_memo':
 (u'\u4fee\u6539\u5b57\u6761  ', 'Title'),
 'title_of_memo':
 (u'\u5b57\u6761\u6807\u9898  ', 'Label'),
 'content':
 (u'\u5185\u5bb9  ', 'Label'),
 'show_memo_contents':
 (u'\u53ea\u663e\u793a\u5b57\u6761\u5185\u5bb9  ', 'Link'),
 'adding_link':
 (u'\u52a0\u5165\u8fde\u7ed3  ', 'Title'),
 'title_of_link':
 (u'\u8fde\u7ed3\u9898\u76ee  ', 'Label'),
 'url':
 (u'\u7f51\u5740  ', ''),
 'document_uploaded':
 (u'\u4e0a\u8f7d\u6587\u4ef6  .', 'Status message'),
 'adding_document':
 (u'\u52a0\u5165\u6587\u4ef6  ', 'Title'),
 'upload_document':
 (u'\u4e0a\u8f7d\u6587\u4ef6  ', 'Label'),
 'title_of_document':
 (u'\u6587\u4ef6\u9898\u76ee  ', 'Label'),
 'search_wt':
 (u'\u641c\u5bfb\u5de5\u4f5c\u574a  ', 'Link label'),
 'searching_wt':
 (u'\u6b63\u5728\u641c\u5bfb\u5de5\u4f5c\u574a  ', 'Label'),
 'search_results':
 (u'\u641c\u5bfb\u7ed3\u679c  ', 'Label'),
 'new_search':
 (u'\u65b0\u7684\u641c\u5bfb  ', 'Label'),
 'search_title':
 (u'\u9898\u76ee  ', 'Label'),
 'search_owner':
 (u'\u6301\u6709\u4eba  ', 'Label'),
 'search_words':
 (u'\u7269\u4ef6\u5305\u542b\u5b57  ', 'Label'),
 'search_object':
 (u'\u7269\u4ef6  ', 'Label'),
 'search_folder':
 (u'\u6587\u4ef6\u5939  ', 'Label'),
 'viewing_search_results':
 (u'\u6d4f\u89c8\u641c\u5bfb\u7ed3\u679c  ', 'Label in the location path'),
 'anyone':
 (u'\u4efb\u4f55\u4eba\u4ed5  ', 'Label'),
 'webtop_link_added':
 (u'\u5df2\u52a0\u5165\u5de5\u4f5c\u574a\u8fde\u7ed3  ', 'Message title'),
 'added_webtop_link':
 (u'\u4f60\u7684\u5de5\u4f5c\u574a\u5df2\u7ecf\u52a0\u5165\u8fde\u7ed3   %s "%s" . \u6309  "\u786e\u8ba4  "\u56de\u5230\u524d\u4e00\u9875  .',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 (u'\u5df2\u52a0\u5165\u8bfe\u7a0b\u6587\u4ef6\u5939  ', 'Message title'),
 'added_proxy':
 (u'\u8bfe\u7a0b  %s\u7684\u8bfe\u7a0b\u7ec4\u5408\u73b0\u5df2\u663e\u793a\u5728\u60a8\u7684\u5de5\u4f5c\u574a  . \u6309  "\u786e\u8ba4  "\u56de\u5230\u524d\u4e00\u9875  .',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 (u'\u6ca1\u6709\u9009\u53d6\u9879\u76ee  !', 'Message dialog title'),
 'select_item_first':
 (u'\u9664\u4e86\u8d34\u4e0a\u5916  , \u5176\u4ed6\u52a8\u4f5c\u4e5f\u987b\u8981\u9009\u53d6\u7269\u4ef6  .',
  'Message dialog message'),
 'no_file_supplied':
 (u'\u6ca1\u6709\u63d0\u4f9b\u6863\u6848  .', 'Message text'),
 'renaming':
 (u'\u6539\u540d\u8fdb\u884c\u4e2d  ', 'Title'),
 'invalid_names':
 (u'\u4ee5\u4e0b\u540d\u5b57\u65e0\u6548  :', 'Message dialog messsage'),
 'same_names':
 (u'\u591a\u4e2a\u9879\u76ee\u4f7f\u7528\u540c\u4e00\u540d\u5b57  .',
  'Message dialog message'),
 'names_in_use':
 (u'\u4ee5\u4e0b\u540d\u5b57\u5df2\u88ab\u4f7f\u7528  :',
  'Message dialog message'),
 'information':
 (u'\u6210\u5458\u8d44\u6599  ', 'Link'),
 'shared_course_folder':
 (u'\u5206\u4eab\u8bfe\u7a0b\u7ec4\u5408 ',
  'Printed after the name of the group folder in webtop contents list.'),
 'preferences':
 (u'\u559c\u597d  ', 'Link'),
 'editing_preferences':
 (u'\u4fee\u6539\u559c\u597d  ', 'Title'),
 'quota_reached_title':
 (u'\u9650\u989d\u5df2\u6ee1  ', 'Title'),
 'quota_reached':
 (u'\u56e0\u4e3a\u4f60\u7684\u5de5\u4f5c\u574a\u9650\u989d\u5df2\u6ee1  , \u4e0d\u80fd\u8fdb\u884c\u64cd\u4f5c  . \u8bf7\u6e05\u9664\u4e00\u4e9b\u7269\u4ef6\u518d\u7ee7\u7eed  .',
  'Message dialog message'),
 'obj_removed':
 (u'(\u8fde\u7ed3\u76ee\u6807\u5df2\u88ab\u6e05\u9664  )',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 (u'&lt; \u9000\u56de  ', 'Link label')}

usermgmnt = {'user':
 (u'\u6210\u5458  ', 'part of browser title'),
 'adding_users':
 (u'\u52a0\u5165\u6210\u5458  ', 'Title'),
 'required_field':
 (u'\u5fc5\u8981\u9879\u76ee  ', ''),
 'nickname':
 (u'\u522b\u540d  ', 'Label'),
 'user_account':
 (u'\u6210\u5458\u6237\u53e3  ', 'Label'),
 'Confirm':
 (u'\u786e\u8ba4  ', ''),
 'you_are_removing':
 (u'\u4f60\u6b63\u88ab\u6e05\u9664  ', ''),
 'invite_user':
 (u'\u9080\u8bf7\u6210\u5458  ', ''),
 'invite_users':
 (u'\u9080\u8bf7\u6210\u5458  ', 'Heading for invitation form'),
 'email_addresses':
 (u'\u7535\u90ae  ', ''),
 'separate_with_comma':
 (u'( \u76f8\u9694\u7b26\u53f7  : , )', ''),
 'Invitation_message':
 (u'\u9080\u8bf7\u8baf\u606f  ', ''),
 'Invitation_language':
 (u'\u9080\u8bf7\u8bed\u8a00  ', ''),
 'Courses_to_invite_to':
 (u'\u9080\u8bf7\u53c2\u4e0e\u8bfe\u7a0b  ', ''),
 'Freeze':
 (u'\u51bb\u7ed3  ', ''),
 'Remove':
 (u'\u6e05\u9664  ', ''),
 'role':
 (u'\u8eab\u4efd  ', 'label'),
 'role_staff':
 (u'\u5458\u5de5  ', 'Global role stuff'),
 'role_user':
 (u'\u6210\u5458  ', 'Global role user'),
 'role_fleadmin':
 (u'FLE \u7cfb\u7edf\u7ba1\u7406  ', 'Global role fleadmin'),
 'invite_again':
 (u'\u518d\u6b21\u9080\u8bf7  ', 'Button label'),
 'warning':
 (u'\u8b66\u544a  ', 'Heading'),
 'want_remove_users':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u4ee5\u4e0b\u6210\u5458  ?',
  'Complete question'),
 'invited_user_manage':
 (u'\u7ba1\u7406\u9080\u8bf7\u6210\u5458  ', 'Title'),
 'info_user':
 (u'\u76f8\u5173\u8d44\u6599   ',
  'Title for user info page, prefix before user name'),
 'edit_user':
 (u'\u4fee\u6539\u6210\u5458  ', 'Link'),
 'editing':
 (u'\u4fee\u6539\u8fdb\u884c\u4e2d  ',
  'Heading for user edit, inserted before user name'),
 'image_of_user':
 (u'\u6210\u5458\u56fe\u7247  ', 'Label'),
 'upload_image_of_user':
 (u'\u4e0a\u8f7d\u4f60\u7684\u56fe\u7247  ', 'Label'),
 'or_link_to_image':
 (u'\u6216\u8fde\u7ed3\u81f3\u4f60\u7684\u56fe\u7247  ',
  'Label, continuing from the upload label'),
 'webtop_bg':
 (u'\u9009\u62e9\u5de5\u4f5c\u574a\u80cc\u666f\u56fe\u6848  ', 'Label'),
 'upload_webtop_bg':
 (u'\u6216\u4e0a\u8f7d\u4f60\u7684\u80cc\u666f\u56fe\u6848  ',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 (u'\u68c0\u67e5\u9080\u8bf7\u540d\u5355  ', ''),
 'add_user':
 (u'\u52a0\u5165\u6210\u5458  ', ''),
 'Unfreeze':
 (u'\u53d6\u6d88\u51bb\u7ed3  ', ''),
 'Users':
 (u'\u6210\u5458  ', ''),
 'gsm':
 (u'\u624b\u63d0\u7535\u8bdd  ', ''),
 'last_name':
 (u'\u59d3  ', ''),
 'first_name':
 (u'\u540d  ', ''),
 'city':
 (u'\u57ce\u5e02  ', ''),
 'organization':
 (u'\u56e2\u4f53  ', ''),
 'professional_interests':
 (u'\u4e13\u4e1a\u5174\u8da3  ', ''),
 'email':
 (u'\u7535\u90ae  ', ''),
 'phone':
 (u'\u7535\u8bdd  ', ''),
 'url_to_photo':
 (u'\u56fe\u7247\u7f51\u5740  ', ''),
 'country_menu_default':
 (u'\u9009\u62e9\u56fd\u5bb6  ', ''),
 'group_menu_default':
 (u'\u9009\u62e9\u7ec4\u522b  ', 'Default value for drop-down menu'),
 'address':
 (u'\u5730\u5740  ', ''),
 'address1':
 (u'\u5730\u5740\u7b2c\u4e00\u884c  ', ''),
 'address2':
 (u'\u5730\u5740\u7b2c\u4e8c\u884c  ', ''),
 'personal_interests':
 (u'\u4e2a\u4eba\u559c\u597d  ', ''),
 'quote':
 (u'\u5f15\u8a00  ', ''),
 'homepage':
 (u'\u4e2a\u4eba\u7f51\u9875  ', ''),
 'upload':
 (u'\u4e0a\u8f7d  ', ''),
 'group':
 (u'\u7ec4\u522b  ', ''),
 'password':
 (u'\u5bc6\u7801  ', ''),
 'background':
 (u'\u80cc\u666f  ', ''),
 'country':
 (u'\u56fd\u5bb6  ', ''),
 'reserved_nickname':
 (u'\u5bf9\u4e0d\u8d77  . \u8fd9\u522b\u540d\u5df2\u88ab\u4f7f\u7528  .',
  'Message'),
 'password_mismatch':
 (u'\u63d0\u4f9b\u5bc6\u7801\u4e0d\u7b26  .', 'Message'),
 'could_not_send_invitation':
 (u'\u4e0d\u80fd\u9001\u51fa\u9080\u8bf7\u8baf\u606f  . \u8bf7\u68c0\u67e5\u4f60\u7684  MailHost\u7269\u4ef6\u662f\u5426\u8bbe\u5b9a\u59a5\u5f53  .',
  'Error message'),
 'invitations_sent':
 (u'\u5df2\u7ecf\u9001\u51fa\u9080\u8bf7  ', 'Message title'),
 'invitations_sent_to':
 (u'\u9080\u8bf7\u4f20\u9001\u81f3  %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 (u'\u9080\u8bf7\u5df2\u7ecf\u4f20\u9001\u81f3  : %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 (u'\u6210\u5458\u5df2\u7ecf\u6e05\u9664  ', 'Message title'),
 'removed_users':
 (u'\u6210\u5458\u5df2\u7ecf\u6e05\u9664  : %s',
  'Message, list inserted inside'),
 'not_removed_users':
 (u'\u4e0d\u80fd\u6e05\u9664\u8fd9\u4e9b\u6210\u5458  : %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 (u'\u5df2\u7ecf\u518d\u6b21\u9001\u51fa\u9080\u8bf7  ', 'Message title'),
 're_invitations_sent_to':
 (u'\u5df2\u7ecf\u518d\u6b21\u9080\u8bf7\u6210\u5458  %s. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 (u'\u5df2\u7ecf\u6e05\u9664\u7b49\u5019\u7528\u8005  ', 'Message title'),
 'pending_removed_users':
 (u'\u5df2\u7ecf\u6e05\u9664\u7b49\u5019\u7528\u8005  : %s',
  'Message, list inserted inside'),
 'pending_not_removed_users':
 (u'\u4e0d\u80fd\u6e05\u9664\u8fd9\u4e9b\u7b49\u5019\u7528\u8005  : %s',
  'Message, list inserted inside'),
 'invitation_subject':
 (u'\u9080\u8bf7\u6765\u4e34  FLE', 'Subject for invitation messages'),
 'invitation_header':
 (u'\u9080\u8bf7  ', 'Header for invitation messages'),
 'invitation_footer':
 (u'\u8bf7\u6d4f\u89c8  : ',
  'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 (u'\u6b22\u8fce\u6765\u4e34  fle. \u8bf7\u586b\u5199\u4ee5\u4e0b\u6210\u5458\u8d44\u6599  .',
  'Welcome message used in invitation registration form'),
 'uname':
 (u'\u767b\u5165  ', 'Label used for user login name in several places'),
 'registration_failed':
 (u'\u767b\u8bb0\u5931\u8d25  ',
  "Title used when invited user can't register."),
 'invitation_key_used':
 (u'\u8fd9\u9080\u8bf7\u7f51\u5740\u5df2\u7ecf\u88ab\u4f7f\u7528\u6216\u65e0\u6548  . \u5982\u82e5\u4f60\u4e0d\u80fd\u767b\u8bb0  , \u8bf7\u8fde\u7edc\u4f60\u7684\u8001\u5e08\u9001\u51fa\u53e6\u4e00\u4e2a\u9080\u8bf7  .',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 (u'\u8ba4\u8bc1\u94a5\u5319\u65e0\u6548  ',
  "Message telling that the authentication key isn't valid."),
 'after_submit_give_name_and_passwd2':
 (u'\u5f53\u6309\u4e0b  "\u9012\u4ea4  "\u952e\u5f8c  , \u8bf7\u586b\u5199\u4f60\u7684\u767b\u5165\u540d\u5b57\u53ca\u5bc6\u7801  .',
  'Message'),
 'frozen':
 (u'\u5df2\u51bb\u7ed3  ', 'User status code'),
 'show_frozen':
 (u'\u663e\u793a\u88ab\u51bb\u7ed3\u6210\u5458 ', 'Link to show all users'),
 'show_active':
 (u'\u53ea\u663e\u793a\u6709\u6548\u6210\u5458 ',
  'Link to show only active users'),
 'no_email':
 (u'\u6ca1\u6709\u7535\u90ae  ', 'Message title'),
 'no_email_explanation':
 (u'\u56e0\u4e3a\u4f60\u672a\u8bbe\u5b9a\u7535\u90ae\u4f4d\u5740  , \u6240\u4ee5\u4e0d\u80fd\u9001\u51fa\u7535\u90ae  .',
  'Message text'),
 'passwd_changed':
 (u'\u5b8c\u6210\u4fee\u6539\u5bc6\u7801  ', 'Message title'),
 'passwd_changed_explanation2':
 (u'\u4f60\u5df2\u6539\u53d8\u4e86\u5bc6\u7801  : \u4f60\u7684\u6d4f\u89c8\u5668\u5c06\u4f1a\u8981\u6c42\u4f60\u7684\u767b\u5165\u540d\u5b57\u53ca\u5bc6\u7801  .',
  'Message text'),
 'external_user_database_explanation':
 (u'\u4f60\u7684  Fle3\u6b63\u5728\u4f7f\u7528\u5916\u6765\u6210\u5458\u8d44\u6599\u5e93  . \u5982\u6b32\u52a0\u5165\u6210\u5458  , \u4f60\u5fc5\u987b\u5148\u5728\u4f60\u7684\u8d44\u6599\u5e93\u52a0\u5165\u8fd9\u4e9b\u6210\u5458 .',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 (u'\u8bfe\u7a0b  ', 'part of browser title'),
 'courses':
 (u'\u8bfe\u7a0b  ', 'Title'),
 'create_course':
 (u'\u52a0\u5165\u8bfe\u7a0b  ', 'Link'),
 'edit_course':
 (u'\u4fee\u6539\u8bfe\u7a0b  ', 'Button label'),
 'edit_participants':
 (u'\u4fee\u6539\u53c2\u52a0\u8005  ', 'Button label'),
 'creating_course':
 (u'\u52a0\u5165\u8bfe\u7a0b\u8fdb\u884c\u4e2d  ', 'Title'),
 'editing_course':
 (u'\u4fee\u6539\u8bfe\u7a0b\u8fdb\u884c\u4e2d  ', 'Title'),
 'course_title':
 (u'\u8bfe\u7a0b\u9898\u76ee  ', 'Label'),
 'organization':
 (u'\u7ec4\u7ec7  ', 'Label'),
 'methods':
 (u'\u65b9\u6cd5  ', 'Label'),
 'starting_date':
 (u'\u5f00\u59cb\u65e5\u671f  ', 'Label'),
 'ending_date':
 (u'\u5b8c\u6210\u65e5\u671f  ', 'Label'),
 'create_groupfolder':
 (u'\u52a0\u5165\u7ec4\u522b  ', 'Link'),
 'create_announcements':
 ('\\u52a0\\u5165\\u5e03\\u544a', 'Link'),
 'edit_announcements':
 ('\\u4fee\\u6539\\u5e03\\u544a', 'Link'),
 'add_announcement':
 ('\\u65b0\\u589e\\u5e03\\u544a', 'Link'),
 'adding_announcement':
 ('\\u65b0\\u589e\\u5e03\\u544a\\u81f3',
  'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('\\u786e\\u5b9a\\u5220\\u9664\\u5e03\\u544a\\uff1f', 'Question'),
 'editing_announcements':
 ('\\u6b63\\u5728\\u4fee\\u6539\\u5e03\\u544a', 'Heading'),
 'viewing_announcements':
 ('\\u6d4f\\u89c8\\u8bfe\\u7a0b %s \\u7684\\u5e03\\u544a',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 (u'\u6b63\u5728\u628a\u6210\u5458\u52a0\u5165\u8bfe\u7a0b\u4e2d  ',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 (u'\u5982\u82e5\u53c2\u52a0\u8005\u4e0d\u662f  Fle3\u6210\u5458  ',
  'Message'),
 'new_participants_to_system':
 (u'\u5728  Fle3\u7cfb\u7edf\u52a0\u5165\u65b0\u6210\u5458  ',
  'Part of a phrase'),
 'by_email':
 (u'\u4f7f\u7528\u7535\u90ae  ', 'Part of a phrase'),
 'manually':
 (u'\u7528\u624b\u64cd\u7eb5  ', 'Part of a phrase'),
 'fle_users':
 (u'FLE3\u6210\u5458  ', 'Heading'),
 'down':
 (u'\u4e0b  ', 'Button label'),
 'up':
 (u'\u4e0a  ', 'Button label'),
 'teachers':
 (u'\u6559\u5e08  ', 'Heading'),
 'tutors':
 (u'\u52a9\u6559  ', 'Heading'),
 'students':
 (u'\u5b66\u751f  ', 'Heading'),
 'add_button':
 (u'\u52a0\u5165   ->', 'Button label'),
 'remove_button':
 (u'<- \u6e05\u9664  ', 'Button label'),
 'viewing_course':
 (u'\u663e\u793a\u8bfe\u7a0b  ', 'Part of a phrase in location path'),
 'viewing_course_resources':
 (u'\u6d4f\u89c8\u8bfe\u7a0b %s\u6765\u6e90 ',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 (u'\u8d44\u6599  ', 'Part of a phrase in location path'),
 'no_course_selected':
 (u'\u6ca1\u6709\u9009\u53d6\u8bfe\u7a0b  !', 'Message dialog title'),
 'select_course_first':
 (u'\u8bf7\u5728\u8bfe\u7a0b\u5217\u9009\u53d6\u8bfe\u7a0b  .',
  'Message dialog message'),
 'set_published':
 (u'\u53d1\u5e03\u77e5\u8bc6\u7c7b\u578b  ', 'Message dialog title/text'),
 'users_updated':
 (u'\u5df2\u66f4\u65b0\u6210\u5458  ', 'Message dialog title/message'),
 'select_some_users':
 (u'\u8bf7\u9009\u53d6\u4f7f\u7528\u6210\u5458  ',
  'Message dialog title/message'),
 'edit_course_info':
 (u'\u4fee\u6539\u8bfe\u7a0b\u8d44\u6599  ', 'Link'),
 'edit_course_participants':
 (u'\u4fee\u6539\u8bfe\u7a0b\u53c2\u52a0\u8005  ', 'Link'),
 'edit_course_resources':
 (u'\u4fee\u6539\u8bfe\u7a0b\u6765\u6e90 ', 'Link'),
 'date':
 (u'\u65e5\u671f  ',
  'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 (u'\u8bfe\u7a0b\u53c2\u52a0\u8005  ', 'Label'),
 'type_sets':
 (u'\u77e5\u8bc6\u7c7b\u578b\u7ec4  ', 'Label, plural'),
 'delete':
 (u'\u6e05\u9664  ', 'Button label'),
 'my_participation':
 (u'\u6211\u7684\u53c2\u4e0e ', 'Label'),
 'my_notes':
 (u'\u6211\u7684\u7b14\u8bb0 ', 'Link'),
 'my_artefacts':
 (u'\u6211\u7684\u4f5c\u54c1 ', 'Link'),
 'course_resources':
 (u'\u8bfe\u7a0b\u6765\u6e90 ', 'Label'),
 'add_typeset':
 (u'\u52a0\u5165\u77e5\u8bc6\u7c7b\u578b\u7ec4  ', 'Link'),
 'tt_yellow':
 (u'\u9ec4  ', 'knowledge type colour name'),
 'tt_yellowlt':
 (u'\u6d45\u9ec4  ', 'knowledge type colour name'),
 'tt_orange':
 (u'\u6a59  ', 'knowledge type colour name'),
 'tt_orangelt':
 (u'\u6d45\u6a59  ', 'knowledge type colour name'),
 'tt_red':
 (u'\u7ea2  ', 'knowledge type colour name'),
 'tt_pink':
 (u'\u7c89\u7ea2  ', 'knowledge type colour name'),
 'tt_purple':
 (u'\u7d2b  ', 'knowledge type colour name'),
 'tt_blue':
 (u'\u7bee  ', 'knowledge type colour name'),
 'tt_bluelt':
 (u'\u6d45\u7bee  ', 'knowledge type colour name'),
 'tt_aqua':
 (u'\u6c34\u7bee  ', 'knowledge type colour name'),
 'tt_green':
 (u'\u7eff  ', 'knowledge type colour name'),
 'tt_greenlt':
 (u'\u6d45\u7eff  ', 'knowledge type colour name'),
 'tt_gray':
 (u'\u7070  ', 'knowledge type colour name'),
 'tt_white':
 (u'\u767d  ', 'knowledge type colour name'),
 'edit_typeset':
 (u'\u4fee\u6539\u77e5\u8bc6\u7c7b\u578b\u7ec4  ', 'Heading'),
 'create_typeset':
 (u'\u52a0\u5165\u77e5\u8bc6\u7c7b\u578b\u7ec4  ', 'Heading'),
 'form':
 (u'\u8868\u683c  ', 'Start of heading'),
 'title':
 (u'\u9898\u76ee  ', 'Start of label'),
 'of_typeset':
 (u'\u7684\u77e5\u8bc6\u7c7b\u578b\u7ec4  ', 'Ending of label'),
 'abbreviations_and_icons':
 (u'\u7f29\u5199\u53ca\u6807\u5fd7  ', 'Ending for heading'),
 'type':
 (u'\u77e5\u8bc6\u7c7b\u578b  ', 'Label'),
 'types':
 (u'\u77e5\u8bc6\u7c7b\u578b  ', 'Title'),
 'types_management':
 (u'\u77e5\u8bc6\u7c7b\u578b\u7ba1\u7406  ', 'Title'),
 'abbreviation':
 (u'\u7f29\u5199  ', 'Label'),
 'color':
 (u'\u989c\u8272  ', 'Label'),
 'icon':
 (u'\u6807\u5fd7  ', 'Label'),
 'starting_phrase':
 (u'\u8d77\u59cb\u9636\u6bb5  ', 'Label'),
 'checklist':
 (u'\u6e05\u5355  ', 'Label'),
 'no_types_entered':
 (u'\u4f60\u6ca1\u6709\u8f93\u5165\u77e5\u8bc6\u7c7b\u578b  . \u6bcf\u4e2a\u77e5\u8bc6\u7c7b\u578b\u7ec4\u4e5f\u8981\u52a0\u5165\u8d77\u7801\u4e00\u4e2a\u77e5\u8bc6\u7c7b\u578b  .',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 (u'\u4f7f\u7528\u9650\u5236  ', 'Heading sentence.'),
 'that_can_start_thread':
 (u'\u53ef\u4ee5\u5f00\u59cb\u8ba8\u8bba  ', 'End of label'),
 'viewing':
 (u'\u6d4f\u89c8\u4e2d  ', 'Part of location bar'),
 'new_typeset_from':
 (u'\u590d\u5236\u53ca\u4fee\u6539\u77e5\u8bc6\u7c7b\u578b\u7ec4  ',
  'Link, followed by knowledge type set name'),
 'unfinished':
 (u'\u672a\u5b8c\u6210  ', 'Label'),
 'manage_types':
 (u'\u7ba1\u7406\u77e5\u8bc6\u7c7b\u578b  ', 'Link'),
 'finalize_typeset':
 (u'\u6539\u53d8\u72b6\u6001\u53ca\u5b8c\u6210  ', 'Button label'),
 'are_you_sure':
 (u'\u4f60\u662f\u5426\u786e\u8981\u6e05\u9664\u4ee5\u4e0b\u8bfe\u7a0b  :',
  'Message dialog message'),
 'are_you_sure_ctx':
 (u'\u4f60\u662f\u5426\u786e\u5b9a\u8981\u6e05\u9664\u8fd9\u8bfe\u7a0b\u7bc7\u5e45  :',
  'Message dialog message'),
 'are_you_sure_tts':
 (u'\u4f60\u662f\u5426\u786e\u5b9a\u6e05\u9664\u4ee5\u4e0b\u77e5\u8bc6\u7c7b\u578b\u7ec4  :',
  'Message dialog message'),
 'typeset_importing':
 (u'\u8bf7\u9009\u62e9\u5c06\u4f1a\u8f93\u5165\u7684\u77e5\u8bc6\u7c7b\u578b\u538b\u7f29\u6863\u6848  .',
  'Instructions for typeset importing'),
 'typesets_imported':
 (u'\u5df2\u7ecf\u8f93\u5165\u65b0\u7684\u77e5\u8bc6\u7c7b\u578b  .',
  'Message'),
 'import_typeset':
 (u'\u8f93\u5165\u77e5\u8bc6\u7c7b\u578b\u7ec4  ', 'link'),
 'course_importing':
 (u'\u8bf7\u9009\u62e9\u5c06\u4f1a\u8f93\u5165\u7684\u77e5\u8bc6\u7c7b\u578b\u538b\u7f29\u6863\u6848  .',
  'Instructions for course importing'),
 'courses_imported':
 (u'\u5df2\u7ecf\u8f93\u5165\u65b0\u7684\u8bfe\u7a0b  .', 'Message'),
 'import_course':
 (u'\u8f93\u5165\u8bfe\u7a0b  ', 'link'),
 'course_imported':
 (u'(\u5df2\u8f93\u5165  )', 'Appended to imported course names.'),
 'can_start_thread':
 (u'\u53ef\u4ee5\u5f00\u59cb\u5206\u652f ', 'column title in a table'),
 'can_be_followed':
 (u'\u53ef\u4ee5\u8ddf\u8fdb ', 'column title in a table'),
 'use_each_type':
 (u'\u6bcf\u4e2a\u77e5\u8bc6\u7c7b\u578b\u5fc5\u987b\u8fde\u63a5\u8d77\u7801\u4e00\u4e2a\u5176\u4ed6\u7c7b\u578b\u6216\u5206\u652f .',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 (u'\u6765\u6e90 ', 'Title for list of course resources'),
 'add_resource':
 (u'\u52a0\u5165\u6765\u6e90 ', 'Link'),
 'editing_course_resources':
 (u'\u4fee\u6539\u8bfe\u7a0b\u6765\u6e90 ', 'Title'),
 'remove_resource_verify':
 (u'\u4f60\u662f\u5426\u786e\u5b9a\u6e05\u9664\u8fd9\u6765\u6e90 ?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 (u'\u52a0\u5165\u5939\u8ba1\u5c0f\u8282  ', 'link'),
 'jam_sessions':
 (u'\u5939\u8ba1\u5c0f\u8282  :',
  'a list of jam session will listed after/under this label'),
 'jam_session':
 (u'\u5939\u8ba1\u5c0f\u8282  ', ''),
 'annotations':
 (u'\u6ce8\u91ca  ', ''),
 'continue_with_version':
 (u'\u7ee7\u7eed\u4f60\u7684\u7248\u672c  ', 'button label'),
 'artefact':
 (u'\u4f5c\u54c1  ', ''),
 'viewing_annotations':
 (u'\u6d4f\u89c8\u6ce8\u91ca  ', ''),
 'Annotations':
 (u'\u6ce8\u91ca  :', 'Label, followed by a list of annotations under it'),
 'add_annotation':
 (u'\u52a0\u5165\u6ce8\u91ca  ', 'link'),
 'adding_jam_session':
 (u'\u52a0\u5165\u5939\u8ba1\u5c0f\u8282  ', ''),
 'edit_jam_session':
 (u'\u4fee\u6539\u5939\u8ba1\u5c0f\u8282  ', ''),
 'editing_jam_session':
 (u'\u4fee\u6539\u5939\u8ba1\u5c0f\u8282  ', ''),
 'title_of_jam_session':
 (u'\u5939\u8ba1\u5c0f\u8282\u6807\u9898  ', 'label'),
 'type_of_jam_session':
 (u'\u5939\u8ba1\u5c0f\u8282\u7c7b\u578b  ', 'label'),
 'mutate_on_previous':
 (u'\u7a81\u53d8\u5148\u524d\u7684  ', 'type of jam session'),
 'explore_possibilities':
 (u'\u63a2\u7d22\u53ef\u80fd\u6027  ', 'type of jam session'),
 'diverge_and_converge':
 (u'\u5206\u6b67\u53ca\u51d1\u5408  ', 'type of jam session'),
 'description_of_jam_session':
 (u'\u5939\u8ba1\u5c0f\u8282\u63cf\u8ff0  ', 'label'),
 'upload_the_starting_artefact':
 (u'\u4e0a\u8f7d\u53ca\u5f00\u59cb\u4f5c\u54c1  ', 'label'),
 'title_of_the_starting_artefact':
 (u'\u8d77\u521d\u4f5c\u54c1\u7684\u6807\u9898  ', 'label'),
 'annotation_of_the_starting_artefact':
 (u'\u8d77\u521d\u4f5c\u54c1\u7684\u6ce8\u91ca  ', 'label'),
 'adding_artefact':
 (u'\u52a0\u5165\u6ce8\u91ca  ', ''),
 'title_of_the_artefact':
 (u'\u6ce8\u91ca\u6807\u9898  ', 'label'),
 'upload_file':
 (u'\u4e0a\u8f7d\u6863\u6848  ', 'label'),
 'you_adding_annotation':
 (u'\u4f60\u5728\u52a0\u5165  arefact\u7684\u6ce8\u91ca  ',
  'message in adding annotations form'),
 'adding_annotation':
 (u'\u52a0\u5165\u6ce8\u91ca\u81f3  ', ''),
 'to_jam_session':
 (u'\u53bb\u5939\u8ba1\u5c0f\u8282  ', 'Part of a message'),
 'to_jam_artefact':
 (u'\u53bb\u5939\u8ba1\u4f5c\u54c1  ', 'Part of a message'),
 'unread_artefacts':
 (u'\u65b0\u4f5c\u54c1  ', 'There is a number before this message'),
 'total_artefacts':
 (u'\u603b\u6570  ', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u4ee5\u4e0b\u5939\u8ba1\u5c0f\u8282  :',
  'Message dialog message'),
 'are_you_sure_jam_session':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u4ee5\u4e0b\u5939\u8ba1\u5c0f\u8282\u8fde\u540c   %s \u4f5c\u54c1  ?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 (u'\u6e05\u9664\u4f5c\u54c1  ', 'Button label for removing jam artefact'),
 'restore_artefact':
 (u'\u66f4\u751f\u4f5c\u54c1  ', 'Button label for restoring jam artefact'),
 'remove_annotation':
 (u'\u6e05\u9664\u9009\u53d6\u7684\u6ce8\u91ca  ',
  'Button label for removing jam annotations'),
 'restore_annotation':
 (u'\u66f4\u751f\u9009\u53d6\u7684\u6ce8\u91ca  ',
  'Button label for restoring jam annotations'),
 'removed_name':
 (u'\u5df2\u6e05\u9664  ', 'Title/name for removed jam artefact'),
 'removed_message':
 (u'\u8fd9\u4f5c\u54c1\u5df2\u88ab  %s\u5728  %s\u6e05\u9664  .',
  "First placeholder is replaced by remover's name and the second by the date"),
 'removed_msg':
 (u'\u4f5c\u54c1\u5df2\u88ab\u6e05\u9664  ',
  'Message shown to the teacher when she has removed an artefact.'),
 'removed_annotation_msg':
 (u'\u6ce8\u91ca\u5df2\u88ab\u6e05\u9664  ',
  'Message shown to the teacher when she has removed an annotation.'),
 'remove_verify':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u8fd9\u4f5c\u54c1  ? \u4f60\u4ee5\u4e0b\u7684\u540d\u5b57\u548c\u8fd9\u65e5\u671f\u5c06\u4f1a\u88ab\u50a8\u5b58  . \u5f53\u8fd9\u4f5c\u54c1\u518d\u88ab\u6d4f\u89c8\u65f6  ,\u8fd9\u4e9b\u8d44\u6599\u5c06\u4f1a\u8fde\u540c\u6e05\u9664\u544a\u793a\u663e\u793a\u51fa\u6765  .',
  'Verification message shown when removing is attempted'),
 'remove_annotations_verify':
 (u'\u4f60\u662f\u5426\u6e05\u9664\u8fd9\u6ce8\u91ca  ? \u4f60\u4ee5\u4e0b\u7684\u540d\u5b57\u548c\u8fd9\u65e5\u671f\u5c06\u4f1a\u88ab\u50a8\u5b58  . \u5f53\u8fd9\u6ce8\u91ca\u518d\u88ab\u6d4f\u89c8\u65f6  ,\u8fd9\u4e9b\u8d44\u6599\u5c06\u4f1a\u8fde\u540c\u6e05\u9664\u544a\u793a\u663e\u793a\u51fa\u6765  .',
  'Verification message shown when removing is attempted'),
 'removed_annotation_body':
 (u'\u8fd9\u6ce8\u91ca\u5df2\u88ab  %s\u5728  %s\u6e05\u9664  .',
  "Body for removed annotation. First placeholder is replaced by remover's name and the second by the date"),
 'search_jam':
 (u'\u641c\u5bfb\u5939\u8ba1  ', 'Link label'),
 'searching_jam':
 (u'\u641c\u5bfb\u5939\u8ba1\u4f5c\u54c1  ', 'Label'),
 'search_artefact_name':
 (u'\u4f5c\u54c1\u540d\u5b57  ', 'Label in search form'),
 'search_artefact_author':
 (u'\u4f5c\u8005  ', 'Label for author of artefact in search form'),
 'search_annotation_words':
 (u'\u6ce8\u91ca\u5305\u542b\u5b57  ',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 (u'\u4f5c\u54c1\u7c7b\u578b  ',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 (u'\u56fe\u6848  ', 'Artefact type'),
 'type_audio':
 (u'\u97f3\u4e50  ', 'Artefact type'),
 'type_text':
 (u'\u6587\u5b57  ', 'Artefact type'),
 'type_html':
 (u'\u7f51\u9875  ', 'Artefact type'),
 'type_video':
 (u'\u5f71\u7247  ', 'Artefact type'),
 'type_archive':
 (u'\u6863\u6848\u5e93  ', 'Artefact type'),
 'search_annotated_by':
 (u'\u6ce8\u91ca\u8005  ', 'Label in search form'),
 'search_results_author':
 (u'\u4f5c\u8005  ', 'Heading in search results table'),
 'search_results_jam_artefact':
 (u'\u5939\u8ba1\u4f5c\u54c1  ', 'Heading in search results table'),
 'search_results_jam_session':
 (u'\u5939\u8ba1\u5c0f\u8282  ', 'Heading in search results table')}

announce = {'comments':
 ('\\u610f\\u89c1', 'Notice / form heading'),
 'no_comments':
 ('\\u6ca1\\u6709\\u610f\\u89c1\\u3002', 'Notice'),
 'recent_comments':
 ('\\u6700\\u8fd1\\u610f\\u89c1', 'Heading'),
 'no_entries':
 ('\\u6ca1\\u6709\\u9879\\u76ee', 'Notice'),
 'recent_entries':
 ('\\u6700\\u8fd1\\u9879\\u76ee', 'Heading'),
 'trackbacks':
 ('\\u5f15\\u7528\\u901a\\u544a', 'Notice'),
 'no_trackbacks':
 ('\\u6ca1\\u6709\\u5f15\\u7528\\u901a\\u544a', 'Notice'),
 'recent_trackbacks':
 ('\\u6700\\u8fd1\\u5f15\\u7528\\u901a\\u544a', 'Heading'),
 'send_trackback':
 ('\\u8bf7\\u5bc4\\u51fa\\u5f15\\u7528\\u901a\\u544a\\u81f3\\uff1a',
  'Part of message, followed by url'),
 'syndicate':
 ('\\u8054\\u5408\\u4f9b\\u7a3f\\u8fd9\\u7f51\\u5740(XML)\\u3002', 'Link'),
 'log_in':
 ('\\u767b\\u5165 Fle3\\u3002', 'Link'),
 'entries':
 ('\\u9879\\u76ee', 'Heading'),
 'category':
 ('\\u7c7b\\u522b', 'Heading'),
 'categories':
 ('\\u7c7b\\u522b', 'Heading'),
 'no_categories':
 ('\\u6ca1\\u6709\\u7c7b\\u522b', 'Notice'),
 'items':
 ('\\u9879\\u76ee', 'Part of message: nn items.'),
 'posted_by':
 ('\\u53d1\\u5e03\\u8005', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%m/%d %H:%M', 'Short date format'),
 'dateformat':
 ('%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 ('\\u5728', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('\\u8d34\\u4e0a\\u610f\\u89c1', 'Heading'),
 'name':
 ('\\u59d3\\u540d', 'Form heading'),
 'email':
 ('\\u7535\\u90ae', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('\\u9898\\u76ee', 'Form heading'),
 'body':
 ('\\u5e03\\u544a\\u4e3b\\u4f53', 'Form heading'),
 'forget_personal':
 ('\\u5fd8\\u8bb0\\u4e2a\\u4eba\\u8d44\\u6599', 'Button'),
 'remember_personal':
 ('\\u5728 cookie \\u8bb0\\u5f55\\u4e2a\\u4eba\\u8d44\\u6599?', 'Label'),
 'teachers_and_tutors_only':
 ('\\u53ea\\u9650\\u6559\\u5e08\\u53ca\\u52a9\\u6559',
  'Message, displayed in parenthesis after a link'),
 'Announcement':
 ('\\u5e03\\u544a', 'Category'),
 'ToDo':
 ('ToDo', 'Category'),
 'Event':
 ('\\u4e8b\\u4ef6', 'Category'),
 'continue_reading':
 ('\\u7ee7\\u7eed\\u9605\\u8bfb', 'Part of message, followed by entry title'),
 'missing1':
 ('\\u5df2\\u5931', 'Part of message'),
 'missingn':
 ('\\u5df2\\u5931', 'Part of message'),
 'comment_preview':
 ('\\u610f\\u89c1\\u9884\\u89c8', 'Heading'),
 'search_results':
 ('\\u641c\\u5bfb\\u7ed3\\u679c', 'Heading'),
 'search_for':
 ('\\u641c\\u5bfb\\u5e03\\u544a', 'Part of message'),
 'no_match':
 ('\\u6ca1\\u6709\\u76f8\\u5173\\u7ed3\\u679c', 'Notice'),
 'about':
 ('\\u5173\\u65bc', 'Title'),
 'archives':
 ('Archives', 'Title'),
 'search':
 ('\\u641c\\u5bfb', 'Heading'),
 'search_help':
 ('\\u60a8\\u53ef\\u4f7f\\u7528 AND/OR \\u4ee5\\u4f7f\\u7528\\u4e8c\\u5143\\u641c\\u5bfb.',
  'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

