# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_it.py,v 1.56 2005/01/15 11:07:36 tarmo Exp $
#
# Copyright 2001, 2002, 2003 by Fle3 Team and contributors
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the Italian translations for all FLE printable strings."""


common = {'language_name':
 ('Italiano', 'Name of this language'),
 'charset_encoding':
 ('iso8859-1',
  'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('Scrivania', 'Main tab for webtop'),
 'Knowledge_Building':
 ('Costruzione di Conoscenza', 'Main tab for knowledge building'),
 'Course_Management':
 ('Gestione Corsi', 'Main tab for course management'),
 'User_Management':
 ('Gestione Utenti', 'Main tab for user management'),
 'Jamming':
 ('Improvvisazione', 'Main tab for jamming'),
 'Type_Management':
 ('Gestione dei tipi degli elementi della Conoscenza', 'Heading'),
 'cancel':
 ('Annulla', 'Button label'),
 'submit':
 ('Invia', 'Button label'),
 'remove':
 ('Rimuovi', 'Button label'),
 'next':
 ('Successivo ->', 'Label for button'),
 'previous':
 ('<- Precedente', 'Label for button'),
 'quick_submit':
 ('Invio veloce', ''),
 'ok':
 ('Ok', 'Button label'),
 'save':
 ('Salva', 'Button label'),
 'create':
 ('Crea', 'Button label'),
 'search':
 ('Cerca', 'Button label'),
 'webtop':
 ('Scrivania', ''),
 'description':
 ('Descrizione', 'Label'),
 'short_date_format_display':
 ('AAAA-MM-GG', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%Y-%m-%d', 'Format string for short dates'),
 'timestamp_format':
 ('%H:%M %Y-%m-%d', 'Format string for long timestamps'),
 'invite':
 ('Invita', ''),
 'add':
 ('Aggiungi', ''),
 'today':
 ('Oggi', ''),
 'yesterday':
 ('Ieri', ''),
 'groupfolder':
 ('Cartella di Corso', 'Heading'),
 'dtml_reloaded':
 ('DTML ricaricato', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('Files DTML per questo progetto ricaricati', 'Message dialog text'),
 'dtmls_reloaded':
 ('DTMLs ricaricati', 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Tutti i files DTML sono stati ricaricati', 'Message dialog text'),
 'css_reloaded':
 ('Fogli di stile ricaricati', 'Title for message dialog'),
 'css_files_reloaded':
 ('File del Foglio di stile per questo oggetto ricaricati', 'Message text'),
 'error':
 ('Errore', ''),
 'warning':
 ('Attenzione', ''),
 'invalid_url':
 ('Url non valido', 'Message title'),
 'invalid_url_message':
 ("Sembra che l'URL che tu hai inserito non sia corretto.<br>Per favore verifica che esso cominci con http://, ftp://, mailto: o con un altro protocollo di indirizzamento Internet che vuoi utilizzare. Per favore, tieni presente che non puoi soltanto inserire gli indirizzi delle pagine web nella forma 'www.mioindirizzo.org' ma che dovresti prima specificare il protocco: 'http://www.mioindirizzo.org'. Se non sei sicuro/a del protocollo per il tuo indirizzo web, prova a copiare ed incollare l'URL completo dal tuo browser web.",
  'Message text'),
 'invalid_name':
 ('Nome non valido', 'Message title'),
 'give_valid_name':
 ('Per favore digita un nome valido', 'Message text'),
 'name_taken':
 ('Un altro elemento ha già il nome "%s". Per favore inserisci un altro nome.',
  'Message text, name inserted inside'),
 'edit':
 ('Modifica', 'Button label'),
 'you_are_in':
 ('Sei in:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ('Non hai riempito tutti i campi richiesti.', 'Erro message text'),
 'confirmation':
 ('Conferma', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Dato inserito non valido', 'Message title'),
 'invalid_fields':
 ('Per i campi seguenti hai inserito un dato non valido',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ('Prima seleziona qualche elemento', 'Message text'),
 'link_to_webtop':
 ('Crea un link sulla Scrivania', 'Link'),
 'proxy_to_webtop':
 ('Aggiungi cartella del corso alla Scrivania', 'Link'),
 'export':
 ('Esporta', 'Button label'),
 'import':
 ('Importa', 'Button label'),
 'importing':
 ('Importazione', 'Heading start'),
 'megabyte':
 ('MB', 'Abbreviation for megabyte'),
 'kilobyte':
 ('KB', 'Abbreviation for kilobyte'),
 'logout_pre3':
 ('Per uscire, chiudi semplicemente il browser.',
  'Instructions for logging out'),
 'logout':
 ('Esci', 'Link for logging out'),
 'any':
 ('Nessuno/a', 'Label'),
 'course':
 ('corso', 'Part of location path'),
 'language':
 ('Lingua', ''),
 'announcements':
 ('##Announcements', 'Link/heading'),
 'sun':
 ('##Sun', 'Weekday abbreviation'),
 'mon':
 ('##Mon', 'Weekday abbreviation'),
 'tue':
 ('##Tue', 'Weekday abbreviation'),
 'wed':
 ('##Wed', 'Weekday abbreviation'),
 'thu':
 ('##Thu', 'Weekday abbreviation'),
 'fri':
 ('##Fri', 'Weekday abbreviation'),
 'sat':
 ('##Sat', 'Weekday abbreviation'),
 'sunday':
 ('##Sunday', 'Weekday'),
 'monday':
 ('##Monday', 'Weekday'),
 'tuesday':
 ('##Tuesday', 'Weekday'),
 'wednesday':
 ('##Wednesday', 'Weekday'),
 'thursday':
 ('##Thursday', 'Weekday'),
 'friday':
 ('##Friday', 'Weekday'),
 'saturday':
 ('##Saturday', 'Weekday'),
 'January':
 ('##January', 'Month'),
 'February':
 ('##February', 'Month'),
 'March':
 ('##March', 'Month'),
 'April':
 ('##April', 'Month'),
 'May':
 ('##May', 'Month'),
 'June':
 ('##June', 'Month'),
 'July':
 ('##July', 'Month'),
 'August':
 ('##August', 'Month'),
 'September':
 ('##September', 'Month'),
 'October':
 ('##October', 'Month'),
 'November':
 ('##November', 'Month'),
 'December':
 ('##December', 'Month'),
 'remove_q':
 ('##Remove?', 'Question')}

kb = {'month':
 ('mese', ''),
 'week':
 ('settimana', ''),
 'you_have_not_replied_to':
 ('Non hai risposto a', 'followed by a list of persons'),
 'total_replies':
 ('Numero totale di risposte a note di altre persone:', 'followed by number'),
 'total_notes_written':
 ('Numero totale di note scritte:', 'followed by number'),
 'graph_type':
 ('Tipo di grafico: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('tipo di conoscenza', 'graph type'),
 'adding_resource':
 ('aggiunta di risorsa', 'part of browser title'),
 'replies':
 ('risposte', 'graph type'),
 'display_by':
 ('Visualizza da:', 'Label for timescale (week/month) selection'),
 'modifying_resource':
 ('modifica di risorsa', 'part of browser title'),
 'title_resource':
 ('Titolo', 'The title of resource'),
 'author_resource':
 ('Autore', 'The author of the resource'),
 'url':
 ('URL', 'Resource URL'),
 'location':
 ('Posizione', 'Resource location'),
 'course_info':
 ('Informazioni sul Corso', 'Label for link to course details'),
 'create_context':
 ('Crea un Nuovo Contesto di Corso', 'Link to create new course context'),
 'hide_context':
 ('Nascondi contesto', 'Link to hide a context from view'),
 'show_context':
 ('Mostra contesto', 'Link to show a hidden context'),
 'new_notes':
 ('nuove note',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('note', 'Label for showing the number of notes'),
 'full_description':
 ('descrizione completa...', ''),
 'course':
 ('corso', "String 'course' in context display"),
 'context':
 ('contesto', "String 'context' in context display"),
 'thread':
 ('thread', "String 'thread' in context display"),
 'note':
 ('nota', "String 'note' in context display"),
 'start_thread':
 ('Inizia thread', 'Link'),
 'short_description':
 ('Descrizione breve', 'Label'),
 'long_description':
 ('Descrizione lunga', 'Label'),
 'full_description':
 ('Descrizione completa', 'Label'),
 'select':
 ('Seleziona',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('tipo di conoscenza', 'Label'),
 'add_note':
 ('Aggiungi nota', 'Button label'),
 'show_notes':
 ('Mostra note', 'Heading start'),
 'show_thread':
 ('per thread', 'heading finish'),
 'show_type':
 ('per tipo di conoscenza', 'heading finish'),
 'show_author':
 ('per persona', 'heading finish'),
 'show_date':
 ('per data', 'heading finish'),
 'select_course':
 ('Seleziona corso',
  'Label, followed by a drop-down list of available courses'),
 'creating_context':
 ('Creazione di un nuovo contesto del corso in',
  'Title, followed by the course name'),
 'editing_context':
 ('Modifica del contesto del corso in', 'Title, followed by the course name'),
 'title_of_context':
 ('Titolo del contesto del corso', 'Label'),
 'type_set':
 ('Set di tipo di Conosenza', 'Label'),
 'creating_note_in':
 ('Creazione di una nuova nota in', 'Title, followed by course context name'),
 'course_context':
 ('contesto del corso', 'Label for course context'),
 'you_are_replying_to':
 ('Stai rispondendo a', 'Label'),
 'title_of_note':
 ('Titolo per la nota', 'Label'),
 'message_body':
 ('Corpo del Messaggio', 'Label'),
 'current_image':
 ('Immagine corrente', 'Label'),
 'replace_with':
 ('Sostituisci con', 'Label for image replacement in note edit'),
 'add_image':
 ('Aggiungi immagine', 'Label'),
 'title_of_image':
 ("Titolo per l'immagine", 'Label'),
 'add_link':
 ('Aggiungi link (URL)', 'Label'),
 'title_of_link':
 ('Titolo per il link', 'Label'),
 'preview':
 ('Anteprima', 'Button label'),
 'previewing_note':
 ("Visualizzazione dell'anteprima della nota in",
  'Title/heading, followed by course context name'),
 'publish':
 ('Pubblica', 'Button label'),
 'search_kb':
 ('Cerca Costruzione di Conoscenza', 'Link label'),
 'searching_kb':
 ('Cerca note di Cotruzione di Conoscenza', 'Label'),
 'search_author':
 ('Autore', 'Label'),
 'search_notes_words':
 ('Note che contengono parole', 'Label'),
 'search_context':
 ('Contesto del Corso', 'Label'),
 'search_tt':
 ('Tipi di Conoscenza', 'Label'),
 'search_note':
 ('Nota', 'Label'),
 'you_didnt_select_type':
 ('Non hai selezionato nessun tipo di conoscenza.', 'Title'),
 'current_note':
 ('Nota corrente', 'Label'),
 'go_back':
 ('Torna indietro', 'Start of message, rendered into a link'),
 'and_select_type':
 ('e seleziona il tipo di conoscenza per la tua nota.', 'Rest of message'),
 'inline_notes':
 ('Mostra il corpo del testo di tutte le note', 'Link'),
 'outline_notes':
 ('Nascondi il corpo del testo di tutte le note', 'Link'),
 'view_info':
 ('vedi informazione', 'Part of location bar'),
 'edit_context':
 ('Modifica il contesto del corso', 'Link'),
 'to_note':
 ('alla nota', 'Part of a message'),
 'full_thread_no':
 ('Mostra solo le note iniziali', 'Link'),
 'full_thread_yes':
 ("Mostra l'intero thread", 'Link'),
 'remove':
 ('Rimuovi nota', 'Button label for censoring notes'),
 'restore':
 ('Ripristina nota', 'Button label for uncensoring notes'),
 'remove_form_title':
 ('Rimozione della nota', 'Title for note censoring form'),
 'remove_form_label':
 ('Rimozione della nota',
  'Explanation in censor form, followed by note subject'),
 'removed_msg':
 ('Il messaggio è stato rimosso',
  'Message shown when teacher censores a note.'),
 'remove_explanation':
 ('Spiegazione della rimozione', 'Label for censor explanation text area'),
 'remove_verify2':
 ('Sei sicuro/a di voler rimuovere questo messggio? Il tuo nome, questa data e la spiegazione che fornisci sotto saranno memorizzate e visualizzate assieme al messaggio di rimozione da chiunque veda questa nota.',
  'Verification message shown when removing is attempted'),
 'removed_subject':
 ('Rimossa', 'Title/subject for censored notes'),
 'removed_body':
 ('Questo messaggio è stato rimosso da %s in data %s.',
  "Body for censored messages. First placeholder is replaced by censorer's name and the second by the date"),
 'notes_from_day':
 ('Note dal', 'Start of heading, followed by a date'),
 'previous':
 ('Precedente', 'Link label'),
 'next':
 ('Successivo', 'Link label'),
 'who_has_read':
 ('Chi ha letto questa nota?', 'Link label'),
 'last_read':
 ('Ultima lettura', 'Label'),
 'times_read':
 ('Numero di letture', 'Label'),
 'back':
 ('< indietro', 'Link label'),
 'unread_to_read_msg':
 ('Tutte le note in un thread marcate come lette.',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Marca tutte le note come lette', 'text in a button'),
 'creating_groupfolder':
 ('Creazione di una nuova cartella del corso in', 'Heading start'),
 'title_groupfolder':
 ('Titolo della cartella del corso', 'Label'),
 'flea_asks':
 ('Chiedi a Flea',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Cambia il Tipo di Conoscenza?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ("Questo è l'unico tipo qui consentito.",
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Cambia', 'Button label'),
 'down_to_note':
 ('Giù fino alla nota nel thread', 'Link label'),
 'use_roleplay':
 ('Usa il gioco di ruolo in questo contesto',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('Impostazione delle regole del gioco di ruolo',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 ('Corsi', "Heading for user's course list"),
 'totals_notes':
 ('Note',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ('Artefatti',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s nuovi / %s totali',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Aggiungi cartella', ''),
 'add_document':
 ('Aggiungi documento', ''),
 'add_link':
 ('Aggiungi link', ''),
 'create_memo':
 ('Crea memo', ''),
 'type':
 ('Tipo', 'Common heading for sort links by_name and by_date'),
 'title':
 ('Titolo', 'Link for sorting by name'),
 'date':
 ('Data', 'Link for sorting by date'),
 'size':
 ('Dimensione', 'Link for sorting by size'),
 'remove':
 ('Rimuovi', 'Button label'),
 'restore':
 ('Ripristina', 'Button label'),
 'rename':
 ('Rinomina', 'Button label'),
 'copy':
 ('Copia', 'Button label'),
 'cut':
 ('Taglia', 'Button label'),
 'paste':
 ('Incolla', 'Button label'),
 'delete':
 ('Cancella', 'Button label'),
 'select_all':
 ('Seleziona tutto', 'Button label'),
 'trash':
 ('Cestino', 'Label for trashcan'),
 'empty_trash':
 ('Svuota cestino', 'Button label'),
 'adding_folder':
 ('Aggiunta di una nuova cartella', 'Heading'),
 'title_of_folder':
 ('Titolo della cartella', 'Label'),
 'creating_memo':
 ('Creazione di un memo', 'Title'),
 'viewing_memo':
 ('Visualizzazione di un memo', 'Title'),
 'editing_memo':
 ('Modifica un memo', 'Title'),
 'title_of_memo':
 ('Titolo del memo', 'Label'),
 'content':
 ('Contenuto', 'Label'),
 'show_memo_contents':
 ('Mostra soltanto i contenuti dei memo', 'Link'),
 'adding_link':
 ('Aggiunta di un link', 'Title'),
 'title_of_link':
 ('Titolo del link', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Documento caricato.', 'Status message'),
 'adding_document':
 ('Aggiunta di un documento', 'Title'),
 'upload_document':
 ('Carica documento', 'Label'),
 'title_of_document':
 ('Titolo del documento', 'Label'),
 'search_wt':
 ('Ricerca Scrivanie', 'Link label'),
 'searching_wt':
 ('Ricerca Scrivanie', 'Label'),
 'search_results':
 ('Cerca risultati', 'Label'),
 'new_search':
 ('Nuova ricerca', 'Label'),
 'search_title':
 ('Titolo', 'Label'),
 'search_owner':
 ('Proprietario', 'Label'),
 'search_words':
 ('Oggetti che contengono parole', 'Label'),
 'search_object':
 ('Oggetto', 'Label'),
 'search_folder':
 ('Cartella', 'Label'),
 'viewing_search_results':
 ('visualizzazione dei risultati della ricerca', 'Label in the location path'),
 'anyone':
 ('Chiunque', 'Label'),
 'webtop_link_added':
 ('link scrivania aggiunto', 'Message title'),
 'added_webtop_link':
 ('Un link %s "%s" è stato creato sulla tua scrivania. Clicca OK per tornare alla pagina precedente.',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 ('Cartella del corso aggiunta', 'Message title'),
 'added_proxy':
 ('La cartella del corso del corso %s è ora visibile sulla tua scrivania. Clicca OK per tornare alla pagina precedente.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ('Nessun elemento scelto!', 'Message dialog title'),
 'select_item_first':
 ("Per favore scegli almeno un elemento per fare azioni diverse dall'incollare.",
  'Message dialog message'),
 'no_file_supplied':
 ('Non hai fornito nessun file.', 'Message text'),
 'renaming':
 ('Rinominazione', 'Title'),
 'invalid_names':
 ('I seguenti nomi non sono validi:', 'Message dialog messsage'),
 'same_names':
 ('Hai dato lo stesso nome per più oggetti.', 'Message dialog message'),
 'names_in_use':
 ('I seguenti nomi sono già in uso:', 'Message dialog message'),
 'information':
 ('Informazioni', 'Link'),
 'preferences':
 ('Preferenze', 'Link'),
 'editing_preferences':
 ('Modifica delle preferenze', 'Title'),
 'shared_course_folder':
 ('Cartella del corso condivisa',
  'Printed after the name of the group folder in webtop contents list.'),
 'quota_reached_title':
 ('Quota limite raggiunta', 'Title'),
 'quota_reached':
 ("L'operazione non può essere eseguita perché hai raggiunto la quota limite nella tua Scrivania. Per favore, rimuovi alcuni oggetti e riprova.",
  'Message dialog message'),
 'obj_removed':
 ("(l'oggetto a cui è collegato il link è stato rimosso)",
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('&lt; indietro', 'Link label')}

usermgmnt = {'user':
 ('utente', 'part of browser title'),
 'adding_users':
 ('Aggiunta di un nuovo utente', 'Title'),
 'required_field':
 ('Campo obbligatorio', ''),
 'nickname':
 ('Pseudonimo', ''),
 'user_account':
 ('Account utente', 'Label'),
 'Confirm':
 ('Conferma', ''),
 'you_are_removing':
 ('Stai rimuovendo', ''),
 'invite_user':
 ('Invita nuovo', ''),
 'invite_users':
 ('Invita utenti', 'Heading for invitation form'),
 'email_addresses':
 ('Indirizzi E-mail', ''),
 'separate_with_comma':
 ('( separa con: , )', ''),
 'Invitation_message':
 ("Messaggio d'invito", ''),
 'Invitation_language':
 ("Lingua d'invito", ''),
 'Courses_to_invite_to':
 ('Corsi per cui invitare a', ''),
 'Freeze':
 ('Blocca', ''),
 'Remove':
 ('Rimuovi', ''),
 'role':
 ('Ruolo', 'label'),
 'role_staff':
 ('Staff', 'Global role stuff'),
 'role_user':
 ('Utente', 'Global role user'),
 'role_fleadmin':
 ('Amministratore di FLE', 'Global role fleadmin'),
 'invite_again':
 ('Invita ancora', 'Button label'),
 'warning':
 ('Attenzione', 'Heading'),
 'want_remove_users':
 ('Vuoi rimuovere i seguenti utenti?', 'Complete question'),
 'invited_user_manage':
 ('Gestione degli utenti invitati', 'Title'),
 'info_user':
 ('Informazione su ', 'Title for user info page, prefix before usre name'),
 'edit_user':
 ('Modifica utente', 'Link'),
 'editing':
 ('Modifica di', 'Heading for user edit, inserted before user name'),
 'image_of_user':
 ("Immagine dell'utente", 'Label'),
 'upload_image_of_user':
 ("Carica un'immagine dell'utente", 'Label'),
 'or_link_to_image':
 ("o indica un link ad un'immagine",
  'Label, continuing from the upload label'),
 'webtop_bg':
 ('Immagine di sfondo della Scrivania ', 'Label'),
 'upload_webtop_bg':
 ('o carica la tua immagine di sfondo',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Mostra non registrati', ''),
 'add_user':
 ('Aggiungi nuovo', ''),
 'Unfreeze':
 ('Sblocca', ''),
 'Users':
 ('Utenti', ''),
 'gsm':
 ('Cellulare', ''),
 'last_name':
 ('Cognome', ''),
 'first_name':
 ('Nome', ''),
 'city':
 ('Città', ''),
 'organization':
 ('Organizzazione', ''),
 'professional_interests':
 ('Interessi professionali', ''),
 'email':
 ('Email', ''),
 'phone':
 ('Telefono', ''),
 'url_to_photo':
 ('URL della foto', ''),
 'country_menu_default':
 ('Seleziona Paese', ''),
 'group_menu_default':
 ('Seleziona gruppo', 'Default value for drop-down menu'),
 'address':
 ('Indirizzo', ''),
 'address1':
 ('Indirizzo 1', ''),
 'address2':
 ('Indirizzo 2', ''),
 'personal_interests':
 ('Interessi personali', ''),
 'quote':
 ('Citazione', ''),
 'homepage':
 ('Homepage', ''),
 'upload':
 ('Carica', ''),
 'group':
 ('Gruppo', ''),
 'password':
 ('Password', ''),
 'background':
 ('Sfondo', ''),
 'country':
 ('Paese', ''),
 'reserved_nickname':
 ('Spiacente. Questo pseudonimo è già in uso.', 'Message'),
 'password_mismatch':
 ('Le password indicate non corrispondono.', 'Message'),
 'could_not_send_invitation':
 ("Non posso spedire il messaggio d'invito. Per favore, verifica che l'oggetto MailHost sia configurato correttamente.",
  'Error message'),
 'invitations_sent':
 ('Inviti spediti', 'Message title'),
 'invitations_sent_to':
 ('Inviti spediti a %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 ('Gli inviti sono stati mandati a: %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Utenti rimossi', 'Message title'),
 'removed_users':
 ('Utenti rimossi: %s', 'Message, list inserted inside'),
 'not_removed_users':
 ('Impossibile rimuovere questi utenti: %s', 'Message, list inserted inside'),
 're_invitations_sent':
 ('Inviti ri-spediti', 'Message title'),
 're_invitations_sent_to':
 ('Inviti ri-spediti a %s utenti. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Utenti in sospeso rimossi', 'Message title'),
 'pending_removed_users':
 ('Utenti in sospeso rimossi: %s', 'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Impossibile rimuovere questi utenti in sospeso: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ('Invito a FLE', 'Subject for invitation messages'),
 'invitation_header':
 ('Invito', 'Header for invitation messages'),
 'invitation_footer':
 ('Per favore visita: ',
  'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Benvenuto/a in FLE. Per favore, scrivi qui sotto le tue informazioni-utente.',
  'Welcome message used in invitation registration form'),
 'uname':
 ('Nome di login', 'Label used for user login name in several places'),
 'registration_failed':
 ('Registrazione fallita', "Title used when invited user can't register."),
 'after_submit_give_name_and_passwd2':
 ('Dopo aver premuto "Invia" fornisci il tuo nome di login e la password.',
  'Message'),
 'invitation_key_used':
 ("Questo URL d'invito è già stato usato o non è più valido. Se non sei stato in grado di registrarti, per favore contatta il tuo insegnante per ottenere un altro invito.",
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ('Le chiavi di autenticazione non sono valide',
  "Message telling that the authentication key isn't valid."),
 'frozen':
 ('Bloccato', 'User status code'),
 'show_frozen':
 ('Mostra gli utenti bloccati', 'Link to show all users'),
 'show_active':
 ('Mostra soltanto gli utenti attivi', 'Link to show only active users'),
 'passwd_changed_explanation2':
 ('Hai cambiato la tua password: il browser ti chiederà un nome di login ed una password.',
  'Message text'),
 'no_email':
 ('Nessun indirizzo email', 'Message title'),
 'no_email_explanation':
 ('Non puoi spedire email perché non hai impostato il tuo indirizzo email.',
  'Message text'),
 'passwd_changed':
 ('Password modificata', 'Message title'),
 'external_user_database_explanation':
 ('La tua copia di Fle3 sta utilizzando un dabase utente esterno. Per aggiungere utenti al sistema devi aggiungerli a quel database.',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 ('corso', 'part of browser title'),
 'courses':
 ('Corsi', 'Title'),
 'create_course':
 ('Crea corso', 'Link'),
 'edit_course':
 ('Modifica corso', 'Button label'),
 'edit_participants':
 ('Modifica partecipanti', 'Button label'),
 'creating_course':
 ('Creazione di un nuovo corso', 'Title'),
 'editing_course':
 ('Modifica corso', 'Title'),
 'course_title':
 ('Titolo del corso', 'Label'),
 'organization':
 ('Organizzazione', 'Label'),
 'methods':
 ('Metodi', 'Label'),
 'starting_date':
 ('Data iniziale', 'Label'),
 'ending_date':
 ('Data finale', 'Label'),
 'create_groupfolder':
 ('Crea un gruppo di cartelle', 'Link'),
 'create_announcements':
 ('##Create announcements', 'Link'),
 'edit_announcements':
 ('##Edit announcements', 'Link'),
 'add_announcement':
 ('##Add announcement', 'Link'),
 'adding_announcement':
 ('##Adding announcement in', 'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('##Really remove this announcement?', 'Question'),
 'editing_announcements':
 ('##Editing announcements', 'Heading'),
 'viewing_announcements':
 ('##viewing announcements of course %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ('Aggiunta di nuovi utenti al corso',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('Nel caso i partecipanti al corso non siano già utenti Fle3', 'Message'),
 'new_participants_to_system':
 ('nuovi partecipanti al sistema Fle3', 'Part of a phrase'),
 'by_email':
 ('via e-mail', 'Part of a phrase'),
 'manually':
 ('manualmente', 'Part of a phrase'),
 'fle_users':
 ('Utentu FLE3', 'Heading'),
 'down':
 ('Giù', 'Button label'),
 'up':
 ('Su', 'Button label'),
 'teachers':
 ('Insegnanti', 'Heading'),
 'tutors':
 ('Tutors', 'Heading'),
 'students':
 ('Studenti', 'Heading'),
 'add_button':
 ('Aggiungi ->', 'Button label'),
 'remove_button':
 ('<- Rimuovi', 'Button label'),
 'viewing_course':
 ('visualizzazione del corso', 'Part of a phrase in location path'),
 'viewing_course_resources':
 ('visualizzazione risorse del corso %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 ('informazione', 'Part of a phrase in location path'),
 'no_course_selected':
 ('Nessun corso selezionato!', 'Message dialog title'),
 'select_course_first':
 ('Per favore scegli un corso dalla lista dei corsi.',
  'Message dialog message'),
 'set_published':
 ('Set di tipo di Conoscenza pubblicato', 'Message dialog title/text'),
 'users_updated':
 ('Utenti aggiornati', 'Message dialog title/message'),
 'select_some_users':
 ('Per favore seleziona degli utenti', 'Message dialog title/message'),
 'edit_course_info':
 ('Modifica le informazioni sul corso', 'Link'),
 'edit_course_participants':
 ('Modifica i partecipanti al corso', 'Link'),
 'edit_course_resources':
 ('Modifica risorse del corso', 'Link'),
 'date':
 ('Data', 'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('Partecipanti al corso', 'Label'),
 'type_sets':
 ('Set dei tipi di Conoscenza', 'Label, plural'),
 'delete':
 ('Elimina', 'Button label'),
 'my_participation':
 ('Le mie partecipazioni', 'Label'),
 'my_notes':
 ('Le mie note', 'Link'),
 'my_artefacts':
 ('I miei artefatti', 'Link'),
 'course_resources':
 ('Risorse del corso', 'Label'),
 'add_typeset':
 ('Aggiungi set di tipo di conoscenza', 'Link'),
 'tt_yellow':
 ('Giallo', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Giallo chiaro', 'Knowledge type colour name'),
 'tt_orange':
 ('Arancione', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Arancione chiaro', 'Knowledge type colour name'),
 'tt_red':
 ('Rosso', 'Knowledge type colour name'),
 'tt_pink':
 ('Rosa', 'Knowledge type colour name'),
 'tt_purple':
 ('Porpora', 'Knowledge type colour name'),
 'tt_blue':
 ('Blu', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Blu chiaro', 'Knowledge type colour name'),
 'tt_aqua':
 ('Acqua', 'Knowledge type colour name'),
 'tt_green':
 ('Verde', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Verde chiaro', 'Knowledge type colour name'),
 'tt_gray':
 ('Grigio', 'Knowledge type colour name'),
 'tt_white':
 ('Bianco', 'Knowledge type colour name'),
 'edit_typeset':
 ('Modifica di un set di tipo di Conoscenza', 'Heading'),
 'create_typeset':
 ('Creazione di un nuovo set di tipo di Conoscenza', 'Heading'),
 'title':
 ('Titolo', 'Start of label'),
 'form':
 ('Modulo', 'Start of heading'),
 'of_typeset':
 ('del set di tipo di conoscenza', 'Ending of label'),
 'abbreviations_and_icons':
 ('abbreviazioni e icone', 'Ending for heading'),
 'type':
 ('Tipo di Conoscenza', 'Label'),
 'types':
 ('Tipi di Conoscenza', 'Title'),
 'types_management':
 ('Gestione dei tipi di conoscenza', 'Title'),
 'abbreviation':
 ('Abbreviazione', 'Label'),
 'color':
 ('Colore', 'Label'),
 'icon':
 ('Icona', 'Label'),
 'starting_phrase':
 ('Frase di partenza', 'Label'),
 'checklist':
 ('Check list', 'Label'),
 'no_types_entered':
 ('Non hai indicato alcun tipo di conoscenza. Un set deve averne incluso almeno un tipo.',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ("Restrizioni d'uso", 'Heading sentence.'),
 'that_can_start_thread':
 ('che può cominciare una discussione', 'End of label'),
 'viewing':
 ('visualizzazione', 'Part of location bar'),
 'new_typeset_from':
 ('Duplica e modifica il set di tipo di conoscenza',
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Non terminato', 'Label'),
 'manage_types':
 ('Amministra i tipi di conoscenza', 'Link'),
 'finalize_typeset':
 ('Cambia lo stato in Terminato', 'Button label'),
 'are_you_sure':
 ('Sei sicuro/a di voler cancellare i seguenti corsi:',
  'Message dialog message'),
 'are_you_sure_ctx':
 ('Sei sicuro/a di voler cancellare questo contesto del corso:',
  'Message dialog message'),
 'are_you_sure_tts':
 ('Sei sicuro/a di voler cancellare i seguenti set di Tipi di Conoscenza:',
  'Message dialog message'),
 'typeset_importing':
 ('Per favore, seleziona il file di esportazione zippato contenente il set di tipi di conoscenza che vorresti importare.',
  'Instructions for typeset importing'),
 'typesets_imported':
 ('I nuovi set di Tipi di Conoscenza sono stati importati.', 'Message'),
 'import_typeset':
 ('Importa set di tipo di Conoscenza', 'link'),
 'course_importing':
 ('Per favore, seleziona il file di esportazione zippato contenente i corsi che vorresti importare.',
  'Instructions for course importing'),
 'courses_imported':
 ('I nuovi corsi sono stati importati.', 'Message'),
 'import_course':
 ('Importa corsi', 'link'),
 'course_imported':
 ('(importato)', 'Appended to imported course names.'),
 'can_start_thread':
 ('Posso cominciare un thread?', 'column title in a table'),
 'can_be_followed':
 ('può essere seguito da', 'column title in a table'),
 'use_each_type':
 ('Ogni tipo di conoscenza deve seguire almeno un altro tipo o deve cominciare un thread.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Risorse', 'Title for list of course resources'),
 'add_resource':
 ('Aggiungi risorsa', 'Link'),
 'editing_course_resources':
 ('Modifica risorsa del corso', 'Title'),
 'remove_resource_verify':
 ('Sei sicuro di voler rimuovere questa risorsa?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ('Aggiungi sessione di improvvisazione', 'link'),
 'jam_sessions':
 ('Sessioni di Improvvisazione:',
  'a list of jam session will listed after/under this label'),
 'jam_session':
 ('sessione di improvvisazione', ''),
 'annotations':
 ('annotazioni', ''),
 'continue_with_version':
 ('Continua con la tua versione', 'button label'),
 'artefact':
 ('artefatto', ''),
 'viewing_annotations':
 ('visualizzazione annotazioni', ''),
 'Annotations':
 ('Annotazioni:', 'Label, followed by a list of annotations under it'),
 'adding_jam_session':
 ('Aggiunta della sessione di improvvisazione', ''),
 'add_annotation':
 ('Aggiungi annotazione', 'link'),
 'edit_jam_session':
 ('Modifica sessione di improvvisazione', ''),
 'editing_jam_session':
 ('Modifica della sessione di improvvisazione', ''),
 'title_of_jam_session':
 ('Titolo della sessione di improvvisazione', 'label'),
 'type_of_jam_session':
 ('Tipo di sessione di improvvisazione', 'label'),
 'mutate_on_previous':
 ('Ripresa di una precedente', 'type of jam session'),
 'explore_possibilities':
 ('Esplora possibilità', 'type of jam session'),
 'diverge_and_converge':
 ('Divergi e Convergi', 'type of jam session'),
 'description_of_jam_session':
 ('Descrizione della sessione di improvvisazione', 'label'),
 'upload_the_starting_artefact':
 ("Carica l'artefatto iniziale", 'label'),
 'adding_artefact':
 ('Aggiunta artefatto', ''),
 'title_of_the_starting_artefact':
 ("Titolo dell'artefatto di partenza", 'label'),
 'annotation_of_the_starting_artefact':
 ("Annotazione per l'artefatto iniziale", 'label'),
 'title_of_the_artefact':
 ("Titolo dell'artefatto", 'label'),
 'upload_file':
 ('Carica file', 'label'),
 'you_adding_annotation':
 ("Stai aggiungendo una annotazione all'artefatto",
  'message in adding annotations form'),
 'adding_annotation':
 ('Aggiunta di una annotazione a', ''),
 'to_jam_session':
 ('a una sessione di improvvisazione', 'Part of a message'),
 'to_jam_artefact':
 ('a un artefatto di improvvisazione', 'Part of a message'),
 'unread_artefacts':
 ('nuovi artefatti', 'There is a number before this message'),
 'total_artefacts':
 ('artefatti in tutto', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ('Sei sicuro di voler cancellare le seguenti sessioni di improvvisazione:',
  'Message dialog message'),
 'are_you_sure_jam_session':
 ('Sei sicuro/a di voler cancellare questa sessione di improvvisazione con %s artefatti?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 ('Rimuovi artefatto', 'Button label for censoring jam artefact'),
 'restore_artefact':
 ('Ripristina artefatto', 'Button label for restoring jam artefact'),
 'remove_annotation':
 ('Rimuovi annotazioni selezionate',
  'Button label for censoring jam annotations'),
 'restore_annotation':
 ('Ripristina annotazioni selezionate',
  'Button label for uncensoring jam annotations'),
 'removed_name':
 ('Rimosso', 'Title/name for censored jam artefact'),
 'removed_message':
 ('Questo artefatto è stato rimosso da %s in data %s.',
  "First placeholder is replaced by censorer's name and the second by the date"),
 'removed_msg':
 ("L'artefatto è stato rimosso",
  'Message shown when teacher censores an artefact.'),
 'removed_annotation_msg':
 ("L'annotazione è stata rimossa",
  'Message shown when teacher censores an annotation.'),
 'remove_verify':
 ('Sei sicuro/a di voler rimuovere questo artefatto? Il tuo nome e questa data saranno memorizzati e visualizzati assieme al messaggio di spiegazione della rimozione a chiunque veda questo artefatto.',
  'Verification message shown when censoring is attempted'),
 'remove_annotations_verify':
 ('Sei sicuro/a di voler rimuovere le annotazioni che hai selezionato? Il tuo nome e la data saranno memorizzati e mostrati assieme al messaggi di rimozione a chiunque veda queste annotazioni.',
  'Verification message shown when censoring is attempted'),
 'removed_annotation_body':
 ('Questa annotazione è stata rimossa da %s in data %s.',
  "Body for censored annotation. First placeholder is replaced by censorer's name and the second by the date"),
 'search_jam':
 ('Cerca Improvvisazione', 'Link label'),
 'searching_jam':
 ('Sto cercando artefatti di improvvisazione', 'Label'),
 'search_artefact_name':
 ("Nome dell'artefatto", 'Label in search form'),
 'search_artefact_author':
 ('Autore', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Annotazioni che contengono parole',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ('Tipo di artefatto',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Immagine', 'Artefact type'),
 'type_audio':
 ('Audio', 'Artefact type'),
 'type_text':
 ('Testo', 'Artefact type'),
 'type_html':
 ('Html', 'Artefact type'),
 'type_video':
 ('Video', 'Artefact type'),
 'type_archive':
 ('Archivio', 'Artefact type'),
 'search_annotated_by':
 ('Annotato da', 'Label in search form'),
 'search_results_author':
 ('Autore', 'Heading in search results table'),
 'search_results_jam_artefact':
 ('Artefatto di Improvvisazione', 'Heading in search results table'),
 'search_results_jam_session':
 ('Sessione di Improvvisazione', 'Heading in search results table')}

announce = {'comments':
 ('##Comments', 'Notice / form heading'),
 'no_comments':
 ('##There are no comments.', 'Notice'),
 'recent_comments':
 ('##Recent comments', 'Heading'),
 'no_entries':
 ('##There are no entries.', 'Notice'),
 'recent_entries':
 ('##Recent entries', 'Heading'),
 'trackbacks':
 ('##Trackbacks', 'Notice'),
 'no_trackbacks':
 ('##There are no trackbacks.', 'Notice'),
 'recent_trackbacks':
 ('##Recent trackbacks', 'Heading'),
 'send_trackback':
 ('##Please send trackback to:', 'Part of message, followed by url'),
 'syndicate':
 ('##Syndicate this site (XML).', 'Link'),
 'log_in':
 ('##Log into Fle3.', 'Link'),
 'entries':
 ('##Entries', 'Heading'),
 'category':
 ('##Category', 'Heading'),
 'categories':
 ('##Categories', 'Heading'),
 'no_categories':
 ('##No categories', 'Notice'),
 'items':
 ('##entries', 'Part of message: nn items.'),
 'posted_by':
 ('##Posted by', 'Part of message'),
 'timeformat':
 ('##%H:%M', 'Time format'),
 'shortdateformat':
 ('##%m/%d %H:%M', 'Short date format'),
 'dateformat':
 ('##%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 ('##at', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('##Post a comment', 'Heading'),
 'name':
 ('##Name', 'Form heading'),
 'email':
 ('##Email', 'Form heading'),
 'url':
 ('##URL', 'Form heading'),
 'title':
 ('##Title', 'Form heading'),
 'body':
 ('##Body of announcement', 'Form heading'),
 'forget_personal':
 ('##Forget personal information', 'Button'),
 'teachers_and_tutors_only':
 ('##teachers and tutors only',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('##Remember your personal information in a cookie?', 'Label'),
 'Announcement':
 ('##Announcement', 'Category'),
 'ToDo':
 ('##ToDo', 'Category'),
 'Event':
 ('##Event', 'Category'),
 'continue_reading':
 ('##Continue reading', 'Part of message, followed by entry title'),
 'missing1':
 ('##is missing', 'Part of message'),
 'missingn':
 ('##are missing', 'Part of message'),
 'comment_preview':
 ('##Comment preview', 'Heading'),
 'search_results':
 ('##Search results', 'Heading'),
 'search_for':
 ('##Search announcements for', 'Part of message'),
 'no_match':
 ('##No matches found', 'Notice'),
 'about':
 ('##About', 'Title'),
 'archives':
 ('##Archives', 'Title'),
 'search':
 ('##Search', 'Heading'),
 'search_help':
 ('##You can use AND/OR for boolean search.', 'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

