# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_cs.py,v 1.3 2005/01/15 11:07:36 tarmo Exp $
#
# Copyright 2001, 2002, 2003 by Fle3 Team and contributors
#
# Questions, comments and suggestions concerning translation
# to Czech please send to jbk@bings.biz
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the english translations for all Fle3 printable strings."""

# How to do a new translation:
#
# 1. Copy this file into a new file, appending the language code after it, so
# you get something like "vocabulary_es.py" for Spanish and so on.
#
# 2. Edit the new file, translating the second portion of each line. The
# first portion is the keyword, which you shouldn't touch. The second is the
# translation that should be translated to the target language. The third
# is the supplementary instruction, that should help you do the translations.
#
# 3. Please note that the file is in Python code and needs to follow certain
# syntax rules:
#  - Strings can either be quoted by singles quotes (') or double quotes (").
#    If you need to use either of these quotation marks in your translation,
#    make sure that you use the other quotation mark to surround the string.
#    If you need to use both quotation marks in the same translation string,
#    you can surround the string with triple quotes (''' or """), which
#    allows you to use either of the quotation marks inside the string.
#  - Line breaks are not allowed inside strings, so make sure you don't
#    use an editor that wraps lines. You can have line breaks between
#    strings, though.
#
# 4. If you need to use special characters (outside of the 127 character
# ASCII range), you have several choices:
#
# A. Write in your native encoding (whatever suits you best). This requires
#    that you change the "charset_encoding" keyword in the "common" module to
#    the encoding type you will use. This document is written in iso8859-1,
#    although as english does not contain special characters, it could be
#    in utf-8 as well without any differences.
#    Most European languages are easiest to write in iso8859-1.
#
# B. Write in utf-8 encoded unicode. If your editor can save files in utf-8,
#    use that feature. If not, you can add the special characters manually
#    with the \x escape sequences. Make sure you remove the keyword
#    "charset_encoding" from the "common" module, or change its value to
#    "utf-8" so that the strings are interpreted correctly.
#    'key', ('\xe3\x82\xaa','This is the katakana letter O,encoded in utf-8.'),
#
# C. Write in unicode. Each unicode string starts with u followed by the
#    quotes. Each unicode character starts with \u followed by the code in
#    hexadecimal notation. The value of the "charset_encoding" keyword
#    is irrelevant if you use unicode all the way.
#    'key', (u'\u30aa','This is the katakana letter O, encoded in unicode.'),
#
# 5. Check your translation. If you have Python installed and you've
#    downloaded Fle3 sources, you can execute "python TranslationLint.py"
#    which will check through all the translation files and will produce
#    an error if there is a syntax error.
#    If you have installed Fle3, you can test the translation yourself
#    by going to Zope Management and selecting the Tools tab in your FLE
#    instance, and clicking on "reload_translations". After this you
#    should be able to select your translation from user preferences
#    and see the translated strings.
#

common = {'language_name':
 ('Čeština', 'Name of this language'),
 'charset_encoding':
 ('utf-8', 'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('WebTop', 'Main tab for webtop'),
 'Knowledge_Building':
 ('Budování znalostí', 'Main tab for knowledge building'),
 'Course_Management':
 ('Správa kurzů', 'Main tab for course management'),
 'User_Management':
 ('Správa uživatelů', 'Main tab for user management'),
 'Jamming':
 ('Jamming', 'Main tab for jamming'),
 'Type_Management':
 ('Správa typů znalostí', 'Heading'),
 'cancel':
 ('Storno', 'Button label'),
 'submit':
 ('Odeslat', 'Button label'),
 'remove':
 ('Odstranit', 'Button label'),
 'next':
 ('Další ->', 'Label for button'),
 'previous':
 ('<- Předchozí', 'Label for button'),
 'quick_submit':
 ('Rychlé odeslání', ''),
 'ok':
 ('OK', 'Button label'),
 'save':
 ('Uložit', 'Button label'),
 'create':
 ('Vytvořit', 'Button label'),
 'search':
 ('Hledat', 'Button label'),
 'webtop':
 ('WebTop', ''),
 'description':
 ('Popis', 'Label'),
 'short_date_format_display':
 ('DD/MM/YYYY', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%d/%m/%Y',
  'Format string for short dates. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'timestamp_format':
 ('%H:%M %d/%m/%Y',
  'Format string for long timestamps. DO NOT CHANGE THE PLACE HOLDER NAMES! You can change their order and the delimiting characters if you want.'),
 'invite':
 ('Pozvat', ''),
 'add':
 ('Přidat', ''),
 'today':
 ('Dnes', ''),
 'yesterday':
 ('Včera', ''),
 'groupfolder':
 ('Složka kurzu', 'Heading'),
 'dtml_reloaded':
 ('DTML aktualizováno', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('DTML soubory pro tento objekt byly aktualizovány',
  'Message dialog text'),
 'dtmls_reloaded':
 ('DTML aktualizovány', 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Všechny DTML soubory byly aktualizovány',
  'Message dialog text'),
 'css_reloaded':
 ('Šablony stylů aktualizovány',
  'Title for message dialog'),
 'css_files_reloaded':
 ('Šablony stylů pro tento objekt byly aktualizovány.',
  'Message text'),
 'error':
 ('Chyba', ''),
 'warning':
 ('Varování', ''),
 'invalid_url':
 ('Neplatná adresa', 'Message title'),
 'invalid_url_message':
 ('Vypadá to, že zadaná adresa je chybná.<br>Zkontrolujte prosím, že začíná http://, ftp://, mailto: nebo jiným platným internetovým protokolem. Bohužel nelze zadat adresu rovnou v podobě "www.myaddress.org", ale musí být nejprve specifikován protokol: "http://www.myaddress.org". Pokud si nejste jisti protokolem pro zadanou adresu, zkuste ji zkopírovat z prohlížeče a potom vložit.',
  'Message text'),
 'invalid_name':
 ('Neplatné jméno', 'Message title'),
 'give_valid_name':
 ('Prosím, vložte platné jméno.', 'Message text'),
 'name_taken':
 ('Jméno "%s" je již obsazené, vyberte prosím jiné.',
  'Message text, name inserted inside'),
 'edit':
 ('Upravit', 'Button label'),
 'you_are_in':
 ('Nacházíte se v:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ('Nevyplnil(a) jste všechna povinná pole.',
  'Erro message text'),
 'confirmation':
 ('Potvrzení', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Neplatný vstup', 'Message title'),
 'invalid_fields':
 ('Následující pole byla zadána špatně:',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ('Nejprve vyberte nějaké položky', 'Message text'),
 'link_to_webtop':
 ('Vytvoř odkaz na WebTopu', 'Link'),
 'proxy_to_webtop':
 ('Vytvoř odkaz na složku kurzu na WebTopu', 'Link'),
 'export':
 ('Export', 'Button label'),
 'import':
 ('Import', 'Button label'),
 'importing':
 ('Import', 'Heading start'),
 'megabyte':
 ('MB', 'Abbreviation for megabyte'),
 'kilobyte':
 ('kB', 'Abbreviation for kilobyte'),
 'logout':
 ('Odhlášení',
  'Link for logging out, also heading in logout dialogs'),
 'logout_pre3':
 ('Pro odhlášení stačí zavřít prohlížeč.',
  'Instructions for logging out'),
 'any':
 ('Jakýkoli', 'Label used in search forms'),
 'course':
 ('kurz', 'Part of location path'),
 'language':
 ('Jazyk', ''),
 'announcements':
 ('##Announcements', 'Link/heading'),
 'sun':
 ('##Sun', 'Weekday abbreviation'),
 'mon':
 ('##Mon', 'Weekday abbreviation'),
 'tue':
 ('##Tue', 'Weekday abbreviation'),
 'wed':
 ('##Wed', 'Weekday abbreviation'),
 'thu':
 ('##Thu', 'Weekday abbreviation'),
 'fri':
 ('##Fri', 'Weekday abbreviation'),
 'sat':
 ('##Sat', 'Weekday abbreviation'),
 'sunday':
 ('##Sunday', 'Weekday'),
 'monday':
 ('##Monday', 'Weekday'),
 'tuesday':
 ('##Tuesday', 'Weekday'),
 'wednesday':
 ('##Wednesday', 'Weekday'),
 'thursday':
 ('##Thursday', 'Weekday'),
 'friday':
 ('##Friday', 'Weekday'),
 'saturday':
 ('##Saturday', 'Weekday'),
 'January':
 ('##January', 'Month'),
 'February':
 ('##February', 'Month'),
 'March':
 ('##March', 'Month'),
 'April':
 ('##April', 'Month'),
 'May':
 ('##May', 'Month'),
 'June':
 ('##June', 'Month'),
 'July':
 ('##July', 'Month'),
 'August':
 ('##August', 'Month'),
 'September':
 ('##September', 'Month'),
 'October':
 ('##October', 'Month'),
 'November':
 ('##November', 'Month'),
 'December':
 ('##December', 'Month'),
 'remove_q':
 ('##Remove?', 'Question')}

kb = {'month':
 ('měsíc', ''),
 'week':
 ('týden', ''),
 'you_have_not_replied_to':
 ('Neodpověděl(a) jste', 'followed by a list of persons'),
 'total_replies':
 ('Celkový počet odpovědí na poznámky ostatních:',
  'followed by number'),
 'total_notes_written':
 ('Celkem napsáno poznámek:', 'followed by number'),
 'graph_type':
 ('Typ grafu: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('Typ znalosti', 'graph type'),
 'replies':
 ('Odpovědi', 'graph type'),
 'display_by':
 ('Zobraz podle:', 'Label for timescale (week/month) selection'),
 'adding_resource':
 ('Přidávání materiálů',
  'part of browser title'),
 'modifying_resource':
 ('Úpravy materiálů', 'part of browser title'),
 'title_resource':
 ('Název', 'The title of resource'),
 'author_resource':
 ('Autor', 'The author of the resource'),
 'url':
 ('adresa', 'Resource URL'),
 'location':
 ('Umístění', 'Resource location'),
 'course_info':
 ('Informace o kurzu', 'Label for link to course details'),
 'create_context':
 ('Vytvořit kontext kurzu', 'Link to create new course context'),
 'hide_context':
 ('Skrýt kontext', 'Link to hide a context from view'),
 'show_context':
 ('Zobrazit kontext', 'Link to show a hidden context'),
 'new_notes':
 ('nové poznámky',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('poznámky', 'Label for showing the number of notes'),
 'full_description':
 ('Úplný popis...', ''),
 'course':
 ('kurz', "String 'course' in context display"),
 'context':
 ('kontext', "String 'context' in context display"),
 'thread':
 ('vlákno', "String 'thread' in context display"),
 'note':
 ('poznámka', "String 'note' in context display"),
 'start_thread':
 ('Založit vlákno', 'Link'),
 'short_description':
 ('Krátký popis', 'Label'),
 'long_description':
 ('Delší popis', 'Label'),
 'full_description':
 ('Úplný popis', 'Label'),
 'select':
 ('Vyberte',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('typ znalosti', 'Label'),
 'add_note':
 ('Přidat poznámku', 'Button label'),
 'show_notes':
 ('Zobrazit poznámky', 'Heading start'),
 'show_thread':
 ('podle vláken', 'heading finish'),
 'show_type':
 ('podle typu znalosti', 'heading finish'),
 'show_author':
 ('podle osoby', 'heading finish'),
 'show_date':
 ('podle data', 'heading finish'),
 'select_course':
 ('Vyberte kurz', 'Label, followed by a drop-down list of available courses'),
 'change':
 ('Změnit', 'Button label'),
 'creating_context':
 ('Vytvářím kontext kurzu v',
  'Title, followed by the course name'),
 'editing_context':
 ('Upravuji kontext kurzu v', 'Title, followed by the course name'),
 'title_of_context':
 ('Nadpis kontextu kurzu', 'Label'),
 'type_set':
 ('Sada typů znalostí', 'Label'),
 'creating_note_in':
 ('Vytvářím poznámku v',
  'Title, followed by course context name'),
 'course_context':
 ('kontext kurzu', 'Label for course context'),
 'you_are_replying_to':
 ('Odpovídáte osobě', 'Label'),
 'title_of_note':
 ('Nadpis poznámky', 'Label'),
 'message_body':
 ('Tělo zprávy', 'Label'),
 'current_image':
 ('Aktuální obrázek', 'Label'),
 'replace_with':
 ('Nahradit obrázkem', 'Label for image replacement in note edit'),
 'add_image':
 ('Přidat obrázek', 'Label'),
 'title_of_image':
 ('Titulek k obrázku', 'Label'),
 'add_link':
 ('Přidat odkaz (URL)', 'Label'),
 'title_of_link':
 ('Název odkazu', 'Label'),
 'preview':
 ('Náhled', 'Button label'),
 'previewing_note':
 ('Zobrazuji náhled poznámky v',
  'Title/heading, followed by course context name'),
 'publish':
 ('Publikovat', 'Button label'),
 'search_kb':
 ('Prohledat budování znalostí', 'Link label'),
 'searching_kb':
 ('Prohledávání poznámek budování znalostí',
  'Label'),
 'search_author':
 ('Autor', 'Label'),
 'search_notes_words':
 ('Poznámky obsahující slova', 'Label'),
 'search_context':
 ('Kontext kurzu', 'Label'),
 'search_tt':
 ('Typy znalostí', 'Label'),
 'search_note':
 ('Poznámka', 'Label'),
 'current_note':
 ('Aktuální poznámka', 'Label'),
 'you_didnt_select_type':
 ('Nevybral(a) jste typ znalosti.', 'Title'),
 'go_back':
 ('Vraťte se zpět', 'Start of message, rendered into a link'),
 'and_select_type':
 ('a vyberte typ znalosti pro vaši poznámku.',
  'Rest of message'),
 'inline_notes':
 ('Zobrazit těla všech poznámek', 'Link'),
 'outline_notes':
 ('Skrýt těla všech poznámek', 'Link'),
 'view_info':
 ('zobrazení informací', 'Part of location bar'),
 'edit_context':
 ('Upravit kontext kurzu', 'Link'),
 'to_note':
 ('k poznámce', 'Part of a message'),
 'full_thread_no':
 ('Zobrazit jen úvodní poznámky', 'Link'),
 'full_thread_yes':
 ('Zobrazit celé vlákno', 'Link'),
 'remove':
 ('Odstranit poznámku', 'Button label for removing notes'),
 'restore':
 ('Obnovit poznámku', 'Button label for restoring notes'),
 'remove_form_title':
 ('Odstranění poznámky', 'Title for note removing form'),
 'remove_form_label':
 ('Odstranění poznámky',
  'Explanation in remove form, followed by note subject'),
 'removed_msg':
 ('Poznámka je odstraněna',
  'Message shown to the teacher when she has removed a note.'),
 'remove_verify2':
 ('Opravdu chcete odstranit tuto zprávu? Vaše jméno, datum a důvod odstranění budou zobrazeny každému, kdo si ji bude chtít přečíst.',
  'Verification message shown when removing is attempted'),
 'remove_explanation':
 ('Důvod odstranění',
  'Label for removee explanation text area'),
 'removed_subject':
 ('Odstraněno', 'Title/subject for removed notes'),
 'removed_body':
 ('Zprávu odstranil(a) %s %s.',
  "Body for removed messages. First placeholder is replaced by remover's name and the second by the date"),
 'notes_from_day':
 ('Poznámky od', 'Start of heading, followed by a date'),
 'previous':
 ('Předchozí', 'Link label'),
 'next':
 ('Další', 'Link label'),
 'who_has_read':
 ('Kdo četl tuto poznámku?', 'Link label'),
 'last_read':
 ('Naposledy přečteno', 'Label'),
 'times_read':
 ('-krát přečteno', 'Label'),
 'back':
 ('&lt; zpět', 'Link label'),
 'unread_to_read_msg':
 ('Všechny poznámky vlákna byly označeny za přečtené.',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Označit všechny poznámky za přečtené',
  'text in a button'),
 'creating_groupfolder':
 ('Creating course folder in', 'Heading start'),
 'title_groupfolder':
 ('Název složky kurzu', 'Label'),
 'flea_asks':
 ('Flea se ptá',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Změnit typ znalosti?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ('Toto je zde jediný povolený typ.',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Změnit', 'Button label'),
 'down_to_note':
 ('Dolů', 'Link label'),
 'use_roleplay':
 ('Používat role',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('Nastavení rolí',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 ('Kurzy', "Heading for user's course list"),
 'totals_notes':
 ('Poznámky',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ('Artefakty',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s nových / %s celkem',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Přidat složku', ''),
 'add_document':
 ('Přidat dokument', ''),
 'add_link':
 ('Přidat odkaz', ''),
 'create_memo':
 ('Přidat poznámku', ''),
 'type':
 ('Typ', 'Link for sorting by type'),
 'title':
 ('Název', 'Link for sorting by title'),
 'date':
 ('Datum', 'Link for sorting by date'),
 'size':
 ('Velikost', 'Link for sorting by size'),
 'remove':
 ('Odstranit', 'Button label'),
 'restore':
 ('Obnovit', 'Button label'),
 'rename':
 ('Přejmenovat', 'Button label'),
 'copy':
 ('Zkopírovat', 'Button label'),
 'cut':
 ('Vyjmout', 'Button label'),
 'paste':
 ('Vložit', 'Button label'),
 'delete':
 ('Smazat', 'Button label'),
 'select_all':
 ('Vybrat vše', 'Button label'),
 'trash':
 ('Koš', 'Label for trashcan'),
 'empty_trash':
 ('Vysypat koš', 'Button label'),
 'adding_folder':
 ('Přidání složky', 'Heading'),
 'title_of_folder':
 ('Název složky', 'Label'),
 'viewing_memo':
 ('Zobrazení poznámky', 'Title'),
 'creating_memo':
 ('Vytvoření poznámky', 'Title'),
 'editing_memo':
 ('Úpravy poznámky', 'Title'),
 'title_of_memo':
 ('Název poznámky', 'Label'),
 'content':
 ('Obsah', 'Label'),
 'show_memo_contents':
 ('Zobrazit pouze obsah poznámky', 'Link'),
 'adding_link':
 ('Přidání odkazu', 'Title'),
 'title_of_link':
 ('Název odkazu', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Dokument byl nahrán.', 'Status message'),
 'adding_document':
 ('Přidání dokumentu', 'Title'),
 'upload_document':
 ('Nahrát dokument', 'Label'),
 'title_of_document':
 ('Název dokumentu', 'Label'),
 'search_wt':
 ('Prohledávat WebTopy', 'Link label'),
 'searching_wt':
 ('Prohledávání WebTopů', 'Label'),
 'search_results':
 ('Výsledky hledání', 'Label'),
 'new_search':
 ('Nové hledání', 'Label'),
 'search_title':
 ('Název', 'Label'),
 'search_owner':
 ('Vlastník', 'Label'),
 'search_words':
 ('Objekty obsahující slova', 'Label'),
 'search_object':
 ('Objekt', 'Label'),
 'search_folder':
 ('Složka', 'Label'),
 'viewing_search_results':
 ('prohlížení výsledků hledání',
  'Label in the location path'),
 'anyone':
 ('Kdokoli', 'Label'),
 'webtop_link_added':
 ('Odkaz byl přidán na WebTop', 'Message title'),
 'added_webtop_link':
 ('Odkaz %s "%s" Byl vytvořen na vašem WebTopu. Stiskněte OK pro návrat na předchozí stránku.',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 ('Složka kurzu byla přidána', 'Message title'),
 'added_proxy':
 ('Složka kurzu %s je nyní k vidění na vašem WebTopu. Stiskněte OK pro návrat na předchozí stránku.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ('Nebyla vybrána žádná položka!',
  'Message dialog title'),
 'select_item_first':
 ('Pro operace jiné než "Vložit" musíte vybrat objekt(y).',
  'Message dialog message'),
 'no_file_supplied':
 ('Nedal(a) jste mi žádný soubor.', 'Message text'),
 'renaming':
 ('Přejmenování', 'Title'),
 'invalid_names':
 ('Následující jména jsou neplatná:',
  'Message dialog messsage'),
 'same_names':
 ('Vybral(a) jste stejné jméno pro více objektů.',
  'Message dialog message'),
 'names_in_use':
 ('Následující jména jsou již používána:',
  'Message dialog message'),
 'information':
 ('Informace o uživateli', 'Link'),
 'preferences':
 ('Nastavení', 'Link'),
 'editing_preferences':
 ('Úprava nastavení', 'Title'),
 'shared_course_folder':
 ('Sdílená složka kurzu',
  'Printed after the name of the group folder in webtop contents list.'),
 'quota_reached_title':
 ('Limit velikosti byl dosažen', 'Title'),
 'quota_reached':
 ('Nemohu provést operaci, protože váš WebTop je plný. Prosím odstraňte některé objekty a zkuste to znovu.',
  'Message dialog message'),
 'obj_removed':
 ('(cíl odkazu byl odstraněn)',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('&lt; zpět', 'Link label')}

usermgmnt = {'user':
 ('uživatel', 'part of browser title'),
 'adding_users':
 ('Přidání uživatele', 'Title'),
 'required_field':
 ('Povinné pole', ''),
 'nickname':
 ('Přezdívka', 'Label'),
 'user_account':
 ('Účet', 'Label'),
 'Confirm':
 ('Potvrdit', ''),
 'you_are_removing':
 ('Odebíráte uživatele', ''),
 'invite_user':
 ('Pozvat uživatele', ''),
 'invite_users':
 ('Pozvat uživatele', 'Heading for invitation form'),
 'email_addresses':
 ('E-mailové adresy', ''),
 'separate_with_comma':
 ('(oddělené čárkou)', ''),
 'Invitation_message':
 ('Pozvánka', ''),
 'Invitation_language':
 ('Jazyk pozvánky', ''),
 'Courses_to_invite_to':
 ('Pozvat do kurzů', ''),
 'Freeze':
 ('Zmrazit', ''),
 'Remove':
 ('Odstranit', ''),
 'role':
 ('Role', 'label'),
 'role_staff':
 ('Zaměstnanec', 'Global role stuff'),
 'role_user':
 ('Uživatel', 'Global role user'),
 'role_fleadmin':
 ('Administrátor FLE', 'Global role fleadmin'),
 'invite_again':
 ('Pozvat znovu', 'Button label'),
 'warning':
 ('Varování', 'Heading'),
 'want_remove_users':
 ('Opravdu chcete odstranit tyto uživatele?', 'Complete question'),
 'invited_user_manage':
 ('Správa pozvaných uživatelů', 'Title'),
 'info_user':
 ('Informace o uživateli ',
  'Title for user info page, prefix before user name'),
 'edit_user':
 ('Upravit uživatele', 'Link'),
 'editing':
 ('Upravuji uživatele',
  'Heading for user edit, inserted before user name'),
 'image_of_user':
 ('Obrázek uživatele', 'Label'),
 'upload_image_of_user':
 ('Nahrajte obrázek', 'Label'),
 'or_link_to_image':
 ('nebo vyplňte odkaz na obrázek',
  'Label, continuing from the upload label'),
 'webtop_bg':
 ('Vybrat pozadí pro WebTop', 'Label'),
 'upload_webtop_bg':
 ('nebo nahrajte vlastní pozadí',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Kontrola pozvánek', ''),
 'add_user':
 ('Přidat uživatele', ''),
 'Unfreeze':
 ('Rozmrazit', ''),
 'Users':
 ('Uživatelé', ''),
 'gsm':
 ('Mobil', ''),
 'last_name':
 ('Příjmení', ''),
 'first_name':
 ('Křestní jméno', ''),
 'city':
 ('Město', ''),
 'organization':
 ('Organizace', ''),
 'professional_interests':
 ('Profesionální zájmy', ''),
 'email':
 ('E-mail', ''),
 'phone':
 ('Telefon', ''),
 'url_to_photo':
 ('URL obrázku', ''),
 'country_menu_default':
 ('Vyberte zemi', ''),
 'group_menu_default':
 ('Vyberte skupinu', 'Default value for drop-down menu'),
 'address':
 ('Adresa', ''),
 'address1':
 ('1. řádek adresy', ''),
 'address2':
 ('2. řádek adresy', ''),
 'personal_interests':
 ('Osobní zájmy a koníčky', ''),
 'quote':
 ('Oblíbený citát', ''),
 'homepage':
 ('Domovská stránka', ''),
 'upload':
 ('Upload', ''),
 'group':
 ('Skupina', ''),
 'password':
 ('Heslo', ''),
 'background':
 ('Kdo jsem', ''),
 'country':
 ('Země', ''),
 'reserved_nickname':
 ('Je mi líto, ale přezdívka je již obsazena.',
  'Message'),
 'password_mismatch':
 ('Hesla se neshodují.', 'Message'),
 'could_not_send_invitation':
 ('Nejsem schopen odeslat pozvánku. Zkontrolujte nastavení MailHost objektu.',
  'Error message'),
 'invitations_sent':
 ('Pozvánky odeslány', 'Message title'),
 'invitations_sent_to':
 ('Pozvánky byly odeslány na adresy: %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 ('Pozvánky nebyly odeslány na adresy: %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Uživatelé odstraněni', 'Message title'),
 'removed_users':
 ('Uživatelé odstraněni: %s',
  'Message, list inserted inside'),
 'not_removed_users':
 ('Tyto uživatele se nepodařilo odstranit: %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 ('Opakované pozvánky byly odeslány', 'Message title'),
 're_invitations_sent_to':
 ('Opakované pozvánky byly odeslány %s uživatelům. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Čekající uživatelé odstraněni',
  'Message title'),
 'pending_removed_users':
 ('Čekající uživatelé odstraněni: %s',
  'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Tyto čekající uživatele se nepodařilo odstranit: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ('Pozvánka do FLE', 'Subject for invitation messages'),
 'invitation_header':
 ('Pozvánka', 'Header for invitation messages'),
 'invitation_footer':
 ('Prosím navštivte: ',
  'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Vítá Vás FLE. Vyplňte své údaje.',
  'Welcome message used in invitation registration form'),
 'uname':
 ('Přihlašovací jméno',
  'Label used for user login name in several places'),
 'registration_failed':
 ('Registrace selhala', "Title used when invited user can't register."),
 'invitation_key_used':
 ('Tato adresa již byla použita nebo zrušena. Jestliže se vám nepodařilo zaregistrovat, požádejte učitele o novou pozvánku.',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ('Autorizační údaje jsou neplatné',
  "Message telling that the authentication key isn't valid."),
 'after_submit_give_name_and_passwd2':
 ('Po stisknutí "Odeslat" Zadejte své přihlašovací jméno a heslo.',
  'Message'),
 'frozen':
 ('Zmrazený', 'User status code'),
 'show_frozen':
 ('Zobrazit zmrazené uživatele', 'Link to show all users'),
 'show_active':
 ('Zobrazit pouze aktivní uživatele',
  'Link to show only active users'),
 'no_email':
 ('E-mailová adresa neexistuje', 'Message title'),
 'no_email_explanation':
 ('Nemůžete poslat e-mail, protože nemáte nastavenou svoji adresu.',
  'Message text'),
 'passwd_changed':
 ('Heslo změněno', 'Message title'),
 'passwd_changed_explanation2':
 ('Změnil(a) jste heslo: Váš prohlížeč se vás zeptá na přihlašovací jméno a heslo.',
  'Message text'),
 'external_user_database_explanation':
 ('Váš Fle3 používá externí databázi uživatelů. Uživatele přidáte do systému tím, že je přidáte do té databáze.',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 ('kurz', 'part of browser title'),
 'courses':
 ('Kurzy', 'Title'),
 'create_course':
 ('Vytvořit kurz', 'Link'),
 'edit_course':
 ('Upravit kurz', 'Button label'),
 'edit_participants':
 ('Upravit účastníky', 'Button label'),
 'creating_course':
 ('Vytvoření kurzu', 'Title'),
 'editing_course':
 ('Úpravy kurzu', 'Title'),
 'course_title':
 ('Název kurzu', 'Label'),
 'organization':
 ('Organizace', 'Label'),
 'methods':
 ('Metody', 'Label'),
 'starting_date':
 ('Datum začátku', 'Label'),
 'ending_date':
 ('Datum ukončení', 'Label'),
 'create_groupfolder':
 ('Vytvořit složku skupiny', 'Link'),
 'create_announcements':
 ('##Create announcements', 'Link'),
 'edit_announcements':
 ('##Edit announcements', 'Link'),
 'add_announcement':
 ('##Add announcement', 'Link'),
 'adding_announcement':
 ('##Adding announcement in', 'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('##Really remove this announcement?', 'Question'),
 'editing_announcements':
 ('##Editing announcements', 'Heading'),
 'viewing_announcements':
 ('##viewing announcements of course %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ('Přidání uživatelů do kurzu',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('Pokud účastníci nejsou ještě uživateli Fle3',
  'Message'),
 'new_participants_to_system':
 ('nové účastníky Fle3 systému',
  'Part of a phrase'),
 'by_email':
 ('e-mailem', 'Part of a phrase'),
 'manually':
 ('ručně', 'Part of a phrase'),
 'fle_users':
 ('FLE3 uživatelé', 'Heading'),
 'down':
 ('Dolů', 'Button label'),
 'up':
 ('Nahoru', 'Button label'),
 'teachers':
 ('Učitelé', 'Heading'),
 'tutors':
 ('Tutoři', 'Heading'),
 'students':
 ('Studenti', 'Heading'),
 'add_button':
 ('Přidat ->', 'Button label'),
 'remove_button':
 ('<- Odstranit', 'Button label'),
 'viewing_course':
 ('prohlížení kurzu',
  'Part of a phrase in location path'),
 'viewing_course_resources':
 ('prohlížení materiálů kurzu %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 ('informace', 'Part of a phrase in location path'),
 'no_course_selected':
 ('Nebyl vybrán žádný kurz!',
  'Message dialog title'),
 'select_course_first':
 ('Prosím vyberte kurz ze seznamu.', 'Message dialog message'),
 'set_published':
 ('Sada typů znalostí byla publikována',
  'Message dialog title/text'),
 'users_updated':
 ('Uživatelé byli aktualizováni',
  'Message dialog title/message'),
 'select_some_users':
 ('Prosím vyberte nějaké uživatele',
  'Message dialog title/message'),
 'edit_course_info':
 ('Upravit informace o kurzu', 'Link'),
 'edit_course_participants':
 ('Upravit účastníky kurzu', 'Link'),
 'edit_course_resources':
 ('Upravit materiály kurzu', 'Link'),
 'date':
 ('Datum', 'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('Účastníci kurzu', 'Label'),
 'type_sets':
 ('Sady typů znalostí', 'Label, plural'),
 'delete':
 ('Smazat', 'Button label'),
 'my_participation':
 ('Moje účast', 'Label'),
 'my_notes':
 ('Moje poznámky', 'Link'),
 'my_artefacts':
 ('moje artefakty', 'Link'),
 'course_resources':
 ('Materiály kurzu', 'Label'),
 'add_typeset':
 ('Přidat sadu typů znalostí', 'Link'),
 'tt_yellow':
 ('Žlutá', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Světle žlutá', 'Knowledge type colour name'),
 'tt_orange':
 ('Oranžová', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Světle oranžová', 'Knowledge type colour name'),
 'tt_red':
 ('Červená', 'Knowledge type colour name'),
 'tt_pink':
 ('Růžová', 'Knowledge type colour name'),
 'tt_purple':
 ('Fialová', 'Knowledge type colour name'),
 'tt_blue':
 ('Modrá', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Světle modrá', 'Knowledge type colour name'),
 'tt_aqua':
 ('Voda', 'Knowledge type colour name'),
 'tt_green':
 ('Zelená', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Světle zelená', 'Knowledge type colour name'),
 'tt_gray':
 ('Šedá', 'Knowledge type colour name'),
 'tt_white':
 ('Bílá', 'Knowledge type colour name'),
 'edit_typeset':
 ('Úpravy sady typů znalostí', 'Heading'),
 'create_typeset':
 ('Vytváření sady typů znalostí',
  'Heading'),
 'form':
 ('Formulář', 'Start of heading'),
 'title':
 ('Název', 'Start of label'),
 'of_typeset':
 ('sady typů znalostí', 'Ending of label'),
 'abbreviations_and_icons':
 ('zkratky a ikony', 'Ending for heading'),
 'type':
 ('Typ znalosti', 'Label'),
 'types':
 ('Typy znalostí', 'Title'),
 'types_management':
 ('Správa typů znalostí', 'Title'),
 'abbreviation':
 ('Zkratka', 'Label'),
 'color':
 ('Barva', 'Label'),
 'icon':
 ('Ikona', 'Label'),
 'starting_phrase':
 ('Úvodní věta', 'Label'),
 'checklist':
 ('Seznam bodů', 'Label'),
 'no_types_entered':
 ('Nevložil(a) jste žádné typy znalostí. Sada musí obsahovat alespoň jeden typ.',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ('Omezení použití', 'Heading sentence.'),
 'that_can_start_thread':
 ('může začít diskusi', 'End of label'),
 'viewing':
 ('zobrazení', 'Part of location bar'),
 'new_typeset_from':
 ('Zkopírovat a upravit sadu typů znalostí',
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Neukončeno', 'Label'),
 'manage_types':
 ('Správa typů znalostí', 'Link'),
 'finalize_typeset':
 ('Změnit stav na Ukončeno', 'Button label'),
 'are_you_sure':
 ('Opravdu chcete odstranit tyto kurzy:', 'Message dialog message'),
 'are_you_sure_ctx':
 ('Opravdu chcete odstranit tento kontext:', 'Message dialog message'),
 'are_you_sure_tts':
 ('Opravdu chcete odstranit tyto sady:', 'Message dialog message'),
 'typeset_importing':
 ('Vyberte prosím ZIP archiv se sadami typů znalostí k importu.',
  'Instructions for typeset importing'),
 'typesets_imported':
 ('Nové sady typů znalostí byly importovány.',
  'Message'),
 'import_typeset':
 ('Importovat sadu typů znalostí', 'link'),
 'course_importing':
 ('Vyberte prosím ZIP archiv kurzů, které chcete importovat.',
  'Instructions for course importing'),
 'courses_imported':
 ('Nové kurzy byly importovány.', 'Message'),
 'import_course':
 ('Import kurzů', 'link'),
 'course_imported':
 ('(importováno)', 'Appended to imported course names.'),
 'can_start_thread':
 ('může založit vlákno',
  'column title in a table'),
 'can_be_followed':
 ('může být následován',
  'column title in a table'),
 'use_each_type':
 ('Každý znalostní typ musí následovat jiný nebo založit vlákno.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Materiály', 'Title for list of course resources'),
 'add_resource':
 ('Přidat materiál', 'Link'),
 'editing_course_resources':
 ('Úprava materiálů kurzu', 'Title'),
 'remove_resource_verify':
 ('Opravdu chcete odstranit tento materiál?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ('Přidat jam session', 'link'),
 'jam_sessions':
 ('Jam sessions:', 'a list of jam session will listed after/under this label'),
 'jam_session':
 ('jam session', ''),
 'annotations':
 ('anotace', ''),
 'continue_with_version':
 ('Pokračovat s vaší verzí', 'button label'),
 'artefact':
 ('artefakt', ''),
 'viewing_annotations':
 ('zobrazení anotací', ''),
 'Annotations':
 ('Anotace:', 'Label, followed by a list of annotations under it'),
 'add_annotation':
 ('Přidat anotaci', 'link'),
 'adding_jam_session':
 ('Přidávání jam session', ''),
 'edit_jam_session':
 ('Upravit jam session', ''),
 'editing_jam_session':
 ('Úpravy jam session', ''),
 'title_of_jam_session':
 ('Název jam session', 'label'),
 'type_of_jam_session':
 ('Typ jam session', 'label'),
 'mutate_on_previous':
 ('Zmutovat předchozí', 'type of jam session'),
 'explore_possibilities':
 ('Průzkum možností', 'type of jam session'),
 'diverge_and_converge':
 ('Divergovat & Konvergovat', 'type of jam session'),
 'description_of_jam_session':
 ('Popis jam session', 'label'),
 'upload_the_starting_artefact':
 ('Nahrát úvodní artefakt', 'label'),
 'title_of_the_starting_artefact':
 ('Název startovacího artefaktu', 'label'),
 'annotation_of_the_starting_artefact':
 ('Anotace pro úvodní artefakt', 'label'),
 'adding_artefact':
 ('Přidání artefaktu', ''),
 'title_of_the_artefact':
 ('Název artefaktu', 'label'),
 'upload_file':
 ('Nahrát soubor', 'label'),
 'you_adding_annotation':
 ('Přidáváte anotaci k artefaktu',
  'message in adding annotations form'),
 'adding_annotation':
 ('Přidání anotace k artefaktu', ''),
 'to_jam_session':
 ('k jam session', 'Part of a message'),
 'to_jam_artefact':
 ('k jam artefaktu', 'Part of a message'),
 'unread_artefacts':
 ('nových artefaktů', 'There is a number before this message'),
 'total_artefacts':
 ('celkem', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ('Opravdu chcete odstranit tyto jam sessions:', 'Message dialog message'),
 'are_you_sure_jam_session':
 ('Opravdu chcete odstranit tuto jam session? Počet artefaktů: %s.',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 ('Odstranit artefakt', 'Button label for removing jam artefact'),
 'restore_artefact':
 ('Obnovit artefakt', 'Button label for restoring jam artefact'),
 'remove_annotation':
 ('Odstranit vybrané anotace',
  'Button label for removing jam annotations'),
 'restore_annotation':
 ('Obnovit vybranou anotaci', 'Button label for restoring jam annotations'),
 'removed_name':
 ('Odstraněno', 'Title/name for removed jam artefact'),
 'removed_message':
 ('Tento artefakt odstranil(a) %s %s.',
  "First placeholder is replaced by remover's name and the second by the date"),
 'removed_msg':
 ('Artefakt je odstraněn',
  'Message shown to the teacher when she has removed an artefact.'),
 'removed_annotation_msg':
 ('Anotace je odstraněna',
  'Message shown to the teacher when she has removed an annotation.'),
 'remove_verify':
 ('Opravdu chcete odstranit tento artefakt? Vaše jméno a datum odstranění bude uloženo a zobrazeno s poznámkou o odstranění každému, kdo si tento artefakt bude chtít zobrazit.',
  'Verification message shown when removing is attempted'),
 'remove_annotations_verify':
 ('Opravdu chcete odstranit vybrané anotace? Vaše jméno a datum odstranění bude uloženo a zobrazeno každému, kdo si bude chtít anotace prohlédnout.',
  'Verification message shown when removing is attempted'),
 'removed_annotation_body':
 ('Tuto anotaci odstranil(a) %s %s.',
  "Body for removed annotation. First placeholder is replaced by remover's name and the second by the date"),
 'search_jam':
 ('Hledat v Jammingu', 'Link label'),
 'searching_jam':
 ('Hledání v jam artefaktech', 'Label'),
 'search_artefact_name':
 ('Jméno artefaktu', 'Label in search form'),
 'search_artefact_author':
 ('Autor', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Anotace obsahují slova',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ('Typ artefaktu',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Obrázek', 'Artefact type'),
 'type_audio':
 ('Zvuk', 'Artefact type'),
 'type_text':
 ('Text', 'Artefact type'),
 'type_html':
 ('Html', 'Artefact type'),
 'type_video':
 ('Video', 'Artefact type'),
 'type_archive':
 ('Archiv', 'Artefact type'),
 'search_annotated_by':
 ('Anotováno od', 'Label in search form'),
 'search_results_author':
 ('Autor', 'Heading in search results table'),
 'search_results_jam_artefact':
 ('Jam artefakt', 'Heading in search results table'),
 'search_results_jam_session':
 ('Jam session', 'Heading in search results table')}

announce = {'comments':
 ('##Comments', 'Notice / form heading'),
 'no_comments':
 ('##There are no comments.', 'Notice'),
 'recent_comments':
 ('##Recent comments', 'Heading'),
 'no_entries':
 ('##There are no entries.', 'Notice'),
 'recent_entries':
 ('##Recent entries', 'Heading'),
 'trackbacks':
 ('##Trackbacks', 'Notice'),
 'no_trackbacks':
 ('##There are no trackbacks.', 'Notice'),
 'recent_trackbacks':
 ('##Recent trackbacks', 'Heading'),
 'send_trackback':
 ('##Please send trackback to:', 'Part of message, followed by url'),
 'syndicate':
 ('##Syndicate this site (XML).', 'Link'),
 'log_in':
 ('##Log into Fle3.', 'Link'),
 'entries':
 ('##Entries', 'Heading'),
 'category':
 ('##Category', 'Heading'),
 'categories':
 ('##Categories', 'Heading'),
 'no_categories':
 ('##No categories', 'Notice'),
 'items':
 ('##entries', 'Part of message: nn items.'),
 'posted_by':
 ('##Posted by', 'Part of message'),
 'timeformat':
 ('##%H:%M', 'Time format'),
 'shortdateformat':
 ('##%m/%d %H:%M', 'Short date format'),
 'dateformat':
 ('##%B %d,%Y %H:%M', 'Date format'),
 'at_time':
 ('##at', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('##Post a comment', 'Heading'),
 'name':
 ('##Name', 'Form heading'),
 'email':
 ('##Email', 'Form heading'),
 'url':
 ('##URL', 'Form heading'),
 'title':
 ('##Title', 'Form heading'),
 'body':
 ('##Body of announcement', 'Form heading'),
 'forget_personal':
 ('##Forget personal information', 'Button'),
 'teachers_and_tutors_only':
 ('##teachers and tutors only',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('##Remember your personal information in a cookie?', 'Label'),
 'Announcement':
 ('##Announcement', 'Category'),
 'ToDo':
 ('##ToDo', 'Category'),
 'Event':
 ('##Event', 'Category'),
 'continue_reading':
 ('##Continue reading', 'Part of message, followed by entry title'),
 'missing1':
 ('##is missing', 'Part of message'),
 'missingn':
 ('##are missing', 'Part of message'),
 'comment_preview':
 ('##Comment preview', 'Heading'),
 'search_results':
 ('##Search results', 'Heading'),
 'search_for':
 ('##Search announcements for', 'Part of message'),
 'no_match':
 ('##No matches found', 'Notice'),
 'about':
 ('##About', 'Title'),
 'archives':
 ('##Archives', 'Title'),
 'search':
 ('##Search', 'Heading'),
 'search_help':
 ('##You can use AND/OR for boolean search.', 'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

