# Fle3 vocabulary file, generated by TranslationLint
# $Id: vocabulary_pt.py,v 1.54 2005/02/19 20:31:04 tarmo Exp $
#
# Copyright 2001, 2002, 2003 by Fle3 Team and contributors
# Translated from English by Artur Goulart <goulart@vizzavi.pt>
#
# This file is part of Fle3.
#
# Fle3 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Fle3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fle3; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

"""Contains the portuguese translations for all Fle3 printable strings."""

common = {'language_name':
 ('Português', 'Name of this language'),
 'charset_encoding':
 ('iso8859-1',
  'Encoding used in this translation (if missing, utf-8 is assumed'),
 'WebTop':
 ('WebTop', 'Main tab for webtop'),
 'Knowledge_Building':
 ('Repositório de Conhecimento', 'Main tab for knowledge building'),
 'Course_Management':
 ('Gestão de Cursos', 'Main tab for course management'),
 'User_Management':
 ('Gestão de Utilizadores', 'Main tab for user management'),
 'Jamming':
 ('Espaço Ideias', 'Main tab for jamming'),
 'Type_Management':
 ('Gestão de Tipos de Conhecimento', 'Heading'),
 'cancel':
 ('Cancelar', 'Button label'),
 'submit':
 ('Submeter', 'Button label'),
 'remove':
 ('Remover', 'Button label'),
 'next':
 ('Próximo ->', 'Label for button'),
 'previous':
 ('<- Anterior', 'Label for button'),
 'quick_submit':
 ('Submissão rápida', ''),
 'ok':
 ('Ok', 'Button label'),
 'save':
 ('Guardar', 'Button label'),
 'create':
 ('Criar', 'Button label'),
 'search':
 ('Procurar', 'Button label'),
 'webtop':
 ('Webtop', ''),
 'description':
 ('Descrição', 'Label'),
 'short_date_format_display':
 ('AAAA/MM/DD', 'String displayed as clue when entering a date'),
 'short_date_format':
 ('%Y/%m/%d', 'Format string for short dates'),
 'timestamp_format':
 ('%Y/%m/%d %H:%M', 'Format string for long timestamps'),
 'invite':
 ('Convidar', ''),
 'add':
 ('Adicionar', ''),
 'today':
 ('Hoje', ''),
 'yesterday':
 ('Ontem', ''),
 'groupfolder':
 ('Pasta de curso', 'Heading'),
 'dtml_reloaded':
 ('DTML re-carregado', 'Title for message dialog'),
 'dtml_files_reloaded':
 ('Ficheiros DTML recarregados para este objecto', 'Message dialog text'),
 'dtmls_reloaded':
 ('DTMLs re-carregados', 'Title for message dialog'),
 'dtmls_files_reloaded':
 ('Todos os ficheiros DTML re-carregados', 'Message dialog text'),
 'css_reloaded':
 ('Style sheets re-carregadas', 'Title for message dialog'),
 'css_files_reloaded':
 ('Ficheiros Style sheet re-carregados para este objecto', 'Message text'),
 'error':
 ('Erro', ''),
 'warning':
 ('Aviso', ''),
 'invalid_url':
 ('URL inválido', 'Message title'),
 'invalid_url_message':
 ('O endereço (URL) que digitou parece não ser válido.<br>Por favor verifique se começa por http://, ftp://, mailto: ou qualquer outro identificador de protocolo Internet que queira utilizar. Tenha em conta que não poderá introduzir apenas endereços de páginas na forma "www.endereco.org"; deverá especificar o identificador de protocolo antes: "http://www.endereco.org". Se não conhecer o identificador de protocolo para o endereço experimente copiar o endereço (URL) completo a partir do seu navegador (browser).',
  'Message text'),
 'invalid_name':
 ('Nome inválido', 'Message title'),
 'give_valid_name':
 ('Por favor escreva um nome válido', 'Message text'),
 'name_taken':
 ('Já exite um item denominado "%s". Por favor escreva outro nome.',
  'Message text, name inserted inside'),
 'edit':
 ('Editar', 'Button label'),
 'you_are_in':
 ('Posição actual:',
  'Heading, without trailing colon - keep in translation if needed'),
 'required_field_missing':
 ('Deve preencher os campos obrigatórios.', 'Error message text'),
 'confirmation':
 ('Confirmação', 'Title for confirmation dialogs'),
 'invalid_input':
 ('Dados incorrectos', 'Message title'),
 'invalid_fields':
 ('Os campos seguintes contêm dados incorrectos',
  'Message text followed by a list of field names'),
 'select_item_first_common':
 ('Seleccione primeiro alguns itens', 'Message text'),
 'link_to_webtop':
 ('Criar um atalho no WebTop', 'Link'),
 'proxy_to_webtop':
 ('Adicionar pasta de curso ao WebTop', 'Link'),
 'export':
 ('Exportar', 'Button label'),
 'import':
 ('Importar', 'Button label'),
 'importing':
 ('Importando', 'Heading start'),
 'megabyte':
 ('MB', 'Abbreviation for megabyte'),
 'kilobyte':
 ('KB', 'Abbreviation for kilobyte'),
 'logout_pre3':
 ('Para terminar a sessão, encerre simplesmente o navegador (browser).',
  'Instructions for logging out'),
 'logout':
 ('Terminar Sessão', 'Link for logging out'),
 'any':
 ('Qualquer', 'Label'),
 'course':
 ('curso', 'Part of location path'),
 'language':
 ('Idioma', ''),
 'announcements':
 ('Anúncios', 'Link/heading'),
 'sun':
 ('Dom', 'Weekday abbreviation'),
 'mon':
 ('Seg', 'Weekday abbreviation'),
 'tue':
 ('Ter', 'Weekday abbreviation'),
 'wed':
 ('Qua', 'Weekday abbreviation'),
 'thu':
 ('Qui', 'Weekday abbreviation'),
 'fri':
 ('Sex', 'Weekday abbreviation'),
 'sat':
 ('Sab', 'Weekday abbreviation'),
 'sunday':
 ('Domingo', 'Weekday'),
 'monday':
 ('Segunda', 'Weekday'),
 'tuesday':
 ('Terça', 'Weekday'),
 'wednesday':
 ('Quarta', 'Weekday'),
 'thursday':
 ('Quinta', 'Weekday'),
 'friday':
 ('Sexta', 'Weekday'),
 'saturday':
 ('Sábado', 'Weekday'),
 'January':
 ('Janeiro', 'Month'),
 'February':
 ('Fevereiro', 'Month'),
 'March':
 ('Março', 'Month'),
 'April':
 ('Abril', 'Month'),
 'May':
 ('Maio', 'Month'),
 'June':
 ('Junho', 'Month'),
 'July':
 ('Julho', 'Month'),
 'August':
 ('Agosto', 'Month'),
 'September':
 ('Setembro', 'Month'),
 'October':
 ('Outubro', 'Month'),
 'November':
 ('Novembro', 'Month'),
 'December':
 ('Dezembro', 'Month'),
 'remove_q':
 ('Remover?', 'Question')}

kb = {'month':
 ('mês', ''),
 'week':
 ('semana', ''),
 'you_have_not_replied_to':
 ('Não respondeu a', 'followed by a list of persons'),
 'total_replies':
 ('Número total de respostas às anotações de outros:',
  'followed by number'),
 'total_notes_written':
 ('Número total de anotações:', 'followed by number'),
 'graph_type':
 ('Tipo de gráfico: ', 'Label for graph type selection'),
 'by_knowledge_type':
 ('tipo de conhecimento', 'graph type'),
 'adding_resource':
 ('adicionando material', 'part of browser title'),
 'replies':
 ('respostas', 'graph type'),
 'display_by':
 ('Escala:', 'Label for timescale (week/month) selection'),
 'modifying_resource':
 ('modificando material', 'part of browser title'),
 'title_resource':
 ('Título', 'The title of resource'),
 'author_resource':
 ('Autor', 'The author of the resource'),
 'url':
 ('Endereço', 'Resource URL'),
 'location':
 ('Localização', 'Resource location'),
 'course_info':
 ('Informação do curso', 'Label for link to course details'),
 'create_context':
 ('Criar novo contexto de curso', 'Link to create new course context'),
 'hide_context':
 ('Ocultar contexto', 'Link to hide a context from view'),
 'show_context':
 ('Apresentar contexto', 'Link to show a hidden context'),
 'new_notes':
 ('anotações novas',
  'Label for showing the number of new notes, eg. "5 new notes"'),
 'notes_total':
 ('anotações', 'Label for showing the number of notes'),
 'full_description':
 ('descrição detalhada...', ''),
 'course':
 ('curso', "String 'course' in context display"),
 'context':
 ('contexto', "String 'context' in context display"),
 'thread':
 ('diálogo?', "String 'thread' in context display"),
 'note':
 ('anotação', "String 'note' in context display"),
 'start_thread':
 ('Iniciar diálogo', 'Link'),
 'short_description':
 ('Descrição resumida', 'Label'),
 'long_description':
 ('Descrição Longa', 'Label'),
 'full_description':
 ('Descrição detalhada', 'Label'),
 'select':
 ('Seleccionar',
  'Start of sentence, followed by a drop-down list of available knowledge types'),
 'knowledge_type':
 ('tipo de conhecimento', 'Label'),
 'add_note':
 ('Adicionar anotação', 'Button label'),
 'show_notes':
 ('Mostrar anotações', 'Heading start'),
 'show_thread':
 ('na forma de diálogo', 'heading finish'),
 'show_type':
 ('por tipo de conhecimento', 'heading finish'),
 'show_author':
 ('por pessoa', 'heading finish'),
 'show_date':
 ('por data', 'heading finish'),
 'select_course':
 ('Seleccionar curso',
  'Label, followed by a drop-down list of available courses'),
 'creating_context':
 ('Criação de novo contexto de curso em',
  'Title, followed by the course name'),
 'editing_context':
 ('Edição de novo contexto de curso em',
  'Title, followed by the course name'),
 'title_of_context':
 ('Título do contexto de curso', 'Label'),
 'type_set':
 ('Conjunto de tipos de Conhecimento', 'Label'),
 'creating_note_in':
 ('Criação de nova anotação em',
  'Title, followed by course context name'),
 'course_context':
 ('contexto de curso', 'Label for course context'),
 'you_are_replying_to':
 ('Está a responder a', 'Label'),
 'title_of_note':
 ('Título para a anotação', 'Label'),
 'message_body':
 ('Conteúdo da mensagem', 'Label'),
 'current_image':
 ('Imagem actual', 'Label'),
 'replace_with':
 ('Substituir por', 'Label for image replacement in note edit'),
 'add_image':
 ('Adicionar imagem', 'Label'),
 'title_of_image':
 ('Título para a imagem', 'Label'),
 'add_link':
 ('Adicionar atalho (URL)', 'Label'),
 'title_of_link':
 ('Título para o atalho', 'Label'),
 'preview':
 ('Pré-visualização', 'Button label'),
 'previewing_note':
 ('Pre-visualizando a anotação em',
  'Title/heading, followed by course context name'),
 'publish':
 ('Publicar', 'Button label'),
 'search_kb':
 ('Procurar Repositório de Conhecimento', 'Link label'),
 'searching_kb':
 ('Procurando anotações no Repositório de Conhecimento', 'Label'),
 'search_author':
 ('Autor', 'Label'),
 'search_notes_words':
 ('Anotações que contêm as palavras', 'Label'),
 'search_context':
 ('Contexto do curso', 'Label'),
 'search_tt':
 ('Tipos de Conhecimento', 'Label'),
 'search_note':
 ('Anotação', 'Label'),
 'you_didnt_select_type':
 ('Não seleccionou nenhum tipo de conhecimento.', 'Title'),
 'current_note':
 ('Anotação actual', 'Label'),
 'go_back':
 ('Volte atrás', 'Start of message, rendered into a link'),
 'and_select_type':
 ('e seleccione o tipo de conhecimento para a sua anotação.',
  'Rest of message'),
 'inline_notes':
 ('Apresentar conteúdos de todas as anotações', 'Link'),
 'outline_notes':
 ('Ocultar conteúdos de todas as anotações', 'Link'),
 'view_info':
 ('ver informação', 'Part of location bar'),
 'edit_context':
 ('Editar contexto do curso', 'Link'),
 'to_note':
 ('para anotação', 'Part of a message'),
 'full_thread_no':
 ('Apresentar apenas anotações iniciais', 'Link'),
 'full_thread_yes':
 ('Mostar todo o diálogo', 'Link'),
 'remove':
 ('Remover anotação', 'Button label for censoring notes'),
 'restore':
 ('Disponibilizar anotação', 'Button label for uncensoring notes'),
 'remove_form_title':
 ('Remoção de anotação', 'Title for note censoring form'),
 'remove_form_label':
 ('Removendo anotação',
  'Explanation in censor form, followed by note subject'),
 'removed_msg':
 ('Esta mensagem foi removida', 'Message shown when teacher censores a note.'),
 'remove_explanation':
 ('Razão pela qual foi removida', 'Label for censor explanation text area'),
 'remove_verify2':
 ('Tem a certeza que quer remover esta mensagem? O seu nome, a data de hoje, e a razão que especificar abaixo serão armazenados e apresentados junto com a informação de que foi removida aos leitores desta anotação.',
  'Verification message shown when removing is attempted'),
 'removed_subject':
 ('Removida', 'Title/subject for censored notes'),
 'removed_body':
 ('Esta mensagem foi removida por %s em %s.',
  "Body for censored messages. First placeholder is replaced by censorer's name and the second by the date"),
 'notes_from_day':
 ('Anotações de', 'Start of heading, followed by a date'),
 'previous':
 ('Anterior', 'Link label'),
 'next':
 ('Próximo', 'Link label'),
 'who_has_read':
 ('Quem leu esta anotação?', 'Link label'),
 'last_read':
 ('Última lida', 'Label'),
 'times_read':
 ('Número de vezes lida', 'Label'),
 'back':
 ('< atrás', 'Link label'),
 'unread_to_read_msg':
 ('Todas as anotações de um diálogo marcadas como lidas..',
  'title and message in a message dialog'),
 'mark_notes_read':
 ('Marcar todas as anotações como lidas', 'text in a button'),
 'creating_groupfolder':
 ('Criando uma nova pasta de curso em', 'Heading start'),
 'title_groupfolder':
 ('Título de pasta de curso', 'Label'),
 'flea_asks':
 ('Flea pergunta',
  'Heading displayed in the scaffolding check list. Flea is the name of the FLE-helper.'),
 'change_type':
 ('Alterar o Tipo de Conhecimento?',
  'Question at the end of the scaffolding check list.'),
 'no_change_possible':
 ('Este é o único tipo permitido aqui.',
  'Text displayed when there is only one possible follow-up type and the type cannot be changed.'),
 'change':
 ('Alterar', 'Button label'),
 'down_to_note':
 ('Aceder à anotação no diálogo', 'Link label'),
 'use_roleplay':
 ('Utilizar personificação neste contexto',
  'Label for option deciding if the course context creator wants to use roleplaying roles for postings in this context.'),
 'setup_roleplay':
 ('Definição de personagens para personificação',
  'Title for form, where roleplaying roles are set')}

webtop = {'users_courses':
 ('Cursos', "Heading for user's course list"),
 'totals_notes':
 ('Anotações',
  'Start of label for displaying the number of notes in a course; works also as a link'),
 'totals_artefacts':
 ('Artefactos',
  'Start of label for displaying the number of artefacts in a course; works also as a link'),
 'totals_body':
 ('%s novo(s) / %s total',
  'Rest of label displaying the number of notes or artefacts in a course'),
 'add_folder':
 ('Adicionar pasta', ''),
 'add_document':
 ('Adicionar documento', ''),
 'add_link':
 ('Adicionar atalho', ''),
 'create_memo':
 ('Criar memo', ''),
 'type':
 ('Tipo', 'Common heading for sort links by_name and by_date'),
 'title':
 ('Título', 'Link for sorting by name'),
 'date':
 ('Data', 'Link for sorting by date'),
 'size':
 ('Tamanho', 'Link for sorting by size'),
 'remove':
 ('Remover', 'Button label'),
 'restore':
 ('Recuperar', 'Button label'),
 'rename':
 ('Renomear', 'Button label'),
 'copy':
 ('Copiar', 'Button label'),
 'cut':
 ('Cortar', 'Button label'),
 'paste':
 ('Colar', 'Button label'),
 'delete':
 ('Apagar', 'Button label'),
 'select_all':
 ('Seleccionar todos', 'Button label'),
 'trash':
 ('Lixo', 'Label for trashcan'),
 'empty_trash':
 ('Esvaziar lixo', 'Button label'),
 'adding_folder':
 ('Adicionando uma pasta', 'Heading'),
 'title_of_folder':
 ('Título da pasta', 'Label'),
 'creating_memo':
 ('Criação de memo', 'Title'),
 'viewing_memo':
 ('Apresentação de um memo', 'Title'),
 'editing_memo':
 ('Edição de um memo', 'Title'),
 'title_of_memo':
 ('Título do memo', 'Label'),
 'content':
 ('Conteúdo', 'Label'),
 'show_memo_contents':
 ('Apresentar apenas o conteúdo do memo', 'Link'),
 'adding_link':
 ('Adição de um atalho', 'Title'),
 'title_of_link':
 ('Título do atalho', 'Label'),
 'url':
 ('URL', ''),
 'document_uploaded':
 ('Documento enviado.', 'Status message'),
 'adding_document':
 ('Adição de um documento', 'Title'),
 'upload_document':
 ('Enviar documento', 'Label'),
 'title_of_document':
 ('Título do documento', 'Label'),
 'search_wt':
 ('Procurar WebTops', 'Link label'),
 'searching_wt':
 ('Procurarando WebTops', 'Label'),
 'search_results':
 ('Resultados', 'Label'),
 'new_search':
 ('Nova procura', 'Label'),
 'search_title':
 ('Título', 'Label'),
 'search_owner':
 ('Proprietário', 'Label'),
 'search_words':
 ('Objectos que contêm as palavras', 'Label'),
 'search_object':
 ('Objecto', 'Label'),
 'search_folder':
 ('Pasta', 'Label'),
 'viewing_search_results':
 ('Apresentando resultados da procura', 'Label in the location path'),
 'anyone':
 ('Qualquer um', 'Label'),
 'webtop_link_added':
 ('Atalho adicionado ao WebTop', 'Message title'),
 'added_webtop_link':
 ('Um atalho %s "%s" foi criado no seu Webtop. Faça clique sobre OK para voltar à página anterior.',
  'Message text; "to type" and "name" inserted into placeholders (2)'),
 'proxy_added':
 ('Pasta de curso adicionado', 'Message title'),
 'added_proxy':
 ('A pasta do curso %s está agora visível no seu Webtop. Faça clique sobre OK para voltar à página anterior.',
  'Message text, course name inserted into placeholder'),
 'no_item_selected':
 ('Não há itens seleccionados!', 'Message dialog title'),
 'select_item_first':
 ('Por favor seleccione pelo menos um item para executar outras acções além de colar.',
  'Message dialog message'),
 'no_file_supplied':
 ('Nenhum ficheiro disponibilizado.', 'Message text'),
 'renaming':
 ('Renomeação', 'Title'),
 'invalid_names':
 ('Os seguintes nomes não são válidos:', 'Message dialog messsage'),
 'same_names':
 ('Atribuiu o mesmo nome a vários objectos.', 'Message dialog message'),
 'names_in_use':
 ('Os seguintes nomes estão já em uso:', 'Message dialog message'),
 'information':
 ('Informação', 'Link'),
 'preferences':
 ('Preferências', 'Link'),
 'editing_preferences':
 ('Edição de preferências', 'Title'),
 'shared_course_folder':
 ('Pasta de curso partilhada',
  'Printed after the name of the group folder in webtop contents list.'),
 'quota_reached_title':
 ('Atingido o limite da quota', 'Title'),
 'quota_reached':
 ('A operação não pode ser executada porque atingiu o limite da quota no seu WebTop. Por favor remova alguns objectos e tente de novo.',
  'Message dialog message'),
 'obj_removed':
 ('(o objecto destino deste atalho foi removido)',
  'This is appended to internal webtop links that point to objects that no longer exist.'),
 'back':
 ('&lt; atrás', 'Link label')}

usermgmnt = {'user':
 ('utilizador', 'part of browser title'),
 'adding_users':
 ('Adição de novos utilizadores', 'Title'),
 'required_field':
 ('Campo obrigatório', ''),
 'nickname':
 ('Nome pelo qual deseja dar-se a conhecer', ''),
 'user_account':
 ('Conta do utilizador', 'Label'),
 'Confirm':
 ('Confirmação', ''),
 'you_are_removing':
 ('Está a remover', ''),
 'invite_user':
 ('Convidar novo', ''),
 'invite_users':
 ('Convidar utilizadores', 'Heading for invitation form'),
 'email_addresses':
 ('Enderços de correio electrónico', ''),
 'separate_with_comma':
 ('( separados por: , )', ''),
 'Invitation_message':
 ('Conteúdo do convite', ''),
 'Invitation_language':
 ('Idioma do convite', ''),
 'Courses_to_invite_to':
 ('Convidar para os cursos', ''),
 'Freeze':
 ('Suspender', ''),
 'Remove':
 ('Remover', ''),
 'role':
 ('Função', 'label'),
 'role_staff':
 ('Administrativo', 'Global role stuff'),
 'role_user':
 ('Utilizador', 'Global role user'),
 'role_fleadmin':
 ('Administrador FLE', 'Global role fleadmin'),
 'invite_again':
 ('Convidar novamente', 'Button label'),
 'warning':
 ('Aviso', 'Heading'),
 'want_remove_users':
 ('Quer remover os seguintes utilizadores?', 'Complete question'),
 'invited_user_manage':
 ('Gestão dos utilizadores convidados', 'Title'),
 'info_user':
 ('Informação sobre ',
  'Title for user info page, prefix before usre name'),
 'edit_user':
 ('Editar utilizador', 'Link'),
 'editing':
 ('Editando', 'Heading for user edit, inserted before user name'),
 'image_of_user':
 ('Fotografia do utilizador', 'Label'),
 'upload_image_of_user':
 ('Colocar uma fotografia do utilizador', 'Label'),
 'or_link_to_image':
 ('ou forneça o endereço da fotografia',
  'Label, continuing from the upload label'),
 'webtop_bg':
 ('Imagem de fundo para o WebTop', 'Label'),
 'upload_webtop_bg':
 ('ou coloque uma imagem de fundo sua',
  'Label, continuing from the webtop_bg'),
 'show_pending_users':
 ('Apresentar não registados', ''),
 'add_user':
 ('Adicionar novo', ''),
 'Unfreeze':
 ('Activar', ''),
 'Users':
 ('Utilizadores', ''),
 'gsm':
 ('Celular', ''),
 'last_name':
 ('Último nome', ''),
 'first_name':
 ('Primeiro nome', ''),
 'city':
 ('Cidade', ''),
 'organization':
 ('Instituição', ''),
 'professional_interests':
 ('Interesses profissionais', ''),
 'email':
 ('Endereço de correio electrónico', ''),
 'phone':
 ('Telefone', ''),
 'url_to_photo':
 ('URL da fotografia', ''),
 'country_menu_default':
 ('Seleccione País', ''),
 'group_menu_default':
 ('Seleccione grupo', 'Default value for drop-down menu'),
 'address':
 ('Endereço postal', ''),
 'address1':
 ('Endereço linha 1', ''),
 'address2':
 ('Endereço linha 2', ''),
 'personal_interests':
 ('Interesses pessoais', ''),
 'quote':
 ('Comentário', ''),
 'homepage':
 ('Página Pessoal', ''),
 'upload':
 ('Envio', ''),
 'group':
 ('Grupo', ''),
 'password':
 ('Password', ''),
 'background':
 ('Imagem de fundo', ''),
 'country':
 ('País', ''),
 'reserved_nickname':
 ('Lamentavelmente o nome que escreveu já foi registado.', 'Message'),
 'password_mismatch':
 ("Supplied passwords don't match.", 'Message'),
 'could_not_send_invitation':
 ('Não foi possível enviar o convite. Por favor verifique que a configuração de servidor de correio está correcta.',
  'Error message'),
 'invitations_sent':
 ('Os convites foram enviados', 'Message title'),
 'invitations_sent_to':
 ('Convite(s) enviado(s) para %s. ',
  'Message, email list is inserted into the placeholder.'),
 'invitations_not_sent_to':
 ('Foram enviados convites para: %s.',
  'Message, email list is inserted into the placeholder.'),
 'users_removed':
 ('Utilizadores removidos', 'Message title'),
 'removed_users':
 ('Utilizadore(s) removido(s): %s', 'Message, list inserted inside'),
 'not_removed_users':
 ('Não foi possível remover este(s) utilizadore(s): %s',
  'Message, list inserted inside'),
 're_invitations_sent':
 ('Convites reenviados', 'Message title'),
 're_invitations_sent_to':
 ('Convites reenviados para os utilizadores %s. ',
  'Message, email count is inserted into the placeholder.'),
 'pending_users_removed':
 ('Utilizadores pendentes removidos', 'Message title'),
 'pending_removed_users':
 ('Utilizadores pendentes removidos: %s', 'Message, list inserted inside'),
 'pending_not_removed_users':
 ('Não foi possível remover os utilizadores pendentes: %s',
  'Message, list inserted inside'),
 'invitation_subject':
 ('Convidado a participar no FLE', 'Subject for invitation messages'),
 'invitation_header':
 ('Convite', 'Header for invitation messages'),
 'invitation_footer':
 ('Por favor visite: ', 'Footer for invitation messages; followed by the URL'),
 'welcome_message':
 ('Benvindo ao FLE. Por favor preencha a sua informação pessoal de utilizador em baixo.',
  'Welcome message used in invitation registration form'),
 'uname':
 ('Nome de utilizador', 'Label used for user login name in several places'),
 'registration_failed':
 ('O registo falhou', "Title used when invited user can't register."),
 'after_submit_give_name_and_passwd2':
 ('Depois de fazer clique sobre "Submeter" escreva o seu nome de utilizador e password.',
  'Message'),
 'invitation_key_used':
 ('O URL deste convite já foi accionado, ou já não é válido. Se não lhe foi possível proceder ao registo, por favor contacte o seu professor para que ele lhe envie outro convite.',
  'Message telling that the registration url has been used.'),
 'authorization_failed':
 ('A chave de autenticação não é válida',
  "Message telling that the authentication key isn't valid."),
 'frozen':
 ('Suspenso', 'User status code'),
 'show_frozen':
 ('Mostrar utilizadores suspensos', 'Link to show all users'),
 'show_active':
 ('Mostrar apenas utilizadores activos', 'Link to show only active users'),
 'passwd_changed_explanation2':
 ('Alterou a sua password: o seu navegador (browser) pedir-lhe-á o nome de utilizador e a password.',
  'Message text'),
 'no_email':
 ('Sem endereço de correio', 'Message title'),
 'no_email_explanation':
 ('Não pode enviar correio porque não especificou o seu endereço de correio electrónico.',
  'Message text'),
 'passwd_changed':
 ('Password alterada', 'Message title'),
 'external_user_database_explanation':
 ('A sua instalação Fle3 está a utilizar uma base de dados externa. Para adicionar utilizadores ao sistema terá de adicioná-los áquela base de dados.',
  'Explanation shown in place of "add users", "invite user" etc. links.')}

coursemgmnt = {'course':
 ('curso', 'part of browser title'),
 'courses':
 ('Cursos', 'Title'),
 'create_course':
 ('Criar curso', 'Link'),
 'edit_course':
 ('Editar curso', 'Button label'),
 'edit_participants':
 ('Editar participantes', 'Button label'),
 'creating_course':
 ('Criação de novo curso', 'Title'),
 'editing_course':
 ('Edição de curso', 'Title'),
 'course_title':
 ('Título do curso', 'Label'),
 'organization':
 ('Organização', 'Label'),
 'methods':
 ('Métodos', 'Label'),
 'starting_date':
 ('Data do início', 'Label'),
 'ending_date':
 ('Data do termo', 'Label'),
 'create_groupfolder':
 ('Criar pasta de grupo', 'Link'),
 'create_announcements':
 ('Criar anúncios', 'Link'),
 'edit_announcements':
 ('Editar anúncios', 'Link'),
 'add_announcement':
 ('Adicionar anúncio', 'Link'),
 'adding_announcement':
 ('Adicionando anúncio em', 'Part of message, followed by course name'),
 'remove_announcement_verify':
 ('Deseja remover este anúncio?', 'Question'),
 'editing_announcements':
 ('Editando anúncios', 'Heading'),
 'viewing_announcements':
 ('visualizando anúncios do curso %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'adding_users_to_course':
 ('Adição de novos utilizadores ao curso',
  'Title, name of course is displayed after this'),
 'if_participants_not_users':
 ('No caso de os participantes no curso não serem ainda utilizadores Fle3',
  'Message'),
 'new_participants_to_system':
 ('novos participantes no sistema Fle3', 'Part of a phrase'),
 'by_email':
 ('por correio electrónico', 'Part of a phrase'),
 'manually':
 ('manualmente', 'Part of a phrase'),
 'fle_users':
 ('Utilizadores FLE3', 'Heading'),
 'down':
 ('Para baixo', 'Button label'),
 'up':
 ('Para cima', 'Button label'),
 'teachers':
 ('Professores', 'Heading'),
 'tutors':
 ('Tutores', 'Heading'),
 'students':
 ('Estudantes', 'Heading'),
 'add_button':
 ('Adicionar ->', 'Button label'),
 'remove_button':
 ('<- Remover', 'Button label'),
 'viewing_course':
 ('visualizando curso', 'Part of a phrase in location path'),
 'viewing_course_resources':
 ('visualizando materiais do curso %s',
  'Part of a phrase in location path, PLACEHOLDER replaced with course name.'),
 'information':
 ('informação', 'Part of a phrase in location path'),
 'no_course_selected':
 ('Nenhum curso seleccionado!', 'Message dialog title'),
 'select_course_first':
 ('Por favor seleccione um curso da llista de cursos.',
  'Message dialog message'),
 'set_published':
 ('Publicado o conjunto de tipos de conhecimento',
  'Message dialog title/text'),
 'users_updated':
 ('Utilizadores actualizados', 'Message dialog title/message'),
 'select_some_users':
 ('Por favor seleccione alguns utilizadores', 'Message dialog title/message'),
 'edit_course_info':
 ('Editar informação do curso', 'Link'),
 'edit_course_participants':
 ('Editar participantes do curso', 'Link'),
 'edit_course_resources':
 ('Editando materiais do curso', 'Link'),
 'date':
 ('Data', 'Label, followed by the starting and ending date of the course.'),
 'course_participants':
 ('Participantes no curso', 'Label'),
 'type_sets':
 ('Conjuntos de tipos de conhecimento', 'Label, plural'),
 'delete':
 ('Apagar', 'Button label'),
 'my_participation':
 ('A minha participação', 'Label'),
 'my_notes':
 ('As minhas anotações', 'Link'),
 'my_artefacts':
 ('os meus artefactos', 'Link'),
 'course_resources':
 ('Materiais do curso', 'Label'),
 'add_typeset':
 ('Adicionar conjunto de tipos de conhecimento', 'Link'),
 'tt_yellow':
 ('Amarelo', 'Knowledge type colour name'),
 'tt_yellowlt':
 ('Amarelo claro', 'Knowledge type colour name'),
 'tt_orange':
 ('Laranja', 'Knowledge type colour name'),
 'tt_orangelt':
 ('Laranja claro', 'Knowledge type colour name'),
 'tt_red':
 ('Encarnado', 'Knowledge type colour name'),
 'tt_pink':
 ('Rosa', 'Knowledge type colour name'),
 'tt_purple':
 ('Violeta', 'Knowledge type colour name'),
 'tt_blue':
 ('Azul', 'Knowledge type colour name'),
 'tt_bluelt':
 ('Azul claro', 'Knowledge type colour name'),
 'tt_aqua':
 ('Azul céu', 'Knowledge type colour name'),
 'tt_green':
 ('Verde', 'Knowledge type colour name'),
 'tt_greenlt':
 ('Verde claro', 'Knowledge type colour name'),
 'tt_gray':
 ('Cinza', 'Knowledge type colour name'),
 'tt_white':
 ('Branco', 'Knowledge type colour name'),
 'edit_typeset':
 ('Editando conjunto de tipos de Conhecimento', 'Heading'),
 'create_typeset':
 ('Criação de conjunto de tipos de Conhecimento', 'Heading'),
 'title':
 ('Título', 'Start of label'),
 'form':
 ('Formulário', 'Start of heading'),
 'of_typeset':
 ('do conjunto de tipos de conhecimento', 'Ending of label'),
 'abbreviations_and_icons':
 ('abreviaturas e ícones', 'Ending for heading'),
 'type':
 ('Tipo de conhecimento', 'Label'),
 'types':
 ('Tipos de conhecimento', 'Title'),
 'types_management':
 ('Gestão de tipos de conhecimento', 'Title'),
 'abbreviation':
 ('Abreviatura', 'Label'),
 'color':
 ('Cor', 'Label'),
 'icon':
 ('Ícone', 'Label'),
 'starting_phrase':
 ('Frase inicial', 'Label'),
 'checklist':
 ('Lista de requisitos', 'Label'),
 'no_types_entered':
 ('Não foram especificados quaisquer tipos de conhecimento. Um conjunto tem de incluir pelo menos um tipo.',
  'Error message for when a new set is created with no types'),
 'restrictions_of_use':
 ('Restrições à utilização', 'Heading sentence.'),
 'that_can_start_thread':
 ('que poderá iniciar um diálogo', 'End of label'),
 'viewing':
 ('visualizando', 'Part of location bar'),
 'new_typeset_from':
 ('Duplicar e editar conjunto de tipos de conhecimento',
  'Link, followed by knowledge type set name'),
 'unfinished':
 ('Incompleto', 'Label'),
 'manage_types':
 ('Gerir tipos de conhecimento', 'Link'),
 'finalize_typeset':
 ('Alterar estado para terminado', 'Button label'),
 'are_you_sure':
 ('Tem a certeza que deseja apagar os seguintes cursos:',
  'Message dialog message'),
 'are_you_sure_ctx':
 ('Tem a certeza que deseja apagar este contexto de curso:',
  'Message dialog message'),
 'are_you_sure_tts':
 ('Tem a certeza que deseja apagar os seguintes conjuntos de tipos de conhecimento:',
  'Message dialog message'),
 'typeset_importing':
 ('Por favor seleccione o ficheiro zip contendo os conjuntos de tipos de conhecimento que deseja importar.',
  'Instructions for typeset importing'),
 'typesets_imported':
 ('Os novos conjuntos de tipos de conhecimento foram importados.', 'Message'),
 'import_typeset':
 ('Importar conjunto de tipos de conhecimento', 'link'),
 'course_importing':
 ('Por favor seleccione o ficheiro zip contendo os cursos que deseja importar.',
  'Instructions for course importing'),
 'courses_imported':
 ('Os novos cursos foram importados.', 'Message'),
 'import_course':
 ('Importar cursos', 'link'),
 'course_imported':
 ('(importado)', 'Appended to imported course names.'),
 'can_start_thread':
 ('Pode iniciar um diálogo?', 'column title in a table'),
 'can_be_followed':
 ('pode ser seguido de', 'column title in a table'),
 'use_each_type':
 ('Cada tipo de conhecimento tem de seguir pelo menos um outro tipo, ou iniciar um diálogo.',
  "Error message when knowledge types don't have any uses specified in edit form 3."),
 'resources':
 ('Materiais', 'Title for list of course resources'),
 'add_resource':
 ('Adicionar material', 'Link'),
 'editing_course_resources':
 ('Editando os materiais do curso', 'Title'),
 'remove_resource_verify':
 ('Tem a certeza que deseja remover este material?',
  'Verification message when trying to delete a resource from course context.')}

jam = {'add_jam_session':
 ('Adicionar espaço ideias', 'link'),
 'jam_sessions':
 ('Espaços Ideias:',
  'a list of jam session will listed after/under this label'),
 'jam_session':
 ('espaço ideias', ''),
 'annotations':
 ('anotações', ''),
 'continue_with_version':
 ('Prosseguir com a sua versão', 'button label'),
 'artefact':
 ('artefacto', ''),
 'viewing_annotations':
 ('visualizando anotações', ''),
 'Annotations':
 ('Anotações:', 'Label, followed by a list of annotations under it'),
 'adding_jam_session':
 ('Adicionando espaço ideias', ''),
 'add_annotation':
 ('Adicionar anotação', 'link'),
 'edit_jam_session':
 ('Editar espaço ideias', ''),
 'editing_jam_session':
 ('Edição de espaço ideias', ''),
 'title_of_jam_session':
 ('Título do espaço ideias', 'label'),
 'type_of_jam_session':
 ('Tipo do espaço ideias', 'label'),
 'mutate_on_previous':
 ('Adaptado do anterior', 'type of jam session'),
 'explore_possibilities':
 ('Exploração de possibilidades', 'type of jam session'),
 'diverge_and_converge':
 ('Divergência e Convergência', 'type of jam session'),
 'description_of_jam_session':
 ('Descrição do espaço ideias', 'label'),
 'upload_the_starting_artefact':
 ('Colocar o artefacto inicial', 'label'),
 'adding_artefact':
 ('Adição de artefacto', ''),
 'title_of_the_starting_artefact':
 ('Título do artefacto inicial', 'label'),
 'annotation_of_the_starting_artefact':
 ('Anotação para o artefacto inicial', 'label'),
 'title_of_the_artefact':
 ('Título do artefacto', 'label'),
 'upload_file':
 ('Colocar ficheiro', 'label'),
 'you_adding_annotation':
 ('Está a adicionar uma anotação ao artefacto',
  'message in adding annotations form'),
 'adding_annotation':
 ('Adicionando anotação a', ''),
 'to_jam_session':
 ('ao espaço ideias', 'Part of a message'),
 'to_jam_artefact':
 ('ao artefacto do espaço ideias', 'Part of a message'),
 'unread_artefacts':
 ('novos artefactos', 'There is a number before this message'),
 'total_artefacts':
 ('artefactos no total', 'There is a number before this message'),
 'are_you_sure_jam_sessions':
 ('Tem a certeza que quer apagar os seguintes espaços ideias:',
  'Message dialog message'),
 'are_you_sure_jam_session':
 ('Tem a certeza que quer apagar este espaço ideias contendo %s artefactos?',
  'Message dialog message. Placeholder is replace with number of jam artefacts'),
 'remove_artefact':
 ('Remover artefacto', 'Button label for censoring jam artefact'),
 'restore_artefact':
 ('Disponibilizar artefacto', 'Button label for restoring jam artefact'),
 'remove_annotation':
 ('Remover as anotações seleccionadas',
  'Button label for censoring jam annotations'),
 'restore_annotation':
 ('Disponibilizar a anotação seleccionada',
  'Button label for uncensoring jam annotations'),
 'removed_name':
 ('Removido', 'Title/name for censored jam artefact'),
 'removed_message':
 ('Este artefacto foi removido por %s em %s.',
  "First placeholder is replaced by censorer's name and the second by the date"),
 'removed_msg':
 ('Artefacto removido', 'Message shown when teacher censores an artefact.'),
 'removed_annotation_msg':
 ('Anotação removida',
  'Message shown when teacher censores an annotation.'),
 'remove_verify':
 ('Tem a certeza que quer remover este artefacto? O seu nome, a data de hoje, e a razão que especificar abaixo serão armazenados e apresentados junto com a  informação de que foi removido a quem vir este artefacto.',
  'Verification message shown when censoring is attempted'),
 'remove_annotations_verify':
 ('Tem a certeza que quer remover as anotações que seleccionou? O seu nome, a data de hoje, e a razão que especificar abaixo serão armazenados e apresentados junto com a informação de que foram removidas aos leitores das anotações.',
  'Verification message shown when censoring is attempted'),
 'removed_annotation_body':
 ('Esta anotação foi removido por %s em %s.',
  "Body for censored annotation. First placeholder is replaced by censorer's name and the second by the date"),
 'search_jam':
 ('Procurar em Espaço Ideias', 'Link label'),
 'searching_jam':
 ('Procurando artefactos do Espaço Ideias', 'Label'),
 'search_artefact_name':
 ('Nome do artefacto', 'Label in search form'),
 'search_artefact_author':
 ('Autor', 'Label for author of artefact in search form'),
 'search_annotation_words':
 ('Anotações que contenham as palavras',
  'Label in search form (those artefacts match whose annotations contains at least one of the given words)'),
 'search_artefact_type':
 ('Tipo de artefacto',
  'Label in search form (type is image, audio, text, etc...)'),
 'type_image':
 ('Imagem', 'Artefact type'),
 'type_audio':
 ('Audio', 'Artefact type'),
 'type_text':
 ('Texto', 'Artefact type'),
 'type_html':
 ('Html', 'Artefact type'),
 'type_video':
 ('Video', 'Artefact type'),
 'type_archive':
 ('Arquivo', 'Artefact type'),
 'search_annotated_by':
 ('Anotado por', 'Label in search form'),
 'search_results_author':
 ('Autor', 'Heading in search results table'),
 'search_results_jam_artefact':
 ('Artefacto', 'Heading in search results table'),
 'search_results_jam_session':
 ('Espaço Ideias', 'Heading in search results table')}

announce = {'comments':
 ('Comentários', 'Notice / form heading'),
 'no_comments':
 ('Não há comentários.', 'Notice'),
 'recent_comments':
 ('Comentários recentes', 'Heading'),
 'no_entries':
 ('Não há entradas.', 'Notice'),
 'recent_entries':
 ('Entradas recentes', 'Heading'),
 'trackbacks':
 ('Referências', 'Notice'),
 'no_trackbacks':
 ('Não há referências.', 'Notice'),
 'recent_trackbacks':
 ('Referências recentes', 'Heading'),
 'send_trackback':
 ('Por favor enviar referência para:', 'Part of message, followed by url'),
 'syndicate':
 ('Sindicalizar este site (XML).', 'Link'),
 'log_in':
 ('Entrar no Fle3.', 'Link'),
 'entries':
 ('Entradas', 'Heading'),
 'category':
 ('Categoria', 'Heading'),
 'categories':
 ('Categoria', 'Heading'),
 'no_categories':
 ('Sem categorias', 'Notice'),
 'items':
 ('entradas', 'Part of message: nn items.'),
 'posted_by':
 ('Colocado por', 'Part of message'),
 'timeformat':
 ('%H:%M', 'Time format'),
 'shortdateformat':
 ('%d/%m %H:%M', 'Short date format'),
 'dateformat':
 ('%d de %B,%Y %H:%M', 'Date format'),
 'at_time':
 ('às', 'Part of a message: Posted by X *at* Y.'),
 'post_comment':
 ('Colocar um comentário', 'Heading'),
 'name':
 ('Nome', 'Form heading'),
 'email':
 ('Email', 'Form heading'),
 'url':
 ('URL', 'Form heading'),
 'title':
 ('Título', 'Form heading'),
 'body':
 ('Corpo de anúncio', 'Form heading'),
 'forget_personal':
 ('Não armazenar informação pessoal', 'Button'),
 'teachers_and_tutors_only':
 ('apenas para professores e tutores',
  'Message, displayed in parenthesis after a link'),
 'remember_personal':
 ('Manter informação pessoal num cookie?', 'Label'),
 'Announcement':
 ('Anúncio', 'Category'),
 'ToDo':
 ('Tarefas', 'Category'),
 'Event':
 ('Evento', 'Category'),
 'continue_reading':
 ('Prosseguir a leitura', 'Part of message, followed by entry title'),
 'missing1':
 ('está em falta', 'Part of message'),
 'missingn':
 ('estão em falta', 'Part of message'),
 'comment_preview':
 ('Pré-visualização de comentário', 'Heading'),
 'search_results':
 ('Resultados da pesquisa', 'Heading'),
 'search_for':
 ('Pesquisar anúncios de', 'Part of message'),
 'no_match':
 ('Não encontrado', 'Notice'),
 'about':
 ('Acerca', 'Title'),
 'archives':
 ('Arquivos', 'Title'),
 'search':
 ('Pesquisa', 'Heading'),
 'search_help':
 ('Pode utilizar-se AND/OR para pesquisas lógicas.',
  'Help text for searching')}

vocabulary={
        'common': common,
        'kb': kb,
        'webtop': webtop,
        'usermgmnt': usermgmnt,
        'coursemgmnt': coursemgmnt,
        'jam': jam,
        'announce': announce,
}

#EOF

